### ISSUE TITLE
Hidden application window

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/PK-Sim#1008]
When presenting PKSim on an additional screen (e.g. in a meeting room), 
after disconnecting from the screen and working in my office environment (closed laptop with 2 external screens) the window was not longer visible nor restorable from the symbol in the windows task bar.

From my experience some applications can handle this situation, some not. Would be glad, if OSP Suite windows would belong to the first category.

**Comment by PavelBal** [comment]
From my experience, it is not a problem of PK-Sim - usually, switching between different outputs is no problem. Must be an occasional issue not related to PK-Sim.

**Comment by msevestre** [comment]
@ju-rgen I concur with @PavelBal . I have not seen that behavior with the suite on my Laptop (not corporate laptop should I say) even though i am am switching context quite often.

What happens if you close PK-Sim and reopen? Does it starts and display as expected?

**Comment by Yuri05** [comment]
Closing the issue due to inactivity. @ju-rgen Please reopen if you still face the problem.
