### ISSUE TITLE
Refresh problem: deleted curves remain in chart

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1019]
7.4 (was already a problem in 7.3)
Once an individual simulation with >1 curves selected was performed: 
* start "Define settings and Run"
* deselect some curves and perform simulation run
Deselected curves are still displayed in chart and Chart Browser/Curves Settings (also after closing/reopening simulation Tab)

![grafik](https://user-images.githubusercontent.com/25061876/48917700-758df280-ee88-11e8-98f9-1f10af6d6be2.png)

After save/close/reopne project removed curves are not displayed anymore (as expected)

**Comment by msevestre** [comment]
This has been fixed with one of the latest bug fix in core

**Comment by msevestre** [comment]
see #1277
