### ISSUE TITLE
Working Journal: "Related Items" subwindow cuts off title (v 7.4 beta)

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#1024]
When executing test case 4.37.2 (creation of new WJ), the empty related items list is truncated in version 7.4 beta. This was fine in v 7.3. However, it will fix itself when the Jounal Listing view is expanded or contracted. Seems to be minor and cosmetic.

See circle in screenshot:
![grafik](https://user-images.githubusercontent.com/27352743/49018786-9dcd6800-f18c-11e8-91a8-dfc4a0e2e624.png)

**Comment by msevestre** [comment]
Looks a  lot like #1018

**Comment by UlrichSi** [comment]
Agreed, this might be solved by solving the refresh problem.

**Comment by msevestre** [comment]
This is the same. Your window is too small. Just make it a bit wider
