### ISSUE TITLE
Errors in storage of compound value origins in snapshot

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/PK-Sim#1026]
In  version 7.4.0.95 EAP Compund stored in TemplateDB and in snapshot have differences in value origin for molweight and pka.
And effective molweight seems to be overwritten.
![grafik](https://user-images.githubusercontent.com/25579536/49083469-f9f7c100-f24c-11e8-9beb-a960465bfe99.png)
![grafik](https://user-images.githubusercontent.com/25579536/49083500-18f65300-f24d-11e8-9ea0-43a58dbaa15c.png)

**Comment by ju-rgen** [comment]
TC 77.38

**Comment by Yuri05** [comment]
Can confirm with 7.0.4.98. Value origins are not saved into snapshots for `pKa`-parameters group and `MolWeight `-parameters group

**Comment by msevestre** [comment]
Going to check it out

**Comment by msevestre** [comment]
I cannot reproduce for MW Group.  I can reproduce it however for CompoundType
MolWeight works fine. I changed the ValueOrigin, saved to tempate, imported it back. It's all there. 

How can I reproduce?

**Comment by Yuri05** [comment]
Export project attached to snapshot and compare the compound C2_MW im original project and after reimport from snapshot.
[P06_ValueOriginCompound.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2633278/P06_ValueOriginCompound.zip)
![grafik](https://user-images.githubusercontent.com/25061876/49291119-65d66580-f4a9-11e8-9103-1221e7a24190.png)

Here I see 2 problems: 
* Value origin in the original compound **_C2_MW_** for 2 non-editable/hidden parameters (`Effective molweight` and `Has halogens`) was overwritten with the user input. This should not be the case.
* Value origin for editable parameters `F` and `I` was not properly reimported from snapshot.

**Comment by msevestre** [comment]
Isn't it because halogens were set after the value origin was updated?


And yes same issue as with compound type. We are updating all parameters in the group which is an error
