### ISSUE TITLE
Error in comparison of compounds: e.g. differences of defaults are not displayed

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/PK-Sim#1027]
Version 7.4.0.93/95 - this is not a result of test case 77, but to reproduce it you can do steps 77.9-11
Then compare C1 and C2.
a) the differences of defaults for Lipophilicity, fu, solubility are not displayed
b) the differences of calculation method for cellular permeabilities are not displayed
a) 
![grafik](https://user-images.githubusercontent.com/25579536/49083972-763ed400-f24e-11e8-90ba-1db12e41815c.png)
![grafik](https://user-images.githubusercontent.com/25579536/49083976-7a6af180-f24e-11e8-8066-4176aea44c20.png)

b)
![grafik](https://user-images.githubusercontent.com/25579536/49083987-822a9600-f24e-11e8-9370-1a6a176c9dc8.png)
![grafik](https://user-images.githubusercontent.com/25579536/49083991-85be1d00-f24e-11e8-9d8a-811ec7c63852.png)

**Comment by Yuri05** [comment]
[CompareDefaults.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2910127/CompareDefaults.zip)
Example project attached. Compounds C1 and C2 have different default alternatives for:
* Lipophilicity
* fu
* Solubility
* Specific intestinal permeability
* Specific organ permeability

None of them is showed in the difference:
![grafik](https://user-images.githubusercontent.com/25061876/53488419-79846e80-3a8e-11e9-9452-6dac0708612e.png)

**Comment by msevestre** [comment]
Ok this is how it looks like
Default and CM are now visible
![image](https://user-images.githubusercontent.com/1041237/53594200-5928e280-3b68-11e9-9b13-4b9175a30b03.png)
