### ISSUE TITLE
Issue with fat partition coefficient parameter

### ISSUE THREAD

**Issue by calixto16** [Open-Systems-Pharmacology/PK-Sim#1040]
Hi,

I'm having an issue with editing a parameter on the individual building block. For my simulation I made a Parameter identification and as a result I ended up changing the partition coefficient (neutral phospolipids/intracellular water) and commiting it to the building block. 

However, when I create a population based on that individual who has that parameter changed, it doesn't seem to stick to it, the population hasn't got that parameter anymore. Even if I create a new simulation for that same individual the parameter doesn't mantain changed, and I have to run the identificacion parameter all over again and change it from there. 

Is there any way I can edit this parameter manually in the individual without going through the parameter identification, and how can I create a population based on this one?

Thank you,

Pilar

**Comment by msevestre** [comment]
@calixto16 Would you mind asking your questions in the forum? PK-Sim issues are for feature requests and bug reports

https://github.com/Open-Systems-Pharmacology/Forum/issues

Thanks
