### ISSUE TITLE
Comparison creation should be possible by context menu of Comparisons folder

### ISSUE THREAD

**Issue by ju-rgen** [Open-Systems-Pharmacology/PK-Sim#1042]
Currently the only way to create a comparison (chart) seems to be:
opening a simulation and clicking the compare results button.

There should also be a context menu "Add comparison" in the Comparisons folder analogously to Simulations, Parameter Identifications, Sensitivity Analyses.

**Comment by ju-rgen** [comment]
Original formulation of testcase 77.26 indicates, that this option had been existing in a previous version.

**Comment by msevestre** [comment]
>Currently the only way to create a comparison (chart) seems to be:
opening a simulation and clicking the compare results button.

This is not quite accurate. You can also create a comparison chart from the main ribbon. 
![image](https://user-images.githubusercontent.com/1041237/49749413-3af0cc00-fc76-11e8-982a-a22e389bdf2d.png)

>There should also be a context menu "Add comparison" in the Comparisons folder analogously to Simulations, Parameter Identifications, Sensitivity Analyses.

We do not know if the comparison is going to be for an individual simulation or population simulation, we would need to create two entries Add Individual Simulation Comparison and Add Population Simulation Comparison. Or we would have to create nested menus...

**Comment by msevestre** [comment]
done via #2674
