### ISSUE TITLE
Fraction eliminated in urine

### ISSUE THREAD

**Issue by samitganguly** [Open-Systems-Pharmacology/PK-Sim#1044]
Hi, 

          I am working with a compound that is mainly renally eliminated unchanged, renal clearance > GFR and it is a substrate of OAT3 and OAT1. Also, in all literature they have confirmed the fraction eliminated in urine. 
          In my model I added OAT1 and OAT3, and by optimizing the parameters for transporter I can predict plasma clearance quite well. 
          Problem is, as I am increasing plasma clearance by optimization of transporter parameter, I see that fraction excreted in urine is decreasing instead of increasing!!!? 
          Fraction excreted can be explained if I use tubular secretion instead. Which I don't want, since using the transporter will be more mechanistic and would also allow me to scale the clearance in different age group. 
          Can you please help me understand this? Why would fraction excreted in urine decrease if renal elimination is increasing?

Regards
Samit

**Comment by PavelBal** [comment]
When you use tubular secretion, the drug is transported from renal plasma into urine.

When you use OAT1 and OAT3, the drug is transported from the interstitial space of the kidney into the cells, as both transporters are expressed in the basolateral membrane. That means, the model accumulates the drug intracellularly, and fraction excreted to urine decreases because less can be filtered via GFR (and GFR is the only process into the urine).

What you need now is the transport of the drug from kidney cells into urine. A typical candidate transporter for this is P-gp. Do you know, if the drug you try to model is a P-gp substrate? In any case, you have to find out which transporter excretes the drug into urine.

**Comment by samitganguly** [comment]
Hi Pavel, 

Thank you for the explanation. 
I agree with you. But I am not sure if this drug is a substrate of any efflux transporter. 
In such condition, do you recommend:
1. Only tubular secretion?
2. Tubular secretion along with the uptake transporters?

Also, if I add only tubular secretion: 
1. How does tubular secretion process mature in PKSim? 
2. Can I make it mature like GFR? So that when I scale my model to a different age group, then I have a better estimation of clearance?

Regards
Samit

**Comment by PavelBal** [comment]
I would first check if it has been examined in vitro whether the drug is substrate of P-gp. If it is, I would try to fit the model using OAT and P-gp. In this case you would automatically have some secretion into bile and slight limitation of oral absorption.
If you do not have any information on P-gp, or it is known not to be a P-gp substrate, or adding P-gp makes the model worse, I would simply add tubular secretion (TS), but not TS and transporters!

TS scales with aging of individuals above 30 years:

`scaling factor = Age <= Age_onset ? 1 : 1 - Decrease_Factor*(Age-Age_onset)^Hill/(TA50^Hill+(Age-Age_onset)^Hill)`

With `Age_onset = 30`, `TA50 = 54`, `Hill = 1.5`, and `Decrease_Factor = 0.9`.

There is no age-dependency of TS for age below 30.

**Comment by samitganguly** [comment]
Hi Pavel, 

There is only one paper which sort of suggests existence of an efflux transport system. That is all I know about this drug and efflux transporter. 
Thank you for the explanation on scaling factor. I am absolutely new to PKSim. 
1. Where do I find this scaling equation?
2. Can I use Rhodin or Hayton equation to scale TS for age below 30? Assuming that TS will mature similar to GFR. 

Regards
Samit

**Comment by msevestre** [comment]
@samitganguly PK-Sim issues are meant to report Bugs or Feature request. If you need assistance or have a question, kindly use the forum instead. I will close the issue for now. Please do not hesitate to open a discussion in the forum for further reference
