### ISSUE TITLE
Repository readme: Add a warning that the repository is for bug-report only

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1046]
I propose to add a warning sentence about the bug-report only nature of this repository at the very beginning of the readme. New members of the community tend to open questions about working with the software in this repositry and may be discouraged by the fact their issues are closed.

While I can understand the developers who want to have a clean overview of the issues they have to work on, the current strategy may be disapponting for new members.

**Comment by msevestre** [comment]
We will implement issue templates when we have time

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/49812781-2a069000-fd34-11e8-98e9-aaf24899b3f0.png)

It is now possible to move issues to another repo!! problem solved

**Comment by PavelBal** [comment]
Great news!
