### ISSUE TITLE
Suite Setup: Warning for 32bit OS

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1062]
7.4-Setup should produce an explicit error message ("64 bit only") on 32-bit systems.
Instead, error message below is shown.

![grafik](https://user-images.githubusercontent.com/25061876/50762381-0e2bd680-126d-11e9-9af0-f12bb4e52fe9.png)

**Comment by msevestre** [comment]
@Yuri05 We had looked into that at the time but did not find anything
http://wixtoolset.org/documentation/manual/v3/xsd/wix/bundle.html

The bundle does not know about the architecture it's supporting. Only the Packages. Probably the error comes from another component. Oh well. There won't be that many 32 bit PC anymore so I think we can live with this
