### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by melagha** [Open-Systems-Pharmacology/PK-Sim#1067]
I am using Parallel Desktop virtual machine on Mac Pro. I am not able to the GENEDB_human.expressionDb that I have saved on My Document folder. Please see the error log below.

Best regards

Application:
PK-Sim® 7.4.0.127

unable to open database file

Stack trace:
```
at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dataProvider, String connectionString)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String workgroupDb, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.DAS.DAS.Connect(String dbName, String user, String password, DataProviders dataProvider)
   at PKSim.Infrastructure.ORM.Core.Database.Connect(String databasePath)
   at PKSim.Infrastructure.ORM.Core.DatabaseDisposer..ctor(IDatabase database, String databasePath)
   at PKSim.Infrastructure.Services.GeneExpressionsDatabasePathManager.ConnectToDatabaseFor(Species species)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.proteinFromQuery(TSimulationSubject simulationSubject, IndividualMolecule newMolecule)
   at PKSim.Presentation.Services.MoleculeExpressionTask`1.AddMoleculeTo[TMolecule](TSimulationSubject simulationSubject)
   at PKSim.Presentation.Presenters.Individuals.MoleculesPresenter`1.AddMolcule[TMolecule]()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by msevestre** [comment]
How did you install PKSim? Using the setup or using the portable install?
Did you run the installation validator?
Did it run successfully?

Can you load a compound from the template database?

Are you sure that the database was downloaded properly? Can you download it one more time?
Is the db saved on a Mac folder or windows folder? Can you move it to a windows folder that is not shared with your Mac os

**Comment by msevestre** [comment]
PS: I moved the issue to the PKSim repo as it is an issue with the installation seemingly

**Comment by melagha** [comment]
I downloaded the the full setup package  and Gene expression database from the website:
https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/7.4.0

The validation run ended successfully and uploading compound also was done without problems.

The Gene expression database was saved in windows document folder and MAC's desktop but no difference.

I am using latest version of Parallel desktop to and macOS Mojave.

**Comment by msevestre** [comment]
Hi @melagha,

I just download the latest released portable version of pksim and the database as well from the release link and I could load an enzyme in the individual. 

Are you sure that the path is set properly in your user settings. Did you update from 7.3 ? 
You also need to select the new database as well 
![image](https://user-images.githubusercontent.com/1041237/51089433-fc4da600-173a-11e9-9f91-ab61485c4540.png)

**Comment by melagha** [comment]
Hello,
I reinstall Parallel Desktop, the Windows and PK-sim and now it is working fine! I do not know what was wrong.

Thank you for your time

**Comment by msevestre** [comment]
We love when bugs solved themselves automatically.
Good luck! Feel free to reach out to the community using the forum if you have questions

**Comment by finattig** [comment]
Hello,

Even though I followed the steps to load the expression database, PK-Sim does not seem to open/recognize the file when creating an individual. I can load the compound templates normally, and I also ran the installation validation, which confirmed that everything should be fine ("Valid"). I've tried reinstalling PK-Sim and changing the directory of the .expressionDb file (the file is in the OSP folder in C: now). I'm using the latest available version of PK-Sim (11.2) in conjunction with the gene expression file (human) available here: [https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v11.2](https://github.com/Open-Systems-Pharmacology/Suite/releases/tag/v11.2).

Only the option shown below is available (shouldn't the "Database query" option be there?):

![addenzymes](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/72104369/35884d5c-eb92-495a-8324-94443a41ca30)

Despite the above, I can access the database query via the building block of the expression profiles after adding an enzyme (as shown below).

![query](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/72104369/f3948b14-f4e8-4ae2-a713-90fff881d2b5)

Does this indicate that everything is correct or am I missing something? Apologies if this change was part of an update.
Any help would be greatly appreciated.

Best regards

**Comment by msevestre** [comment]
If you have questions, ask in the forum and never comment on a closed issue otherwise it won't be answered. So create another issue in the forum if you want some help. Thanks

**Comment by PavelBal** [comment]
@finattig The workflow for adding expression to individuals has changed in version 11 with the introduction of the new "Expression Profiles"-building block, please follow the documentation: https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-profile

In short, you access the data base in the Expression Profile BB (your second screenshot) and then add expression profiles to the individuals (first screenshot).

**Comment by msevestre** [comment]
PLEASE DO NOT COMMENT ON CLOSED ISSUE. NO ONE
