### ISSUE TITLE
Feature: Advanced protocol for user-defined applications

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#1070]
A feature to allow definition of an advanced protocol for user-defined applications (e.g. to allow multiple dose simulations with intervals >OnceDaily for SC dosed mAbs).

**Comment by LkKov** [comment]
Hello everybody!
Is this still an issue wich is going to be tackled? Since I am also highly interested in using the advanced protocol for user-defined application to allow specific multiple dosing regimens.
This would be really helpful!

Thank you very much in advance!
Best regards,
Lukas

**Comment by msevestre** [comment]
Is a duplicate of #1170
