### ISSUE TITLE
Transport protein in red blood cells

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/PK-Sim#1071]
Dear all,

I would like to create a transporter in PK-Sim which is expressed in different tissues, and red blood cells is one of them.
Is there a reason why enzymatic processes and binding partners can be expressed in red blood cells (or the vascular endothelum) but transporters cannot? Since red blood cells are not available in the list of tissues where the transporters can be expressed. 

Best regards,

Donato

**Comment by Yuri05** [comment]
implemented in V10 
@teutonicod Check the beta version ;)
