### ISSUE TITLE
Open and modify .expressionDB?

### ISSUE THREAD

**Issue by HenrikCordes** [Open-Systems-Pharmacology/PK-Sim#1072]
Dear All, 
in the recent update of PK-Sim, the access expression database (.mdb) was substituted with an .expressionDB database file.
Linking and accessing the new DB to PK-Sim works fine, but I can't open and modify the .expressionDB file with MS access. 

I didn't find any clues in the manual or other forum issues. 
A quick google search for the .expressionDB format lead me to this article and R package: https://www.ncbi.nlm.nih.gov/pubmed/29095940 
However, I couldn't make the connection between .expressionDB file and the package.

Is there a way to open and modify the .expressionDB as it was possible with the previous .mdb file? 
Which software is needed here?

Thank you for your help and advice 
Henrik

**Comment by msevestre** [comment]
I moved the issue to PKSim now since we are getting technical.

Is it the database provided by the setup or a database you modified?

You said you could connect to the DB earlier. 
Have you restarted your laptop since the installation? If not, can you try?

**Comment by HenrikCordes** [comment]
Thank you for the reply.

Its the database  provided by the set up. I did not modify the database yet. 

Yes I can connect to the database for example via KNIME or RSQLite.

I restarted the computer after the PK-Sim installation and the same error occure. 

Kind regards,

**Comment by msevestre** [comment]
Are you sure that you have updated your settings in the application?
Could they have been reset to the old DB for some reason? Can you verify that the path is correct. Is the db saved on a shared drive?

Can you save and open a project?
Can you load from template?

**Comment by HenrikCordes** [comment]
I installed PK-Sim 7.4 and downloaded the expression DB. After installing PK-Sim I went to Options->Application and set the path for Human specie to the downloaded non modified expression DB.

I can save and open projects and load and save templates. Also the ones I migrated from 7.3

**Comment by msevestre** [comment]
- Can you verify that the path is correct? 
- Is the db saved on a shared drive? If yes, try to move it on another drive (c:\temp) and see if this solves the issue
- Can you try downloading the file again and try? 

The operation that failed is the `Opening of the database`. So something is quite wrong for the engine that we do not really influence at that stage.

**Comment by HenrikCordes** [comment]
Dear @msevestre 
Please excuse me for ignoring your suggestion for the shared drive.
Copying the DB to a local temp folder did the trick. 

Thank you for your patients and help!

**Comment by msevestre** [comment]
Great. Is there anything special about this share drive? THis is not the first time that we have a similar issue and we can never reproduce it.

**Comment by msevestre** [comment]
@HenrikCordes I have created another issue here #1073 
Can you please add here any info that you might have that could help us understand how to reproduce the issue as well as some info as how your share drive is configured?

**Comment by HenrikCordes** [comment]
As mentioned in #1073 the drive was not mapped to a drive letter, putting it on C:... solved it.

Thank you @msevestre and @Yuri05 !
