### ISSUE TITLE
ExpressionDB on share drive: Sometimes, user can't open the file

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1073]
1. Can we reproduce it somehow? (@Yuri05 This should be possible for you considering the complexity of your IT infrastructure :-))
1. Can we do something about it?
1. Can we somehow catch this generic error and be more specific about it?

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1072#event-2088859256

**Comment by Yuri05** [comment]
Solution: always map the network drive

**Comment by msevestre** [comment]
I think we have a method that actually deals wit that. Maybe it's not used for ExpressionDB (I would not be surprised...)
Do you have the same issue if you put a PKSim project in one of this folder ?

**Comment by Yuri05** [comment]
It works for project files.
But crashes for User-templates DB as well

**Comment by msevestre** [comment]
@Yuri05 We use DAS For both templates and expression DB... THis is definitely fixable then. We have a toUNCPath or sthg like that, that needs to be caleld
