### ISSUE TITLE
Remove Qualification Plan node from PKSim

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1079]
This is obsolete

@Yuri05 
What about the integration in PKSim (e.g. QualificationSteps). Is this also not required anymore? I think so but I am not sure

**Comment by Yuri05** [comment]
>What about the integration in PKSim (e.g. QualificationSteps). Is this also not required anymore? I think so but I am not sure

Yep, not required anymore.
