### ISSUE TITLE
PKSimCLI. Export

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1093]
Should also export results as csv an optionally / by default export using UI nomenclature?

@Yuri05 What do you think: Should we export by default using the pksim nomenclature? and have an option to turn it off? Or the opposite?

**Comment by Yuri05** [comment]
Think "export by default using the pksim nomenclature" is better

**Comment by msevestre** [comment]
actually this is only for csv output that we do not use in comparison anymore. I am going to rename them
