### ISSUE TITLE
PKSIm.CLI: Support for input in qualifications

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1098]

**Comment by msevestre** [comment]
@Yuri05 This is NOT The actual implementaiton of what an input will be. Simply the infrastrcuture for it

I don't really like the name input. Can we name it something else?

**Comment by Yuri05** [comment]
>I don't really like the name input. Can we name it something else?

Suggestions? 
Actually it's the description of the model inputs. So maybe _InputsDescription_? Or _ModelInputsDescription_?

**Comment by msevestre** [comment]
I still don't get what the output is going to be. How is a simulation an input of the model?
Or is the goal just to export  parameter values (e.g. user defined parameters for a given bb?)

**Comment by msevestre** [comment]
Very unclear to me. Need feedback;-)
