### ISSUE TITLE
Working Journal and simulation comparison

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#110]
If simulation was loaded from working journal, comparison with other simulations does not work properly.
E.g. in the project attached, simulation _**Paracetamol Solution**_ was loaded from working journal (also attached).
Comparing it with the simulation _**NEW_rabbit paracetamol solution**_ shows no differences (both in Compare Formula and Compare Value mode). But e.g. body weight and all organ volumes differ.
[Comparison_WJ.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/920197/Comparison_WJ.zip)

**Comment by msevestre** [comment]
In which version does the problem occurs?

**Comment by Yuri05** [comment]
7.1

**Comment by msevestre** [comment]
And NOT in 7.0?

**Comment by msevestre** [comment]
What i want to figure out is: Is this a new bug due to 7.1 port or not.

**Comment by msevestre** [comment]
Yes this seems to be only in 7.1

**Comment by msevestre** [comment]
actually comparison between simulation does not work
