### ISSUE TITLE
Supersaturation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1100]
Enable simulations of [Supersaturation](https://en.wikipedia.org/wiki/Supersaturation) for particles dissolution.

Will be realized as following:
* Compound-BB becomes new parameter `Enable supersaturation`
  * New parameter will be defined as advanced parameter in the "_Particle dissolution_" group
* Default value is: _false_ (no supersaturation, corresponds to the status quo)
* Effective drug concentration in lumen is currently described as:
   `min(Solubility/MW ; M/Liquid)`
   This will be changed to:
   `Enable_supersaturarion ? M/Liquid : min(Solubility/MW ; M/Liquid)`

**Comment by Yuri05** [comment]
@KatrinCoboeken @sfrechen @AndreDlm FYI

**Comment by msevestre** [comment]
@Yuri05 Will it be part of  7.5?

**Comment by Yuri05** [comment]
yes
