### ISSUE TITLE
Project conversion (supersaturation)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1101]
Project conversion for #1100 (new compound parameter)

**Comment by msevestre** [comment]
@Yuri05 What needs to be done here?

**Comment by Yuri05** [comment]
Parameter `Enable supersaturation` must be added into Compound-BBs.
Value: NO (zero)
IsInput: true(!)

parameter_name | can_be_varied | read_only | visible | can_be_varied_in_population | group_name | sequence | build_mode | building_block_type | is_input
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Enable supersaturation | 1 | 0 | 1 | 0 | COMPOUND_PARTICLE_DISSOLUTION | 100 | PROPERTY | COMPOUND | 1
