### ISSUE TITLE
Error recreating Pop-Simulation from Snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1115]
[BugPopFromSnapshot.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2905241/BugPopFromSnapshot.zip)
* Project **Digoxin_Bug_Snapshot_02** (created with 7.4) was exported to snapshot **Digoxin_Bug_Snapshot_02.json**
* Project **Digoxin_Bug_Snapshot_02_reloaded_from_Snapshot** was recreated from this snapshot
* Trying to open a (population) simulation _Nyberg 1980 neonates_ in the recreated project results in the error message below
![grafik](https://user-images.githubusercontent.com/25061876/53410868-517d0880-39c5-11e9-9f40-0a612dafad5e.png)

**Comment by Yuri05** [comment]
@incei FYI

**Comment by msevestre** [comment]
@Yuri05 This sounds like a merged dimension issue when reading from snapshot

**Comment by msevestre** [comment]
hum in 7.5 I do not get the error...

**Comment by msevestre** [comment]
ok so it's only when loading right from the snaphsot. IF you save and open the project, the issue is gone

**Comment by msevestre** [comment]
ok Fixed :)
