### ISSUE TITLE
Define Markdown export for compound

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1128]
Should be something like this:
[Midazolam.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2962585/Midazolam.xlsx)
![grafik](https://user-images.githubusercontent.com/25061876/54421309-78994100-470c-11e9-90b4-6b28ccde0dba.png)

**Comment by msevestre** [comment]
@Yuri05 This is neat in excel but markdown does not support his type of multiple header

For example we could have somethign like that

# Compound: Midazolam

## Parameters

Name                                             | Value          | ValueOrigin                                       | Alternative  | Default
------------------------------------------------ | -------------- | ------------------------------------------------- | ------------ | ------- 
Solubility at reference pH                       | 0.049 mg/ml    | Publication-FaSSIF (Heikkinen 2012)               | Measurement  | True   
Reference pH                                     | 6.5            | Publication-FaSSIF (Heikkinen 2012)               | Measurement  | True   
Lipophilicity                                    | 3.13 Log Units | Database-Unknown-Drugbank                         | Measurement  | True   
Fraction unbound (plasma, reference value)       | 0.2            | Parameter Identification-Parameter Identification | Measurement  | True   
Specific intestinal permeability (transcellular) | 2E-06 dm/min   | Parameter Identification-Parameter Identification | Optimization | True   

## Calculation Methods

## Processes

**Comment by msevestre** [comment]
@Yuri05 If this is not desired, please update the desired outcome, **AS MARKDOWN**

**Comment by msevestre** [comment]
@Yuri05 This all export is extremely time consuming!

**Comment by msevestre** [comment]
@Yuri05 Updated markdown with processes and parmaeters

# Compound: Midazolam

## Parameters

Name                                             | Value          | Value Origin                                      | Alternative  | Default
------------------------------------------------ | -------------- | ------------------------------------------------- | ------------ | ------- 
Solubility at reference pH                       | 0.049 mg/ml    | Publication-FaSSIF (Heikkinen 2012)               | Measurement  | True   
Reference pH                                     | 6.5            | Publication-FaSSIF (Heikkinen 2012)               | Measurement  | True   
Lipophilicity                                    | 3.13 Log Units | Database-Unknown-Drugbank                         | Measurement  | True   
Fraction unbound (plasma, reference value)       | 0.016          | Parameter Identification-Parameter Identification | Measurement  | True   
Specific intestinal permeability (transcellular) | 2E-06 dm/min   | Parameter Identification-Parameter Identification | Optimization | True   
Plasma protein binding partner                   | 1              |                                                   |              |        
Cl                                               | 1              | Unknown                                           |              |        
F                                                | 1              | Unknown                                           |              |        
Is small molecule                                | 1              |                                                   |              |        
Molecular weight                                 | 325.77 g/mol   |                                                   |              |        
## Calculation methods

Name                    | Value              
----------------------- | ------------------- 
Partition coefficients  | Rodgers and Rowland
Cellular permeabilities | PK-Sim Standard    
## Processes

### CYP3A4-Optimization

Molecule: CYP3A4
Metabolite: 
#### Parameters

Name                 | Value        | Value Origin                                     
-------------------- | ------------ | ------------------------------------------------- 
Enzyme concentration | 1 µmol/l     |                                                  
Vmax                 | 0 µmol/l/min |                                                  
Km                   | 2.73 µmol/l  |                                                  
kcat                 | 13 1/min     | Parameter Identification-Parameter Identification
### Glomerular Filtration-GFR

Process Type: Glomerular Filtration
#### Parameters

Name         | Value | Value Origin
------------ | -----:| ------------:
GFR fraction |     1 |

**Comment by Yuri05** [comment]
Theoretically possible to display all in one table via html (s.below), but I think it's not worth the effort and your implementation (N tables) is ok.

<details><summary>Expand to see the table</summary>
<table>
 <tr><td colspan=5 align="center"><h2>Compound: Midazolam</h2></td></tr>
 <tr><td colspan=5 align="center"><h3>Parameters</h3></tr>
 <tr>
  <th>Name</th>
  <th>Value</th>
  <th>Value Origin</th>
  <th>Parameter-Alternative</th>
  <th>Default</th>
 </tr>
 <tr>
  <td>Is small molecule</td>
  <td>Yes</td>
  <td></td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>Plasma protein binding partner</td>
  <td>Albumin</td>
  <td></td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>Lipophilicity</td>
  <td>3.13 Log Units</td>
  <td>Database-Unknown-Drugbank</td>
  <td>Measurement</td>
  <td>Yes</td>
 </tr>
 <tr>
  <td>Lipophilicity</td>
  <td>2 Log Units</td>
  <td></td>
  <td>Optimization</td>
  <td>No</td>
 </tr>
 <tr>
  <td>Fraction unbound (plasma, reference value)</td>
  <td>0.2</td>
  <td>Parameter Identification-Parameter Identification</td>
  <td>Measurement</td>
  <td>Yes</td>
 </tr>
 <tr>
  <td>Molecular weight</td>
  <td>325.77 g/mol</td>
  <td></td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>Cl</td>
  <td>1</td>
  <td>Unknown</td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>F</td>
  <td>1</td>
  <td>Unknown</td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>Solubility at reference pH</td>
  <td>0.049 mg/ml</td>
  <td>Publication-FaSSIF (Heikkinen 2012)</td>
  <td>Measurement</td>
  <td>Yes</td>
 </tr>
 <tr>
  <td>Reference pH</td>
  <td>7</td>
  <td>Publication-FaSSIF (Heikkinen 2012)</td>
  <td>Measurement</td>
  <td>Yes</td>
 </tr>
 <tr>
  <td>Compound Type 0</td>
  <td>Base</td>
  <td></td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>pKa 0</td>
  <td>6.15</td>
  <td></td>
  <td></td>
  <td></td>
 </tr>
 <tr>
  <td>Specific intestinal permeability (transcellular)</td>
  <td>2E-6 dm/min</td>
  <td>Parameter Identification-Parameter Identification</td>
  <td>Optimization</td>
  <td>Yes</td>
 </tr>
 <tr>
  <td colspan=5 align="center"><h3>Calculation Methods</h3></td>
 </tr>
 <tr>
  <th>Name</th>
  <th>Value</th>
  <th colspan=3></th>
 </tr>
 <tr>
  <td >Cellular partition coefficient method</td>
  <td>Rodgers and Rowland</td>
  <td colspan=3></td>
 </tr>
 <tr>
  <td >Cellular permeability</td>
  <td>PK-Sim Standard</td>
  <td colspan=3></td>
 </tr>
 <tr>
  <td colspan=5 align="center"><h3>Processes</h3></td>
 </tr>
 <tr>
  <th>Name</th>
  <th>DataSource</th>
  <th>Molecule</th>
  <th colspan=2></th>
 </tr>
 <tr>
  <td >MetabolizationSpecific_MM</td>
  <td>Optimization</td>
  <td>CYP3A4</td>
  <td colspan=2></td>
 </tr>
 <tr>
  <td colspan=5 align="center"><h4>Process-Parameters</h4></td>
 </tr>
 <tr>
  <th>Name</th>
  <th>Value</th>
  <th >Value Origin</th>
  <th colspan=2></th>
 </tr>
 <tr>
  <td >Enzyme concentration</td>
  <td>1.0 µmol/l</td>
  <td></td>
  <td colspan=2></td>
 </tr>
 <tr>
  <td >Vmax</td>
  <td>0.0 µmol/l/min</td>
  <td></td>
  <td colspan=2></td>
 </tr>
 <tr>
  <td >Km</td>
  <td>2.73 µmol/l</td>
  <td></td>
 </tr>
 <tr>
  <td >kcat</td>
  <td>13 1/min</td>
  <td>ParameterIdentification-ParameterIdentification</td>
  <td colspan=2></td>
 </tr>
 <tr>
  <th>Name</th>
  <th>DataSource</th>
  <th>Species</th>
  <th colspan=2></th>
 </tr>
 <tr>
  <td >GlomerularFiltration</td>
  <td>GFR</td>
  <td>Human</td>
  <td colspan=2></td>
 </tr>
 <tr>
  <td colspan=5 align="center"><h4>Process-Parameters</h4></td>
 </tr>
 <tr>
  <th>Name</th>
  <th>Value</th>
  <th >Value Origin</th>
  <th colspan=2></th>
 </tr>
 <tr>
  <td>GFR fraction</td>
  <td>1</td>
  <td></td>
  <td colspan=2></td>
 </tr>
</table>

</details>

@Incei @sfrechen FYI

**Comment by msevestre** [comment]
@Yuri05 Html is not markdown. Not sure what you mean

**Comment by msevestre** [comment]
It's also possible in excel or word. But that's beside the point

**Comment by Yuri05** [comment]
GitHub supports html as part of markdown (s. above). 
Some other tools do. But as I said, for me it's OK to have the output in N tables

**Comment by msevestre** [comment]
Sure. It's however a github specific artefact that they support markdown AND html
but html is not part of the markdown specs
