### ISSUE TITLE
Observer import: rename if existing

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1148]
If observer with existing name is imported, a rename dialog should appear instead of exception.

**Comment by msevestre** [comment]
@Yuri05 Can you explain why you think this feature is required? 
I don't think it's necessary for 7.5 in anyways!

**Comment by Yuri05** [comment]
I think this could easily happen when users create observers with commonly used names e.g. _TotalAmount_, _AverageConcentration_ etc.

Regarding "7.5 or not": let ask users who have requested the feature (@fweysser)

**Comment by msevestre** [comment]
Sure. Let's implement if we have time
