### ISSUE TITLE
MatlabIndividualFactory: "CreateIndividual" method without ontogenies

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1163]
`CreateIndividual(OriginData matlabOriginData, IEnumerable<MoleculeOntogeny> moleculeOntogenies)`

requires an enumerable of molecule ontogenies. If no custom ontogenies are available, Matlab creates an empty vector []<MoleculeOntogeny> and passes it to `CreateIndividual`. The R-to-.NET interface cannot create empty arrays of a certain type, so `CreateIndividual(OriginData matlabOriginData, IEnumerable<MoleculeOntogeny> moleculeOntogenies` cannot be called.

Solution: create a method `CreateIndividual(OriginData matlabOriginData)` that would be called by R.

**Comment by PavelBal** [comment]
On it.

**Comment by msevestre** [comment]
CAn you pass null from R?

**Comment by PavelBal** [comment]
Yes. Would checking for null in .NET code be the prefered solution?

**Comment by msevestre** [comment]
@PavelBal Not necessarily.  Compatibility is always an issue. I do not know if the matlab .NET interface supports overloads for example.

**Comment by msevestre** [comment]
@PavelBal See suggestion on PR. We are going to stick with your suggestion. Simply rewrite how you create an empty enumerable and we are good to go
