### ISSUE TITLE
Feature request: Combination of user defined administrations with advanced protocols

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1170]
Possibility to select "Used defined" as administration when creating and "Advanced protocol".

**Comment by NinaHanke** [comment]
Is this the same proposal? 
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1070#issue-400133683

Would be highly appreciated!!!

**Comment by msevestre** [comment]
@NinaHanke Yes same feature. Going to close one so that we do not have too many duplicates. Thanks for pointing it out

**Comment by LkKov** [comment]
This would help a lot in my case as well!

**Comment by DeniTue** [comment]
Good idea!
I think this would be helpful.

**Comment by msevestre** [comment]
Sneak Preview:
![image](https://user-images.githubusercontent.com/1041237/56326543-69127b00-6144-11e9-91b6-a6b9841c59e8.png)


I just starting tonight. We'll see if I can manage to make it work

**Comment by msevestre** [comment]
Here we go. 
![image](https://user-images.githubusercontent.com/1041237/56382244-fa392e80-61e4-11e9-904f-66db3712a5f2.png)

This will be part of next release if no issue is found in more advanced scenarios
