### ISSUE TITLE
Suggestion: fraction metabolized displayed in PKSim

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/PK-Sim#1171]
Hello. I suppose it would be very helpful to enable showing fraction metabolized by a certain metabolic enzyme when modelling. Maybe as a parameter?

**Comment by AndreDlm** [comment]
I think that would be highly beneficial :)

**Comment by msevestre** [comment]
@AndreDlm Agreed. Not sure why we never implemented it before

/cc @Yuri05 @TWendl @aedginto LET'S DO IT!!

**Comment by msevestre** [comment]
@All: FYI I have landed an implementation here
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1178

With a bit of luck, this will be part of the next release
