### ISSUE TITLE
Names of parameters from PI are exported to snapshot but not re-imported

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#1183]
Snapshot shows correctly:
{
          "Name": "Km UGT1A4",
          "Scaling": "Linear",
          "IsFixed": true,
          "LinkedParameters": [
            "po 3 mg (solution)|Midazolam-UGT1A4-Optimized|Km",
            "po 0.003 mg (solution)|Midazolam-UGT1A4-Optimized|Km",
            "iv 1 mg (5 min)|Midazolam-UGT1A4-Optimized|Km",
            "iv 0.001 mg (5 min)|Midazolam-UGT1A4-Optimized|Km"
          ],
          "Parameters": [
            {
              "Name": "Start value",
              "Value": 37.8,
              "Unit": "µmol/l"
            },
            {
              "Name": "MinValue",
              "Value": 1.0,
              "Unit": "µmol/l"
            },
            {
              "Name": "MaxValue",
              "Value": 378.0,
              "Unit": "µmol/l"
            }
          ]
        }

However, after import of snapshot, the parameter name is just "Km" (which is an issue here, because there is another Km parameter in this PI

**Comment by msevestre** [comment]
Good find
Fixed with https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1184
