### ISSUE TITLE
Suggestion: Rename pksim5 extension to pksim (same with mobi5 to mobi)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1199]
It's safe to assume that our very, very old 4.2 files won't be loaded on a new machine anymore
I'd suggest to rename the extension (of course still support pksim5) but remove the version number in the name, which was a bad idea to begin with

**Comment by PavelBal** [comment]
Agree!

**Comment by UlrichSi** [comment]
I would suggest that project files with the current extension will be still loaded without having to rename them.

**Comment by Yuri05** [comment]
Will not work at least for `.mobi` because the file extension is already in use
https://www.loc.gov/preservation/digital/formats/fdd/fdd000472.shtml
