### ISSUE TITLE
Default Excel export format

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#120]
In 7.1 default Excel export format (for all export operations, e.g. simulation results) seems to be .xls.
Should be .xlsx

**Comment by msevestre** [comment]
I think this is the same behavior as previously. I just tried to export an observed data to excel with 6.3 and the default filter is xls as well.
Can you confirm that this is not new?

**Comment by Yuri05** [comment]
Yes, seems to be the same in 6.3 and 7.0 :confused:
