### ISSUE TITLE
Extract Individual within Population Box Whisker Analysis

### ISSUE THREAD

**Issue by hdiedam** [Open-Systems-Pharmacology/PK-Sim#122]
A right-click option should be available to extract individuals with the plotted values, e.g. specific quantiles of PK parameters, to separate individual building blocks. This would allow follow-up analyses on those individuals, e.g. separate sensitivity analyses for the 5,50 and 95 percentile individuals.

@michblock @Yuri05 

Edit: split into two separate issues (#124 to visualize the information of the individuals to be extracted in the mouse-over).

**Comment by msevestre** [comment]
Should this issue be closed?

**Comment by Yuri05** [comment]
Questions:

:one: Do we need 5 separate menu entries (one per percentile, e.g. **_Extract 5% percentile Individual_**) or just one menu entry for all percentiles? Or both?
:two: How should we proceed if there is more than 1 individual matching some percentile?

**Comment by hdiedam** [comment]
1) One menu entry. The usual ones necessary would be 5/50/95. #123 and #124 combined deal with all other cases that might come up.
2) Warn, stop if too many, export all if its a reasonable number.

**Comment by msevestre** [comment]
>How should we proceed if there is more than 1 individual matching some percentile?
We will export whatever individual Id is shown in the tool tip.

How should we name those individual? Using their id, their percentile or both?

**Comment by michblock** [comment]
I would suggest to combine id and percentile with id in the beginning.
