### ISSUE TITLE
Strange UI behaviour

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1224]
PK-Sim 7.5.0.70, Windows 10, **Windows text size is set to 150%**

* Open PK-Sim, create new empty project and create a PI.
* Right-click on PI and select "Export to Matlab..." 
* Click Cancel in the "Select directory dialog"

The **whole PK-Sim UI is resized** after click on "Export to Matlab..." (even before the dialog is closed via Cancel), especially all the text captions becomes smaller (except for the tree node which is currently selected)

Checked it with 7.4: works fine, no strange resizing.

![grafik](https://user-images.githubusercontent.com/25061876/57074744-14930200-6ce5-11e9-9910-0e269da06c31.png)

Also the display of texts in 150% font size does not look good in 7.5
S. below: left half 7.4, right half 7.5 (
![grafik](https://user-images.githubusercontent.com/25061876/57075656-ad2a8180-6ce7-11e9-9e4f-d590f576004f.png)

**Comment by Yuri05** [comment]
P.S. UI Settings (Icon sizes, Skin) are the same in 7.4 and 7.5

**Comment by msevestre** [comment]
7.4 did not work properly on high res monitor. 
Here is what was happening when starting PK-Sim on a high res monitor

![image](https://user-images.githubusercontent.com/1041237/57078941-48f2c800-6cbd-11e9-8fd1-ebd0886abeaa.png)

or 
![image](https://user-images.githubusercontent.com/1041237/57078965-5a3bd480-6cbd-11e9-9941-3d5e54fb3ac2.png)


We have updated devexpress component and I have removed this one line here (that was not in MoBi and creating a lot of trouble see above)
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim/Program.cs#L26

I am not sure what needs to be done for 150% font. I would suggest that you contact DevExpress support with some screenshots and ask what we should do. 

Maybe we can play with the other settings?  such as this one
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim/Program.cs#L24

**Comment by msevestre** [comment]
https://documentation.devexpress.com/WindowsForms/116666/Common-Features/High-DPI-Support

**Comment by Yuri05** [comment]
>We have updated devexpress component and I have removed this one line here (that was not in MoBi and creating a lot of trouble see above)

Indeed, both MoBi 7.4 and 7.5 look shitty with 150% fonts.

**Comment by PavelBal** [comment]
I think we have fixed this.
