### ISSUE TITLE
Remove TODO in description (Add Observers)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1226]
<img width="400" src="https://user-images.githubusercontent.com/25061876/57133590-8df12a00-6da3-11e9-9780-2b4cebf07cdc.png"></img>

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/57153260-c98bf400-6da3-11e9-8a99-95adfa890fd2.png)
