### ISSUE TITLE
Imported observer not available in the simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1228]
[03_RenameObs.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3141628/03_RenameObs.zip)

In the project attached: Observer-BB contains imported Observer **Plasma_Unbound**
In the simulation this observer is not available
<img src="https://user-images.githubusercontent.com/25061876/57134649-13c2a480-6da7-11e9-8b30-1515d8f5bc3f.png" width="350"></img>

<img src="https://user-images.githubusercontent.com/25061876/57134269-ec1f0c80-6da5-11e9-83cc-3c97d20ce240.png" width="350"></img>

Observer was created by:
* export PK-Sim simulation to MoBi
* rename **Plasma Unbound**-observer to **Plasma_Unbound**
* export **Plasma_Unbound**-observer as pkml and import in PK-Sim

Thus **Plasma_Unbound** should be identical with the original **Plasma Unbound**-Observer and must appear in the list

**Comment by msevestre** [comment]
Thanks for the description. Looks like it should work. Will investigate

**Comment by msevestre** [comment]
Definitely in the simulation 
```
Observer: Plasma Unbound
	Path: asd|Organism|PortalVein|Plasma|Theophylline|Plasma Unbound
	Formula: C_pls*fu
		C_pls: asd|Organism|PortalVein|Plasma|Theophylline|Concentration(0 [µmol/l])
		fu: asd|Theophylline|Fraction unbound (plasma)(0.44)

Observer: Plasma_Unbound
	Path: asd|Organism|PortalVein|Plasma|Theophylline|Plasma_Unbound
	Formula: C_pls*fu
		C_pls: asd|Organism|PortalVein|Plasma|Theophylline|Concentration(0 [µmol/l])
		fu: asd|Theophylline|Fraction unbound (plasma)(0.44)

```

**Comment by msevestre** [comment]
That's because of this guy
```
      private void adjustDisplayNameForMoleculeObserver(PathElements pathElements, IObserver observer)
      {
         //For all fraction observers, the name should remain as is except for liver zone observers that need to be rename explicitly
         if (observerIsFractionOfDoseLiver(observer))
            updateNameElementForFractionOfDose(pathElements, observer);

         else if (!FractionObservers.Any(observer.Name.StartsWith))
            updateNameElementToQuantityDimensionName(pathElements, observer);
      }

```

In this case, we rename the observer to the dimension!

**Comment by msevestre** [comment]
Maybe we should not do that at all. Kind of weird
![image](https://user-images.githubusercontent.com/1041237/57140517-ef0a0500-6d85-11e9-8658-2b537e0cdc26.png)

**Comment by Yuri05** [comment]
hmm, interesting...

**Comment by msevestre** [comment]
These are the names that are renamed

![image](https://user-images.githubusercontent.com/1041237/57143431-e10bb280-6d8c-11e9-9247-2dc80d399ce2.png)


Seems to be wrong for Liver Periportal and Pericentral no?

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/57143639-4b245780-6d8d-11e9-867d-bfcfff8ed9a3.png)

**Comment by msevestre** [comment]
yep
![image](https://user-images.githubusercontent.com/1041237/57143862-d1d93480-6d8d-11e9-8b1b-0b711eb0e8c2.png)
