### ISSUE TITLE
Extract Individual within Building Block

### ISSUE THREAD

**Issue by hdiedam** [Open-Systems-Pharmacology/PK-Sim#123]
A Right-click option on a population building block that opens a GUI element to select an individual within the population by its number and extracts this individual to a separate individual building block is desirable. A spinner with additional text input with limits set to minimum and maximum individual and an OK button should be sufficient. This would unify the user interface and would be a first step toward the extraction described in #122.

@michblock @Yuri05

**Comment by msevestre** [comment]
@hdiedam: A few questions here:

* What is meant here by ` individual number`?

* This would unify the user interface: What do you mean?


If I understand the request properly, the wish is to be able to select a range of individual by `number` (here we need to clarify what that means) and create a new building block for each of the selected individual?  Should we define a limit to the maximum of individual that should be imported at once?

**Comment by Yuri05** [comment]
>Should we define a limit to the maximum of individual that should be imported at once?

That's for sure. Creating 10000 Individuals as building block will for sure kill the UI for a while :boom:

**Comment by Yuri05** [comment]
> What is meant here by `individual number`?

`individual number` is an index of the individual (0 to N-1) used e.g. in the population export to CSV or exporting population results (individual curves) to CSV.

**Comment by hdiedam** [comment]
• This would unify the user interface: What do you mean?

Getting back from the population to a selected individual. #121 would have been a workaround through an export/import. This would be a direct extraction.

**Comment by msevestre** [comment]
Extraction of Range does not make much sense in my opinion.
UI element will allow for comma separated input of Individual Id .
For example
`10, 25,44`

**Comment by msevestre** [comment]
Here is a screenshot of the current implementation. Feedback welcome
![image](https://cloud.githubusercontent.com/assets/1041237/26561779/035251f6-448f-11e7-8537-92eb9b167295.png)

* There are two fields: one where the user enters Ids to generate (comma separated)
* Naming Pattern: used to generate name of individuals created

**Comment by michblock** [comment]
That's exactly, what I had in mind.
Do we get in the Population Simulation Analysis the information about which indiviual(s) is related 
to e.g. to the different percentiles?

**Comment by msevestre** [comment]
@michblock yes: this is a separate issue https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/124

see https://cloud.githubusercontent.com/assets/1041237/26383741/9a09de66-4002-11e7-8f7a-54a35cf537f7.png
