### ISSUE TITLE
EAP 7.5: Create/Edit Observer set shows heavy construction tool

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#1234]
When right-clicking underneath the text in the window, the "Wrench - customize layout" dialogue window appears. The same happens if an observer BB is opened for edit. I presume this is not intended.

![grafik](https://user-images.githubusercontent.com/27352743/57298431-7d59f000-70d2-11e9-8c40-d3eddadfc8ce.png)

**Comment by msevestre** [comment]
indeed
