### ISSUE TITLE
Show Individual Numbers within Population Box Whisker Analysis

### ISSUE THREAD

**Issue by hdiedam** [Open-Systems-Pharmacology/PK-Sim#124]
To connect the values in those plots, e.g. specific quantiles of PK parameters, with individuals, the mouse-over text above the box whisker analysis plots should additionally show the individual numbers associated with the corresponding value. This would allow follow-up analyses on those individuals, e.g. separate sensitivity analyses for the 5,50 and 95 percentile individuals.

(split from #122 that would allow a quick extraction of those individuals)

**Comment by msevestre** [comment]
@hdiedam Same question as in #123 
`show the individual numbers associated with the corresponding value`.

**Comment by msevestre** [comment]
`individual number` is the `individualId` (generated based on the index of the individual in the population)

**Comment by msevestre** [comment]
@hdiedam @Yuri05 
A little issue here is that the percentile value (for example 95%) does not necessarily corresponds to an exact value in the population. 

see implementation here
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Extensions/MathExtensions.cs#L123

Which IndividualId should then be used? the k -1 or k (k refers to the parameter in the code)

**Comment by msevestre** [comment]
@all: I have used k, as k-1 is a value that potentially can be below the percentile
Here is how it look like. Please let me know if this is what you had in mind or how I should modify the tooltip

![image](https://cloud.githubusercontent.com/assets/1041237/26383741/9a09de66-4002-11e7-8f7a-54a35cf537f7.png)

**Comment by hdiedam** [comment]
The tooltip looks great. I will open a separate ticket for an improved documentation regarding the quantile methods involved.

**Comment by Yuri05** [comment]
Should we add **Individual** into the tool tip, e.g. 
_95%=100 kg, **Individual** #12345_ ?

**Comment by msevestre** [comment]
Let me put a screenshot with that as well and we can decide what looks
best. Also we could use IndividualId = xx since this is what we export in
Excel?

**Comment by Yuri05** [comment]
>Also we could use IndividualId = xx since this is what we export in Excel?

Yep, sounds good for me

**Comment by msevestre** [comment]
With Individual

![image](https://cloud.githubusercontent.com/assets/1041237/26405979/ec86a266-4064-11e7-9d1f-a35ce9da0271.png)

With IndividualId
![image](https://cloud.githubusercontent.com/assets/1041237/26406021/0b7aceea-4065-11e7-88c6-2cb1902e8725.png)

Thoughts?

**Comment by Yuri05** [comment]
`IndividualId = NN` looks better for me
