### ISSUE TITLE
Advanced Application protocol not imported correctly from snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1242]
[ErrorImportAppFormSnapshot.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3161717/ErrorImportAppFormSnapshot.zip)
Project attached has advanced import protocol with 6 repetitions
After Export/Import from snapshot: only 1 repetition

#Before
![grafik](https://user-images.githubusercontent.com/25061876/57448398-9214c000-7259-11e9-9ad5-2832a2941722.png)

#After
![grafik](https://user-images.githubusercontent.com/25061876/57448427-a658bd00-7259-11e9-95b1-4a8d37d92362.png)

**Comment by msevestre** [comment]
@Yuri05 How was this protocol created. For some reasons, the parameters Number of rep etc.. are not marked as IsInput and as such are not saved into the snapshot. 

Was it created BEFORE we introduced the IsInput flag?

I cannot reproduce with a brand new advanced protocol

**Comment by Yuri05** [comment]
with a new adv protocol I cannot reproduce as well.
@sfrechen any comments on how the protocol was created?

**Comment by sfrechen** [comment]
I assume via cloning of others (but created with 7.4). Anyway, I'll fix manually now.

**Comment by msevestre** [comment]
@sfrechen That would be good to be able to reproduce it. If the source protocol was indeed created in 7.4, then there is a bug. If it was created in 7.3 then no bug....

**Comment by Yuri05** [comment]
cannot reproduce it anymore. closing
@sfrechen please reopen if you get this error again
