### ISSUE TITLE
Multiple compound definitions (over a 100) in PKSim

### ISSUE THREAD

**Issue by PriKalra** [Open-Systems-Pharmacology/PK-Sim#1259]
Dear All, 

Is there a smart way to define 150+ compounds in PKSim without constantly adding a compound?
Like some software allow a batch input of the various values which are compound specific and hence help create the compound. 

Best, 
Pri

**Comment by msevestre** [comment]
@PriKalra This seems to be a very unlikely scenario for PK-Sim. What are you trying to achieve? What type of information do you have on each compound?

**Comment by msevestre** [comment]
@PriKalra Otherwise there is some hidden batch features. You can follow the suggestion here 
https://github.com/Open-Systems-Pharmacology/Forum/issues/305

but as mentioned before, this is probably not how you should be using PK-Sim

**Comment by StephanSchaller** [comment]
Depending on the differences between the compounds, if you generate a generic PKSim Simulation that includes generic processes that contain all of the ADME properties of all compounds and then go to MATLAB/R it should be easy to go through a batch simulation that loops through a table (e.g. excel/csv sheet) containing the specific ADME processes parameters for each compound…


I guess you would want to be in R anyway to analyze the results from a batch run.

**Comment by PriKalra** [comment]
Hi, 
Thank you for the comments. My intention is to roughly go in this direction with the same: [Incorporating High-Throughput Exposure Predictions With Dosimetry-Adjusted In Vitro Bioactivity to Inform Chemical Toxicity Testing](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4620046/)

**Comment by StephanSchaller** [comment]
Yes, so as I wrote above. Maybe the excel table would contain the raw input compound properties (in-vitro physchem & metabolism) and you would do some IVIVE pre-calculations within the script as they do in their paper and then plug these values into your generic PBPK in high-throughput fashion in R.

It will take some time but you will not really be able to do this conveniently through the GUI in PK-Sim (but maybe through the CLI, but I guess more challenging, depending on by how much the PBPK models for each compound differ).

And of course it is convenient if you need to do 100 more at a later time.

**Comment by PriKalra** [comment]
thanks a lot stephan! I will use the batch input approach.

**Comment by msevestre** [comment]
@PriKalra Closing. Please reopen the issue if you need more assistance. Also as an FYI, questions are better asked in the forum. Cheers
