### ISSUE TITLE
Figure in Formulation BB displaying Fraction dissolved has cropped x-axis title

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1263]
In v.8.0.5 the x-axis title and annotation of the Figure showing the dissolved fraction for e.g. a Weibull function is cropped:

![Untitled](https://user-images.githubusercontent.com/26541603/58265837-c1125200-7d80-11e9-86da-4a71e53dafee.png)

This happens for any formulation type, not just Weibull

**Comment by msevestre** [comment]
Weird

**Comment by msevestre** [comment]
@AndreDlm Fixed. Thanks for reporting
