### ISSUE TITLE
Irritating info message

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1268]
Info message "_Qualification run finished_" comes every time **_before_** the next project is loaded from snapshot and exported. Thus it looks like below for several minutes and the user might think that the qualification runner is finished (or crashed).
<img width="300" src="https://user-images.githubusercontent.com/25061876/58323774-47806f80-7e25-11e9-803c-90d091b189d6.png"></img>

The info message should either come **_after_** the project is loaded from snapshot or should not come at all. 
Actually instead of "_Qualification run finished_" in the screen above I would expect something like "_Reloading project from snapshot. This might take some time_"

**Comment by msevestre** [comment]
here is the output now
![image](https://user-images.githubusercontent.com/1041237/58589115-29ed4480-822f-11e9-8494-d650eb121909.png)
