### ISSUE TITLE
Another Strange Behavior of the Chart Editor PK-Sim 7.4

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1271]
steps to reproduce:
create Simulation with existing BB. click Run, let everything on default (only peripheral venous blood plasma is selcted) and click OK

![image](https://user-images.githubusercontent.com/25585248/59023470-2ae62d80-8850-11e9-9638-776a215156dd.png)

results look like expected
![image](https://user-images.githubusercontent.com/25585248/59023505-40f3ee00-8850-11e9-83ca-25e2acb9fc59.png)
than save project and close.
Open Project again, open Simulation (e.g. Test 3) . Now Venous Blood Plasma and Lume fraction of oral dose absorbed is visible (However it is not checked or selected)

![image](https://user-images.githubusercontent.com/25585248/59023554-59fc9f00-8850-11e9-861a-7b8a9397ec69.png)

Why does this happen apparently without any user input?

**Comment by tobiasK2001** [comment]
[Bug Curves and Axes Options in Graph editor.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3261019/Bug.Curves.and.Axes.Options.in.Graph.editor.zip)

**Comment by msevestre** [comment]
These outputs are always available in order to calculate different fractions for PK-Analysis. So this is just a display issue. Nothing to worry about

**Comment by tobiasK2001** [comment]
Ah, Ok. Thanks for letting me know;-)
