### ISSUE TITLE
Issue when exporting snapshot with changed building block parameters in simulations

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#1290]
If a project cotains simulations with changed building block parameters (red sign), thex export to json throws a warning.
However, actually it works properly. Also re-loading the snapshot works with the changed parameter. Only the "red sign" is missing (it shows the green sign.)

Please fix!

**Comment by msevestre** [comment]
```
WARNING:
Some simulations are in a changed state (red icon) and may not be re-imported correctly.
```

hum... clearly the message says don't do this because reimport won't work. What's the problem?

**Comment by sfrechen** [comment]
Well, obviously it happens that we work with changed state simulations and would like to keep it. Is it problematic to implement?

**Comment by msevestre** [comment]
@sfrechen Yes it is not straightforward. That's why it is not implemented.

**Comment by sfrechen** [comment]
The changed state is probaly a property? Can it not be added to the json specification?

**Comment by Yuri05** [comment]
>Can it not be added to the json specification?

This does not make sense. Changed state must be recognized automatically.

Also imagine e.g. the following scenario:
* you change some pH value (e.g. pH of intracellular space) in a simulation from 7 to 7.5 and export to a snapshot.
* In the next PK-Sim version you decide that `pH=7.5` should become the **new default value in the individual** and change the PK-Sim database accordingly.
* Now when recreating your project from a snapshot the program must **guess** how to handle it - was your intention to use in the simulation:
  1. the **default pH value from the individual** or
  2. the **fixed value pH=7.5**

In case 1: e.g. reconfiguring a simulation and selecting another individual with another pH will **change it in the simulation**
In case2: the same action will **keep pH=7.5** in the simulation.

Ofc PK-Sim could ask you for all those cases explicitely, how to handle then, but this would produce another problems (recreating from a snapshot must be completed without any interactions with user in batch mode like qualification workflows etc.)

So as you can see there are quite some complications with exporting simulations in a changed state to a snapshot.

**Comment by sfrechen** [comment]
Rather theroretic than practical ;-) but fair enough. The alternative (current implementation) is also npt unproblematic. I would suggest:
In case building block parameters are changed in simulations -> keep them as simulation parameters and convey the "changed state" icon.

**Comment by Yuri05** [comment]
btw. my example was invalid :) (exchanging an individual-BB in a simulation would also replace the changed pH). Have to think about a better one.

**Comment by msevestre** [comment]
> In case building block parameters are changed in simulations -> keep them as simulation parameters and convey the "changed state" icon.

This is not the only scenario.
If you change a building block parameter (for example your individual) and export to snapshot, the simulation will be recreated using the changed building block, not the original one. 

The only scenario that could work would be "Changing parameters in simulation". As soon as you change a parameter in the building block, you are in for a lot of pain

**Comment by sfrechen** [comment]
Changing a building block parameter in the building block and not updating any simulation is not meaningful and should not be done for any of our compounds being officially released at OSP.

"Changing parameters in simulation" is quite common for a few simulations within a project!

**Comment by msevestre** [comment]
ok. If we agree to only take parameters changed in the simulation, then that could work. We should be able to retrieve the simulation state for each building block and overall state. 
If the building block were changed however, this will fail

**Comment by sfrechen** [comment]
Perfect!

**Comment by StephanSchaller** [comment]
Can we identify the use-cases, where you may have several simulations with changed parameters?

This might also be an opportunity to change the logic such that we might not need "changed" simulations.

E.g. an example that I have is different Kd FcRn for different species. Similar to e.g. lipophilicity it should be possible to define several Kd FcRn values per compound.

**Comment by msevestre** [comment]
>This might also be an opportunity to change the logic such that we might not need "changed" simulations.

You are referring to building block augmentation (e..g adding a variation of a parameter). Ideally this should not lead to simulation becoming red, but this is not always clear cut.

As soon as someone changes a parameter in the simulation (this is the use case we are talking about here I believe) the simulation will turn red. I don't see any other way around this

**Comment by StephanSchaller** [comment]
> You are referring to building block augmentation

Correct. 

> changes a parameter in the simulation (this is the use case we are talking about here I believe)

Yes, but in an ideal scenario, if a project is "cleaned up", there should be no more "red" simulations, or not?
But at this time sometimes you are forced to. "Forced" meaning, there is no way around it (e.g. in my given use-case above).

...just a thought. maybe not the right thread to bring it up,

**Comment by sfrechen** [comment]
Building block augmentation maybe a reasonable way for some parameters but definitely not for all and nor every case. So, let's focus here on cases where changed simulations make sense ;-)

**Comment by msevestre** [comment]
ok this will be implemented in V9

**Comment by msevestre** [comment]
>However, actually it works properly. Also re-loading the snapshot works with the changed parameter. Only the "red sign" is missing (it shows the green sign.)

Upon further investigation. It does not work properly. I can update the red flag to show the status update. However the comparison will not work at the moment. Investigating to see if this is easily fixable or not.
