### ISSUE TITLE
Error on file opening

### ISSUE THREAD

**Issue by wilbertdew** [Open-Systems-Pharmacology/PK-Sim#1298]
Hi All,

After editing my file yesterday, when everything worked fine, reopening today gave the following error:
![image](https://user-images.githubusercontent.com/8969023/61520295-2cd60b80-aa0e-11e9-8831-cbd92ce5be48.png)

Interestingly, I can still open the history tab after closing this error window and see what I did yesterday:
![image](https://user-images.githubusercontent.com/8969023/61520378-54c56f00-aa0e-11e9-84ff-7a2b8cb5bf87.png)

However, when I try to rollback 722, the opening of the file today, nothing happens. When I try to rollback 721, I get the following error:
![image](https://user-images.githubusercontent.com/8969023/61520449-82aab380-aa0e-11e9-8b81-0b0d411d7101.png)

Any ideas how I can recover my work?

Best,

Wilbert

**Comment by msevestre** [comment]
@wilbertdew You can send me your project and I can look at it (michael@design2code.ca)
If your project is public, you can simply upload it here
Cheers

**Comment by wilbertdew** [comment]
@msevestre Thanks for your offer. Unfortunately, I cannot share the file due to the confidential observed data included. I already tried with the nightbuild, same problem. I am afraid I have to redo the work then.
Thanks for your time. Based on a previous thread on this forum where I read that the PK-Sim files are SQLite databases I followed the steps as described [here](https://www.recoveryandmanagement.com/repair-sqlite-database-manually/). I could complete all steps but retrieved the same error, and did not get an error about a corrupted file from the DB browser.

**Comment by msevestre** [comment]
This is not an issue with the database. It is probably an action that you performed that resulted in a corrupted state. 

When does this error occur? When you start the project? Or when you open a simulation?

**Comment by wilbertdew** [comment]
When I open the project.

**Comment by msevestre** [comment]
@wilbertdew it is likely an easy fix in that case. At any rate, if you change your mind, let me know (or we can sign an NDA). Cheers

**Comment by wilbertdew** [comment]
@msevestre Thanks, I think that could be helpful for the future! For now, redoing the work is probably faster than waiting for the NDA ;)

**Comment by msevestre** [comment]
Sure. It would be great to know however what you did so that we can fix the bug. Because it will happen again
