### ISSUE TITLE
Population export to CSV - constants mapping

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1300]
The CSV resulting from export of a PK-Sim population has rows "IndividualId", "Gender", "RaceIndex", "PopulationName", and the paths of the parameters.

Is there somewhere a list defining how the numerical entries of Gender and RaceIndex are mapped to the selected genders and populations?
In case of gender, I guess `{1, 2, 3} = {MALE, FEMALE, UNKNOWN}`.

RaceIndex is probably
```
European_ICRP_2002 = 0, WhiteAmerican_NHANES_1997 = 1, BlackAmerican_NHANES_1997 = 2,
MexicanAmericanWhite_NHANES_1997 = 3, Asian_Tanaka_1996 = 4, Preterm = 5, Japanese_Population = 6
```
but how is it for non-human species? E.g., `Dog = 22`, but where can I actually see a list of correct mappings?

**Comment by msevestre** [comment]
This all comes from the database. Typically those are internal values only and as a user, you should normally not have to care about them

from the pksim db 

tab species

species | display name | description | sequence | user_defined | icon_name | is_human
-- |-- |-- |-- |-- |-- |-- 
Beagle |Beagle |Beagle |3 |0 |Beagle |0
Dog |Dog |Dog |4 |0 |Dog |0
Human |Human |Human |1 |0 |Human |1
Minipig |Minipig |Minipig |5 |0 |Minipig |0
Monkey |Monkey |Monkey |2 |0 |Monkey |0
Mouse |Mouse |Mouse |7 |0 |Mouse |0
Rabbit |Rabbit |Rabbit |10 |0 |Rabbit |0
Rat |Rat |Rat |6 |0 |Rat |0


tab populations

population | race_index | species | display_name | description | is_age_dependent | is_height_dependent | icon_name | sequence
-- | -- | -- | -- | -- | -- | -- | -- | -- 
Asian_Tanaka_1996 | 4 | Human | Asian (Tanaka, 1996) | Asian (Tanaka, 1996) | 1 | 1 | 5
Beagle | 20 | Beagle | Beagle | Beagle | 0 | 0 | 9
BlackAmerican_NHANES_1997 | 2 | Human | Black American (NHANES, 1997) | Black American (NHANES, 1997) | 1 | 1 | 3
Dog | 23 | Dog | Dog | Dog | 0 | 0 | 10
European_ICRP_2002 | 0 | Human | European (ICRP, 2002) | European (ICRP, 2002) | 1 | 1 | 1
Japanese_Population | 6 | Human | Japanese (2015) | Japanese (2015) | 1 | 1 | 7
MexicanAmericanWhite_NHANES_1997 | 3 | Human | Mexican American - White (NHANES, 1997) | Mexican American - White (NHANES, 1997) | 1 | 1 | 4
Minipig | 24 | Minipig | Minipig | Minipig | 0 | 0 | 11
Monkey | 25 | Monkey | Monkey | Monkey | 0 | 0 | 12
Mouse | 26 | Mouse | Mouse | Mouse | 0 | 0 | 13
Pregnant | 7 | Human | Pregnant (Dallmann et al. 2017) | Pregnant (Dallmann et al. 2017) | 1 | 1 | 8
Preterm | 5 | Human | Preterm | Preterm | 1 | 1 | 6
Rabbit | 28 | Rabbit | Rabbit | Rabbit | 0 | 0 | "" | 15
Rat | 27 | Rat | Rat | Rat | 0 | 0 | 14
WhiteAmerican_NHANES_1997 | 1 | Human | White American (NHANES, 1997) | White American (NHANES, 1997) | 1 | 1 | 2

**Comment by PavelBal** [comment]
> Typically those are internal values only and as a user, you should normally not have to care about them

I have to care if I want to create a population-csv in MatLab using the function PKSimCreatePopulation ;)

Thanks!

**Comment by msevestre** [comment]
```
      /// <summary>
      ///    Id of population (as defined in the database)
      /// </summary>
      public string Population { get; set; }
```
 I think you need the population Id not the index...
