### ISSUE TITLE
PK-Sim erroneously consumes almost full processor capacity

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/PK-Sim#1301]
PK-Sim consumes almost full processor capacity even though "priority" has been set to "low".

- standard PBPK Model
- PK-Sim 8, build 22
- Windows 10

**Comment by msevestre** [comment]
@lkuepfer Can you explain the context of this processor usage? 
Are you running a simulation, population simulation, PI, Sensitivity?

Also note that by default, for all the tasks that can be parallelized, PK-Sim will use `Number Of Core -1` on your machine

So If you have 8 cores, it will use 7. This setting can be changed in the UserSettings . What value do you have in your user settings?

**Comment by lkuepfer** [comment]
I am doing a „simple“ PI with 7 dosing schemes i.e. simulations. The maximal number of processors to use is set to 7 in the user settings.

However, PK-Sim was basically taken over all computational resources of my (rather new) laptop such that I could basically not work any more. As mentioned I had even set the priority to “low” .

Von: Michael Sevestre <notifications@github.com>
Gesendet: Montag, 29. Juli 2019 14:45
An: Open-Systems-Pharmacology/PK-Sim <PK-Sim@noreply.github.com>
Cc: Lars Kuepfer <lars.kuepfer@bayer.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Open-Systems-Pharmacology/PK-Sim] PK-Sim erroneously consumes almost full processor capacity (#1301)


@lkuepfer<https://github.com/lkuepfer> Can you explain the context of this processor usage?
Are you running a simulation, population simulation, PI, Sensitivity?

Also note that by default, for all the tasks that can be parallelized, PK-Sim will use Number Of Core -1 on your machine

So If you have 8 cores, it will use 7. This setting can be changed in the UserSettings . What value do you have in your user settings?

**Comment by msevestre** [comment]
> As mentioned I had even set the priority to “low” .

**Comment by lkuepfer** [comment]
I.e. the priority of PK-Sim in the  Task-Manager was set to “low”

Von: Michael Sevestre <notifications@github.com>
Gesendet: Montag, 29. Juli 2019 15:51
An: Open-Systems-Pharmacology/PK-Sim <PK-Sim@noreply.github.com>
Cc: Lars Kuepfer <lars.kuepfer@bayer.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Open-Systems-Pharmacology/PK-Sim] PK-Sim erroneously consumes almost full processor capacity (#1301)


As mentioned I had even set the priority to “low” .

**Comment by Yuri05** [comment]
@lkuepfer 

>I am doing a „simple“ PI with 7 dosing schemes i.e. simulations. The maximal number of processors to use is set to 7 in the user settings.

If` maximal number of processors=7` is the _deafult_ setting: that means that you have 8 cores (or 8 hyper threads).
7 simulations in your PI will be then perfectly parallelized on 7 cores and PK-Sim will consume 87.5% of your CPU. If other tasks are active at the same time: you CPU usage will be even higher.

Setting priority of PK-Sim to low will just give priority to other potential applications (and the usage of CPU by PK-Sim will be only reduced by `amount of other's applications usage - 12.5%`). Thus your overall CPU usage will be in this case always between 87.5% and 100% irregardless how you set its priority.

In my eyes everything is working as expected.

**Comment by lkuepfer** [comment]
Even if other „applications“ means opening a simple folder? Basically, I could not work at all and had to close PK-Sim. Something like that never happened before…

Von: Juri Solodenko <notifications@github.com>
Gesendet: Montag, 29. Juli 2019 18:59
An: Open-Systems-Pharmacology/PK-Sim <PK-Sim@noreply.github.com>
Cc: Lars Kuepfer <lars.kuepfer@bayer.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Open-Systems-Pharmacology/PK-Sim] PK-Sim erroneously consumes almost full processor capacity (#1301)


@lkuepfer<https://github.com/lkuepfer>

I am doing a „simple“ PI with 7 dosing schemes i.e. simulations. The maximal number of processors to use is set to 7 in the user settings.

If maximal number of processors=7 is the deafult setting: that means that you have 8 cores (or 8 hyper threads).
7 simulations in your PI will be then perfectly parallelized on 7 cores and PK-Sim will consume 87.5% of your CPU. If other tasks are active at the same time: you CPU usage will be even higher.

Setting priority of PK-Sim to low will just give priority to other potential applications (and the usage of CPU by PK-Sim will be only reduced by amount of other's applications usage - 12.5%). Thus your overall CPU usage will be in this case always between 87.5% and 100% irregardless how you set its priority.

In my eyes everything is working as expected.

**Comment by msevestre** [comment]
I think the key is "Pi with 7 simulations".
This will use one core per simulation because you are allowing 7 cores to be used

If you decide to use your laptop while doing PI with many simulations, the easiest way is to restrict the number of cores to 6 or less

And it's not because you are not doing anything that the computer is not doing something.... Especially when you know of the infamous `virenscanner`

**Comment by lkuepfer** [comment]
Thank you very much for your help! That makes sense. I will give it a try.

Von: Michael Sevestre <notifications@github.com>
Gesendet: Montag, 29. Juli 2019 22:45
An: Open-Systems-Pharmacology/PK-Sim <PK-Sim@noreply.github.com>
Cc: Lars Kuepfer <lars.kuepfer@bayer.com>; Mention <mention@noreply.github.com>
Betreff: Re: [Open-Systems-Pharmacology/PK-Sim] PK-Sim erroneously consumes almost full processor capacity (#1301)


I think the key is "Pi with 7 simulations".
This will use one core per simulation because you are allowing 7 cores to be used

If you decide to use your laptop while doing PI with many simulations, the easiest way is to restrict the number of cores to 6 or less

And it's not because you are not doing anything that the computer is not doing something.... Especially when you know of the infamous virenscanner

**Comment by PavelBal** [comment]
From my experience it is the RAM that limits the overall performance, not the CPU load. Check the memory usage in the task manager.

**Comment by Yuri05** [comment]
Closing. @lkuepfer Please reopen if you still face the problem.
