### ISSUE TITLE
IsInput for advanced protocol parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1302]
When adding protocol parameters on the fly: `IsInput `should be set to true
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/739a0d73c2832762d4879bf5c0004bf0612b662b/src/PKSim.Core/Model/SchemaFactory.cs#L45-L47

At the moment we get sometimes problems with advanced protocol parameters (e.g. number of repetitions or time between repetitions) when exporting projects to snapshots.
Parameters are changed by user but do not appear in the snapshot.
This happens also to newly created projects (e.g. created with PK-Sim 7.4)
Hard to reproduce however.

When we set those parameters to `IsInput=true` from the beginning (which I think should be the case anyway), the problem should be solved.

**Comment by Yuri05** [comment]
@sfrechen @AndreDlm FYI

**Comment by msevestre** [comment]
Also linked to #1601 and fixed with #1648
