### ISSUE TITLE
Deactivated processes activated after reimport from snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1314]
In hte project attached GFR in compound was defined, but deactivated in the simulation configuration
[P3.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3575570/P3.zip)
![grafik](https://user-images.githubusercontent.com/25061876/64273740-42fa4580-cf42-11e9-9c2f-8c6853533511.png)

When exporting to snapshot and reimporting: GFR is active.
![grafik](https://user-images.githubusercontent.com/25061876/64273903-8f458580-cf42-11e9-825f-9d9fbf031cee.png)

**Comment by msevestre** [comment]
The same also for other processes it seems

**Comment by msevestre** [comment]
>When exporting to snapshot and reimporting: GFR is active.

**Comment by msevestre** [comment]
In fact, we have the same issues with interactions but to a lesser extent because we do not really map automatically I believe
