### ISSUE TITLE
Cannot confugure or clone simulation after renaming of Administratio Protocol

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1320]
If simulation has the same name as administration protocol used in it: after renaming of the administration protocol simulation cannot be reconfigured or cloned anymore.
![grafik](https://user-images.githubusercontent.com/25061876/65378331-2aff2180-dcb7-11e9-8e81-624e05505313.png)

To reproduce: in the project attached rename the administration protocol from `aa `to `bb `and try to reconfigure the simulation: error below pops up.
[P3.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3639022/P3.zip)

![grafik](https://user-images.githubusercontent.com/25061876/65378543-1a03df80-dcba-11e9-8af5-2aaad22a19bd.png)

somehow renaming was made in the wrong place (the correct path would be _**aa**|Applications|**bb**|..._)

**Comment by msevestre** [comment]
Murphy's law or something....

**Comment by msevestre** [comment]
I am not sure why you think this is a nasty bug @Yuri05 I have just spent 4 hours trying to fix it and this is not easy at all. Any reason why naming stuff the same makes any sense?
