### ISSUE TITLE
Value origin Japanese Population

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1323]
Now after Japanese population report was finally published (https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/blob/master/Japanese_Population/Report.md):
we should update value origin for the Japanese population data in the PK-Sim database.

**Comment by StephanSchaller** [comment]
This looks nice! Well done!

Is there also a publication associated with this?
Can you also make an announcement on the release of the Report in the Forum?
