### ISSUE TITLE
Unhandled exception with PK-sim and Windows

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1326]
Pk-sim just crashed with this note:
![image](https://user-images.githubusercontent.com/25585248/66897279-eedd8900-eff6-11e9-80b4-58ac41d6c326.png)

I was just trying to update a chart template to save some minor change in a comparison chart.
while reponing I realised that the app was still running in the background
![image](https://user-images.githubusercontent.com/25585248/66897368-26e4cc00-eff7-11e9-89a8-b6b386bb7331.png)
 Not sure if you can reproduce it or if it even worth it trying to do so. Just to let you know.

Best, Tobias

**Comment by msevestre** [comment]
@tobiasK2001 Thanks for reporting. This looks like a memory pressure issue. We probably won't be able to reproduce. Please reopen if this happens again

**Comment by Yuri05** [comment]
>This looks like a memory pressure issue. We probably won't be able to reproduce. Please reopen if this happens again

Agree. 
@tobiasK2001  You can also try to [increase max. amount of windows graphic handles](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/862#issuecomment-466048852) if the problem occurs again

**Comment by tobiasK2001** [comment]
Thanks Juri,
I did a change in the regedit accordingly and will let you know, if the problem happens again.
Best, Tobias
