### ISSUE TITLE
Population export: Replace RaceIndex and gender as number with actual string?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1327]
At the moment, we export gender with 1 and 2 and Race with index in pop. My suggestion would be to move away from index as defined in the db and use strign instead. This would allow further classification in R (group by gender etc..) to be much more straighforward

**Comment by msevestre** [comment]
@Yuri05 thoughts?

**Comment by Yuri05** [comment]
Fine with that.

**Comment by msevestre** [comment]
We would still support the old format when loading a pop in PKSim

**Comment by PavelBal** [comment]
Yes!

**Comment by msevestre** [comment]
ok moving to v9 then as this will be very useful for R integration

**Comment by msevestre** [comment]
This has been implemented in #1333 
Project conversion required but now, Gender and Race are exported using their DB name as opposed to index

**Comment by msevestre** [comment]
Should we call the column Population BTW? Or are we happy with Race?

**Comment by Yuri05** [comment]
>Should we call the column Population BTW?

I would say YES

**Comment by msevestre** [comment]
AGreed. I'll do it
