### ISSUE TITLE
Export to snapshot / reimport in PK-Sim alters protein reference concentration

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1330]
The attached PK-Sim file contains a European Standard individual with 2 CYP3A4 enzymes (`CYP3A4` and `CYP3A4 1`), both loaded from the gene expression database with a reference concentration of 4.32 µmol/L each.
When exporting the file to Snapshot (attached) and re-importing it in PK-Sim, the reference concentration of  `CYP3A4 1` is set to 1 µmol/L.

[Alprazolam.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3766422/Alprazolam.zip)

**Comment by msevestre** [comment]
Because we do not save the relexp query (rather the relexp expression value), I'd suggest to `always` save the global parameters in snapshot (RelExp and T1/2s). We hardly have any default value anyways and this would make the whole experience much cleaner and predictable

**Comment by Yuri05** [comment]
>I'd suggest to always save the global parameters in snapshot (RelExp and T1/2s). 

@AndreDlm @sfrechen @TWendl do you agree?

**Comment by sfrechen** [comment]
Agree to Michael.
Might be worth to re-evaluate once we would come up with another database concept for relExp and refConc.

**Comment by TWendl** [comment]
Agree to Michael as well!
For future releases: Would it be possible to technically enable the matching of two processes to the same enzyme? E.g. in AndreDlm's example two metabolic processes to the same enzyme (CYP3A4) such that there is no need to create an additional Enzyme (CYP3A4 1)?

**Comment by sfrechen** [comment]
@TWendl That is already possible.

**Comment by TWendl** [comment]
@sfrechen OK! Didn't know that! Thanks!

**Comment by msevestre** [comment]
Ok majority rules here (sorry @AndreDlm as you did not respond). I'll implement it as described here
