### ISSUE TITLE
Concentration observer

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1351]
@msevestre Any idea why the "Concentration in container" observer is not just set to "..\Concentration" (concentration parameter) but has the same formula instead?
![grafik](https://user-images.githubusercontent.com/25061876/68942721-8fb39580-07a9-11ea-9110-0f943e82ea16.png)
![grafik](https://user-images.githubusercontent.com/25061876/68942818-c5587e80-07a9-11ea-99f3-fbdf3f20716c.png)

**Comment by Yuri05** [comment]
so actually I would expect that the observer is defined as below and not by duplicating the formula.
(for the special cases like concentration in lumen we have **additional** observers; thus for the "standard" concentration observer I don't see any use cases where we could not just set it = concentration parameter)
![grafik](https://user-images.githubusercontent.com/25061876/68943062-6a735700-07aa-11ea-8cc4-094d38fd7cc6.png)

**Comment by msevestre** [comment]
@Yuri05 Could it be because of the numerical issue with observers? Maybe this is not relevant anymore but at some point it might have been ?

**Comment by Yuri05** [comment]
>Could it be because of the numerical issue with observers?

No, setting Observer = f(Parameter) is save. The opposite direction would be dangerous.

>Maybe this is not relevant anymore but at some point it might have been ?

Maybe.. It's not wrong anyway, just not optimally solved due to the formula duplication.

**Comment by msevestre** [comment]
@Yuri05 Should I just update it?

**Comment by Yuri05** [comment]
yes

**Comment by msevestre** [comment]
ok done in #1352
