### ISSUE TITLE
AUCR and CmaxR wrong calculated in PL-Analysis if dose is changed in Simulation parameters

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#1362]
A DDI simulation was created with linear CL processes. So AUCR and CmaxR should not change when doubling the victim dose. However, when victim dose is doubled in simulation Parameters, Simulation rerun and clicked in PK-analysis to rerun CmaxR and AUCR, the ratios have doubled.
If the original DDI simulation is cloned and the double victim dose is used in the clone, after Simulation rerun and clicked in PK-analysis to rerun CmaxR and AUCR, the ratios are the same.

Looks like if the victim dose is just increased in the simulation parameters and the DDI is rerun the AUC without inhibitor is not calculated with the right victim dose given in the simulation parameters. 
Looks like a nasty bug for me. PK-sim 8 build 22 was used.

best, Tobias

**Comment by msevestre** [comment]
Can you attach a project that reproduces the issue?

**Comment by tobiasK2001** [comment]
I cannot attach the original one, but here is the problem reproduced with PK-Sim template BB.
As I used the Midazolam template the CL is not linear in this example. However the effect should only be slight and not skyrocketing when just doubling the dose. Other wise the Simulations were created as described above. While reproducing I had the feeling the problem could be connected to the fact that the victim is given in an "advanced protocol at day 4. However I didn't try if it is the same with a simple  protocol.

[AUCR and CmaxR wrong calculated in PL-Analysis if dose is changed in Simulation parameters (#1362).zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3897641/AUCR.and.CmaxR.wrong.calculated.in.PL-Analysis.if.dose.is.changed.in.Simulation.parameters.1362.zip)


Good luck

**Comment by msevestre** [comment]
ok i see. you are changing the protocol IN the simulation .Sorry I missed that bit of info

**Comment by msevestre** [comment]
Ok found the issue. It will be fixed in the next version
