### ISSUE TITLE
Feature reqeust: Bi-directional active transports

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1363]
For transporter proteins, we can select "Influx" and "Efflux" (and "Pgp-like", whatever that means) as directions. However, many transpoters transport in both ways based on the concentration gradient.

Can this option be implemented?

**Comment by UlrichSi** [comment]
I believe that should be possible - at least via MoBi, the transport equations can already be changed to have bidirectional transport. 
The question is if a bidirectional transport is not easier to implement via a passive transport which is already present and where just its permeability coefficient may have to be changed. If you need asymmetric transport, the combination of increased permeability and a unidirectional active transport into the desired direction might be a solution.

Regarding "Pgp-like", you may want to start here to better understand the mechanism and find its synonyms:
https://en.wikipedia.org/wiki/P-glycoprotein
Briefly, it is a protein that removes lipophilic/amphiphilic substances that have diffused into the cell membrane by actively pumping them to the outside.

**Comment by PavelBal** [comment]
Yes, everything is possible in MoBi...

Implementing a bi-directional transport via changes in passive diffusion is a) not really physiological, b) does not account for the different expression of the transporter in tissues (yes I can change the diffusion proportionality factor for each organ separately, but wow this is really against the idea of physiological bottom-up approach) c) not saturable (e.g. using in-vitro Km), d) does not allow to simulate different phenotypes etc (pharmacogenomix)...

Yes, I know what P-gp is ;) It is not clear for me what is the reason to add the "passive diffusion neutralizing" part to the rate equation.

**Comment by UlrichSi** [comment]
> It is not clear for me what is the reason to add the "passive diffusion neutralizing" part to the rate equation.

Often, the experimental data consists of just these values: Background passive diffusion and the enhancing effect of pgp. PK-Sim appears to be configured to directly use such data.

If it is to be implemented, that method could make sense for the bidrectional active transport too. Knowing how the process is typically described by experimental data, I mean, and using exemplary data in the development discussions.

**Comment by PavelBal** [comment]
## Individuall-BB
- "Bi-directional" is selectable as a transport direction for all organs (except for Kidney and Liver intracellular, where the direction is always "Excretion")

## Compounds-BB
- ADME-Tab -> Transport & Excretion:
  - Instead of one selection field "Process type", two field are available:
  - 1) "Uni-directional transport" with the same selection as currently available (Intrinsic active transport - Michaelis-Menten, Specific active transport - Michaelis-Menten, Specific active transport - Hill, In vitro active transport (vesicular assay) - Michaelis-Menten)
  - 2) "Bi-directional transport" with the selection "Specific active transport - Michaelis-Menten". Inputs - Vmax and Km. Equation used for transport rate:
   `TM * kcat * (C_src * K_water_src - C_target * K_water_target) / (Km + C_src * K_water_src + C_target * K_water_target)`
  - `TM`: Transporter amount
  - `C_src`: concentration of substrate in source compartment
  - `K_water_src`: Partition coefficient of the substrate in the source compartment
  -  `C_target`: concentration of substrate in target compartment
  - `K_water_target`: Partition coefficient of the substrate in the target compartment

**Comment by msevestre** [comment]
@PavelBal 
Why do you need two fields?

**Comment by msevestre** [comment]
Can't we just have the  Specific active transport (Bi Directional) - Michaelis-Menten in the list?

**Comment by msevestre** [comment]
hum why do we neeed anything in the compound in fact? Isn't it just a mapping at the simulation level?

**Comment by PavelBal** [comment]
> Can't we just have the Specific active transport (Bi Directional) - Michaelis-Menten in the list?

Because we allow different direction selection in different organs. So it could be that in the Liver the direction is Influx - in that case we should offer all possibilities we have for influx. And in the kidney the direction is bi - in this case we cannot offer e.g. Hill.

**Comment by msevestre** [comment]
In that case the simulation creation will fail then. there is no way around this at the moment.  Kinetic is not linked to location whatsoever at the moment. Introducing this is a massive change that I am not even willing to consider
So do we postpone or what?

**Comment by PavelBal** [comment]
I vote for postponing.

**Comment by msevestre** [comment]
I have started unfortunately alrady the implementation for one PlasmaInterstial BiDirectional  Going to spend another one hour or two to see if this could work.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/111827841-c5e2b700-88c0-11eb-998c-7a365e65829d.png)

Ok so it works without any problem provided that we ar able to throw a descent error message when selecting HILL

**Comment by msevestre** [comment]
This is the error message we have now
![image](https://user-images.githubusercontent.com/1041237/111827996-02aeae00-88c1-11eb-9b8a-9ee3c9434e3e.png)


It will need to be less in your face  something like

"Hill kinetic is not supported with BiDirectional transport or sthg like this"
(or we define the kinetic for hill :))

**Comment by msevestre** [comment]
and formula
![Uploading image.png…]()

**Comment by PavelBal** [comment]
Nice! 
I would not know how the equation would look like for Hill. Will think about a proper error message and maybe adding a warning information when selecting Hill that it is not compatible with bi-directional.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/111831885-5f609780-88c6-11eb-8f09-5d53ec65097b.png)

**Comment by msevestre** [comment]
A little bit less cryptic for now :)
Ok I am going to add it for a few other and I'll push so that you can play with it and we ca ndecide whether we use it or drop it

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/111835288-27a81e80-88cb-11eb-9f75-b224dd916eeb.png)


Ok implemented everywhere. EVen more TODO and display stuff to create

![image](https://user-images.githubusercontent.com/1041237/111835370-44445680-88cb-11eb-8a43-c661366a8285.png)


I am going to create a new issue for this

**Comment by PavelBal** [comment]
>A little bit less cryptic for now :)

@msevestre I think we should not write "not **yet** implemented", Hill will probably never be.

**Comment by msevestre** [comment]
We can let the user hope :)

**Comment by msevestre** [comment]
Implemented except CAptions: see  #1681

**Comment by PavelBal** [comment]
> We can let the user hope :)
I prefer not to make any false promise ;)

**Comment by StephanSchaller** [comment]
I think we can leave it. Never Say Never Again! ;-)

**Comment by PavelBal** [comment]
It's done, I guess..
