### ISSUE TITLE
Parameter identification: Calculation methods variation does not work

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#137]
1) Open example project "Theophylline.pksim5".
2) Right-click on simulation "Kaumeier IV 208 mg fit" and select "Start Parameter Identification...".
3) Switch to tab "Configuration" and select "Calculation methods variation" under "Options"-selection.
4) Enable "Cellular permeabilities" and the next three options.
5) Select "Run".
6) Optimization fails with
Run #	Description	Total Error	Number of Evaluations	Elapsed Time	Status	 	
3	PK-Sim Standard	Infinity	0	00m:11s:887ms	Faulted

**Comment by msevestre** [comment]
Does this work with 7.0?
Also does CM variation works with other project?
Thanks :)

**Comment by PavelBal** [comment]
Can't say about 7.0, but it fails with 6.4.1.
It works when the Fraction Excreted (Urine) data is de-selected.
Single optimization with fraction excreted works as expected.

**Comment by msevestre** [comment]
oh so this is with version 6.4.1. I thought it was version 7.1. Ok thanks

**Comment by PavelBal** [comment]
No, the issue is for 7.1, but is also present in 6.4.1. I cannot say whether it is in 7.0, as I do not have the latter.

**Comment by msevestre** [comment]
ok thanks for clarification. AT least it's not something new so it's
definitely in 7.0

**Comment by msevestre** [comment]
I can reproduce the issue

**Comment by msevestre** [comment]
This is again due to rename of `fraction excreted` to `fraction excreted to urine`.. The output cannot be found in newly created simulation.

**Comment by msevestre** [comment]
Solution is to reconfigure the simulation. This will recreate the simulation ensuring that the output is  available

@Yuri05 That should probably be done sooner than later

**Comment by Yuri05** [comment]
Better: project conversion for PI - renaming `fraction excreted` to `fraction excreted to urine` in the output mapping

**Comment by msevestre** [comment]
No that does not work. We need to rename output as well in simulation. And
it's too late. The version is already out

**Comment by msevestre** [comment]
We could still implement a conversion in 7.1 :

Simulation
PI
Settings
Plot?

**Comment by Yuri05** [comment]
Ok, let's implement the conversion "fexc"==>"fexc2urine"

**Comment by msevestre** [comment]
Example project: Simulation should be reconfigured and calculated (don't forget to select the new excreted to urine output)
