### ISSUE TITLE
Unable to perform parameter identification

### ISSUE THREAD

**Issue by rhishi24niper** [Open-Systems-Pharmacology/PK-Sim#1373]
I am trying to perform parameter identification for my simulation, but I am having issues with adding simulation for parameter identification. When I am selecting "Add Simulation" for "Parameter Identification" there is no simulation file in the "Select Simulations" window. See attached screenshot.
[Simulation parameter identification issue.docx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/3966110/Simulation.parameter.identificaiton.issue.docx)

**Comment by Yuri05** [comment]
Parameter Identification is currently possible only with **Individual** simulations.
In your project there is only one **Population** simulation, that's why the selection dialog is empty

**Comment by rhishi24niper** [comment]
Got it. Thanks.
