### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1375]
`When_creating_a_population_simulation_with_the_standard_building_block_and_iv_bolus_for_all_populations.should_be_able_to_simulate_the_simulation` fails

```
Population simulation for the population 'Beagle' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set
Population simulation for the population 'Dog' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set
Population simulation for the population 'Minipig' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set
Population simulation for the population 'Monkey' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set
Population simulation for the population 'Mouse' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set
Population simulation for the population 'Rat' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set
Population simulation for the population 'Rabbit' failed: Initial value of simulation|Applications|Protocol|Application_1|Drug was not set

```

The reason is: **test** populations created by `DomainFactoryForSpecs.CreateDefaultPopulation` return `NaN`-Arrays for Weight **for all animal populations**.
Then the initial dosis in the corresponding test cannot be calculated.

![grafik](https://user-images.githubusercontent.com/25061876/71196497-7dd57e80-2290-11ea-987e-fd70365e4407.png)

**Comment by msevestre** [comment]
This has not changed between v8 and v9. So something has changed down the
line no?

**Comment by Yuri05** [comment]
No idea. Passing BW=Nan is not good anyway. (actually BW shouldn't be passed to the pop calculation at all??)

**Comment by msevestre** [comment]
No idea why this breaks suddenly. We'll check it out
