### ISSUE TITLE
Range plot is different in population comparison

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/PK-Sim#1382]
Dear all, 
I have made two range plots in PK-Sim, for two different populations. I wanted to put the two graph on the same plot for comparison, so I tried the population comparison option. 
When making the comparison one of the two plot changed, making a strange shape. I think this can be related to the binning of the weights, but in both simulations I used the same population (--> same weights). You can see below the original plot, and the one in the population comparison (the gray plot). What you see on the y axis is an AUC. Do you have any explanation for this? And is there a way to solve it?

Thanks a lot.

Donato

![image](https://user-images.githubusercontent.com/11489621/72536790-39330800-387b-11ea-80fd-fc6e614f7e61.png)

![image](https://user-images.githubusercontent.com/11489621/72536811-48b25100-387b-11ea-881e-61f1a81d16b0.png)

**Comment by msevestre** [comment]
This is a bug in PK-Sim

**Comment by msevestre** [comment]
here https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Core/Services/RangeChartsDataCreator.cs#L68
