### ISSUE TITLE
Improve error message when a table formulation without any entries is selected

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1396]
See https://github.com/Open-Systems-Pharmacology/Forum/issues/453

The current error is of no help at all. Also, the reference to "systems-biology.com" is outdated?

**Comment by msevestre** [comment]
It should not be possible to create a table without point in the first place

**Comment by msevestre** [comment]
The schema is now gone anyways. Plus now it's not possible to create such a formulation
Fixed with #1397
