### ISSUE TITLE
It should not be possible to use a TableFormulation without any point

### ISSUE THREAD

**Issue by shbae1211** [Open-Systems-Pharmacology/PK-Sim#1398]
Hello.
I'm a beginner of using PK-sim and it may be a technical problem.
After I clicked 'run' button for simulation, there was an error massage pop-up.

Does anyone have great idea solving this problem?

> 
![image](https://user-images.githubusercontent.com/48671465/73440466-aaeb7580-4394-11ea-96b0-03011a62eda6.png)

**Comment by msevestre** [comment]
@shbae1211 I am quite curious. How did you manage to create a  formulation without ANY point any it? What was your workflow ?

**Comment by shbae1211** [comment]
@msevestre  That was a mistake. I made several formulations tab in Building Blocks without templates and chose wrong formulation tab. I am learning how to use PK-Sim by myself finding open-source materials.

**Comment by msevestre** [comment]
@shbae1211 Yeah no problem. But it's impossible to create a table formulation without a point (e.g the OK button is disabled) .So how did you do it :)

**Comment by msevestre** [comment]
@Yuri05 I have added a check here but still :)
![Uploading image.png…]()

**Comment by shbae1211** [comment]
@msevestre  Oh, I understood your point. 

This is my wrong formation (tablet) tab..

![image](https://user-images.githubusercontent.com/48671465/73507696-23961480-441d-11ea-8823-309ab2ab419a.png)

And OK button is available in 'Simulations'. and after I clicked the button, there was no error massage,, however 'run' is not available.

![image](https://user-images.githubusercontent.com/48671465/73507753-4aece180-441d-11ea-9b0a-5046466752b5.png)



This 'tablet'  tab was made(created) in 'Administration' tab in 'Create simulation'  because I missed input 'Formulation information' prior to conducting simulation process.

Anyway, thank you for your help :)

**Comment by Yuri05** [comment]
@msevestre 
>But it's impossible to create a table formulation without a point (e.g the OK button is disabled) .So how did you do it :)

E.g. create a table formulation first, then open it for editing and remove all points.
