### ISSUE TITLE
Individual simulation: "Export for Matlab/R"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1404]
Exported SimModel is not required by the R-Toolbox anymore.
However as long as SimModel-Xml structure does not change, it can be used by the last available Matlab-Toolbox version (which can be downloaded on demand by users)
(and is also helpfull for debugging in case of numerical issues or problems in SimModel).

Thus I think we should keep it but rename to something different (good suggestions are welcome :)

**Comment by StephanSchaller** [comment]
The new R-Package just requires a PKML of the simulation, right?

Why don't just call it "Save as xml"? ;-)

**Comment by msevestre** [comment]
I don't think we should keep it. This is going to be annoying at best and probably also confuse users
I would vote for removing the option. If people want to still use xml, they should stick with v8

**Comment by msevestre** [comment]
>and is also helpfull for debugging in case of numerical issues or problems in SimModel

Therefore I will only allow the option using the dev mode for now

**Comment by Yuri05** [comment]
Export to XML is available twice in the popup
![grafik](https://user-images.githubusercontent.com/25061876/74105502-b55cfa80-4b5e-11ea-92d8-d714fe848e0a.png)

**Comment by msevestre** [comment]
No this is the simulation XML (e .g the serialized xml of the simulation). Nothing to do with SimModel
