### ISSUE TITLE
Remove/Modify "Population simulation: "Export for cluster computations"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1406]
At the moment it exports SimModel-XML, Population.csv, AgingData.csv (if simulation was configured with aging) and outputs.csv (list of selected outputs).
![grafik](https://user-images.githubusercontent.com/25061876/73828888-561b8500-4802-11ea-8ed5-8bd29ca04083.png)

In case we would like to process a pop simulation with the new R-Toolbox
* pkml is exported by "save simulation to pkml"
* population data is exported by "Export population to csv" (however without aging data - I think it should be extended; s. #1405)

Thus I think we should just export SimModel-XML and drop the rest of the "Export for cluster computations"-functionality (and name the menu entry same as in individual simulations - s. #1404)

**Comment by StephanSchaller** [comment]
Don't you need a script here, to execute pop-sims?
Maybe we should export a compilable bundle that runs the simulation and creates plots in R (via TLF-package)?

**Comment by Yuri05** [comment]
Executing pop-sims is pretty straight-forward in the R-Toolbox (however aging is not supported yet? @PavelBal @msevestre )

>Maybe we should export a compilable bundle that runs the simulation and creates plots in R (via TLF-package)?

Would be nice indeed.. however I wouldn't do it in v9 (there are enough more urgent TODOs here :))

**Comment by PavelBal** [comment]
What does aging have to do with popSim, cant an individual simulation have aging, too?

Either way, we did not look into it at all. I guess if an individual simulation has been created with aging and exported to pkml, it will work. But creating a new individual with the aging property is probably not possible - the same would go for populations. We have to think how to export/generate aging table parameters.

**Comment by StephanSchaller** [comment]
> Would be nice indeed.. however I wouldn't do it in v9 (there are enough more urgent TODOs here :))

Should I create an issue in PK-Sim and MoBi Repo?

**Comment by Yuri05** [comment]
> I guess if an individual simulation has been created with aging and exported to pkml, it will work.

Yes.

>What does aging have to do with popSim, cant an individual simulation have aging, too? 

You just answered your question yourself: for individual simulations aging parameters will be exported as part of pkml (table parameters). No additional inputs are required then.
For population simulations with aging: those table parameters must be overwritten with table (aging) parameters of other individuals.

>We have to think how to export/generate aging table parameters.

Yep. Open new issues for this: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/295

**Comment by msevestre** [comment]
I think we should still have it because it conveniently exports everything. However we export pkml, and population files.
