### ISSUE TITLE
Add "Export to C++ code"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1407]
Individual/Pop-Simulations: add "Export to C++ code" (or find a better name) in developer mode.

**Comment by msevestre** [comment]
@Yuri05 What method should be called here?

**Comment by Yuri05** [comment]
this one: 

https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/blob/7a684877d4e1348b4de93f5d63424b5168403645/src/OSPSuite.SimModel/Simulation.cs#L620
