### ISSUE TITLE
Population simulation: "Import simulation results"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1408]
Is it compatible with the output of the new R-Toolbox?
If no: adjust the toolbox? Or remove/temporarily deactivate this functionality?

**Comment by msevestre** [comment]
Should be compatible

**Comment by msevestre** [comment]
@Yuri05 I should ask: Why do you think it won't be compatible?

**Comment by Yuri05** [comment]
I don't know (and didn't try), so just wanted to be sure it is compatible. If yes: we can close the issue.

**Comment by msevestre** [comment]
It should be compatible. However someone should verify (oh...that would be you:))

**Comment by Yuri05** [comment]
yep. works.
