### ISSUE TITLE
ODE Export

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1416]
@msevestre Any reason why ODE export is enabled in MoBi but not in PK-Sim?
I would enable it in PK-Sim as well

**Comment by msevestre** [comment]
It was not in Pksim before. It just as it was ;-)

**Comment by Yuri05** [comment]
I know. I intended to open this issues since years, just forgotten it every time.

**Comment by msevestre** [comment]
Oh I see. Well we can add it. No problemo

**Comment by msevestre** [comment]
It's starting to become very hard to use in PKSim with so many menus
![image](https://user-images.githubusercontent.com/1041237/74186716-177a3600-4c19-11ea-962b-f370c19c45e3.png)


Should we put them in a sub menu instead maybe?

**Comment by msevestre** [comment]
I have also removed the duplicated entry here
