### ISSUE TITLE
Perform memory leak analysis

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1421]
Loaded a project with v9 from [this snapshot](https://github.com/Open-Systems-Pharmacology/Oxycodone-Model/blob/master/Oxycodone.json) (lot of pop sims etc.)
After closing the project: PK-Sim occupies ca. 3.6GB RAM (also nuch multiple GCs in the dev mode)

**Comment by msevestre** [comment]
Anything new here?

**Comment by Yuri05** [comment]
You mean if it is new in v9? 
Don't know, investigating

**Comment by msevestre** [comment]
yes. Code has not changed really...so I am wondering what is sticking and where

**Comment by Yuri05** [comment]
[P1.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4191130/P1.zip)
Compared v8 vs v9 with this snapshot. Both v8 and v9 started in dev mode and GC performed after every step.

Action|RAM usage v8 (MB)|RAM usage v9 (MB)| Difference v9-v8 (MB)
-------|---------------------|---------------------|------------------------
Start PK-Sim|376|401|25
Load project from Snapshot|1086|1759|**673**
Open all simulations and switch to the Time profile tab|2827|3707|**880**
Close project|562|1247|**685**

**Comment by msevestre** [comment]
What's surprising is such a difference after loads from snapshot. Is the snapshot calculating anything?

**Comment by msevestre** [comment]
If yes, this could be a simmodel issue.

**Comment by Yuri05** [comment]
>Is the snapshot calculating anything?

Yes, population simulations (in very high res).

>If yes, this could be a simmodel issue.

Yep, could be.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/74339298-d0538880-4d71-11ea-9085-19baa5722401.png)


1GB unmanaged...

**Comment by msevestre** [comment]
I think the snapshot is too big to be analyzed however. Can you reduce the snapshot file so that it is significant but yet not soo big?

**Comment by msevestre** [comment]
and in v8...  380MB
![image](https://user-images.githubusercontent.com/1041237/74343264-cb460780-4d78-11ea-95c6-5b8046ab1974.png)


So I think the leak comes from SimModel at the moment

**Comment by msevestre** [comment]
or something needs to be cleared

**Comment by Yuri05** [comment]
[P2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4192782/P2.zip)
smaller snapshot (only 1 sim)

**Comment by msevestre** [comment]
@Yuri05 The difference in unmanaged memory is about 625MB so it's almost spot on with what you saw in your test

**Comment by msevestre** [comment]
Much better here. 
Unamanaged goes up during calculations but gets cleared and is almost constant 
![image](https://user-images.githubusercontent.com/1041237/74556256-a5149900-4f2b-11ea-89d4-16fc06f6115b.png)

**Comment by msevestre** [comment]
271MB at PKSim start to 320 after loading the whole snapshot and calculating
So there is still some leak (about 50MB) but much better than 625 MB:)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/74556581-59162400-4f2c-11ea-9801-28a3d685ce1f.png)

Very cool I have to say
