### ISSUE TITLE
Project has changed?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1422]
v9: open the project from https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1314 and close it. Prompt "_Project has changed. Save changes?_" appears.

Same in v8 works as expected.
Project was created in v8.

**Comment by msevestre** [comment]
Well there is a project conversion so.....

**Comment by msevestre** [comment]
I don't undertand the issue.
This is a project created with an older version. So a project conversion will happen
If there is any of
```
PopulationSimulation
PopulationAnalysisChart
Population
```

in this project, a conversion will take place.

Please explain why this is not ok :)

**Comment by Yuri05** [comment]
Well, unexpected from users perspective (and project conversion is not obvious for a user).
But not really a problem.
