### ISSUE TITLE
Observed data error

### ISSUE THREAD

**Issue by TTLL88** [Open-Systems-Pharmacology/PK-Sim#1430]
I was using PK-Sim for my PBPK project but I constantly encountered an issue: When I imported the observed concentration data to do a visual evaluation of my model, the value of the observed data changed (e.g. 807 ng/ml changed to 765 ng/ml). The unit is the same in the observed and simulation. Anyone experienced this before? Thank you

**Comment by msevestre** [comment]
Can you add a project so that we can understand your problem and potentially offer a solution?

**Comment by TTLL88** [comment]
![image](https://user-images.githubusercontent.com/61062080/74556916-08eb9180-4f2d-11ea-8b7b-f203382d2b26.png)

**Comment by TTLL88** [comment]
My issue is pretty straightforward, upper figure is the observed data shown in building block; lower figure is predicted vs observed. Take first point for example, the value changed...very weird. 
Thank you for your time guys.

**Comment by msevestre** [comment]
Can you attach the project so that I can see what's going on?

**Comment by msevestre** [comment]
Going to see if we can fix this for the upcoming release. Thanks for reporting

**Comment by msevestre** [comment]
ok I could reproduce the issue. It is probably also an issue when comparing two population simulation using different compounds (e.g. with different molweight)

**Comment by TTLL88** [comment]
Exactly. Thanks so much for your efforts. It didn’t happen in individual
simulation though . It is also surprising that the bug was not reported
before. Maybe it will get fixed in the next new release ? Thanks.

**Comment by msevestre** [comment]
>It is also surprising that the bug was not reported before. 

Well nothing is perfect. We will fix it in the next version

**Comment by TTLL88** [comment]
Appreciate it! Thanks.
