### ISSUE TITLE
Height in aging simulations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1436]
Height is not properly scaled in aging simulations

**Comment by msevestre** [comment]
Why is height defined as a constant parameter and not a distributed parameter in the model?

**Comment by msevestre** [comment]
Going to check this out and see of this is feasable easily

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/74962305-a5a2a900-53dd-11ea-8650-db5c33909961.png)
