### ISSUE TITLE
Gastric Emptying Time in Simulated Population

### ISSUE THREAD

**Issue by TTLL88** [Open-Systems-Pharmacology/PK-Sim#1444]
Hi Guys,
Happy Friday.
I found something weird in the gastric emptying time in my simulated population (male, European). The median is 15 min (range 6-60 min). However, from physiology point of view, gastric empty time is about 2h, T1/2=20min (for liquids). The difference is quite huge. Could someone comment on that? 
Many Thanks!

[image](https://user-images.githubusercontent.com/61062080/75575149-97800880-5a2d-11ea-83d3-2778844de794.png)

![image](https://user-images.githubusercontent.com/61062080/75575587-fa719f80-5a2d-11ea-8a57-ebc945352518.png)

**Comment by StephanSchaller** [comment]
Where do you get the 2h from, and what do they mean (completely empty, 95% empty)?

Gastric Emptying Time (GET) in PK-Sim is defined as:
![image](https://user-images.githubusercontent.com/25477643/75587786-91167e80-5a77-11ea-83f8-baaaf3a43468.png)

Meaning, your stomach is not empty after 15 min. As an approximation, depending on your GET, the remaining fraction of liquids after the time of GET has passed would be: (1-1/GET)^GET = (1/exp(1)) for GET --> inf, which amounts to roughly the 36-37% mentioned in the snippet.

Fits quite well with the figure above.

**Comment by TTLL88** [comment]
Hi, Stephan. Thanks so much for the clarification.The value makes sense to
me now. Thanks.

esqlabs GmbH <notifications@github.com> 于2020年2月28日周五 下午4:21写道：
