### ISSUE TITLE
Clicking on + - on some tables requires a double click after update to devexpress

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1445]
This happens on SimulationInterval and Compound

**Comment by msevestre** [comment]
Only v9

**Comment by msevestre** [comment]
@Yuri05 All ranorex tests are now passing so I am assuming it's done. But there might be a few instances where it's not the case
Can you think of other place where we have + - icons?

**Comment by Yuri05** [comment]
Advanced administration protocol. Works as well there.

**Comment by Yuri05** [comment]
ok, assuming it's fixed. Closing.
