### ISSUE TITLE
Method to "Dissolve" Sub-folder Structure

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#1449]
When managing observed data (or simulations) you may sort these within subfolders.
It would be convenient to have a feature to "dissolve" the existing folder structure to put everything bat on the same folder level.

E.g. by right-click on a folder --> "dossolve" sub-folders" to level the folder hierarchy within that folder.

**Comment by msevestre** [comment]
There is already something like this. Clear folder and keep data no?

**Comment by StephanSchaller** [comment]
Ah, nice. Thanks. Somehow always overlooked ...

**Comment by msevestre** [comment]
Please double-check that it's there... I might be wrong

**Comment by StephanSchaller** [comment]
Yes it's there. And working great! ;-)
