### ISSUE TITLE
Removing gridlines from the simulation output time profile analysis image

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/PK-Sim#1450]
Hello,

Could anyone please suggest me on how to remove the gridlines from the time profile analysis image of  a simulation when exporting the image.

Sincerely,
Kash

**Comment by Yuri05** [comment]
just deactivate grid lines in the chart settings before exporting as image?

**Comment by yvkashyap** [comment]
Hi Juri,

Thank you so much for replying to my question. Sorry for bothering you with such a simple question. For some reason, some of my population simulations are not giving me with an option to remove the gridlines. I an unable to see the "Chart Editor" option. Please see the first image below.
For other simulations, i can see the "Chart Editor" option and was able to remove the gridlines. Please see the second image.
![Figure 1](https://user-images.githubusercontent.com/42623466/77236314-f34c3600-6b82-11ea-97e5-49e6b94c503d.JPG)
![Figure 2](https://user-images.githubusercontent.com/42623466/77236328-2a224c00-6b83-11ea-9e11-d0cbc2d79812.JPG)
