### ISSUE TITLE
Renaming protein in individual does not trigger changed state of simulation

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1451]
I came across the following unexpected behavior in PK-Sim: In this file [here](https://github.com/AndreDlm/Erythromycin-Model/blob/master/Erythromycin.pksim5), renaming a protein in the individual BB (e.g. LST-3TM12 into OATP1B1) does not trigger a changed state of the simulation that uses the individual. I would have expected a red exclamation mark to appear. 

Cloning the simulation, however, opens the configure simulation window. Yet, to propagate the changed protein name to the simulation, the individual used in the simulation has to be changed to another individual and thereafter re-selected.

**Comment by AndreDlm** [comment]
still a bug in version 9.1. Any idea when this will be fixed? :)
@msevestre 
@Yuri05

**Comment by msevestre** [comment]
I bet this is fixed in v10. We changed completely the internal structure and renaming a protein is now a BIG thing. Let's assign it to v10
