### ISSUE TITLE
Problem with creating a new individual

### ISSUE THREAD

**Issue by adriankhoei** [Open-Systems-Pharmacology/PK-Sim#1456]
I am using portable PK-Sim version 9.0.117 to create an individual in R toolbox, as discussed in this [post](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1453). 
Using initPkSim, I get this error:

`>initPKSim("F:/PK-Sim_portable/PK-Sim 9.0.117")`
`Error in rClr::clrLoadAssembly(pksimR) : 
  Failure in rclr_ms_call_static_method, but could not retrieve an error message`

I would appreciate any help.

**Comment by msevestre** [comment]
Can you start PKSim ? e.g. go to "F:/PK-Sim_portable/PK-Sim 9.0.117 and start PKSim.exe?

**Comment by adriankhoei** [comment]
> Can you start PKSim ? e.g. go to "F:/PK-Sim_portable/PK-Sim 9.0.117 and start PKSim.exe?

Yes.

**Comment by msevestre** [comment]
Can you perform some basic operations in R using the toolbox? Load simulation, calculate etc?

**Comment by msevestre** [comment]
is F a local or remote folder? Can you move this to the partition where R is installed?

**Comment by adriankhoei** [comment]
> Can you perform some basic operations in R using the toolbox? Load simulation, calculate etc?

No. It returns this error:

`Error in initPKSim() : 
  Could not find an installation of PK-Sim on the machine. Please install the OSPSuite or use 'initPKSim()' to specify the installation path`

>is F a local or remote folder? Can you move this to the partition where R is installed?

It is a local one. I moved the PK-Sim 9.0.117 folder to "C:\Program Files\Open Systems Pharmacology" but it returns the same Error in rClr.

**Comment by msevestre** [comment]
LoadSimulation does not require PKSim
export a sim to pkml and do

sim <- loadSimulation(xxx)

I just want to make sure that your R stuff is installed properly

**Comment by adriankhoei** [comment]
> LoadSimulation does not require PKSim
> export a sim to pkml and do
> 
> sim <- loadSimulation(xxx)
> 
> I just want to make sure that your R stuff is installed properly

Right. 
loadSimulation works:

`> library(ospsuite)`
`> dataPath <- file.path(setwd("C:/Users/Adrian/Dropbox/DrNeelyLab/voriconazoleProject/models/pediatricPKML"), fsep = .Platform$file.sep)`
`> simFilePath <- file.path(dataPath, paste0("patient1.pkml"), fsep = .Platform$file.sep)`
`> simPatient1 <- loadSimulation(simFilePath)`
`> print(simPatient1)`

`Simulation: 
  Name: Patient1
  Source file: C:/Users/Adrian/Dropbox/DrNeelyLab/voriconazoleProject/models/pediatricPKML/patient1.pkml`

**Comment by msevestre** [comment]
hum ok 

The only thing that I can think of is incompatibility between  OSPSuite-R and PKSim, I'll have to check with the latest version and get back to you

**Comment by msevestre** [comment]
@adriankhoei Did you manage to get it working?

**Comment by adriankhoei** [comment]
> @adriankhoei Did you manage to get it working?

Dear Michael,

My apologize for very late response.

For now, I have stopped working on this project. I will let everyone know as soon as I get back to this.

Thank you.

**Comment by msevestre** [comment]
closing then
