### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1465]
| Severity	| Code |	Description	| Project |	File	|Line|	Suppression  State |
| -- | -- | -- | -- | -- | -- | -- |
|Warning	|CS0618	|'ConsoleLoggerExtensions.AddConsole(ILoggerFactory, LogLevel)' is obsolete: 'This method is obsolete and will be removed in a future version. The recommended alternative is AddConsole(this ILoggingBuilder builder).'	| PKSim.CLI |	C:\projects\PK-Sim\src\PKSim.CLI\Program.cs|	69	|Active|
| Warning	| CS0618	| 'DebugLoggerFactoryExtensions.AddDebug(ILoggerFactory, LogLevel)' is obsolete: 'This method is obsolete and will be removed in a future version. The recommended alternative is AddDebug(this ILoggingBuilder builder).'	| PKSim.UI  | 	C:\projects\PK-Sim\src\PKSim.UI\BootStrapping\ApplicationStartup.cs | 	86 | 	Active|

**Comment by msevestre** [comment]
@StephanSchaller Ths could be a good research task for georgios

**Comment by msevestre** [comment]
@georgeDaskalakis Maybe you could check this out. happy to explain the issue when you have time

**Comment by StephanSchaller** [comment]
@msevestre sure.
@georgeDaskalakis, feel free to tackle this any time after May 1st ;-) (but of course also now, if you want)
