### ISSUE TITLE
QualificationRunner 9 does not work anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1466]
With every project, error message `Project configuration for '<Project>' `is invalid. comes.
To reproduce:
clone e.g. the repo https://github.com/Open-Systems-Pharmacology/Raltegravir-Model and start QualiRunner via:
`QualificationRunner.exe -i "C:\Raltegravir\Evaluation_plan.json" -o "C:\Report" -p "C:\PKSim9Portable" --logLevel Debug`

This results in:
```
...
info: Qualification Runner[0]
      Starting validation runs...
dbug: Qualification Runner[0]
      Starting qualification run for project 'Raltegravir'
dbug: Qualification Runner[0]
      Qualification configuration for project 'Raltegravir' exported to 'C:\Report\temp\Raltegravir\config.json'
fail: Qualification Runner[0]
      Project configuration for 'Raltegravir' is invalid. Please check log file at 'C:\Report\temp\Raltegravir\log.txt' for details.
fail: Qualification Runner[0]
      Qualification Workflow failed
```

Log file 'C:\Report\temp\Raltegravir\log.txt' mention in the error message is not created.
The whole content of the output folder created till the crash is here: [out.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/4521587/out.zip)

This happens with QualiRunner **9.0.57** and PK-Sim 9 portable **9.0.135**

**Comment by msevestre** [comment]
ok this is  an issue with PKSim. The app.config is missing
