### ISSUE TITLE
Copy to clipboard of graph broken on screen with 150% scaling

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1473]
It's  impossible to copy a graph to clipboard in PKSim (or MoBi) when using 150% scaling. The 
issue is maybe a very funky implementation of copy that uses EMF

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/5ff27d3706368ccd574481be3c46b3cf09d32aaf/src/OSPSuite.UI/Controls/UxChartControl.cs#L87

We should use try something else

**Comment by PavelBal** [comment]
Same for MoBi (obviously).

**Comment by msevestre** [comment]
Yes it is the same.
As an info, here is how it looks like

![image](https://user-images.githubusercontent.com/1041237/80981511-1449ad00-8df8-11ea-9e10-346f6e8bac59.png)

One can see the frame around the pasted picture on the left side. This is absolutely useless

**Comment by msevestre** [comment]
This is fixed in V9 available in tonight's build
