### ISSUE TITLE
Equation for transfer rate from plasma of small / large intestine to mucosa plasma compartments

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#1478]
A catch from Paul:

The equation defining the rates of mass transfer from plasma of small and large intestine to the different mucosa plasma compartments, name "Mass transfer rate (intestine to mucosa plasma)", is wrong. 
Currently it reads "(Q*(1-HCT)-Q_lymph)*C_pls". 
The correct equation is: "Q*(1-HCT)*C_pls", i.e. without "Q_lymph", as in other organs.

**Comment by msevestre** [comment]
@Yuri05 version 9?
