### ISSUE TITLE
Auc_tEnd not properly calculated in V9

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1483]
[Auc_tEnd.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4650281/Auc_tEnd.zip)
![grafik](https://user-images.githubusercontent.com/25061876/82325219-207a6080-99db-11ea-8c1e-f5ac86ad639f.png)

**Comment by StephanSchaller** [comment]
Maybe also in V8? I just did a Sensitivity Analysis and there were not results for AUC_tend

**Comment by msevestre** [comment]
It's probably a display issue. Clearly AUC_tEnd is calculated because AUC_inf is calculated

**Comment by Yuri05** [comment]
@StephanSchaller No, v8 is ok.

**Comment by msevestre** [comment]
I think this is another case of PEBCAK error
I just started PKSim v9, ensured that all my dependencies were ok (postclean.bat)

![image](https://user-images.githubusercontent.com/1041237/82338140-860a2500-99ba-11ea-8e10-75efd30b3ee6.png)

**Comment by Yuri05** [comment]
>I think this is another case of PEBCAK error

Could be... after clean everything and full rebuild works for me. closing.
