### ISSUE TITLE
V9: missing project conversion of PK-parameters in population plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1485]
In V9 some PK-Parameters were renamed (internal names).
If in old projects those parameters were used in population plots: they are not displayed anymore when a project is opened with v9.

Example: project was created with v8, exported to snapshot and loaded from snapshot in v9.
[01_Pop_BWPlots.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4655287/01_Pop_BWPlots.zip)

V8:
![grafik](https://user-images.githubusercontent.com/25061876/82418881-deeec180-9a7d-11ea-9bae-f93b8688a58d.png)

V9:
![grafik](https://user-images.githubusercontent.com/25061876/82418937-f8900900-9a7d-11ea-8053-083b57a29816.png)

**Comment by msevestre** [comment]
Well. De do not convert the snapshot....that clearly can't work

What happens when you open the V8 project in v9?

**Comment by Yuri05** [comment]
>What happens when you open the V8 project in v9?

Looks good. Only from snapshot does not work. We can take it as known issue into Release Notes

**Comment by msevestre** [comment]
CLsoing issue. I added the miletsonde 9 so this should be release notes
