### ISSUE TITLE
It seems that 'select all' in the simulation settings doesn't work

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/PK-Sim#1487]
![1](https://user-images.githubusercontent.com/45459593/82516624-d5cd2580-9b4d-11ea-9355-831d8220742e.jpg)
I've tried and failed to select all by one-click. Click one by one is time-consuming.

**Comment by msevestre** [comment]
@regulus92 By clicking on the filter icon, you are filtering
If you want to select multiple at one, you need to do it differently

Now "Select ALL" molecules in your system is probably NOT what you want to do as it will save all outputs for all possible species

That being said, the way to do it is to click on a header and select

![image](https://user-images.githubusercontent.com/1041237/82560706-f3938e00-9b3f-11ea-87c6-1f417a7a2cf4.png)

so if you want all, you can group by for example Molecule and
![image](https://user-images.githubusercontent.com/1041237/82560776-132ab680-9b40-11ea-8966-f0adfd049198.png)

**Comment by regulus92** [comment]
@msevestre  OK. Thank you very much.
