### ISSUE TITLE
Partition Coeff (blood cells/plasma unbound)  should be hidden from distribution tab

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1499]
Because it's a function of HCT and therefore does not have a constant value
see 

https://github.com/Open-Systems-Pharmacology/Forum/issues/542

@Yuri05 Thoughts?

**Comment by Yuri05** [comment]
@msevestre I think there is nothing to do here.
The parameter `Partition coefficient (blood cells/plasma unbound)` is editable in a population simulation like tons other parameters defined by formula. If the user overwrites it and destroys the formula - it's the users responsibility.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/41291770-63c2-4507-993a-5343c0830e85)

**Comment by msevestre** [comment]
This is not the problem
It's a function of HCT which is not constant per individual
Therefore this value shown here is wrong

**Comment by Yuri05** [comment]
Ok, I see.
Setting it then to "CanBeVaried in Population = true"
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/36afcca4-6e14-4c43-953d-61b316762193)
