### ISSUE TITLE
Value origin for unstirred water layer thickness is wrong

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1506]
The value origin for the unstirred water layer thickness in the particle dissolution model seems to be wrong:
![Annotation 2020-06-17 112529](https://user-images.githubusercontent.com/26541603/84880775-46a02880-b08d-11ea-9db4-f22396948979.png)

In the [referenced publication](https://www.sciencedirect.com/science/article/pii/S0939641110001517), Table 3, a value of 30 µm is given.

@Incei 
@KatrinCoboeken

**Comment by Incei** [comment]
Thanks for mentioning Andre, this value needs to be set to 30, or the references needs to be adjusted.

**Comment by msevestre** [comment]
@Yuri05 What should we do here?

**Comment by msevestre** [comment]
Updating the default value to 30
