### ISSUE TITLE
Logging to File will not work after migration to .NET Core 3.1

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/PK-Sim#1508]
Logging to a file will not be working in PK-Sim after migrating to .NET Core 3.1. This will be happening because the FileLoggerProvider is keeping a reference to the StreamWriter and is actually closing the file at disposal. With the migration the object will be disposed after starting up the application, since we are no longer keeping a reference to a LoggerFactory as a Singleton in the IoC. This way the file will be closed for writting before even we start logging on it.

Proposed solution: Replace the existing FileLoggerProvider with a ready file logging provider provided by Serilog

**Comment by msevestre** [comment]
What do you mean it's not working? We are using it successfully when creating stuff with the cli.
In fact, the file update lives that why we are flushing after each log

**Comment by msevestre** [comment]
The whole qualification framework is using PKSim.cli which uses this file to log mechanism

**Comment by georgeDaskalakis** [comment]
@msevestre you are right the title and description were confusing - I corrected them. File logging IS currently working - it would not be working after the migration to Core 3.1.
