### ISSUE TITLE
Request for Symbol Change in Legend for Population Simulation

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/PK-Sim#1522]
A reviewer pointed out that the symbols in the legend do not match the symbols on the graph for the observed data in population simulation graphs, like in this example.

![image](https://user-images.githubusercontent.com/29066045/86406146-96334680-bc80-11ea-9da4-8fd8e273dcde.png)

Recommend a feature request to have these match.

Paul

**Comment by msevestre** [comment]
Wow. Can't believe we never realized that before. 
Do you think you can attach a sample project to reproduce?

**Comment by prvmalik** [comment]
I think this method will work for file transfer. It happens in any population simulation.

[Gentamicin.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/4866592/Gentamicin.zip)

**Comment by msevestre** [comment]
It's never too late
![image](https://user-images.githubusercontent.com/1041237/150565653-0b21a62b-b5a8-4e0b-83d8-fec4e7b45d09.png)

**Comment by prvmalik** [comment]
Nice to see Michael!
