### ISSUE TITLE
Selecting a checkbox requires three clicks

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1528]
1) Open PK-Sim
2) Create a compound
3) Create an second Lipophilicity-entry
4) Selecting the "Default"-checkbox for the second entry requires three clicks on the checkbox.

**Comment by msevestre** [comment]
probably https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1445

**Comment by msevestre** [comment]
This was fixed as part of 9.1
