### ISSUE TITLE
7.1: Suite setup fails under Win7, 32 bit

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#153]
Full Setup cannot be installed under Win7, 32 bit (both on systems with and without internet access)

![clipboard01](https://cloud.githubusercontent.com/assets/25061876/25747281/44d61a5e-31a7-11e7-8650-b5cafe8fd21a.jpg)

Issue reproducible. Seems to be a problem with VC++ Runtime?

[Open_Systems_Pharmacology_Suite_7.1.0_20170505141203.log.txt](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/979151/Open_Systems_Pharmacology_Suite_7.1.0_20170505141203.log.txt)
[dd_vcredist_x86_20170505141652.log.txt](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/979152/dd_vcredist_x86_20170505141652.log.txt)

**Comment by msevestre** [comment]
I tried on Win7 VM 32 bit and it works (that's my VM)

**Comment by msevestre** [comment]
Please verify that the machine you are installing the suite onto is not corrupted. 
This error could be a system error apparently and not a file error.

**Comment by msevestre** [comment]
Cannot reproduce on a fresh VM installed Win7 32bit

**Comment by Yuri05** [comment]
Works with SP1 installed
