### ISSUE TITLE
pH-dependent solubility profile

### ISSUE THREAD

**Issue by Vichelfer** [Open-Systems-Pharmacology/PK-Sim#1551]
Hello,
I would like to know if there is a way to include a pH-dependent solubility profile (a chart of solubility per pH) for the compound?
Also, what impact this information would have on the simulations? This could improve the simulations or is negligible?

**Comment by Yuri05** [comment]
yes, it's possible. https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-compounds-definition-and-work-flow#intestinal-solubility-as-table-function-of-ph

**Comment by Vichelfer** [comment]
Great! Thank you!
