### ISSUE TITLE
immunosuppression for rats

### ISSUE THREAD

**Issue by lauraolivo11** [Open-Systems-Pharmacology/PK-Sim#1557]
How to characterize immunosuppression for an individual rat in PKSIM?

**Comment by StephanSchaller** [comment]
Which Biomarker / Effect of immunosuppression do you ant to capture?

**Comment by lauraolivo11** [comment]
Blood cells number

**Comment by StephanSchaller** [comment]
Maybe you can elaborate a bit so people can better help you.

But blood cell numbers are e.g. reflected in the hematocrit (blood cell volume) which you could adapt in the model.
