### ISSUE TITLE
Installing previous versions of PK-Sim

### ISSUE THREAD

**Issue by jgg1822** [Open-Systems-Pharmacology/PK-Sim#1560]
I'm trying to open a collaborator's PK-Sim file created a few years ago, but I get the attached error message saying that the file is incompatible with my newer version of PK-Sim software (v9). Apologies if I missed this on the forum, but can you direct me to where I can download a previous version in order to open the file? If I download a previous version in order to open it, will this disrupt use of my current, newer version of the software?

Thanks!

![image](https://user-images.githubusercontent.com/35234695/93901626-b9d8bc80-fcc4-11ea-97b0-be985efb11bd.png)

**Comment by msevestre** [comment]
@jgg1822 
yes version 59 is a very old version of the software (5.x). With version 9, we decided to not supported these projects anymore
My suggestion would be to convert the project to a newer version using for example v8 and then open it with v9

To do so, install the portable version of v8 (zip file to download anywhere, unzip start pksim)
Then start your project. Make sure you open each simulation in the project and all building block and then save your project to something else (save as). Try to open it in v9 and you should be good to go

**Comment by msevestre** [comment]
and here the zip 
https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/download/v8.0/pk-sim-portable-setup.zip

**Comment by jgg1822** [comment]
Thanks, the version in the zip file allows me to open and view the older versions, and re-save. Thanks for the quick response!
