### ISSUE TITLE
Error exporting observed data from conc vs time plots with v9

### ISSUE THREAD

**Issue by jgg1822** [Open-Systems-Pharmacology/PK-Sim#1562]
I've noticed since upgrading to v9 of PK-Sim that there is a mismatch in the observed data when it is exported from concentration vs time plots in simulations. I've attached an example of this, which is the direct output I get in Excel when I right click on the plot and export. When you scroll down and compare the reported observed values to the correct observed values in the plot below, you can see the mismatch. I confirmed this with other model files and two other PK-Sim users. I suspect it may be a v9 bug worth reporting to you. Thanks!

![image](https://user-images.githubusercontent.com/35234695/94580615-1fd6be00-0248-11eb-8d00-3286ae60c0b7.png)
[Time Profile Analysis.xlsx](https://github.com/Open-Systems-Pharmacology/Forum/files/5300228/Time.Profile.Analysis.xlsx)

**Comment by msevestre** [comment]
Moving it as PKSim issue
Can you explain what you mean with `mismatch`?

**Comment by msevestre** [comment]
Can you safely attach the project here as well?

**Comment by jgg1822** [comment]
By ‘mismatch’ – the values themselves are mismatched. For example, the first observed concentration is 27.62 umol/L (or 9.14 mg/L), but when you export it from the simulation plot, it’s listed as 9.14 * 10^-6 umol/L (row 131 in the second tab of that Excel sheet). I think something has gone a bit wrong with the units when exporting.

We’re able to easily work around this, but I thought it would be good to highlight to you as a potential bug.

**Comment by jgg1822** [comment]
I'm unfortunately not able to respond via email with PK-Sim file (too large), or attach it here on forum link (file type not supported). What's the best way to get this file to you?

**Comment by msevestre** [comment]
If it's ok for you to have it public, you can zip it and upload it
Otherwise you can send it to me privately (michael@design2code.ca) by uploading it for instance in google drive and sending me a link :)

**Comment by jgg1822** [comment]
Zip file attached, thanks!
[Furosemide.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5300404/Furosemide.zip)

**Comment by Yuri05** [comment]
Fixed in the meanwhile. Closing
