### ISSUE TITLE
Project Conversion : Relative Expression Redesign

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1568]
## Individual

- [x] Add f_endo parameter in all organ and liver zones
- [x] Convert molecules location to new localization

**Comment by msevestre** [comment]
@Yuri05 @PavelBal 
How do we convert or old Localization 

![image](https://user-images.githubusercontent.com/1041237/97727076-56e9fa80-1aa6-11eb-82e7-58397978a5ff.png)

to our new one?

As a reminder
![image](https://user-images.githubusercontent.com/1041237/97727174-7bde6d80-1aa6-11eb-9b85-b3e87a9c5d8b.png)

![image](https://user-images.githubusercontent.com/1041237/97727186-813bb800-1aa6-11eb-92e0-404400dba38b.png)

![image](https://user-images.githubusercontent.com/1041237/97727209-88fb5c80-1aa6-11eb-9b66-c0c141fe7988.png)

I need this asap :)

**Comment by Yuri05** [comment]
Tissue | VascEndo | f_expr_intracellular | f_expr_interstitial | f_expr_BC_intracellular | f_expr_BC_interstitial | f_expr_VascEndo_Endosome | f_expr_VascEndo_Plasma | f_expr_VascEndo_Tissue
-- | -- | -- | -- | -- | -- | -- | -- | --
Intracellular | Endosomal | 1 | 0 | 1 | 0 | 1 | 0 | 0
Intracellular | Interstitial | 1 | 0 | 1 | 0 | 0 | 0 | 1
Extracellular   Membrane | Apical | 0 | 1 | 0 | 1 | 0 | 1 | 0
Extracellular   Membrane | Basolateral | 0 | 1 | 0 | 1 | 0 | 0 | 1
Interstitial |   | 0 | 1 | 1 | 0 | 0 | 0 | 1

@PavelBal Please check

**Comment by msevestre** [comment]
@Yuri05 I am more interested in the Flag combination in the UI.

**Comment by Yuri05** [comment]
f_expr_XXX correspond 1:1 to the flags in the UI - or do I miss something?

**Comment by msevestre** [comment]
Maybe.

here is what i have
```
  public static Localization ConvertToLocalization(TissueLocation tissueLocation, MembraneLocation membraneLocation,
         IntracellularVascularEndoLocation vascularEndoLocation)
      {
         switch (tissueLocation)
         {
            case TissueLocation.Interstitial:
               return Localization.Interstitial | Localization.BloodCellsIntracellular | Localization.VascMembraneBasolateral;

            case TissueLocation.Intracellular:
               var vacEndoLocalization = vascularEndoLocation == IntracellularVascularEndoLocation.Endosomal
                  ? Localization.VascEndosome
                  : Localization.VascMembraneBasolateral;
               return Localization.Intracellular | Localization.BloodCellsIntracellular | vacEndoLocalization;

            case TissueLocation.ExtracellularMembrane:
               var membLocation = membraneLocation == MembraneLocation.Apical
                  ? Localization.VascMembraneApical
                  : Localization.VascMembraneBasolateral;
               return Localization.Interstitial | Localization.BloodCellsMembrane | membLocation;

            default:
               throw new ArgumentOutOfRangeException(nameof(tissueLocation), tissueLocation, null);
         }
      }
```

**Comment by Yuri05** [comment]
looks good for me

**Comment by PavelBal** [comment]
`f_expr BC interstitial`
What is it? Shouldn't it be `f_expr BC membrane`?

>f_expr_XXX correspond 1:1 to the flags in the UI. So if f_expr_XXX=1: flag is activated, if f_expr_XXX=0: flag is deactivated - or do I miss something?

Looks correct to me.

**Comment by Yuri05** [comment]
>f_expr BC interstitial
What is it? Shouldn't it be f_expr BC membrane?

Yep. Changed.

**Comment by msevestre** [comment]
this is implemented
