### ISSUE TITLE
Remove  Undo Concept from PKSim (and MoBi)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1570]
With PKSim v5, we started the concept of Command in order to protocol each action performed by the user. We also went ahead and decided to implement the concept of undo and rollback for most of the actions performed by the user. 

I would like to suggest to remove the undo and rollback functions from the suite. 
## BUT WHY??

1. The code is extremely complicated at times because we have to keep track of how to undo an action. Especially with the concept of building blocks commit etc, we always have to make sure that we know exactly in which state we can rollback to. Moreover, we need to perform some very simple actions and a complicated way just to ensure that we can perform an undo

1. I don't think that people are using this feature often. 

1. Memory overhead. We need to perform many actions just to support undoing. For example, deleting a building block means we need to store the building block in memory just in case the user wants to go back. So we need to serialize it as well. None of this would be required if we were just deleting the BB or simulation.

1. But first and foremost, it makes also new development difficult. For example with the rel exp redesign. We want to add some features to set some values for fractions expressed xxx based on some user actions. If we want to be consistent with the rest of the UI, we have to implement everything in such a way that it can be undone. It becomes extremely cumbersome

Therefore I would suggest keeping the command concept as they provide a nice way to document user actions. But I am proposing to remove the undo/rollback capability

Thoughts? @Yuri05 @sfrechen @TWendl @PavelBal @StephanSchaller @Christoph27 @JanSchlender

**Comment by PavelBal** [comment]
I am against this proposal, I use this feature A LOT! It actually saved my life for many-many times.

I see your points regarding the complex implementation and memory overhead. Can we maybe find a compromise here? Let's see what other users have to say.

**Comment by msevestre** [comment]
I would argue that your project should be under source control (or Dropbox of whatever) so that even if you make a mistake, you can always go back to a safe state.

I honestly do not think that the overhead in terms of complexity is sustainable, especially looking at what we want to do with OSMOSES. The engineering will be much more difficult because of the undo capabilities

**Comment by Yuri05** [comment]
I am against the proposal as well. Undo is extremely useful feature and I do use it quite often.

**Comment by StephanSchaller** [comment]
I don't use it much but I guess this depends on personal preferences.

I can confirm that most other users I know and we have trained use this feature a lot and would certainly be very disappointed if it was removed.

Could we do anything to make it easier to set up rollback functionality for new features?

**Comment by msevestre** [comment]
>Could we do anything to make it easier to set up rollback functionality for new features?

Maybe. However, we spent quite some time designing this and I would nto know how to make it better. For instance ,I don't see any way around saving the state before applying a change. Deleting a simulation => You need to save the simulation .Configuraign a simulation, you need to save the previous simulation etc... 

At any rate, we could maybe define actions such as Delete Simulation, configure simulations etc.. as irreversible actions. At least we would not have to carry everything in memory until the project is closed.

That will not make things easier for the rest for instance. It is required to always program using commands and composing commands just to ensure undoability.

**Comment by Christoph27** [comment]
I ~never use the PK-Sim undo function and instead go back within the SVN versioning (I’m using the SVN “commit” quite often).

**Comment by msevestre** [comment]
@Christoph27 my man:)

Ok I think we'll keep that feature for now. Maybe we can think about removing undo for some major actions if need be
