### ISSUE TITLE
Disable right mouse click in context menus

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1574]
In context menus (e.g., Simulation -> Commit to Building Block"), clicking with the right mouse button triggers the action. I think most users do not expect any action with the rmb here.

Same for MoBi.

**Comment by Yuri05** [comment]
Indeed... never tried this. Fortunately we have an UNDO 😉 
Some programs behave the same (e.g. Firefox), but I agree, right-click on a context-menu entry should not trigger the action

**Comment by PavelBal** [comment]
Unfortunately, UNDO doesn't work for "commit to BB" in MoBi :(

![Uploading image.png…]()

**Comment by msevestre** [comment]
This is the standard behavior of context menus....Why would we change this

**Comment by msevestre** [comment]
Actually I am yet to find a tool where this is not like this. I have tried in Slack, Zoom, VStudio etc... this always behave likes this
I am against this proposal

**Comment by PavelBal** [comment]
I am very surprised but I must admit that yes, it seems to be a standard behavior (has it always been like this?). Well, I still don't like it, but if it is the standard...

**Comment by msevestre** [comment]
Yes. I would not have expected otherwise.. Closing
