### ISSUE TITLE
Value of blood volume: difference between PK-SIM and reference, ICRP

### ISSUE THREAD

**Issue by Lee21A** [Open-Systems-Pharmacology/PK-Sim#1575]
Hi everyone!

According to PK-SIM default Individual data, values of venous blood volume and arterial blood volume are 0.96 L and 0.42 L, respectively. (European, ICRP, 2002). 
If the total blood volume is the sum of venous blood volume and arterial blood volume,  this value is quite different from the value in the references(ICRP, 5.3L).

I would be grateful if you could explain this to me.

Lee

**Comment by StephanSchaller** [comment]
Hi Lee,

total blood volume also includes the blood volume within each organ (that's volume of plasma and RBCs in each organ).
Hope this helps,
Stephan

**Comment by Lee21A** [comment]
Thank you Stephan.
I understood.
And if possible, would you give me a comment about #1571 ? 

Lee

**Comment by Lee21A** [comment]
@StephanSchaller , Thank you very much for your comment.  

Lee
