### ISSUE TITLE
Simulation comparison does not show differences in RHS formula of parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#158]
In the project attached compare 2 simulations **NEW** and **Xanthium Lint 80**.
Comparison shows only 1 difference (new observer).

However, there are differences in the RHS formulas, which are not shown:

_Parameter: Xanthium Lint 80|Applications|oral 300mg|Xanthium Lint80|Application_1|Suspension fraction Duodenum
    Value: 0
    Formula: 0
    RHS_Formula: Use_As_Suspension ? ( TabletIsActive AND OralApplicationsEnabled ? (w_fact*( GET *fraction_sto*FillLevelFlag_duo-w_duo*fraction_duo*FillLevelFlag_uje)) : 0)  : 0_

**vs.**

_Parameter: NEW|Applications|oral 300mg|Xanthium Lint80|Application_1|Suspension fraction Duodenum
    Value: 0
    RHS_Formula: Use_As_Suspension ? ( TabletIsActive AND OralApplicationsEnabled ? (w_fact*( w_sto *fraction_sto*FillLevelFlag_duo-w_duo*fraction_duo*FillLevelFlag_uje)) : 0)  : 0
[Theophylline_TestCases_Problem.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1006912/Theophylline_TestCases_Problem.zip)
_

**Comment by msevestre** [comment]
This is by design:
Those parameters are hidden in PK-Sim. Hidden parameters are not shown in difference

```
   public bool ShouldCompareParametersIn(IComparison<IParameter> comparison)
      {
         if (!comparison.ComparedObjectsDefined)
            return true;

         var parameter1 = comparison.Object1;
         var parameter2 = comparison.Object2;
         if (parameter1.Visible && parameter2.Visible)
            return true;

         //at least one parameter hidden
         return comparison.Settings.CompareHiddenEntities;
      }
```
@Yuri05  Do you want to change that behavior for PK-Sim?
Alternatively, `CompareHiddenEntities` could be a visible setting of the comparison. (this is not visible in the UI but can be set)

**Comment by msevestre** [comment]
This is how it could look like
![image](https://cloud.githubusercontent.com/assets/1041237/26642747/e4b8ce4a-45fc-11e7-9f3d-d84e9336ba0f.png)

**Comment by Yuri05** [comment]
Yep, I think we need this option.

**Comment by msevestre** [comment]
done in https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/103
