### ISSUE TITLE
Feature wish: Display distribution models in simulation dialog box on mouseover

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1586]
I think some of the information displayed in the dialog box on mouseover of a simulation is less relevant, e.g. `Model` and `Allow Aging` and could be removed. However, other important information is missing. 
For example, when testing multiple distribution models (e.g. partition coeffs) during model building, I often forget which distribution model is used in the different simulations. Opening the `Configure` window for each simulation is quite cumbersome and I would appreciate if this information could be displayed in the dialog box on mouseover like this:

![Untitled](https://user-images.githubusercontent.com/26541603/98240233-64e9c080-1f69-11eb-8b22-eb00c7fe1eb8.png)

**Comment by msevestre** [comment]
@AndreDlm Completely agree with this.
I think we do not even need the building blocks as they are visible when you expand the node.
Even the Calculation methods are related to the individual and cannot be overwritten

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/109708274-2e176600-7b69-11eb-8f61-ca7042f468c7.png)

It has to be `per compound` as different compound may have different distribution models
