### ISSUE TITLE
Verify Initial Concentration for transporters

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1596]
@PavelBal the nightly will allow you to create transporter and simulations using this transporter (simply use the indiivudal...no need to create a transport process as it is not used  at the moment)

**Comment by msevestre** [comment]
FYI @Yuri05

**Comment by PavelBal** [comment]
I will just compile all my comments here:

1. There are now multiple entries in the PSV-BB where both the Formula and the Value are not available:
![image](https://user-images.githubusercontent.com/25903040/100065304-ea0f1980-2e33-11eb-85d8-a5be99123997.png)

Until now such values were zero. It is somehow strange to see "not available" for both properties.

2. I now simply do not understand the logic, when a certain parameter is created. E.g., "fraction expressed apical" is only available for certain organs, and the only in Intracellular. It is just not clear where such property is defined.

**Comment by msevestre** [comment]
@PavelBal 

For 1: This is where are structure is not 100% . Parameters are either local or global. So far, a PSV has one entry for each local parameters. However some of those parameters do not make sense. We have decided to "remove" parameters where values and formula is NaN. Now in PK-Sim, we could ensure that those entries are removed when we create the PSV so that exporting to MoBi would not  show them.
Alternatively, we could say that no entry is created by default if the value of the parameter is NaN. At least this is then consistent between PK-Sim and MoBi. PK-Sim then adds special non NaN entries only

2/ Fraction expressed apical should be available in all organ with lumen intracellular no? 

3/ok needs to be fixed. It's a bug

4/Yep thanks

5/yes it was discussed yesterday. Makes sense. What about brain initial concentration in other compartments?

**Comment by msevestre** [comment]
@PavelBal @Yuri05 
>Initial concentration for VenousBlood, ArterialBlood, and PortalVein BloodCells is not set - should be set to formula "InitialConcentrationBloodCells_Transporter"

We did not have any transporter in those location before. Is this ok to add that now? I am not sure what can of worm we are opening here

**Comment by PavelBal** [comment]
@msevestre It is the transporter between RBC and plasma, we did not have this at all. If the transporter is present in the RBC membrane in any tissue, it is also in the "global" blood ;)

**Comment by msevestre** [comment]
ok fair enough

**Comment by msevestre** [comment]
V_pls  not availale. I'll have to use f_vas* (1-HCT)

**Comment by msevestre** [comment]
ok 3 and 4 fixed

**Comment by msevestre** [comment]
@Yuri05 How do you feel about not generating entries in PSV for parameter whose value is set to NaN? This would remove a lot of unnecessary entries in the PSV. PK-Sim will add explicitly the one for values != NAN

**Comment by msevestre** [comment]
Parmaeter name for fraction bbb? `Fraction expressed at blood brain barrier`?

**Comment by Yuri05** [comment]
>How do you feel about not generating entries in PSV for parameter whose value is set to NaN? This would remove a lot of unnecessary entries in the PSV. PK-Sim will add explicitly the one for values != NAN

Don't see a problem if we exclude NANs from PSV.

>Parmaeter name for fraction bbb? Fraction expressed at blood brain barrier?

Fine for the moment. We will need to go through all names/descriptions of new parameters and check/adjust them anyway once all the functionality is there.

**Comment by msevestre** [comment]
No entries with NaN (value and formula) are created in PSV

@PavelBal Feedback required for item 2 please
I created an entry for 5 as it is still not clear to me (#1602 )

**Comment by Yuri05** [comment]
>If you could fix that...that would be great :) but wait until my changes are merged.

Yes. LEt me know when you are done with your changes.

**Comment by msevestre** [comment]
@PavelBal Please review again. Especially plasma start value fuer BBB

**Comment by PavelBal** [comment]
1. Enzymes are missing in blood organs VenousBlood, ArterialBlood, PortalVein (isPresent is not set and initial concentrations are set to 0).

2. Initial concentration parameters in Endosomes are somehow "Source of start value not defined"
![image](https://user-images.githubusercontent.com/25903040/100750528-74342080-33e6-11eb-9373-09aa292beb81.png)

3. `InitialConcentrationBrainPlasma_Transporter`

`RC * rel_exp_brn * f_exp_brn_bbb` should scale with plasma volume, I think, so

`RC * rel_exp_brn * f_exp_brn_bbb * 1/(f_vas*(1-HCT))`

**Comment by PavelBal** [comment]
tbc

**Comment by msevestre** [comment]
2/ This is because your spatial structure is Small Molecule but the PSV are generated for 2 COMP as well
3/ I'll trust you on this :)

**Comment by msevestre** [comment]
ok I have fixed 1 and 2. 3 to be discussed once you are sure

**Comment by msevestre** [comment]
in fact that's not quite true. The formula that we have for Plasma does not apply for vascular organs.
Can you send me the formula for vascular organs? (e.g Volume Endothelium does not exist)

**Comment by PavelBal** [comment]
Here is the summary of the equations for the initial concentrations of transporters with visualization in the ppt. Please review and compare with implemented state.
[InitialConcentrationsTransporters.pptx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5636158/InitialConcentrationsTransporters.pptx)

- RBC
  - `RC * rel_exp_bc`
- Plasma (excl. AB, VB, PV)
  - `RC * rel_exp_vasc * V_vasc / (V_org * f_vas * (1 - HCT))`
- Interstitial
  - `RC * rel_exp_org * f_exp_org_basolat * 1 / f_int`
- Intracellular Kidney, Liver, Mucosa
  - `RC * rel_exp_org * f_exp_org_apical * 1 / f_cell`
-Plasma Brain
  - `RC * rel_exp_brn * f_exp_brn_bbb * 1 / (f_vas * (1 - HCT))`
- Interstitial Brain
  - `RC * rel_exp_brn * f_exp_brn_tissue * 1 / f_int`

**Comment by msevestre** [comment]
all right. Done
