### ISSUE TITLE
PK-Sim 7.0 vs. PK-Sim 6.4.1: Differences in physiological parameter values

### ISSUE THREAD

**Issue by edschm** [Open-Systems-Pharmacology/PK-Sim#160]
Based on the publication: [http://dx.doi.org/10.1007/s40262-016-0422-3](url)

When creating an individual with the same biometrics, the physiology is, however, different in both versions.

**Comment by msevestre** [comment]
@edschm Are they different from the publication or are the values in 7.0 different from 6.4?

**Comment by edschm** [comment]
@msevestre The values in 7.0 are different from 6.4.1. Both versions are actually based on the publication.

**Comment by msevestre** [comment]
@edschm 7.0 is not . The upcoming 7.1 is
