### ISSUE TITLE
relExp-Redesign: background color

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1600]
set read-only fields bg-color to grey 
![grafik](https://user-images.githubusercontent.com/25061876/99878040-c749ee80-2c02-11eb-9606-273529cec0ec.png)

Compare current version:
![grafik](https://user-images.githubusercontent.com/25061876/99878094-493a1780-2c03-11eb-9145-1bd042615444.png)

**Comment by msevestre** [comment]
The problem with this is that you do not nsee the lines. With a simple UI like before, no problem. But with the new more packed UI, it is hard to see what belongs with what

**Comment by msevestre** [comment]
see here
![image](https://user-images.githubusercontent.com/1041237/99879713-8c34c480-2bdc-11eb-937a-1a42be6584a7.png)

**Comment by Yuri05** [comment]
Setting cell borders to bold/dark colour does not help?

**Comment by msevestre** [comment]
This is not something we do anywhere. Not using background color for disabled cell is something we do. Therefore...for consistency purposes...I would not change anything.
Let's discuss
