### ISSUE TITLE
Information in advanced protocol is lost in snapshot

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#1601]
Steps to reproduce:
Create a project with an advanced protocol as the following one:
![advancedProtocol](https://user-images.githubusercontent.com/26460649/100090017-db842a80-2e52-11eb-9c35-b17f99fa74da.PNG)
Then export the project to snapshot. The snapshot does not contain the information about the repetitions anymore, see here:
![SnapshotAdvancedProtocol](https://user-images.githubusercontent.com/26460649/100090032-df17b180-2e52-11eb-92ae-41f996fd86f1.PNG)

**Comment by Yuri05** [comment]
Interestingly, If I take such a protocol, change the type from **advanced** to **simple**, then change back to **advanced** and recreate all the settings (number of repetitions etc.) - then the export to snapshot is correct

**Comment by Yuri05** [comment]
@TWendl Somehow I cannot rproduce it anymore. Can you upload a project where the problem happens?

**Comment by sfrechen** [comment]
@Yuri05 
https://github.com/Open-Systems-Pharmacology/Cimetidine-Alprazolam-DDI/blob/main/Cimetidine-Alprazolam-DDI.json

**Comment by Yuri05** [comment]
@sfrechen This does not really help to reproduce the problem. We need a **project** (not snapshot) with an administration protocol which is not correctly recreated from snapshot.

**Comment by TWendl** [comment]
[Bug.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5658646/Bug.zip)

**Comment by Yuri05** [comment]
[026_App_Snapshot.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5658791/026_App_Snapshot.zip)
Reduced to only 1 administration protocol.

Before exporting to snapshot:
![grafik](https://user-images.githubusercontent.com/25061876/101475440-b3b1be00-394c-11eb-885c-8ca6e71f36af.png)

After Export/Reimport from Snapshot:
![grafik](https://user-images.githubusercontent.com/25061876/101475490-c6c48e00-394c-11eb-8780-f7a477eb42c1.png)

**Comment by msevestre** [comment]
WTF...Ok probably an easy fix. Thanks for sharing the project @TWendl
