### ISSUE TITLE
Feature request : Enabling the export of 'PI for matlab' from PKSIM (in developer mode) for new PKSIM

### ISSUE THREAD

**Issue by Sulav1** [Open-Systems-Pharmacology/PK-Sim#1603]
This feature in the previous PKSIM enabled to work with PI in other code based language such as Matlab. Disenabling this feature in the new version unfortunately causes loss of an important function.

**Comment by msevestre** [comment]
This is implemented
![Uploading image.png…]()

**Comment by Sulav1** [comment]
Hi @msevestre, the issue (export of PI to XML which was possible previously) is still not fixed in the version 10. This was tested in the dev mode, but no option to export the PI to XML was shown.

**Comment by msevestre** [comment]
@Sulav1 @Yuri05 

This was the only version we had before. 

![image](https://user-images.githubusercontent.com/1041237/131365768-ae22d982-b4f6-4ef8-a6f1-32008a80b21c.png)

(screenshot from v8). 
I am not sure what you are requesting ...

**Comment by msevestre** [comment]
note that this export the m file as well as am XML file in a folder
![image](https://user-images.githubusercontent.com/1041237/131365893-be0500a3-0543-44a2-9887-4d610464de12.png)


As far as I am concerned...this is it

**Comment by msevestre** [comment]
Well let me check that we are creating the XML file as well in v10. But this should be the same core

**Comment by msevestre** [comment]
it's there allrigth. Nothing to change
