### ISSUE TITLE
Cannot reload simulation from snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1604]
[Problem01.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5606773/Problem01.zip)
When saving the attached project and reloading it from snapshot, the error message below comes and the simulation cannot be loaded:
```
Warning: Parameter 'Specific intestinal permeability (transcellular)' defined in molecule 'Itraconazole' has an invalid value: NaN
Error: Cannot load Simulation 'LNG 0.03 mg + EE 0.03 mg_Itraconazole 100 mg DDI 28th day'
```

Permeabilty is not NaN for sure in the original project; I can also run the simulation and everything is fine. But the snapshot crashes...

**Comment by msevestre** [comment]
Snapshot loader says it's NaN so it is NaN. End of discussion

**Comment by Yuri05** [comment]
The problem is that Intestinal Permeability (and also Permeability) is not correctly saved into the snapshot:
in the original-BB it looks like this:
![grafik](https://user-images.githubusercontent.com/25061876/100460199-142c3a00-30c7-11eb-8df3-e878491f2bfe.png)
![grafik](https://user-images.githubusercontent.com/25061876/100460253-2c03be00-30c7-11eb-99f4-437d3ba14a25.png)

And in the exported snapshot:
![grafik](https://user-images.githubusercontent.com/25061876/100460163-08407800-30c7-11eb-9df3-53fa84eee8b2.png)

So only the *name* of parameter alternative is exported, but not the value. When this parameter alternative is created during loading from snapshot, the value is set to NaN and it crashes in the simulation

**Comment by msevestre** [comment]
Was this created with V8 or v9? I am pretty sure we fixed a very similar issue already.

**Comment by msevestre** [comment]
Can you reproduce with v9?

**Comment by Yuri05** [comment]
The project was created with V8 (or below).
In V9 (if I create a new compound) I cannot reproduce. Also cannot reproduce if I load a compound from the template database
(e.g. the Itraconazole template is currently saved with PK-Sim 7.4. Loading it in V9 and exporting to a snapshot works fine as well)

**Comment by msevestre** [comment]
Ok well there is nothing we can do here. I think we corrected this in v8 and if the snapshot is exported with an older version, it is wrong,.

**Comment by Yuri05** [comment]
The snapshot was exported with V9, but the project was created with <=V8

**Comment by msevestre** [comment]
Ok I have no idea then. A project conversion issue?!?

**Comment by msevestre** [comment]
@Yuri05 Can you try to reproduce?

**Comment by Yuri05** [comment]
With the project attached [Problem01_03.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6879655/Problem01_03.zip) I can reproduce. But this is again just the reduced version of the originally attached project (Created in V8 or so).
With projects created in V9 or V10 - cannot reproduce.

**Comment by msevestre** [comment]
ok this happens bacuae the flag IsDefault is not set properly (or IsInput) in the conversion from 7.2 to 7.3
I think most projects have been covnerted already at that stage so there is nothing we can really do. I could fix the conversion but it would require too much time. 
I am going to close this with "won't fix" please reopen if you see otherwise
