### ISSUE TITLE
Update PK-Sim DB to support cascading

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1610]
@Yuri05 I am done with the DB for the next few days. Can you do it in the meantime? 
Please let me know when you plan on starting with this

**Comment by msevestre** [comment]
Please make a branch of the ` feature/relative_expression_redesign` branch!

**Comment by msevestre** [comment]
and PR to this branch of course 👍  feature/relative_expression_redesign

**Comment by msevestre** [comment]
@Yuri05 I need to do an update in the DB. It will be merged tomorrow in the branch

**Comment by Yuri05** [comment]
Duplicates #1578
@msevestre will try to do it today

**Comment by msevestre** [comment]
@Yuri05 I have edited the DB. Please wait until tomorrow if possible or until I give you the ok

**Comment by Yuri05** [comment]
ok

**Comment by msevestre** [comment]
@Yuri05 Make a branch of https://github.com/Open-Systems-Pharmacology/PK-Sim/tree/1609-snapshot-project-conversion
I won't update the db again today. Create a PR then on this branch
