### ISSUE TITLE
Initial concentrations for enzymes

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1617]
Here is the summary of the equations for the initial concentrations of enzymes with visualization in the ppt. Please review and compare with implemented state.

[InitialConcentrationsEnzymes.pptx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5635875/InitialConcentrationsEnzymes.pptx)

- RBC
  - `RC * rel_exp_bc * f_exp_bc_cell`
- Plasma Vascular tissues (ArterialBlood, VenousBlood, PortalVein)
  - RC * (rel_exp_pls + rel_exp_bc * f_exp_bc_membrane * HCT / (1 - HCT) + rel_exp_vasc * f_exp_vasc_apical * V_vasc / V_pls)

As the vascular tissues do not have volume of endothelium, the formula is reduced to 
    - RC * (rel_exp_pls + rel_exp_bc * f_exp_bc_membrane * HCT / (1 - HCT)

To use the same formula, parameter “Volume (endothelium)” could be added to the three organs with the value 0.
- Plasma organ tissues
  - RC * (rel_exp_pls + rel_exp_bc * f_exp_bc_membrane * HCT / (1 - HCT) + rel_exp_vasc * f_exp_vasc_apical * V_vasc / V_pls)
- Endosome
  - RC * rel_exp_vasc * f_exp_vasc_endo * 1 / f_endo
- Interstitial
  - RC * (rel_exp_org * f_exp_org_int * 1 / f_int + rel_exp_vasc * f_exp_vasc_basolat * V_vasc / (f_int * V_org))
- Intracellular
  - RC * rel_exp_org * f_exp_org_cell * 1 / f_cell

**Comment by msevestre** [comment]
I think I'd rather not add parameter that do not make sense but I can be converted. @Yuri05 ?

**Comment by Yuri05** [comment]
>I think I'd rather not add parameter that do not make sense

Fully agree.

**Comment by msevestre** [comment]
What's the plasma concentration in vascular organ for transporter?

**Comment by msevestre** [comment]
would it be
RC * rel_exp_vasc * HCT / (1 - HCT)?

**Comment by PavelBal** [comment]
For **transporter**? Zero, nothing to transport there.

**Comment by msevestre** [comment]
Well we have the influx /efflux plasma <=> interstitial

**Comment by PavelBal** [comment]
What do you mean by "Vascular organ"? ArterialBlood, VenousBlood, PortalVein? Of so - the do not have interstitial -> no transport.

For other organs it is 

`RC * rel_exp_vasc * V_vasc / (V_org * f_vas * (1 - HCT))`

**Comment by msevestre** [comment]
Sorry I meant plasma<=> blood cells

**Comment by PavelBal** [comment]
These are located in BloodCells and not Plasma.

**Comment by msevestre** [comment]
Formula for AtiveInflux at the moment look like so (e.g. Plasma=>Cell)
![image](https://user-images.githubusercontent.com/1041237/101367268-f8b5f180-3873-11eb-8404-fe0064aafee1.png)

it looks at the TARGET volume but the SOURCE concentration of the transporter. If there is no transporter, we can't have a transport

Or should Inflxu use the TARGET Cocnentration of the transporter?

/CC
@Yuri05 

In theory, we only need one kinetic for all our Inflxu and one for all our efflux

I checked in V9 and it's the same
![image](https://user-images.githubusercontent.com/1041237/101367526-416daa80-3874-11eb-9af4-9296c6612a8a.png)

Influx is something like [TRANSPORTER_SOURCE] * VOL_TARGET

**Comment by msevestre** [comment]
ok @PavelBal I'llupdate the code. I'll make an update here when I am done

**Comment by msevestre** [comment]
All right. Please check the pkml attached here. I have influx and efflux process defined in all possible directions.
[Influx and Efflux.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/5654356/Influx.and.Efflux.zip)

**Comment by msevestre** [comment]
I am going to merge this code and the nightly tomorrow will produce exactly this

**Comment by PavelBal** [comment]
Looks good so far, did not find anything wrong so far. Great work!

**Comment by msevestre** [comment]
Brain fixed
