### ISSUE TITLE
PK-Sim doesn't allow performing two reactions with the same enzyme

### ISSUE THREAD

**Issue by pklei05** [Open-Systems-Pharmacology/PK-Sim#162]
Sunitinib is metabolized by CYP 3A4 (CYP 3A11 comparable enzyme in mice) to its active metabolite SU12662, which is further metabolized by the same enzyme. 
I set up a simulation with the following reaction diagram:

![image](https://cloud.githubusercontent.com/assets/28653466/26164962/a88b7810-3b2e-11e7-9138-9f62b02cf6a4.png)

PK-Sim doesn't allow perfoming two reactions with the same enzyme. Expression data are set to zero for the second reaction:

![image](https://cloud.githubusercontent.com/assets/28653466/26165110/0f11c83c-3b2f-11e7-87c7-d00b8a81577d.png)

**Comment by msevestre** [comment]
@pklei05 I think this is simply a display issue at that stage. The expression data are independent from the Drug. They are defined in the individual. if you go with your cursor over let say 'HEART' you will see that this is the expression for Heart|Interstitial that is set to 0
![image](https://cloud.githubusercontent.com/assets/1041237/26167573/17199f20-3b05-11e7-8903-791ec99bc00d.png)

I believe that the two reactions are happening as expected (the diagram shows that the reactions are created in the simulation). Or do you have the impression that one of the reaction is not taking place?

**Comment by msevestre** [comment]
@pklei05
Those parameters are defined because of the setting  `Local. Vasc. Endothelium = Interstitial` for `CYP3A11`
However they are not used anywhere in the system because the value of the Relative Expression is set to a predefined ratio in this case 
```
Chapter 14. PK-Sim® - Expression Data

In addition, for the vascular endothelium, proteins can either be located in the cytosol or in endosomes. In PK-Sim®, only the endosomal space of the vascular endothelium is explicitly represented by respective compartments. Since the cytosol of the vascular endothelium is not explicitly represented, cytosolic proteins of the vascular endothelium are technically implemented in the interstitial space of the organs. To account for the true cytosolic location, the respective protein activities are calculated on the basis of an expression value corrected by the ratio of the volumes of vascular endothelium and interstitial space. For this reason, the following selections are possible in the drop-down menu:

    Location in vasc. endothelium: Endosomal

    Location in vasc. endothelium: Interstitial as surrogate for cytosolic space
```

I think those parameters in interstitial should be simply hidden in this case.

**Comment by msevestre** [comment]
@Yuri05 Thoughts?

**Comment by Yuri05** [comment]
>I think those parameters in interstitial should be simply hidden in this case.

Yes, those relative expression in interstitial parameters should be hidden for
`Localization in Tissue=Intracellular` & `Localization in vasc. Endo=Interstitial`

**Comment by msevestre** [comment]
ok going to close if favor of issue 
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/166

**Comment by pklei05** [comment]
@msevestre 
You're right, it's just a display issue. When I changed the localization of CYP 3A11 to 'endosomal', the duplicates were gone. Both reactions are taking place. 
Thank you!

**Comment by Dr-K1997** [comment]
@pklei05 Hi, I dont find CYP3A11 in PK-SIM. Could you please help me in locating
