### ISSUE TITLE
Update pgp

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1623]
For reasons of downward compatibility:
the PgP transport implementation remains for the time being AS IS:
* PgP is only offered where it has already been the case so far (and where it was really a PgP and not just efflux as with "PgP Kidney =>Urine" etc.), so:
  * Tissue organs: Interstitial => Intracellular
  * Brain (in the case of BloodBrain-Barrier) also plasma <=> Interstitial
  * Lumen <=>Mucosa / Intracellular

- [x] For the transports implemented in the OSP 10 NEW (plasma <=> BloodCells etc.) no PgP is initially offered
- [x] When creating new transports, PgP is never offered as the default
- [x] For the transporters where we currently have Default = "PgP", from now we use Default = "Efflux" 
- [x] However, the user can still manually switch the transporter type to PgP

**Comment by msevestre** [comment]
@Yuri05 Google translate of your email on pgp :)

**Comment by Yuri05** [comment]
>Google translate...

Quite good I would say :)

**Comment by msevestre** [comment]
@Yuri05 
We add this so far
| transport\_direction | process | source\_organ | source\_compartment | target\_organ | target\_compartment |
| :--- | :--- | :--- | :--- | :--- | :--- |
| PgpIntracellularToInterstitial | PgpSpecific | Fat | Intracellular | Fat | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Gonads | Intracellular | Gonads | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Heart | Intracellular | Heart | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | LargeIntestine | Intracellular | LargeIntestine | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Lung | Intracellular | Lung | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Muscle | Intracellular | Muscle | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Pancreas | Intracellular | Pancreas | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Skin | Intracellular | Skin | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | SmallIntestine | Intracellular | SmallIntestine | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Spleen | Intracellular | Spleen | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Stomach | Intracellular | Stomach | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Bone | Intracellular | Bone | Interstitial |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | Caecum | Intracellular | Lumen | Caecum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | ColonAscendens | Intracellular | Lumen | ColonAscendens |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | ColonDescendens | Intracellular | Lumen | ColonDescendens |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | ColonSigmoid | Intracellular | Lumen | ColonSigmoid |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | ColonTransversum | Intracellular | Lumen | ColonTransversum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | Duodenum | Intracellular | Lumen | Duodenum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | LowerIleum | Intracellular | Lumen | LowerIleum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | LowerJejunum | Intracellular | Lumen | LowerJejunum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | Rectum | Intracellular | Lumen | Rectum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | UpperIleum | Intracellular | Lumen | UpperIleum |
| PgpMucosaIntracellularToLumen | MucosaPgPToLumen | UpperJejunum | Intracellular | Lumen | UpperJejunum |
| PgpIntracellularToInterstitial | PgpSpecific | Caecum | Intracellular | Caecum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | ColonAscendens | Intracellular | ColonAscendens | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | ColonDescendens | Intracellular | ColonDescendens | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | ColonSigmoid | Intracellular | ColonSigmoid | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | ColonTransversum | Intracellular | ColonTransversum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Duodenum | Intracellular | Duodenum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | LowerIleum | Intracellular | LowerIleum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | LowerJejunum | Intracellular | LowerJejunum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Rectum | Intracellular | Rectum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | UpperIleum | Intracellular | UpperIleum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | UpperJejunum | Intracellular | UpperJejunum | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Pericentral | Intracellular | Pericentral | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Periportal | Intracellular | Periportal | Interstitial |
| PgpIntracellularToInterstitial | PgpSpecific | Kidney | Intracellular | Kidney | Interstitial |
| PgpBrainTissueToInterstitial | PgpSpecific | Brain | Intracellular | Brain | Interstitial |
| PgpBrainInterstitialToPlasma | BrainPgPToPlasma | Brain | Interstitial | Brain | Plasma |

Do I need to remove anything? I don't think so but I am bit confused with usage of some <=> in your description

**Comment by msevestre** [comment]
@Yuri05 This is fixed I believe

**Comment by Yuri05** [comment]
nothing to remove here. In the current version we have processes like "KidneyPgpToUrine", "LiverPgpToDuodenum", "LiverPgpToDuodenum" - which are in fact Effluxes - but they don't appear in your list. So all fine.
