### ISSUE TITLE
Can't edit weights of an existing individual building block

### ISSUE THREAD

**Issue by kartiklakhotia** [Open-Systems-Pharmacology/PK-Sim#1629]
I am using PK-Sim for drug pharmacokinetic modeling and have created a template building block for a person. Now, I wish to create individual building blocks for the subjects with specific weight/height/age parameters. However, looks like PK-Sim doesn't allow editing these parameters for an existing building block. I am also unable to edit them after cloning or in simulations.

**Comment by msevestre** [comment]
You can use the scale function for this (right click on individual, scale)

Changing BW requires the create individual algorithm to kick in. This is why you can't just change the BW (or height, Age etc..)

Scale is what you need
