### ISSUE TITLE
Simulation: error bars don't disappear

### ISSUE THREAD

**Issue by pklei05** [Open-Systems-Pharmacology/PK-Sim#163]
If I unselect the box for visualization of my observed data, the data points disappear but the standard deviation remains visible. 

![image](https://cloud.githubusercontent.com/assets/28653466/26163321/971adc10-3b29-11e7-8373-f1fba8b4de7b.png)

[Example Sunitinib github.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1008458/Example.Sunitinib.github.zip)

**Comment by msevestre** [comment]
Hi @pklei05 
Thanks. This is indeed a bug in 7.0 that was fixed already (in PKSim and in MoBi)
https://github.com/Open-Systems-Pharmacology/MoBi/issues/45

and will be part of the upcoming release 7.1.
Cheers
