### ISSUE TITLE
Bug when creating a population from an individual in PK-Sim

### ISSUE THREAD

**Issue by teutonicod** [Open-Systems-Pharmacology/PK-Sim#1630]
Hi all,

I think I found a bug in PK-Sim, but I am still using an older version (8 build 22) and I would like to know if you are able to reproduce in the current version:

1. Create an individual in PK-sim, you can leave the default values
2. Double click on the individual to open it in PK-Sim
3. Then make a right click on the individual BB and select "Add population" WITHOUT closing the tab with the individual
4. In the population create a population with the same parameters as your individual in both ranges (see below). This is a realistic example, since it would mean include the variability of a subject of certain covariates (e.g. same age and weight but difference in the proportions of tissue weight). When doing so, it is important that you do not fix the BMI as well, as I did in the screenshot, otherwise you get an error message that the population cannot be created
 
![image](https://user-images.githubusercontent.com/11489621/103884216-89375a00-50de-11eb-8417-b687900682a2.png)

When you create the population you find the following error:

![image](https://user-images.githubusercontent.com/11489621/103884851-6e191a00-50df-11eb-9b1e-1185cde85922.png)

If you click on "Quit", I got a message from Windows saying that PK-Sim does not work correctly and the program closes automatically. If you chose "Continue" the population windows does not close and it seems non responsive. It become responsive if you edit any covariate (like change the weight of the population). In this case you see the button Next appearing again, but this is unexpected from the user I think.

**Another important point: if you do exactly the same process WITHOUT STEP 2, so without having the subject tab open, everything works fine without any error. The population I wanted is created and works fine.**

Hope that I was clear enough in the different steps, otherwise let me know, and sorry for not been able to test it in the current PK-Sim version.
In case you have questions just let me know!

Donato

**Comment by StephanSchaller** [comment]
Hi Donato,

Thanks for posting this.
I could not reproduce this error in V9.1 Build 2.

But for you, everything also works fine if you close the "individual tab" right? So it is only a minor (non-essential bug) for you?

Best,
Stephan

**Comment by teutonicod** [comment]
Hi Stephan,

Yes, also in my case everything worked fine if the individual tab was not open. I just posted the bug since I found it strange that the error message was related to having the tab open or not. 
I also forgot to mention that I am still on Windows 7, so this could also be the origin of the error message.
Donato

**Comment by msevestre** [comment]
I cna reproduce the bug

**Comment by msevestre** [comment]
@teutonicod the error was also that you were trying to create a 73cm person with weight 176 kg (clearly mixing height and weight)
The message will come again, this time however the app won't crash
