### ISSUE TITLE
Chart Editor: sort available axis dimensions in dropdown menu alphabetically

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1641]
Could be an April Fool's and it took me quite some time to find the axis dimension `Amount` in the Chart Editor. It is well hidden in the middle of the dropdown menu:

![image](https://user-images.githubusercontent.com/26541603/108240854-899a2a80-714b-11eb-8977-e766b1a6c173.png)

**Comment by msevestre** [comment]
This is a regression. It should be sorted. Good find

**Comment by AndreDlm** [comment]
And what about the dimension `Mass`? I couldn't find that at all in the list
The unit kg is available though when choosing `Amount`

**Comment by msevestre** [comment]
The chart use what we call MErgedDimension so that you can mix and match
Amount = Mass + molar Amount
Concentration = Mass + Molar Concentration

**Comment by AndreDlm** [comment]
Ok I see thx

**Comment by msevestre** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1041237/110158326-382ea400-7db7-11eb-90ca-1fab38f5141e.png)
