### ISSUE TITLE
Unable to export full report in pdf format

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/PK-Sim#1645]
Hello,

I am having trouble exporting the full project report from PK Sim in pdf format. I am getting an error message saying that the pdf file is damaged and cannot be repaired. I am using Adobe Acrobat Pro DC (32-bit). Any help is appreciated.

Thanks,
Kash

**Comment by Yuri05** [comment]
pdf reports are not supported anymore. closing
