### ISSUE TITLE
PKSim.CLI - run (arguments, limit output file size (.csv))

### ISSUE THREAD

**Issue by SRuedesh** [Open-Systems-Pharmacology/PK-Sim#1660]
Hello PK-Sim community,
I have a question/request regarding the "run" functionality in the PKSim.CLI:
Would it be possible to possible to add further arguments to "run" that would help limit the file output?

Use case:
Currently, I use "run" to conveniently run and export all simulations in my snapshot-files to .csv.
This works reasonably well, especially for individual simulations.
However, if I am correct, the produced output ("simulation_name-Result.csv") contains the predictions for all simulated compounds in all compartments in PK-Sim. This results in large file sizes (up to multiple GB for population simulations) of the .csv files.
As most PK-Sim users are probably only interested in a handful of predictions (i.e. PVB, amounts excreted...), it would be helpful to limit the output before running, either by specifying the observer paths in a list (or file) or, probably more convenient, provide keywords (i.e. "Midazolam" + "PeripheralVenousBlood") or regex to obtain the preferred output. Unfortunately, I found no such option in the PKSim.CLI help/documentation.
My current workaround (script iterating through all .csvs, deleting all the "unneeded" columns) works, but is unfortunately very slow when dealing with these large files. 

Thank you in advance for your help.

**Comment by msevestre** [comment]
Cool. Moving it to PK-Sim. With a bit of luck, we might be able to implement it

**Comment by msevestre** [comment]
@SRuedesh This is implemented in #1665 
something like this in the future
`PKSim.CLI.exe run -i "C:\tests\10.0\Snapshots" -o "C:\tests\10.0\Snapshots\out" -c --forAll`

**Comment by msevestre** [comment]
so if forAll is not set then only selected output will be exported. Thanks for the suggesiton
