### ISSUE TITLE
PARAM_StartAmount_Protein formula should use Volume of compartment

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1666]
and not Volume of protein container

@Pavel @Yuri05 Do we need this parameter `Volume of protein container` anymore?

**Comment by msevestre** [comment]
@Yuri05 I have removed it. It's not used anywhere else

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1669

**Comment by Yuri05** [comment]
>Do we need this parameter Volume of protein container anymore?

No :)
