### ISSUE TITLE
New Parameter description

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1668]
There are few TODOS left

| parameter\_name | display\_name | description |
| :--- | :--- | :--- |
| Fraction expressed basolateral | Fraction expressed basolateral | TODO: Fraction expressed basolateral |
| Fraction expressed apical | Fraction expressed apical | TODO: Fraction expressed apical |
| Fraction expressed at blood brain barrier | Fraction expressed at blood brain barrier | TODO: Fraction expressed at blood brain barrier |
| Fraction expressed brain tissue | Fraction expressed brain tissue | TODO: Fraction expressed brain tissue |

We will rename apical as plasma side and basolateral as tissue side,. Still :)

**Comment by msevestre** [comment]
@PavelBal Do we rename those guys as well?
![image](https://user-images.githubusercontent.com/1041237/110679912-0007d680-81a6-11eb-9f69-3d4c7495e239.png)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/110679957-0e55f280-81a6-11eb-819c-18af869cf3bf.png)

**Comment by PavelBal** [comment]
@msevestre These are for transporters only, right? But for transporters we do not have "apical as plasma side and basolateral as tissue side". Please specify the parameters we are talking about.

**Comment by msevestre** [comment]
Sure. But you see that we have Fraction expressed basolateral and Fraction expressed apical. Should not we change those as well?
Or is basolateral and apical clear in this case?

Last we still need a description for the parameter

**Comment by PavelBal** [comment]
The parameter names can be left as apical/basolateral to keep it consistent between liver/kidney/mucosa, but the display names could be adjusted as follows:

organ | parameter_name | display_name | description
-- | -- | -- | --
Kidney and Liver | Fraction expressed basolateral | Fraction expressed in tissue | Fraction of total protein expressed on the membrane transporting between organ cells and interstitial space
Kidney | Fraction expressed apical | Fraction expressed epithelial | Fraction of total protein expressed in the epithelial cells actively excreting compounds into urine
Liver |  Fraction expressed apical | Fraction expressed epithelial | Fraction expressed epithelial | Fraction of total protein expressed in the epithelial cells actively excreting compounds into bile
Brain | Fraction expressed at blood brain barrier | Fraction expressed at blood brain barrier | Fraction of total protein expressed at the blood-brain-barrier, transporting between blood plasma and brain interstitial
Brain | Fraction expressed brain tissue | Fraction expressed brain tissue | Fraction of total protein expressed in the cellular membrane, transporting between brain interstitial and intracellular spaces
Intestinal mucosa | Fraction expressed basolateral | Fraction expressed basolateral | Fraction of total protein expressed on the membrane transporting between organ cells and interstitial space
Intestinal mucosa | Fraction expressed apical | Fraction expressed apical | Fraction of total protein expressed on the membrane transporting between intestinal lumen and mucosal space


@Yuri05 @StephanSchaller please review, esp. regarding the proposed descriptions for liver and kidney.

**Comment by msevestre** [comment]
It is not possible to have different descriptions based on WHERE the parameter is located for the same parameter

**Comment by msevestre** [comment]
so we only have 4 parameters independent from the location. if we need specific localized parameter (such as in brain) we need to add them extra. Much more work

**Comment by msevestre** [comment]
damn parameter rename AGAIN!
