### ISSUE TITLE
when moving observed data to compare it with the predicted data 

### ISSUE THREAD

**Issue by amaghrabi** [Open-Systems-Pharmacology/PK-Sim#1675]
hi everyone,

when i want to move the observed data to compare it with the predicted data, it is coming a message said "the observed data cannot be added to the analysis"
its dimentions (dimentionless)  is not in the list of possible dimentions: concentration
![pk sim dimentions](https://user-images.githubusercontent.com/80226127/111435852-5c24aa80-8712-11eb-89da-85db26d37571.JPG)

as you can see below in snapshot 

thanks in advance

**Comment by msevestre** [comment]
I would suggest to ask your question in the forum 
https://github.com/Open-Systems-Pharmacology/Forum/discussions
This is only for bug reports
