### ISSUE TITLE
The predefined templates for age groups are not supported anymore

### ISSUE THREAD

**Issue by maalbrec89** [Open-Systems-Pharmacology/PK-Sim#1679]
PK-Sim version 9.1
![Scale Across Age Groups-0037 ](https://user-images.githubusercontent.com/52818721/111635419-bfd4d380-87f7-11eb-98a4-3cf03a290636.png)
![Scale Across Age Groups-0038 ](https://user-images.githubusercontent.com/52818721/111635425-c1060080-87f7-11eb-80d5-3d9d5b6fb130.png)

**Comment by msevestre** [comment]
GOOD FIND!!
