### ISSUE TITLE
Name for BiDirectional Transport

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1681]
Time to name this feature properly before we start using it. We need name, descriptions etc..

**Comment by msevestre** [comment]
# PROCESS_NAME (visible in MoBi)

| container\_name | display\_name | description |
| :--- | :--- | :--- |
| ActiveBiDirectionalSpecificPlasmaInterstitial | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificPlasmaInterstitial\_MM | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificPlasmaBloodCells | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificPlasmaBloodCells\_MM | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificInterstitialIntracellular | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificInterstitialIntracellular\_MM | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificLumenMucosaIntracellular | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificLumenMucosaIntracellular\_MM | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificBrainInterstitialIntracellular | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificBrainInterstitialIntracellular\_MM | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificBrainPlasmaInterstitial | Specific bi-directional transport - Michaelis-Menten | TODO |
| ActiveBiDirectionalSpecificBrainPlasmaInterstitial\_MM | Specific bi-directional transport - Michaelis-Menten | TODO |


# TRANSPORT_DIRECTION (visible in PKSim)

| transport\_direction | display\_name | description |
| :--- | :--- | :--- |
| BiDirectionalPlasmaInterstitial | BiDirectionalPlasmaInterstitial | TODO BiDirectionalPlasmaInterstitial |
| BiDirectionalPlasmaBloodCells | BiDirectionalPlasmaBloodCells | TODO BiDirectionalPlasmaBloodCells |
| BiDirectionalInterstitialIntracellular | BiDirectionalInterstitialIntracellular | TODO BiDirectionalInterstitialIntracellular |
| BiDirectionalLumenMucosaIntracellular | BiDirectionalLumenMucosaIntracellular | TODO BiDirectionalLumenMucosaIntracellular |
| BiDirectionalBrainInterstitialTissue | BiDirectionalBrainInterstitialTissue | TODO BiDirectionalBrainInterstitialTissue |
| BiDirectionalBrainPlasmaInterstitial | BiDirectionalBrainPlasmaInterstitial | TODO BiDirectionalBrainPlasmaInterstitial |

![image](https://user-images.githubusercontent.com/1041237/111835812-d0ef1480-88cb-11eb-96a7-2ca4d3431689.png)

**Comment by StephanSchaller** [comment]
Bi-directional transport between interstitial and intracellular across cell membrane?

**Comment by PavelBal** [comment]
@msevestre Can you paste the corresponding descriptions for the e.g. Influx Michaelis-Menten?

**Comment by msevestre** [comment]
| container\_name | display\_name | description |
| :--- | :--- | :--- |
| ActiveEffluxSpecificIntracellularToInterstitial | Specific active efflux - Michaelis-Menten | The transmembrane efflux transporter actively transports the compound from the intracellular to the interstitial compartment. |
| ActiveEffluxSpecificIntracellularToInterstitial\_Hill | Specific active efflux - Hill | The transmembrane efflux transporter actively transports the compound from the intracellular to the interstitial compartment. |
| ActiveEffluxSpecificIntracellularToInterstitial\_MM | Specific active efflux - Michaelis-Menten | The transmembrane efflux transporter actively transports the compound from the intracellular to the interstitial compartment. |
| ActiveInfluxSpecificInterstitialToIntracellular | Specific active influx - Michaelis-Menten | The transmembrane influx transporter actively transports the compound from the interstitial to the intracellular compartment. |
| ActiveInfluxSpecificInterstitialToIntracellular\_Hill | Specific active influx - Hill | The transmembrane influx transporter actively transports the compound from the interstitial to the intracellular compartment. |
| ActiveInfluxSpecificInterstitialToIntracellular\_MM | Specific active influx - Michaelis-Menten | The transmembrane influx transporter actively transports the compound from the interstitial to the intracellular compartment. |
| ActiveTransport\_InVitro\_VesicularAssay\_MM | In vitro active transport \(vesicular assay\) - Michaelis-Menten | A transporter mediated unidirectional transfer of a compound across a cellular membrane is described as saturable process following Michaelis-Menten type kinetics. The corresponding kcat value is calculated from a specific Vmax normalized to the amount of transporter as input value which was determined in a vesicular transport assay. |
| ActiveTransportIntrinsic\_MM | Intrinsic active transport - Michaelis-Menten | A transporter mediated unidirectional transfer of a compound across a cellular membrane is described as saturable process following Michaelis-Menten type  kinetics. Specific Vmax is calculated from intrinsic liver Vmax normalized to the organ weight as input value. |
| ActiveTransportSpecific\_Hill | Specific active transport - Hill | A transporter mediated unidirectional transfer of a compound across a cellular membrane is described as saturable process displaying a cooperativity which is characterized by the Hill equation. The corresponding kcat value is calculated from a specific Vmax as input value. |
| ActiveTransportSpecific\_MM | Specific active transport - Michaelis-Menten | A transporter mediated unidirectional transfer of a compound across a cellular membrane is described as saturable process following Michaelis-Menten type kinetics. The corresponding kcat value is calculated from a specific Vmax as input value. |

**Comment by msevestre** [comment]
Also the Note should be updated

@Yuri05 @PavelBal @StephanSchaller 
![image](https://user-images.githubusercontent.com/1041237/112024176-4e07cd00-8b0a-11eb-963f-c577b8b9ad8c.png)

`
Always verify localization of the defined transporter in tissues displaying apico-basal polarity (liver, kidney, intestine, brain). Apical (or basolateral) localization is tissue dependent and may not be consistent in all polarized cell types.
`

**Comment by PavelBal** [comment]
@msevestre Why are there entries like
`ActiveBiDirectionalSpecificPlasmaInterstitial`
and 
`ActiveBiDirectionalSpecificPlasmaInterstitial_MM`
? What is the difference?

**Comment by msevestre** [comment]
Good question. One would be the generic definition and the other one specific to the kinetic. In our case, they can be set to the same value for now

**Comment by PavelBal** [comment]
For MoBi - why do we need `ActiveBiDirectionalSpecificBrainInterstitialIntracellular` and `ActiveBiDirectionalSpecificBrainPlasmaInterstitial`? The kinetics are exactly the same as for all other organs. Actually, the same is true for the infux/efflux processes.

**Comment by PavelBal** [comment]
- Remove process "BrainActiveEffluxToPlasma_MM"
- Remove condition "not tagged with Brain" from "ActiveEffluxSpecificInterstitialToPlasma_MM"

**Comment by PavelBal** [comment]
1) Error message when combining bi-directional with e.g. Hill kinetics: Can it be extended by adding "Only Michaelis-Menten is supported"?
![image](https://user-images.githubusercontent.com/25903040/113281658-2a9d0900-92e6-11eb-8c6a-0187aff1afb1.png)

2) Adjust descriptions of transport processes: 
![image](https://user-images.githubusercontent.com/25903040/113282182-e1998480-92e6-11eb-983b-152afc30f4ce.png)

In all "Michaelis-Menten", remove the word "unidirectional".
In "Hill", add
> WARNING! Cannot be used when transporter direction is "Bi-directional".

3) Process namings:

# PROCESS_NAME (visible in MoBi)

| container\_name | display\_name | description |
| :--- | :--- | :--- |
| ActiveBiDirectionalSpecificPlasmaInterstitial | Specific bi-directional transport - Michaelis-Menten | The transporter protein facilitates transfer of compound molecules between bloood plasma and interstitial space along the substrates concentration gradient |
| ActiveBiDirectionalSpecificPlasmaBloodCells | Specific bi-directional transport - Michaelis-Menten | The transporter protein facilitates transfer of compound molecules between bloood plasma and blood cells along the substrates concentration gradient |
| ActiveBiDirectionalSpecificInterstitialIntracellular | Specific bi-directional transport - Michaelis-Menten | The transporter protein facilitates transfer of compound molecules between interstitial and intracellular spaces along the substrates concentration gradient |
| ActiveBiDirectionalSpecificLumenMucosaIntracellular | Specific bi-directional transport - Michaelis-Menten | The transporter protein facilitates transfer of compound molecules between intestinal lumen and mucosal cells along the substrates concentration gradient |

# TRANSPORT_DIRECTION (visible in PKSim)

| transport\_direction | display\_name | description |
| :--- | :--- | :--- |
| BiDirectionalPlasmaInterstitial | Bi-directional transport between blood plasma and interstitial space  |  The transporter protein facilitates transfer of compound molecules between bloood plasma and interstitial space along the substrates concentration gradient |
| BiDirectionalPlasmaBloodCells | Bi-directional transport between blood plasma and blood cells| The transporter protein facilitates transfer of compound molecules between bloood plasma and blood cells along the substrates concentration gradient |
| BiDirectionalInterstitialIntracellular | Bi-directional transport between interstitial and intracellular space | The transporter protein facilitates transfer of compound molecules between interstitial and intracellular spaces along the substrates concentration gradient |
| BiDirectionalLumenMucosaIntracellular | Bi-directional transport between intestinal lumen and mucosal cells | The transporter protein facilitates transfer of compound molecules between intestinal lumen and mucosal cells along the substrates concentration gradient |
| BiDirectionalBrainInterstitialTissue | Bi-directional transport between interstitial and intracellular space | The transporter protein facilitates transfer of compound molecules between interstitial and intracellular spaces along the substrates concentration gradient |
| BiDirectionalBrainPlasmaInterstitial | Bi-directional transport across the blood-brain-barrier | The transporter protein facilitates transfer of compound molecules across the blood-brain-barrier along the substrates concentration gradient |


4) 
> Also the Note should be updated

I thing this particular note is outdated and should not be shown at all.

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/113446301-85596200-93c5-11eb-9f3e-a642c132a06f.png)

Seems like the style is a bit off no?

**Comment by msevestre** [comment]
even the display name is a bit longue I think
![image](https://user-images.githubusercontent.com/1041237/113446351-a752e480-93c5-11eb-809d-cd922463080c.png)

**Comment by PavelBal** [comment]
@msevestre Yes I agree with you, did not have time to propose a new solution.

**Comment by msevestre** [comment]
This is not done yet

**Comment by PavelBal** [comment]
@msevestre I am confused here... I have drafted the `Description` in the same style as here https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1681#issuecomment-804128289

But it is not used in the `Transport direction` field? (https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1681#issuecomment-812671171)

**Comment by msevestre** [comment]
No the transport direction is not the Transporter. The same direction can have different transporter. The transport direction is what is shown in the user interface in the individual so to speak

**Comment by PavelBal** [comment]
# TRANSPORT_DIRECTION (visible in PKSim)

transport_direction | display_name | description
-- | -- | --
BiDirectionalPlasmaInterstitial | Bi-directional transport between blood plasma and interstitial space | Bi-directional plasma <-> interstitial
BiDirectionalPlasmaBloodCells | Bi-directional transport between blood plasma and blood cells | Bi-directional plasma <-> blood cells
BiDirectionalInterstitialIntracellular | Bi-directional transport between interstitial and intracellular space | Bi-directional interstitial <-> intracellular
BiDirectionalLumenMucosaIntracellular | Bi-directional transport between intestinal lumen and mucosal cells | Bi-directional lumen <-> mucosa
BiDirectionalBrainInterstitialTissue | Bi-directional transport between interstitial and intracellular space | Bi-directional interstitial <-> intracellular
BiDirectionalBrainPlasmaInterstitial | Bi-directional transport across the blood-brain-barrier | Bi-directional plasma <-> interstitial

**Comment by PavelBal** [comment]
@msevestre updated
