### ISSUE TITLE
Parameter Identification Parameters tab: option to keep parameter fixed

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#169]
It would be very useful (as in the old PI toolbox) to have a tick box to keep parameter value fixed at its start value. 

Comment 1: what about not optimizing the parameter?
Comment 2: yes, but you may have a more complex configuration with multiple simulations. You might want to put everything together and then test different settings (including and excluding some parameters from PI).
Comment 3: Another application of this feature is the ability to change parameters for the PI run. Select parameter, change its value, and select "fixed".
Comment 4: Especially as long as its not clear which parameters are correlated and how many parameters you can actually estimate based on the measurements. An additional checkbox, next to "use as factor", such as "is fixed" would be sufficient. Any fixed parameter should not be exposed to the optimization algorithm.

**Comment by msevestre** [comment]
@Yuri05, @sfrechen, @ hdiedam 

What about the jacobian matrix ? Should we remove fixed parameters as well from the jacobian calculation since they are set to a specific value?

**Comment by sfrechen** [comment]
Yes! Theese parameters can be removed from the jacobian matrix.
