### ISSUE TITLE
How model an exposure decrease with time administration in animals ?

### ISSUE THREAD

**Issue by Nathalie06** [Open-Systems-Pharmacology/PK-Sim#1693]
I am building PBPK models in rat, rabbit and dog for a same compound. In some species (rat and rabbit) after repeated administration, AUC decreases between the 1st and the 10th administration. In human I have information concerning possible CYP induction but I have no CYP information in animals (I only have clearance in S9 and clearance in hepatocytes). 
I don't know how I can handle this within PKsim ? adding for example a ratio between clearance on day 1 and on day 10 ?

Thanks in advance,
Best,
Nathalie

**Comment by msevestre** [comment]
@Nathalie06 Sorry we missed your question. Please ask your question in our Forum so that other user can help
https://github.com/Open-Systems-Pharmacology/Forum/discussions
