### ISSUE TITLE
Export units for population parameters

### ISSUE THREAD

**Issue by TheiBa** [Open-Systems-Pharmacology/PK-Sim#170]
When exporting a population, it would be helpful to also export units. I guess everything is based on PK-Sim standard units, so in principle ok, but sometimes inconvenient and confusing. For example, for some composite parameters, values/units might not correspond to expectation and to what is displayed within PK-Sim, e.g. a BMI values of 0.25 not 25. I suggest putting units in brackets behind the parameter name or adding an additional line.

**Comment by rwmcintosh** [comment]
@Yuri05 Is there anywhere else that we need to adjust if the header row changes from just having the path to having the path and the unit? Matlab maybe?

**Comment by Yuri05** [comment]
Matlab (Population Runner) has to be adjusted.

**Comment by msevestre** [comment]
This break population simulation run with aging data.
Unit should only be added when exported to file

**Comment by msevestre** [comment]
Method `CreatePopulationDataFor` is public and is not only used for export to file

**Comment by msevestre** [comment]
`When_creating_an_aging_population_simulation_with_the_standard_building_block_and_iv_bolus` this is the test failing in PK-Sim

**Comment by msevestre** [comment]
We can make sure that we do not export unit when exporting for cluster. That might be the best of both worlds. What do you think @Yuri05

**Comment by TheiBa** [comment]
yep, better - thanks. units exported and the few I checked also seem reasonable. as this will be done automatically, I assume that I do not need to validate all exported units.
