### ISSUE TITLE
PKSIm.CLI: It feels like the log file is not created as expected

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1700]
/cc @georgeDaskalakis @abdelr 
As discussed this morning. We should check it out

I'll try to add steps to reproduce

**Comment by msevestre** [comment]
@abdelr and @georgeDaskalakis 
Can you let me know what needs to be done to ensure that the log file is created as expected?
Or maybe review the code to see if something obvious is missing?

**Comment by abdelr** [comment]
@msevestre Could it be that we are not passing LogFileFullPath to the command? if you look into PKSim.CLI.Program.initializeLogger(CLICommand runCommand) you will see that the FileLogger is only added if runCommand has a non empty/null LogFileFullPath. There is a clear reason here for the logger to only log to console if this run param is not provided. Could you check if this is the source of the problem?

**Comment by msevestre** [comment]
@abdelr I'll check but I don't think so. This was working before and the caller did not change the call I believe

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/QualificationRunner/blob/develop/src/QualificationRunner.Core/Services/QualificationEngine.cs#L109

It's here. PArameter is -l and is always available

**Comment by msevestre** [comment]
This may be fixed. I had log files yesterday. Closing for now
