### ISSUE TITLE
TODO in constant

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1703]
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/ffe5a780ce39c65aca87e660d992ef43421369b7/src/PKSim.Assets/PKSimConstants.cs#L2173
what is this const for?

**Comment by msevestre** [comment]
We do not support this stuff and it is not used anywhere .

**Comment by Yuri05** [comment]
ok, let's remove then
