### ISSUE TITLE
Add observed data from configuration: wrong behaviour

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1706]
When I select "add observed data from configuration" and select previously saved configuration file - I would expect that I'm asked for the data file in the next step and then the configuration is applied to this data file and the importer dialog opens.

Instead: the **data file which was used during the saving of the configuration** is imported automatically without any prompts.

Actually I think the "load configuration" button in the importer dialog would be the better option

In any case: the saved configuration should not contain the originally used data files and should be applicable to any (further) data sources.

**Comment by abdelr** [comment]
@Yuri05 This was already addressed in core but the reference in PKSim has not been jet updated.

**Comment by Yuri05** [comment]
obsolete
