### ISSUE TITLE
Apply stored configuration to different file

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/PK-Sim#1709]
After loading a file in the importer, it should be possible to apply a configuration that has been saved before. This means that:

1. All information except sheets and source file will be applied to the existing data coming from the current file. 
    - Information to use:
        - Mappings
        - Filters
        - Naming pattern
        - NaN-settings (indicator, row settings)
    - If some mapping columns are missing in the current file, the user should be informed but the process should continue.
2. Sheet information from the configuration should be ignored. 
3. If it ends up in an inconsistent state, the view should show the errors but the process should continue.
    - As inconsistent state, consider for example that the time column is missing, or that the units of measurement and error have different dimensions. In this case the view should clearly show the error but allow the user to fix such an error.
4. The user should be warned that the existing mappings will be dropped and prompt if he/she would like to continue anyway.

**Comment by StephanSchaller** [comment]
> an inconsistent state

What could be an "inconsistent state" (just an example to make sure we know what is meant)

**Comment by abdelr** [comment]
> > > an inconsistent state
> > 
> > What could be an "inconsistent state" (just an example to make sure we know what is meant)

> As inconsistent state, consider for example that the time column is missing, or that the units of measurement and error have different dimensions. In this case the view should clearly show the error but allow the user to fix such an error.

I have just added this text, please let me know if this is clear enough.

**Comment by Yuri05** [comment]
>All mappings will be applied to the existing data coming from the current file. 

Also:
 - filters
 - naming pattern
 - NaN-settings (indicator, row settings)

**Comment by abdelr** [comment]
> > All mappings will be applied to the existing data coming from the current file.
> 
> Also:
> 
> * filters
> * naming pattern
> * NaN-settings (indicator, row settings)

I added the missing specifications. Thanks!
