### ISSUE TITLE
Data import: "Undefined"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1715]
Remove the "Undefined" option from Species, organ, compartment, Gender.
In PK-Sim 9 it was required because the meta data was mandatory and could not be left empty, which is not the case anymore
![grafik](https://user-images.githubusercontent.com/25061876/116137098-6b185880-a6d3-11eb-91f4-7b89c098eb0e.png)![grafik](https://user-images.githubusercontent.com/25061876/116137451-dcf0a200-a6d3-11eb-9179-005a5d0ec0ea.png)![grafik](https://user-images.githubusercontent.com/25061876/116137532-f72a8000-a6d3-11eb-81f2-11c5303f8ba8.png)![grafik](https://user-images.githubusercontent.com/25061876/116137820-54becc80-a6d4-11eb-9a1b-67e2ab4c5ad4.png)

**Comment by StephanSchaller** [comment]
Bug or Feature? ;-)

**Comment by Yuri05** [comment]
>Bug or Feature? 

Well, I don't see a reason why we should have "Undefined" if we can just reset all of those to "None" and import as empty.

**Comment by StephanSchaller** [comment]
It was a joke :-)
I agree.

I think we should we also display the icons for species, organ and compartment, right?

**Comment by abdelr** [comment]
Yes, one of the issues that Georgios created recently was precisely to add the icons
