### ISSUE TITLE
Data import: missing "Peripheal Venous Blood" in the organs list

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1716]
![grafik](https://user-images.githubusercontent.com/25061876/116138103-b0895580-a6d4-11eb-8c35-6002c023a625.png)

**Comment by abdelr** [comment]
Currently the list of organs is populated from this list:
organism.OrgansByType(OrganType.VascularSystem | OrganType.Tissue | OrganType.Lumen)
This was copied from the old importer. I guess Peripheral Venous Blood is on another organ type. Missing types on this list are: GiTractOrgans, TissueOrgansNotInGiTract, Unknown but tissue is GiTractOrgans | TissueOrgansNotInGiTract meaning the only missing type is Unknown. Was there any reason why to leave Unknown out of the list? Maybe I looked into the wrong code and it actually needs Unknown to be added? Or maybe it was not but it should be. In any case, Unknown adds EndogenousIgG, Gallbladder, Organ, PeripheralVenousBlood and Saliva. I am adding Unknown type to the list but please @Yuri05 if there is any reason to leave it out please let me know.

**Comment by msevestre** [comment]
This is inacurate. Please use the same code for populating the lists as we had before
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/master/src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs#L272
