### ISSUE TITLE
Data Import: Reload does not ask for file

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1718]
"Reload All under same settings" does not ask for a new file name but imports from previously used file automatically
![grafik](https://user-images.githubusercontent.com/25061876/116263625-cef55c80-a779-11eb-89dc-7da93d8c09dc.png)

**Comment by msevestre** [comment]
@Yuri05 Isn't it how it should work? Reload all not import another file from..

**Comment by Yuri05** [comment]
>Isn't it how it should work?

No. It should be possible to update from **another** file using the originally used configuration. Otherwise we would always need to **overwrite** the original file with the new version every time we get a new data file.

**Comment by abdelr** [comment]
I am not sure I understand this use case. Maybe we should discuss it tomorrow if it is OK for you.

**Comment by Yuri05** [comment]
The use case is: update previously imported data from a new data source.
Example:
1) I import [Day1.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6386609/Day1.xlsx)
<img width="300" src="https://user-images.githubusercontent.com/25061876/116289795-163c1700-a793-11eb-850d-9710ecad611a.png">    ➡️     <img width="300" src="https://user-images.githubusercontent.com/25061876/116289891-2fdd5e80-a793-11eb-91e5-5d7c979c4045.png">

2) I get the *updated* dataset [Day1_Day2.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6386631/Day1_Day2.xlsx)

3) I select "Reload.. with the same settings" (by the way I would rename "reload" to "update"
![grafik](https://user-images.githubusercontent.com/25061876/116290327-a2e6d500-a793-11eb-8d93-da8fd4701195.png)

4) **This step is currently missing** File selection dialog opens and I select the *new data source Day1_Day2.xlsx*

5) The (previously saved) configuration is applied to the new data source and I get the overview of changes
![grafik](https://user-images.githubusercontent.com/25061876/116290941-4fc15200-a794-11eb-95b6-6e9aa93fa99c.png)

6) If I click OK: previously imported observed data sets (datasource=day1.xlsx) are updated(!) with the data from the new data source (day1_day2.xlsx)

**Comment by Yuri05** [comment]
P.S. At the moment the only way for me to do this is: before Update I **overwrite** _day1.xlsx_ with the content of _day1_day2.xlsx_
Then I can update and get the expected result. Why should I overwrite the initial file every time I want to update?

**Comment by abdelr** [comment]
I understand. I think the change makes sense and it will be really easy to add so we should be able to change it.

**Comment by StephanSchaller** [comment]
Yes, I agree it makes sense this way, but I also initially understood it as an update from the corrected same datafile which was used for the original import.
But with versioning of files for quality control reasons even this use-case is likely with two different files.

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #987](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/987) via [**ZenHub**](https://www.zenhub.com/)
