### ISSUE TITLE
Error importing LLOQ values

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1719]
[030_TCUnitLLOQ.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6385579/030_TCUnitLLOQ.xlsx)
Imported LLOQ values are 100 greater than expected (0.5 instead of 0.005)
![grafik](https://user-images.githubusercontent.com/25061876/116264959-fef12f80-a77a-11eb-8363-abb429d52a7d.png)
![grafik](https://user-images.githubusercontent.com/25061876/116265580-86d73980-a77b-11eb-83d8-66d82a6fbb5e.png)

**Comment by georgeDaskalakis** [comment]
The reason for this error is that the values are read from the excel file as numbers whereas the LLOQ as a string. You will notice in your screenshots that 0.1 is with dot whereas the LLOQ <0,01 with comma. Interestingly, in the Core starter I do not get the issue with the specific file, but on PK-Sim I do. 

We can guarantee that we parse the numeric values with the same culture they are read from the excel with, but for the LLOQ that we are reading as a string we cannot do this. I could change the culture this is parsed, but I could break another file that way.

**Comment by Yuri05** [comment]
> I could change the culture this is parsed, but I could break another file that way.

I would not do this. Instead, I would make 2 replacements before converting the string into numeric:
1. replace **point** with the current decimal separator 
2. replace **comma** with the current decimal separator 

Theoretically it still could be situations where this does not work (e.g. if you have "." as 1000-separator like "<2.000.000,1") - but as LLOQ are usually small number this will virtually never happen, so in the 99,99% of all cases the conversion above would work.

**Comment by georgeDaskalakis** [comment]
Implemented according to Juri's suggestion.

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1009](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1009) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Yuri05** [comment]
@georgeDaskalakis In the last PK-Sim nightly (10.0.135) the error is still there (OSPSuite.Core not updated in PK-Sim?)

**Comment by georgeDaskalakis** [comment]
@Yuri05 correct. The last update on the core packages was on May 6th, so there should be quite a few issues that are solved on Core but not updated on PK-Sim. I will create a pull request for this.
