### ISSUE TITLE
Data import: Typo

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1720]
![grafik](https://user-images.githubusercontent.com/25061876/116276325-b0489300-a784-11eb-9e65-1684059ed07b.png)

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #977](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/977) via [**ZenHub**](https://www.zenhub.com/)
