### ISSUE TITLE
How to add lag time to absorption phase of an oral molecule?

### ISSUE THREAD

**Issue by yvkashyap** [Open-Systems-Pharmacology/PK-Sim#1721]
Hello Everyone,

I am working on an oral molecule that is known to be absorbed by the lymphatic system in the GI tract. Because of that, there is a difference of about 1 to 2 hours in Cmax between observed and simulated data. (Simulated Cmax being faster than observed Cmax). Can we somehow add lag time to the absorption process of the compound in the simulation so that the time taken for lymphatic uptake is accounted for? Any help is highly appreciated.

Sincerely,
Kash

**Comment by StephanSchaller** [comment]
Hi Kash, are you using the "large molecule" model structure which has lymph flow?

But on another note: the delay in cmax may not only be due to lymphatic transport delay but also originating from the compounds dissolution/release properties and a general very low intestinal permeability?

**Comment by yvkashyap** [comment]
Hi Stephan,

Sorry for the late reply. Thanks for your suggestions. I modified the dissolution rate based on available data for my drug product using the "Table" option in the formulation and was able to reduce the delay in Cmax.

Sincerely,
Kash
