### ISSUE TITLE
Internal check whether user has changed relExp values

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1722]
In version 10, a (preliminary) warning pops up when expression in all localizations of a given group (Tissue=Int/Cell, BC=BC/Membrane, VascEndo=PLS/INT/ENDO) is deactivated:
![image](https://user-images.githubusercontent.com/26541603/116374090-44ab0800-a80e-11eb-9f1d-3bc6a2ce97f5.png)

I would suggest to implement a check whether the user really has changed expression values in these groups so that the warning is only shown when user-defined values are reset. Otherwise, this warning will also pop up if e.g. expression in blood cells is activated and then again deactivated

**Comment by Incei** [comment]
Also I assume the 'TODO'  text will be updated after release :)

**Comment by msevestre** [comment]
BEFORE RELEASE:)
And it is done already in the current EAP
