### ISSUE TITLE
Expression Parameters: Amend equations for InitialConcentrations in case of f_{vas;int;cell} = 0

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1727]
Not sure if this will be very relevant, but I suggest amending the equations for InitialConcentrations in v10 as follows (amendments displayed in ___bold-italic___):

InitialConcentrationInterstitial = V_org  ___* f_int___ > 0 ? RC * (rel_exp_org * f_exp_org_int * 1/ f_int + rel_exp_vasend * f_exp_vasend_tissue * V_vasend / (f_int * V_org)) : 0

InitialConcentrationIntracellular = ___f_cell > 0 ?___ RC * rel_exp_org * f_exp_org_cell * 1 / f_cell ___: 0___

InitialConcentrationPlasma = V_org ___* f_vas___ > 0 ? RC * (rel_exp_pls + rel_exp_bc * f_exp_bc_membrane * HCT / (1 - HCT) + rel_exp_vasend * f_exp_vasend_plasma * V_vasend / (f_vas * (1 - HCT) * V_org)) : 0

The modified if-statements might only cover very special cases (as e.g. the compartment for the amniotic fluid in the pregnancy model where f_cell = 0), but it's probably not too much work to change that?

**Comment by msevestre** [comment]
Nope. Easy peasy

**Comment by msevestre** [comment]
In fact, your suggestions is what should have been implemented in the first place. **Never assume anything** should be my mantra:)

**Comment by Yuri05** [comment]
Same for transporter and for endosome I guess? Currently:

. | .
-- | --
InitialConcentrationBrainInterstitial_Transporter | RC *   rel_exp_brn * f_exp_brn_tissue *  1 /   f_int
InitialConcentrationBrainPlasma_Transporter | RC * rel_exp_brn *   f_exp_brn_bbb * 1 / (f_vas * (1 - HCT))
InitialConcentrationInterstitial_Transporter | RC * rel_exp_org *   f_exp_org_tissue * 1 / f_int
InitialConcentrationIntracellular_Transporter | RC * rel_exp_org *   f_exp_org_epithelial * 1 / f_cell
InitialConcentrationPlasma_Transporter | V_org > 0 ? RC *   rel_exp_vasend * V_vasend / (f_vas * (1 - HCT) * V_org) : 0
InitialConcentrationEndosome | RC * rel_exp_vasend *   f_exp_vasend_endosomes * 1 / f_endo

**Comment by msevestre** [comment]
yes. I'll update the condition on all of them to make sure we'll never have NaN
