### ISSUE TITLE
Snapshot converstion to v10 does not work with Apical/basolateral

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1739]

**Comment by msevestre** [comment]
@Yuri05 

Why do you expect everything to be apical since the snapshot `Human_MultipleIV_Efflux.json` only has

```
"Expression": [
            {
              "Name": "Brain",
              "MembraneLocation": "BloodBrainBarrier",
              "Value": 0.8
            },
            {
              "Name": "Periportal",
              "MembraneLocation": "Apical",
              "Value": 1.0
            },
            {
              "Name": "Pericentral",
              "MembraneLocation": "Apical",
              "Value": 1.0
            }
          ],
          "Parameters": [
```

**Comment by msevestre** [comment]
@Yuri05 I can't reproduce the problem. While the values are seemingly different, the relexp are zero and therefor it should not make any difference. For non zero values, where MembraneLocation was actually set, the values are set accordingly

![image](https://user-images.githubusercontent.com/1041237/116891919-40f7f680-abfd-11eb-8004-404d97a80dac.png)

So output differs but I don't think that this is the reason

**Comment by Yuri05** [comment]
You are right. I think the **default** values for apical/basolateral in kidney/liver/GI should be the same as in V9 (created an issue for that , https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1740) but the problem here is elsewhere...

**Comment by msevestre** [comment]
CLosing this one

the problem I believe is that all Interstial concentrations are different. That's why we have differences in many simulations. I am wondering if we really have an issue...I do not know where else to look. Closing this one for now
