### ISSUE TITLE
Transporter: default polarity (apical/basolateral) changed between v9 and v10

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1740]
In PK-Sim 9, when creating a new transport (without predefined directions in the database): default in **liver/kidney/GI** was **apical**.
In PK-Sim 10 it changed to **basolateral** (`f_exp_tissue=1` `f_exp_epithelial=0`).
I think we should set the default values in kidney/liver/GI `f_exp_tissue=0` `f_exp_epithelial=1`
<img width="280" src="https://user-images.githubusercontent.com/25061876/116994607-3743c100-acd9-11eb-9c17-f691e8a7559c.png">  <img width="500" src="https://user-images.githubusercontent.com/25061876/116994786-740fb800-acd9-11eb-9141-9d7d336efa5d.png">

**Comment by Yuri05** [comment]
it works now for Efflux and PgP transporters. However for **Influx**-Transporters we had as per default **apical** in the **mucosa**:
<img width="550" src="https://user-images.githubusercontent.com/25061876/131883446-12e34e25-30c9-4caf-9939-d5a5e6b11663.png">


In V10 however influx is per default basolateral everywhere. However fraction apical in the intestinal mucosa should be 1
<img width="550" src="https://user-images.githubusercontent.com/25061876/131883724-35cca37f-5bf5-4565-be85-d8d324e2f904.png">

**Comment by Yuri05** [comment]
#1840 seems also not to be fixed - maybe just a followup of this issue

**Comment by msevestre** [comment]
#1840 is fixed for me. Can you explain what is not working?

**Comment by PavelBal** [comment]
Hmm yes, influx should be apical.

**Comment by msevestre** [comment]
and Efflux should also be apical?

**Comment by msevestre** [comment]
Fixed with #1840
