### ISSUE TITLE
Transports: hints/warnings

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1741]
In v9 we had some additional information shown for the transporter (s. below)
![grafik](https://user-images.githubusercontent.com/25061876/116997037-8e976080-acdc-11eb-8f50-b6b5d0ecd90e.png)

In V10 it's not shown anymore. While we need more space in V10 and it's probably ok not to show it all the time: we could include this information as a **tooltip** of the _Direction_ panel (and change the caption of the panel to something like "Direction (s. the mouse over tooltip for additional info)
![grafik](https://user-images.githubusercontent.com/25061876/116997662-62301400-acdd-11eb-97fe-281c5f6efda0.png)

**Comment by msevestre** [comment]
@Yuri05 We removed the tooltip because it does not make sense anymore (at least the way it is written now). 
I never understood that warning anyways so I was not upset. Not sure what we should show instead

**Comment by msevestre** [comment]
Plus I believe it really is the job of the user to check this out anyways

**Comment by PavelBal** [comment]
Even more - if I add a transporter manually (not from DB), it is somehow surprising to see a hint about the transporter not being found in the DB.

**Comment by msevestre** [comment]
@Yuri05 Thoughts?

**Comment by msevestre** [comment]
all right..bye bye
