### ISSUE TITLE
RelExp V10: Error resolving path

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1757]
* Open the project [10.0.135_Fabs_DDI_MultipleCombinations_EffluxOnly.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6500609/10.0.135_Fabs_DDI_MultipleCombinations_EffluxOnly.pksim5.zip)
* Open the individual-BB and remove CYP3A4 
  <img width="300" src="https://user-images.githubusercontent.com/25061876/118637333-f6b66e00-b7d5-11eb-988a-cb85b1537c14.png">

* In the simulation: Update the individual from Building Block and click Next: the error message below comes
![grafik](https://user-images.githubusercontent.com/25061876/118637565-3b420980-b7d6-11eb-93f6-8b19cdab5bc3.png)

**Comment by Yuri05** [comment]
P.S. Before updating from the Individual-BB: the equation for **VenousBlood|Plasma|AADAC|Initial concentration** looks good, no "cross-references" to CYP3A4 or whatsoever
```
Parameter: 10.0.135_Rifampicin|Organism|VenousBlood|Plasma|AADAC|Initial concentration
	Value: 3.9102564103E-05 [µmol/l]
	Formula: (1 - HCT) > 0 ? RC * (rel_exp_pls + rel_exp_bc * f_exp_bc_membrane * HCT / (1 - HCT)) : 0
		f_exp_bc_membrane: 10.0.135_Rifampicin|AADAC|Fraction expressed in blood cells membrane(0)
		RC: 10.0.135_Rifampicin|AADAC|Reference concentration(1 [µmol/l])
		rel_exp_bc: 10.0.135_Rifampicin|AADAC|Relative expression in blood cells(3.9102564103E-05)
		rel_exp_pls: 10.0.135_Rifampicin|AADAC|Relative expression in plasma(3.9102564103E-05)
		HCT: 10.0.135_Rifampicin|Organism|Hematocrit(0.47)
```

**Comment by msevestre** [comment]
Looks like the issue that @Christoph27  had with a mix of path....very interesting

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/118673398-f8c50080-b7c6-11eb-8369-2476ff5001b1.png)

Ok this is the same as @Christoph27 

HOW CAN I REPRODUCE?? The Individual is corrupted

**Comment by Yuri05** [comment]
Ok, seems reproducable:
* Load the project from snapshot [Fabs_DDI_MultipleCombinations_EffluxOnly.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6502608/Fabs_DDI_MultipleCombinations_EffluxOnly.zip)
* Save the project and close it.
* Reopen the project: initial concentrations of AADAC point to CYP3A4

**Comment by msevestre** [comment]
cool

**Comment by msevestre** [comment]
I can reproduce with a snapshit with only one individual and two molecules.... very cool" )
