### ISSUE TITLE
Cannot clone/configure simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1763]
PK-Sim 10.0.137
Load the snapshot [07_MM_Competitive_Competitive_Mechanismbased_Mechanismbased.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6509630/07_MM_Competitive_Competitive_Mechanismbased_Mechanismbased.zip)
Try to clone the simulation.
![grafik](https://user-images.githubusercontent.com/25061876/118832842-3f972100-b8c1-11eb-80e6-ed2940bc7941.png)

Same error when trying to configure the simulation

**Comment by msevestre** [comment]
those molecule dependent path in inviduals are a killer!

**Comment by msevestre** [comment]
ok this is something else. Undefined liver crap

**Comment by msevestre** [comment]
ok got you, stupid bug
