### ISSUE TITLE
Refresh Problem when renaming BBs or Simulations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1768]
Happens both in V9 and V10.
When I rename a building block or a simulation and give it a long name: it's truncated in the BB-/Sim-Explorer
<img width="500" src="https://user-images.githubusercontent.com/25061876/119477188-093d2400-bd4f-11eb-8e10-f5063ecba85e.png"> <img width="300" src="https://user-images.githubusercontent.com/25061876/119477535-55886400-bd4f-11eb-80f9-22b3dfcf1595.png">

The long name is only displayed properly after I reopen the project or add another building block/simulation

![grafik](https://user-images.githubusercontent.com/25061876/119477880-a4ce9480-bd4f-11eb-9c6c-7ef2e43d08b6.png)

**Comment by Yuri05** [comment]
Add a dummy node and remove it immediately every time when a node is renamed?

**Comment by msevestre** [comment]
that works!
