### ISSUE TITLE
9.1 "Interaction factor" Fix not included in 10.0

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1769]
It seems that the fix of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1523 (which was done in PK-Sim 9.1.2) did not find its way into PK-Sim 10

E.g. import [9.1_07_29_Noncom_Noncom_Mbased_Mbased.json.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6540396/9.1_07_29_Noncom_Noncom_Mbased_Mbased.json.zip) in V9 and V10 and create simulation report.

V9.1 (9.1.2)
```
Parameter: Organism|VenousBlood|Plasma|C1-CYP3A4-Tracy 1999|CLspec/[Enzyme] interaction factor
	Formula: 1/(1 + K_water_cTD1*IcTD1/KcTDI1 + K_water_n1*In1/KnI1)
		IcTD1: Organism|VenousBlood|Plasma|Clarithromycin|Concentration(0 [µmol/l])
		K_water_cTD1: Organism|VenousBlood|Plasma|Clarithromycin|Partition coefficient (water/container)(0.299)
		KcTDI1: Clarithromycin|CYP3A4-fitted|Ki(6.04 [µmol/l])
		In1: Organism|VenousBlood|Plasma|Noncompetitive_CYP3A4_1|Concentration(0 [µmol/l])
		K_water_n1: Organism|VenousBlood|Plasma|Noncompetitive_CYP3A4_1|Partition coefficient (water/container)(0.017)
		KnI1: Noncompetitive_CYP3A4_1|CYP3A4-noncompet_1|Ki(0.1 [µmol/l])
```

V10
```
Parameter: Organism|VenousBlood|Plasma|C1-CYP3A4-Tracy 1999|CLspec/[Enzyme] interaction factor
	Formula: 1/(1 + K_water1*IcTD1/KcTDI1 + K_water1*In1/KnI1)
		IcTD1: Organism|VenousBlood|Plasma|Clarithromycin|Concentration(0 [µmol/l])
		K_water1: Organism|VenousBlood|Plasma|Clarithromycin|Partition coefficient (water/container)(0.299)
		KcTDI1: Clarithromycin|CYP3A4-fitted|Ki(6.04 [µmol/l])
		In1: Organism|VenousBlood|Plasma|Noncompetitive_CYP3A4_1|Concentration(0 [µmol/l])
		KnI1: Noncompetitive_CYP3A4_1|CYP3A4-noncompet_1|Ki(0.1 [µmol/l])
```

**Comment by Yuri05** [comment]
@msevestre FYI

**Comment by Yuri05** [comment]
@msevestre It seems that the hotfix 9.1 was merged into master with [this PR](https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1530) but not into develop... (found only [this PR](https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1534/commits) which was not merged then)

**Comment by msevestre** [comment]
would it explain some of the batch differenceS?

**Comment by Yuri05** [comment]
>would it explain some of the batch differenceS?

Yes :)

**Comment by msevestre** [comment]
hum... I am still seing differences. Maybe I am not comparing the right things.. but

**Comment by msevestre** [comment]
pdf attached after new run

**Comment by msevestre** [comment]
however it might just be the reason that we did not have curves before? not sure :)

**Comment by msevestre** [comment]
[Open Systems Pharmacology Suite - 9-Installation Validation_05_25_21_16_48_44.pdf](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6542295/Open.Systems.Pharmacology.Suite.-.9-Installation.Validation_05_25_21_16_48_44.pdf)

**Comment by Yuri05** [comment]
that's ok. all the differences are the Efflux transporter (which is called **P-gp** here), because now it is located in Interstitial and in the past it was located in Intracellular (except APICAL location in liver/kidney/GI). But there are no differences in the drug/metabolite concentrations - that's good :)

I just run Batch/Comparison for **DDI_MultipleCombinations_EffluxOnly.json** - the result is below.
[Open Systems Pharmacology Suite - 9-Installation Validation_05_26_21_11_54_02.pdf](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6545919/Open.Systems.Pharmacology.Suite.-.9-Installation.Validation_05_26_21_11_54_02.pdf)

<details><summary><b>Simulation output comparer output</b></summary>

```
Starting output comparisons...
Comparing files 'DDI_MultipleCombinations_EffluxOnly-01_MM_Competitive_Competitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-02_MM_Uncompetitive_Uncompetitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-03_MM_Noncompetitive_Noncompetitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-04_MM_Mixed_Mixed.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-05_MM_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-06_MM_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-07_MM_Competitive_Competitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-08_MM_Uncompetitive_Uncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-09_MM_Noncompetitive_Noncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-10_MM_Mixed_Mixed_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-11_MM_Mechanismbased_Mechanismbased_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-12_MM_All_DDI_Types.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-21_1st_Competitive_Competitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-23_1st_Noncompetitive_Noncompetitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-24_1st_Mixed_Mixed.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-25_1st_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-26_1st_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-27_1st_Competitive_Competitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-28_1st_Uncompetitive_Uncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-29_1st_Noncompetitive_Noncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-30_1st_Mixed_Mixed_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-31_1st_Mechanismbased_Mechanismbased_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-32_1st_All_DDI_Types.json'...Valid
```

![grafik](https://user-images.githubusercontent.com/25061876/119645407-491f0c80-be1e-11eb-9265-2a08f10f1b6a.png)
</details>

Almost all differences are now the transporter itself. With 2 things I'm still not happy:
a) There is only 1 Individual in this project, which has this Efflux-Transporter. Thus ALL simulations have the transporter, meaning that ALL of them should be marked as invalid. But only 6 out of 23 sims are reported as invalid. Seems to me like a bug in Simulation Comparer?? I created an issue for that: https://github.com/Open-Systems-Pharmacology/InstallationValidator/issues/218
b) In 1 case I still saw a difference in concentration. Not much and could be a numeric issue - but nevertherless I'm going to investigate
![grafik](https://user-images.githubusercontent.com/25061876/119648567-e596de00-be21-11eb-8f8d-9f419cff66fe.png)
![grafik](https://user-images.githubusercontent.com/25061876/119648613-f6475400-be21-11eb-9d82-da8957a84453.png)
![grafik](https://user-images.githubusercontent.com/25061876/119648648-ffd0bc00-be21-11eb-8557-7af2d5a3616a.png)
