### ISSUE TITLE
Observed data import redesign: Refresh Problem

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1782]
If observed data is plotted somewhere (simulation, PI): after updating the observed data via "Reload under the same settings": simulation/PI has to be closed and reopened in order to display the new observed data values.

**Comment by PavelBal** [comment]
Just a remark - it has been like this forever. If the user manually changes the data in MoBi (by opening the observed data and changing the values there), the plots in the simulations or PI are only updated when re-opening.
