### ISSUE TITLE
Observed data import Redesign: "Sheet" should not be mandatory metadata

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1783]
When importing from a CSV file: sheet is empty. When opening an imported observed data set for editing - sheet name is shown with the error red cross.
![grafik](https://user-images.githubusercontent.com/25061876/120184345-28392b80-c211-11eb-9b23-51b7436522fa.png)

**Comment by abdelr** [comment]
Should have been closed
