### ISSUE TITLE
Observed data import Redesign: add Subject ID as default mapping name

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1792]
Subject Id should be added as default mapping name here:

![image](https://user-images.githubusercontent.com/26541603/122216024-37c0a180-ceac-11eb-923d-c0c47fb62174.png)

**Comment by PavelBal** [comment]
- Add "Patient Id" as meta data.

**Comment by Yuri05** [comment]
>Add "Patient Id" as meta data.

**Subject Id** is a generalization of "Patient Id" and should replace it.

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1134](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1134) via [**ZenHub**](https://www.zenhub.com/)
