### ISSUE TITLE
Switch from efflux to influx transporter should set Fraction expressed epithelial to 0

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1798]
Currently, when adding a transporter in the individual building block, the default transport direction is `Efflux` with a `Fraction expressed epithelial` of 1 in cells with polarity (e.g. Kidney, Liver), meaning the transporter is expressed in the apical membrane between intracellular space and lumen. 
When changing the direction to `Influx`, the `Fraction expressed epithelial` remains at 1, meaning that the influx transporter is not expressed in the membrane between interstitial and intracellular space.
I would therefore suggest that the change in transport direction from `Efflux` to `Influx` automatically triggers a switch in the `Fraction expressed epithelial` from 1 to 0 so that the influx transporter is expressed in the (basolateral) membrane between interstitial and intracellular space.

@sfrechen, @TWendl: any comments?

**Comment by msevestre** [comment]
>I would therefore suggest that the change in transport direction from Efflux to Influx automatically triggers a switch in the Fraction expressed epithelial from 1 to 0 so that the influx transporter is expressed in the (basolateral) membrane between interstitial and intracellular space.

And what about change from Influx to Efflux? Should we set the value from 0 to 1?

What happens if the value was set by the user (for instance 0.5)? Do we leave the value as is?

**Comment by AndreDlm** [comment]
> And what about change from Influx to Efflux? Should we set the value from 0 to 1?

I would say yes

> What happens if the value was set by the user (for instance 0.5)? Do we leave the value as is?

I would leave it on the user-defined value

**Comment by msevestre** [comment]
awesome
