### ISSUE TITLE
Import of v9 Snapshot in v10 removes expression of influx transporters

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1799]
When importing a Snapshot created in v9.1 (e.g. this one [here)](https://raw.githubusercontent.com/Open-Systems-Pharmacology/Erythromycin-Model/v1.1/Erythromycin-Model.json) in v10, the influx transporter in the individual has a `Fraction expressed epithelial` of 1, but it  should be 0.

**Comment by msevestre** [comment]
@AndreDlm Can you tell me which Individual you are talking about? There are quite a few to consider... :)
![image](https://user-images.githubusercontent.com/1041237/122780777-277a3f00-d27d-11eb-981f-e07d59efd9b8.png)

**Comment by AndreDlm** [comment]
The influx transporter is OATP1B1 (LST-3TM12) and should be present in all individuals

**Comment by msevestre** [comment]
Ok. Can you describe what is wrong then? I see some values for some parameters set to 1 (instead maybe of the expected default 0 for fraction expressed epithelial.) but the relexp is 0 so this has no influence on the simulation whatsoever

**Comment by AndreDlm** [comment]
Well, the transporter was added as apical protein in v9, so I expected to see an expression in the interstitial-cell membrane of organs with polar cells (liver etc). But this doesn't seem to be the case?

**Comment by msevestre** [comment]
This is the snapshot values (snapshot does not container expression == 0)
```
 {
              "Name": "Brain",
              "MembraneLocation": "BloodBrainBarrier",
              "Value": 0.00014166666667,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            },
            {
              "Name": "Gonads",
              "MembraneLocation": "Basolateral",
              "Value": 0.0141666667,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            },
            {
              "Name": "Heart",
              "MembraneLocation": "Basolateral",
              "Value": 0.0008253968254,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            },
            {
              "Name": "Periportal",
              "MembraneLocation": "Basolateral",
              "Value": 1.0,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            },
            {
              "Name": "Pericentral",
              "MembraneLocation": "Basolateral",
              "Value": 1.0,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            },
            {
              "Name": "Lung",
              "MembraneLocation": "Basolateral",
              "Value": 4.0079365079E-05,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            },
            {
              "Name": "Muscle",
              "MembraneLocation": "Basolateral",
              "Value": 0.00064682539683,
              "ValueOrigin": {
                "Source": "Unknown"
              }
            }
```

as you see, only value for periportal and pericentral are not 0
For those entries, here is what the snapshot looks like in v10
![image](https://user-images.githubusercontent.com/1041237/122785003-f996f980-d280-11eb-86ba-3b1dbb6a1e9d.png)

Looks good to me?

**Comment by AndreDlm** [comment]
That looks indeed good. Let me see if I can reproduce the error I got previously, otherwise I'll close it

**Comment by msevestre** [comment]
@AndreDlm Any news on this?

**Comment by AndreDlm** [comment]
Cannot reproduce at the moment
