### ISSUE TITLE
Change names for Fraction expressed epithelial and Fraction expressed in tissue

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1800]
In v10 the names `Fraction expressed epithelial` and `Fraction expressed in tissue` could be changed to `Fraction expressed in apical membrane` and `Fraction expressed in basolateral membrane`, respectively, to have a terminology consistent with transporter directions/cellular polarity. 

@sfrechen, @TWendl: any suggestions?

**Comment by msevestre** [comment]
@PavelBal Can you explain why the rename was suggested in the first place? :)

**Comment by msevestre** [comment]
As FYI: If we want to rename this , this needs to be done NOW. Once v10 is out, it is too late

**Comment by PavelBal** [comment]
Because I always had to think about "what is apical and what is basolateral" in the respective tissue and somehow we agreed that "Epithelial/tissue" is more intuitive to understand.

If the majority of users see it the other way (prefer to have apical/basolateral), I will not object.

**Comment by AndreDlm** [comment]
@PavelBal ok I see. I find the apical/basolateral concept more intuitive, but that's probably just a personal preference to some degree

Could we have at least a description in the mouse-over field which term is apical and which is basolateral?

**Comment by msevestre** [comment]
Sure. Want to make a suggestion on what should be displayed in the tooltips?

**Comment by msevestre** [comment]
I just had a chat with Andrea. She believes also that she should be called Apical and Basolateral as this is what is in the literature when dealing with transporters
I don't care either way :)

**Comment by Yuri05** [comment]
Renaming the parameters now will require:
* Adjustments of equations (modify parameter aliases so that they match new parameter names)
* Repeat batch comparison tests
* Adjust documentation (https://github.com/Open-Systems-Pharmacology/docs/blob/ProteinExpressions/part-3/pk-sim-expression-data.md)

Just saying...

**Comment by JanSchlender** [comment]
Generally agree to Andre's proposal. However, since we do not have a membrane and a transporter is rather implemented as a floating protein within a compartment, it would technically make more sense to stick to the current naming

**Comment by sfrechen** [comment]
Strongly support "apical" vs "basolateral". That is also common microscopic anatomy terminology.
"Epithelial" vs "tissue" is not clear for me from an anatomic point of view... What should that be? The epithelium is not well defined - there are plenty of different epithelium tissues.

**Comment by PavelBal** [comment]
Change "Expressed in tissue" -> "Fraction expressed basolateral"
Change "Fraction expressed endothelial" -> "Fraction expressed apical"

**Comment by PavelBal** [comment]
`f_exp_org_tissue`-> `f_exp_org_basolatateral`
`f_exp_org_epithelial` -> `f_exp_org_apical`

**Comment by Christoph27** [comment]
I like Pavel’s suggestion. (But “Fraction expressed in brain tissue” should be kept …)
