### ISSUE TITLE
Project conversion V10: relExp

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1804]
Remaining Issues in PK-Sim 10.0.165:

[02_V9_Individual.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6700785/02_V9_Individual.zip)
1. `Fraction expressed in blood cells` must be 1 for enzymes/binding partners for the (V9) tissue localizations **Intracellular** and **Interstitial**
![grafik](https://user-images.githubusercontent.com/25061876/123075571-a0fa6480-d418-11eb-8997-9c9cfb5dd5ca.png)

2. `Fraction expressed in endosomes` must be 1 for enzymes/binding partners for the (V9) localization Intracellular/Endsomal
![grafik](https://user-images.githubusercontent.com/25061876/123077115-09961100-d41a-11eb-8dd4-497f467ae35a.png)

3. `Fraction expressed intracellular` must be 0 for enzymes/binding partners for the (V9) tissue localizations **Extracellular** and **Interstitial**
![grafik](https://user-images.githubusercontent.com/25061876/123080400-2a139a80-d41d-11eb-84b5-2212e5ac40e5.png)

4. `Fraction expressed on plasma-side membrane of vascular endothelium` must be 1 for the (V9) localization **Extracellular/Apical**
![grafik](https://user-images.githubusercontent.com/25061876/123081163-f6854000-d41d-11eb-87cd-ccd5c231faa1.png)

**Comment by Yuri05** [comment]
@PavelBal Can you double-check this?

**Comment by msevestre** [comment]
yeah..one line is missing

**Comment by msevestre** [comment]
@Yuri05 I am merging so that I can start with the rename
