### ISSUE TITLE
App crashes when importing file

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/PK-Sim#1808]
[Book1.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6714732/Book1.xlsx)

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1136](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1136) via [**ZenHub**](https://www.zenhub.com/)
