### ISSUE TITLE
History

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#181]
If I save project history in .xlsx format, the file is named .xlsx, but is saved in .xls format
it cannot be opened by excel directly (wrong format) but can be opened after renaming to .xls.

Affected version: 7.1

**Comment by msevestre** [comment]
Does saving as xlsx works in previous version?

**Comment by msevestre** [comment]
We changed the order of filtering (xlsx first as per request) but no implementation was changed. Wonder if it ever works

**Comment by Yuri05** [comment]
Works for other exports (simulation results, observed data)

**Comment by Yuri05** [comment]
History export to xlsx also didn't work in 6.3

**Comment by msevestre** [comment]
Issue is in ReportTask. This does not use the standard export stuff for some reason
