### ISSUE TITLE
Wrong parameter descriptions

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1810]
Parameter t1/2 (liver) and t1/2 (intestine) have the wrong description.
![grafik](https://user-images.githubusercontent.com/25061876/123462314-73651500-d5ea-11eb-9f84-9f31eb24fabb.png)
Must be changed to:
* **Half-life of the protein turnover in the liver** 
* **Half-life of the protein turnover in the intestine**

**Comment by msevestre** [comment]
I can do this now as I am working in the DB. Good timing
