### ISSUE TITLE
Some of the new icons in V10 are not set yet

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1812]
![grafik](https://user-images.githubusercontent.com/25061876/123464339-f7b89780-d5ec-11eb-93e5-313cf25c1228.png)  ![grafik](https://user-images.githubusercontent.com/25061876/123464458-1e76ce00-d5ed-11eb-8bf0-8c126b90eef8.png)

**Comment by Yuri05** [comment]
@AndreDlm FYI

**Comment by msevestre** [comment]
Well the icon is set at the container level.. If no icon was set previously, I don't think it will appear just by miracle...

**Comment by msevestre** [comment]
hum..howver it should at least for Endosome.. How can I reproduce?

**Comment by Yuri05** [comment]
>How can I reproduce?

For endosome: e.g. add an enzyme and activate "Show initial concentration"
<img width="500" src="https://user-images.githubusercontent.com/25061876/123505693-ddb89c80-d660-11eb-844a-3186bae60996.png">
Or just switch to Hierarchy view in Individual:
<img width="300" src="https://user-images.githubusercontent.com/25061876/123505724-02147900-d661-11eb-89da-f0275677ecfd.png">

Interestingly, in the Hierarchy view some organs which have icons in other views still don't have an icon, e.g.
<img width="300" src="https://user-images.githubusercontent.com/25061876/123505871-b31b1380-d661-11eb-88e6-244030429881.png">   :left_right_arrow:   <img width="400" src="https://user-images.githubusercontent.com/25061876/123505830-82d37500-d661-11eb-9462-f70ca3f3cf7c.png">

**Comment by msevestre** [comment]
I am a bit confused. How do i CREATE such a simulation in PKSim?

**Comment by msevestre** [comment]
nevermind...
![image](https://user-images.githubusercontent.com/1041237/123804475-3f744300-d8bb-11eb-9081-f8018bb87dfb.png)

**Comment by msevestre** [comment]
There is a bit of two issues. The icon needs to be set in the DB nad probably we can also ensure that we duplicate some of the icon by name. Let me see
