### ISSUE TITLE
population plots are missing the context menu

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#182]
7.1 All population plots are missing the context menu

**Comment by Yuri05** [comment]
[POP_Plots.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1022049/POP_Plots.zip)
Just an example

**Comment by msevestre** [comment]
What s in the context menu?

**Comment by Yuri05** [comment]
Reset Zoom, Edit, Copy as Image, export to Excel/PDF.
The whole menu is missing

**Comment by msevestre** [comment]
I feel with fixed something like that already. Does it ring a bell?

**Comment by Yuri05** [comment]
sthg like this (registration issue)? #96

**Comment by rwmcintosh** [comment]
There was a PISA context menu issue #73

**Comment by msevestre** [comment]
no something different. after devexpress update, I remember that you had to change the way some menu was displayed by default. We did it for the Chart component, but the pop is using something else

**Comment by rwmcintosh** [comment]
something was different with barmanager...

**Comment by msevestre** [comment]
```
  _barManager.SetPopupContextMenu(this, _popupMenu);
```
in UxChartControl

should be done in constructor propably
