### ISSUE TITLE
After import: observed data may not be modified anymore (except for the meta data)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1820]
It should not be possible to edit observed **data** in PK-Sim (**meta data** can be edited as before)
If data needs to be changed: the new "Update" functionality must be used instead.

![grafik](https://user-images.githubusercontent.com/25061876/123847766-403ac280-d917-11eb-911c-adf141843df2.png)

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1145](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1145) via [**ZenHub**](https://www.zenhub.com/)
