### ISSUE TITLE
Crash when calculating PK-parameters for molecules that are educts and products of each other.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1821]
If molecule A is metabolized to molecule B, and molecule B is metabolized to molecule A, simulating the model and selecting "Show PK Parameters" crashes PKSim.

SUch a model structure leads to an infinite loop in 

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/2ebf3f549551f58feb7fef0fbfeea8b5c5d133a9/src/OSPSuite.Core/Domain/ModelCoreSimulationExtensions.cs#L45

Minimal example attached.

[AdministrationLoop.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/6748464/AdministrationLoop.zip)

**Comment by msevestre** [comment]
Nice....

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1151](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1151) via [**ZenHub**](https://www.zenhub.com/)
