### ISSUE TITLE
Plots: Default BG color does not match

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1822]
tbf

**Comment by msevestre** [comment]
Probably a fix in core but potentially something to do in MoBi as well

**Comment by msevestre** [comment]
I actually cannot reproduce when I change the default color. So it has to be something related to the default chart color. Investigating

**Comment by msevestre** [comment]
yeah it's the default color that is not supported (Transparent). Changing in core to white

**Comment by Yuri05** [comment]
In the new plots: the BG color is still shown as "white", although the BG is grey
![grafik](https://user-images.githubusercontent.com/25061876/131837775-e1cc0bd6-e810-4912-b174-ddbe209682bc.png)

**Comment by msevestre** [comment]
Try on fresh install. Pretty sure the project conversion of settings didn't work for you

**Comment by msevestre** [comment]
@Yuri05 Can you confirm this is not the case upon fresh install?

**Comment by msevestre** [comment]
or by removing your v10 settings
