### ISSUE TITLE
PK-Sim 10: Snapshot export/import switches sides of expression for influx transporters

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#1840]
Probably relates to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1799

# Workflow:

Create Individual in PK-Sim 9.1:
![image](https://user-images.githubusercontent.com/26569320/131084643-48a46536-9069-4060-9037-22cc5451b922.png)

Reimport to PK-Sim 10 works: The transport is correctly expressed at the basolateral side:
![image](https://user-images.githubusercontent.com/26569320/131084882-2f6e99e4-b569-4445-9832-c5aa15a1dd02.png)

Export snapshot from PK-Sim10 and reimport to PK-Sim 10 does not work (apical vs basolateral switches):
![image](https://user-images.githubusercontent.com/26569320/131085271-094f2389-648e-44b1-b064-fad9307e450a.png)

# Files:
[Snapshots.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7064866/Snapshots.zip)

@Open-Systems-Pharmacology/ospsuite-developers 
@Open-Systems-Pharmacology/suite-core-developers 
@AndreDlm 
@TWendl

**Comment by msevestre** [comment]
This one is closed now...
