### ISSUE TITLE
Checkboxes must be selected multiple times

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1844]
Hi @Yuri05 and @msevestre 

[...]

However I repeatedly noticed that while making any selection, like the one highlighted in the attached snapshot, it requires 2 to 3 times clicking of mouse to activate the selection. This type of problem I am faced frequently with v10 beta.

Thanks and regards,
Anant
![PK-Sim10Beta_Selection Problem](https://user-images.githubusercontent.com/32693494/131209205-8e52cc9f-4384-44fd-8d1b-3c6187ec5d32.JPG)

**Comment by PavelBal** [comment]
I can reproduce, very annoying.

**Comment by Yuri05** [comment]
@PavelBal Same in Mobi probably? 
I just tried it with many different parameter views in PK-Sim - could reproduce it only for the **application** parameters view; everywhere else it seems to work fine.

**Comment by PavelBal** [comment]
No, I could not reproduce this in MoBi.
