### ISSUE TITLE
Protein Expressions as standalone Building Block?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1847]
During discussions about ["Protein Inheritance"](https://github.com/Open-Systems-Pharmacology/QualificationPlan/discussions/161) (urgently required for more flexibility in the qualification workflows) a new idea was born: 
### *should we define Protein Expressions as a standalone building block in PK-Sim?*

This would allow not only the protein inheritance within qualification (which would be then just a building block inheritance), but would also allow easy implementation of additional use cases (e.g. definition of high/low metabolizers ) and would be also beneficial for OSMOSES.

There are different possible implementations, each has some advantages/disadvantages which should be discussed.

### Option 1
* Protein expressions are defined as a standalone building block.
* Protein expressions are completely removed from Individual/Population bulding blocks
* During simulation creation: additional Protein mapping tab is added, where proteins can be added to selected individual or population
![grafik](https://user-images.githubusercontent.com/25061876/131995185-1008cbed-861c-44bd-b4e5-7b82bb35b110.png)

Pro:
* lower implementation effort compared to the following options

Contra
* For populations: it is not possible to define the variation of protein specific parameters (e.g. ReferenceConc, Ontogeny factors) on the building block level. It will be only possible on the simulation level.
* Adding proteins in the simulation must be redone for every new simulation
* It is not possible to edit or show the **initial concentrations** of proteins on the building block level (new feature in V10)

### Option 2
* Protein expressions are defined as a standalone building block.
* In individual/population building blocks: **placeholder** for proteins are defined (similiar to the formulation placeholder within application protocol)
* During simulation creation: additional Protein mapping tab is added, where **protein placeholders must be mapped to existing protein building blocks**

Pro
* Proteins cannot be "forgotten" during the mapping

Contra (same as option 1):
* For populations: it is not possible to define the variation of protein specific parameters (e.g. ReferenceConc, Ontogeny factors) on the building block level. It will be only possible on the simulation level.
* Mapping proteins in the simulation must be redone for every new simulation
* It is not possible to edit or show the **initial concentrations** of proteins on the building block level (new feature in V10)

### Option 3
Same as option 2. Additionally:
* In the population building block: for each added protein placeholder, it is possible to vary a **factor** for some protein specific parameters (Reference Conc, ontogeny factors etc.)

Pro
* Variation of protein specific parameters can be defined on the building block level for populations

Contra
* Mapping proteins in the simulation must be redone for every new simulation
* It is not possible to edit or show the **initial concentrations** of proteins on the building block level (new feature in V10)

### Option 4
Introduction of something like "sub-building blocks"

* Protein expressions are defined as a standalone building block.
* In individuals/simulations: **references** to existing protein building blocks are added
* Referenced proteins are read-only and cannot be edited within individual/population

Pro
* Variation of protein specific parameters can be defined on the building block level for populations
* No additional mapping of proteins required during simulation creation
* Initial concentrations of proteins can be shown (but not edited) within individual building block

Contra
* Higher implementation effort
* It is not possible to edit the **initial concentrations** of proteins on the building block level

### Option 5
**Editable** "sub-building block"

* Same as option 4, but now it is possible to **edit** the protein parameters within the individual/population building block

Pro
* Variation of protein specific parameters can be defined on the building block level for populations
* No additional mapping of proteins required during simulation creation
* Initial concentrations of proteins can be edited within individual building block

Contra
* highest implementation effort
* we would need to introduce update/commit between the protein-sub-building blocks within individuals/populations and the protein building blocks

**Comment by Yuri05** [comment]
@Aedginto @AndreDlm @Christoph27 @Erik-Sjogren @Incei @JanSchlender @JoseDavidGomez @msevestre @PavelBal @sfrechen @StephanSchaller @teutonicod @tobiasK2001 @TWendl 
Please share your thoughts on this!

**Comment by StephanSchaller** [comment]
I have to think on this... I have a gut feeling this could also synergies with the remaining issues we have in handling expressions for the modularization in MoBi (OSMOSES)

**Comment by Yuri05** [comment]
>I have to think on this...

Cogito ergo sum :)

**Comment by msevestre** [comment]
This will be released in v11
