### ISSUE TITLE
Tags of ProcessRate-parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1849]
Add tag `Influx `for influx transports and tag `NotInflux ` for all other active transports (efflux, pgp, bidirectional)
Not sure if the "Active" tag is used elsewhere except for calculation of mass absorbed - so I would keep.
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/2bdc97acd7de29717d6905ea194eae63478c4e57/src/OSPSuite.Core/Domain/Mappers/TransportBuilderToTransportMapper.cs#L67-L70

**Comment by msevestre** [comment]
This was done in core
