### ISSUE TITLE
Better user interface display for AMD Ryzen CPU user

### ISSUE THREAD

**Issue by regulus92** [Open-Systems-Pharmacology/PK-Sim#1857]
Hello, everyone. Here I have a minor request. I found that OSP Suite running in a AMD CPU computer shows a fuzzy interface. Intel Core CPU works well. Maybe it is due to different image processing mechanisms?

**Comment by msevestre** [comment]
What about screen resolution? Can you show us some pictures?

**Comment by regulus92** [comment]
Screen resolution is high (1920*1080), only the OSP interface can't reach this resolution. I have tested in R3 2200G,  R5 2500U and R5 4500U. I will paste pictures later. Thank you.

**Comment by PavelBal** [comment]
Cannot confirm that this is an issue with Ryzen. OSPS works fine with Ryzen gen1 and Threadripper. Your CPU has an integrated graphics processor, right? This might be an issue with scaling display resolution.

**Comment by regulus92** [comment]
@PavelBal Yes, I'm using Ryzen APU with Vega Graphics. I'm not sure if separate AMD GPU have this problem. But Intel CPU with its integrated graphics is definitely OK.
![_20210908211838](https://user-images.githubusercontent.com/45459593/132517948-0a0b9d11-0948-4dfc-8cf3-d5155a696198.jpg)

**Comment by regulus92** [comment]
The clear one in i5-10500 desktop.
![_20210908211847](https://user-images.githubusercontent.com/45459593/132518197-28e1ea17-ab60-4d06-be54-35eca3a9e47d.jpg)
I opened the software in default settings after its installation.

**Comment by msevestre** [comment]
damn...enough to get a seizure!

**Comment by msevestre** [comment]
you are comparing PKSim and MoBi however. Can you show the same tool on both systems?

**Comment by regulus92** [comment]
highly possible a scaling display issue, but by default this is the case.

**Comment by PavelBal** [comment]
Definitely a scaling problem (maybe some settings in the graphics driver), nothing PKSim/MoBi can do here.

**Comment by msevestre** [comment]
@regulus92 This should be fixed with the upcoming version v11
