### ISSUE TITLE
Predefined templates: use the "master" version of Building Blocks from GitHub

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1860]
At the moment the built-in (predefined) templates are released as part of the OSP Suite. Because of that they become sometimes out of sync with the "master" version of the template on GitHub. Also the templates cannot be updated between releases.
<img width="300" src="https://user-images.githubusercontent.com/25061876/133437653-36956b2f-6b9b-4906-b664-55def2a1c425.png">

Instead (or additionally), building block templates could be loaded **dynamically** from the "master" project snapshots.
For this I would create something like `TemplateMaster.json` on GitHub, which could be read by PK-Sim during program start, allowing using the latest (and up to date) version of released building locks at any time

<kbd>
<img src="https://user-images.githubusercontent.com/25061876/133436875-0f8ef360-660c-4cbb-b871-19a859d15193.png">
</kbd>

<br><br>
<details><summary><b>TemplatesMaster.json</b></summary>

```
{
  "Templates": [
    {
      "Type": "Individual",
      "Name": "European (P-gp modified, CYP3A4 36 h)",
      "Project": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Rifampicin-Model/v1.1/Rifampicin-Model.json",
      "Version": 1.1,
      "Description": "BlaBla"
    },
    {
      "Type": "Compound",
      "Name": "Rifampicin",
      "Project": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Rifampicin-Model/v1.1/Rifampicin-Model.json",
      "Version": 1.1,
      "Description": "BlaBla"
    },
    {
      "Type": "Compound",
      "Name": "Cimetidine",
      "Project": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Cimetidine-Model/v1.0/Cimetidine-Model.json",
      "Version": 1.0,
      "Description": "BlaBla"
    }
  ]
}
```
</details>

**Comment by msevestre** [comment]
I would remove the compound from the template database completely

**Comment by sfrechen** [comment]
In general, the idea is good but needs further refinement, i.e. all officially released compounds should be selectable --> PK-SIm would need to search in the repository (?)

**Comment by Yuri05** [comment]
It's not a repository, but just kind of "table of contents", which points to all available templates. As soon as you e.g. release a new substance model you need to extend this TOC with the new entry and it will be automatically found by PK-Sim.

**Comment by PavelBal** [comment]
That would actually be amazing.

Have to think about the details, e.g. every model snapshot has not only the compound, but also the individual - how to deal with that?

**Comment by Yuri05** [comment]
>every model snapshot has not only the compound, but also the individual - how to deal with that?

Here we are talking in the first instance about the **building block** templates. So compound and individual would be 2 different templates. The idea was to **extract** the building blocks from the referenced model snapshots.

E.g. if the user wants to load the **Rifampicin** compound template, then **Rifampicin-Model.json** is downloaded, the **Rifampicin** compound building block is extracted from it and used in the project.

```
    {
      "Type": "Compound",
      "Name": "Rifampicin",
      "Project": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Rifampicin-Model/v1.1/Rifampicin-Model.json",
      "Version": 1.1,
      "Description": "BlaBla"
    }
```

**Comment by msevestre** [comment]
Why do we want to use this indirection? (e.g. a content file and then you have another file to download)?
Wouldn't it be easier to have just one json file with everything ?(e.g list of compounds. individuals etc..). It would be installed with PKSim and the user would have the possibility to update the file if there is a new version available....

(the size of such a file might grow...but it is just text....nothing else)

**Comment by msevestre** [comment]
e.g. something like this
![image](https://user-images.githubusercontent.com/1041237/133657785-7d2fa8c2-f7ce-4960-bbf8-88cf774db95d.png)

**Comment by msevestre** [comment]
Adding a new template would just mean adding a new entry in this file. diff would be trivial with github etc..

**Comment by Yuri05** [comment]
>Why do we want to use this indirection? (e.g. a content file and then you have another file to download)?
Wouldn't it be easier to have just one json file with everything ?(e.g list of compounds. individuals etc..). It would be installed with PKSim and the user would have the possibility to update the file if there is a new version available....

Because the model development usually happens elsewhere (e.g. Rifampicin-Model is developed in https://github.com/Open-Systems-Pharmacology/Rifampicin-Model and the Rifampicin compound BB can be found there in the latest release model snapshot.) If we store all the BBs into one single file - then with every new release of the project snapshot we need to manually replace all the BBs with their updated version from the project snapshot.
It seems to me much less error prone to replace just the reference to the new project snapshot instead of copying whole building blocks all the time.

**Comment by msevestre** [comment]
the linked file is a project file with individual etc... where we only want one compound.... weird

**Comment by msevestre** [comment]
and that also means that you need one repo for every template you want to deliver....

**Comment by Yuri05** [comment]
>and that also means that you need one repo for every template you want to deliver....

Yes. It's even a must for me (all predefined templates must be released somewhere, meaning they must live in a repository).
But it's not necesserily 1 repo per template: 1 repo could contain several templates (either in the same project snapshot or in different snapshots). But it's just my opinion :)

**Comment by msevestre** [comment]
* I would not use the word `master` anymore but `main` or nothing at all.

* We could add a line in the version.xml file 
`https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/versions.xml`
with the template database version. That way, we could always bump the version when we need to and PKSim would check on start if there is something new and update if required. No need to download the template master file all the time

* I don't like the idea of duplicating content such as version or description. Ideally, we would read the info from the snapshot when creating the json file automatically. This is just a nice to have

**Comment by Yuri05** [comment]
>We could add a line in the version.xml file
https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/versions.xml
with the template database version. That way, we could always bump the version when we need to and PKSim would check on start if there is something new and update if required. No need to download the template master file all the time

Yep, good idea.

>I don't like the idea of duplicating content such as version or description. Ideally, we would read the info from the snapshot when creating the json file automatically. This is just a nice to have

Yep... if it's filled. At the moment none of the released compounds on Github has a description (building block description is empty).
The version can be extracted from the link to the snapshot (e.g. .../v1.1/... ==> 1.1 ) - so no need to duplicate for sure.

**Comment by msevestre** [comment]
@Yuri05 Do you want me to start working on this on a separate branch for a v10 Update 1 ?

**Comment by Yuri05** [comment]
@msevestre Yes :)

**Comment by msevestre** [comment]
How about this: we have the file that you described above. Everytime the file changes, we create (automatically) another file that will be the list of all building blocks as snapshot. This file can be downloaded on demand in pksim and also installed with the setup. Why? Because we do not have to download the whole project all the time just to get a snapshot. It should also speed things up because everything will be local (after the initial download)

If we want to add a new snapshot or update a snapshot, the master file will change. PR will therefore trigger a rebuild of the "snapshot file"

**Comment by msevestre** [comment]
In fact, what we can also try is to download the snapshot files on demand and save them into the user profile (e.g. `C:\Users\<UserName>\AppData\Roaming\Open Systems Pharmacology\PK-Sim\10.0`). That way if the file was downloaded already, no need to download again. 

So for instance looking at
![image](https://user-images.githubusercontent.com/1041237/135773061-aab1e6e7-e2da-4bfa-a3bf-9ea54c8cdb2d.png)


we would download Rifampicin-model under sthg like Rifampicin-model-v1.1.json
e.g

![image](https://user-images.githubusercontent.com/1041237/135773123-eaf3b53a-08fc-4ad5-86a4-a7e4f3e6c054.png)

Having the version has properties becomes required as we should not rely on path I believe to get the version.

**Comment by msevestre** [comment]
Update
