### ISSUE TITLE
Bug: Drug and Metabolite transporter inhibition

### ISSUE THREAD

**Issue by Erik-Sjogren** [Open-Systems-Pharmacology/PK-Sim#1861]
Hi,

I have found a potential bug related to transporter inhibition mediated by Drug and metabolite. 
The included example includes a Perpetrator (**Perp**), its metabolite (**Perp_Met**) and a Victim (**Vict**).

Following processes are included:
**Perp**: Substrate to CYP3A4 creating Perp_Met, Comp inhibitor of CYP2C9 and OATP1B1
**Perp_Met**: Substrate to CYP2C9 and OATP1B1, Comp inhibitor of CYP2C9 and OATP1B1. 
**Vict**: Substrate to CYP2C9 and OATP1B1

Issue:
**Perp_Met** is not included in the inhibition of **Vict** OATP1B1 transport. Most likely due to that the same formula for the OATP1B1 parameter “_Km interaction factor_” is used for both **Perp_Met** and **Vict** “_OATP1B1-OATP1B1-Km interaction factor_”

See picture and included model files. 

BR,
Erik

<img width="1131" alt="Snapshot-Metabolite transporter inhibition" src="https://user-images.githubusercontent.com/29089721/133585725-c2b147ec-0893-4ab2-81aa-11b47b302682.PNG">
[Metabolite transporter inhibition.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7176517/Metabolite.transporter.inhibition.zip)

**Comment by sfrechen** [comment]
Well spotted, @Erik-Sjogren 
That is indeed a bug (@Yuri05).

For CYP2C9, it works out fine. 
![image](https://user-images.githubusercontent.com/26569320/133606280-49f82c4e-4749-4bfb-bfa4-766beb07bf4b.png)

Thus, only transporters affected.

**Comment by msevestre** [comment]
@sfrechen can you attach the project with CYP2C9? or how can I see this screen?

**Comment by Yuri05** [comment]
Cannot reproduce it with a simple project. 
Created a new project (in V9) with:
* **Drug**: transported by **T1** 
* **Inhibitor1**: inhibits **T1** and metabolized by **CYP** to **Inhibitor1_meta**
* **Inhibitor1_meta**: inhibits **T1**
* **Inhibitor2**: inhibits **T1**

Then created 2 simulations:
* Sim1: Drug+Inhibitor1+Inhibitor2
* Sim2: Drug+Inhibitor1+inhibitor1_meta

In both simulations Drug/T1/Km_InteractionFactor looks correct (both inhibitors included)
[V9_Test.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7177772/V9_Test.zip)
![grafik](https://user-images.githubusercontent.com/25061876/133614204-59958793-45b1-4e6d-921f-9e0824afc60c.png)
![grafik](https://user-images.githubusercontent.com/25061876/133614939-169216a1-8e5a-4d61-a600-581bd54670e4.png)

**Comment by Erik-Sjogren** [comment]
[Metabolite transporter inhibition.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7177874/Metabolite.transporter.inhibition.zip)

**Comment by Yuri05** [comment]
also added, that Inhibitor1_meta is transported by **T1** . Still cannot reproduce.
* **Drug**: transported by **T1** 
* **Inhibitor1**: inhibits **T1** (competitive) and metabolized by **CYP** to **Inhibitor1_meta**
* **Inhibitor1_meta**: inhibits **T1** (competitive) and transported by **T1** 
* **Inhibitor2**: inhibits **T1** (competitive)
[V9_Test.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7177867/V9_Test.zip)
![grafik](https://user-images.githubusercontent.com/25061876/133616164-04e0595c-9584-4c13-84c0-cd232a8a5efe.png)

**Comment by Erik-Sjogren** [comment]
Ah, my zip file (containing the model files) was not correctly attached in my first post.

**Comment by Yuri05** [comment]
finally, added another enzyme (CYP2) which is also inhibited by 2 compounds:
* **Drug**: transported by **T1** and metabolized by **CYP2**
* **Inhibitor1**: inhibits **T1** (competitive) and metabolized by **CYP** to **Inhibitor1_meta** and inhibits **CYP2** (competitive)
* **Inhibitor1_meta**: inhibits **T1** (competitive) and transported by **T1** and metabolized by **CYP2** and inhibits **CYP2** (competitive)
* **Inhibitor2**: inhibits **T1** (competitive) and inhibits **CYP2** (competitive)

So in terms of DDI/Transports/Metabolizations it should be exactly what @Erik-Sjogren has in his project. But still unable to reproduce... Something in Eriks project seems to be very special.
[V9_Test.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7178077/V9_Test.zip)
![grafik](https://user-images.githubusercontent.com/25061876/133620386-279ef2d0-d83c-44cb-9e24-75d190c0771e.png)

**Comment by Erik-Sjogren** [comment]
Strange. 
OK, I will start from scratch and see if I can recreate the issue.

**Comment by msevestre** [comment]
We have the project where we can reproduce the issue so we'll be able to find what's going on. Don't waste your time on this @Erik-Sjogren

**Comment by Erik-Sjogren** [comment]
OK, many thanks.

**Comment by sfrechen** [comment]
Can fully reproduce if I set up a project from scratch in PK-Sim 10.

Perp -> M1 via CYP
Perp substrate and inhibitor of OATP1B1
M1 substrate and inhibitor of OATP1B1
Victim substrate  of OATP1B1

For "all" OATP1B1 objects under the the thre compounds, the Km interaction factor is the same formula:
![image](https://user-images.githubusercontent.com/26569320/133643542-81b0e814-aabb-4254-90fa-3d32c906c103.png)
![image](https://user-images.githubusercontent.com/26569320/133643255-b1e8de13-c5f9-42c6-817a-aca8be2fff2e.png)

Thus, always only Perp is inhibiting (even itself which should not be the case).

**Comment by msevestre** [comment]
I managed to reproduce too....workign on this

**Comment by Erik-Sjogren** [comment]
Many thanks @msevestre @sfrechen @Yuri05

**Comment by msevestre** [comment]
ok found the bug. Fix is coming

**Comment by Erik-Sjogren** [comment]
Wow! That was fast. 
Perfect
