### ISSUE TITLE
Add reference to the "Japanese" population

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#1878]
In the population selection view

https://user-images.githubusercontent.com/11330453/135459165-7c149cb6-4a1c-488c-ae84-462fcb95e78d.png

**Comment by Yuri05** [comment]
The reference is: https://github.com/Open-Systems-Pharmacology/OSPSuite.Documentation/blob/master/Japanese_Population/Report.md
Maybe we could change it to "Schlender 2015"? @JanSchlender Thoughts?

**Comment by Yuri05** [comment]
ok, after short check with Jan:
**Schlender 2015** for the Japanese population

And: **Claassen 2015** for the preterm pop
