### ISSUE TITLE
Changing "Icon Sizes" doesn't change much

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/PK-Sim#1879]
I noticed (and @PavelBal confirms the same behavior with `9.1` version) that changing `Icon Sizes` in `Options` doesn't change anything (except for the Simulations pane)
 
![image](https://user-images.githubusercontent.com/11330453/135828371-d4d07bea-22dc-4e34-91f2-8228ea749855.png)

**Comment by msevestre** [comment]
You will need to restart the application

**Comment by IndrajeetPatil** [comment]
That worked! Thanks.

Should this be documented, or should the UI provide a hint to restart the application? 

The issue is resolved on my end, but will leave it open if you think it's still a documentation issue.

**Comment by Yuri05** [comment]
we could change the caption of the panel to "Icon sizes (application restart required)"

**Comment by msevestre** [comment]
lol. @Yuri05 A few seconds faster :)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/135910956-d4d63c07-a89f-4b23-a706-2dd8834846c9.png)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/135911254-da97ab75-1b43-4287-9b57-4ceb18b1f41e.png)
