### ISSUE TITLE
Web-setup not working

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#189]
```
[0B90:0C6C][2017-05-24T18:49:38]i338: Acquiring package: miktex, payload: miktex, download from: https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi
[0B90:0C6C][2017-05-24T18:49:41]e000: Error 0x80070005: Failed attempt to download URL: 'https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi' to: 'C:\Users\POWERU~1\AppData\Local\Temp\{5DB6A314-2E66-45D0-9F3E-38681DDB925A}\miktex'
```
MikTex package cannot be downloaded by Web-Setup. However entering the download address directly into IE or Firefox works. 
As we can see in the screen, download link redirects to the GitHub cloud. Can this be an issue for the setup?
![clipboard01](https://cloud.githubusercontent.com/assets/25061876/26415476/eb53fa62-40b2-11e7-8b9a-45acfdfc001e.jpg)

**Comment by msevestre** [comment]
if the miktex package cannot be downloaded, neither will any of the other
packages. No idea why

**Comment by msevestre** [comment]
@Yuri05 look at the disucssion here
https://github.com/aspnet/Home/issues/1192

**Comment by msevestre** [comment]
Does that make it work? (other msi won't be found anyways because we haven't release them yet)
> 
It is a network error. By default, Windows 2012 R2 has IE Enhanced Security Configuration enabled. Disable IE Enhanced Security Configuration (for both Administrators and Users) using either the Server Manager or powershell (or regedit), then run the exe again. It will succeed.

**Comment by msevestre** [comment]
@all: I have no idea has to what may be happening here.

**Comment by msevestre** [comment]
0x80070005 means access denied. so somehow, the installer does not have access to the internet.
Do we have a way to put the files on an ftp server (without password)?

**Comment by rwmcintosh** [comment]
I tried a few things with the URL including replacing the github url with the redirected one, trying without encryption. I could not find a solution. The redirected URL that is given in response to the initial request expires, so we cannot use that anyway.

Best thing to try now is a different file host with direct link to the msi.

**Comment by msevestre** [comment]
Let's fix that in 7.2, even if it means setting up our own server via azure

**Comment by msevestre** [comment]
We just tried by moving MikTex to our own ftp server .Works like a charm

**Comment by msevestre** [comment]
@Yuri05 How do you want to proceed? We could host a domain with for example netfirms.com to simply use their ftp

Or is there an ftp server we could use (download without password) ?

**Comment by msevestre** [comment]
@Yuri05 Any progress on that?

**Comment by Yuri05** [comment]
In progress

**Comment by msevestre** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/Suite/pull/9
