### ISSUE TITLE
Exporting an individual as pkml for MoBi will also export the expression profile

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1913]
If one is available

**Comment by rwmcintosh** [comment]
@msevestre I think we discussed that this is not the expectation now. Can we close this one?

**Comment by msevestre** [comment]
No this is absolutely the expectation.
Individual without the expression profiles is useless

**Comment by PavelBal** [comment]
@msevestre Let's schedule a meeting to discuss this. I do not think that expression profilies are required for the use case of individual export, but am open for a discussion.

**Comment by msevestre** [comment]
I have no time at the moment so I'd suggest you explain why you think it makes sense to export the individual without the profile (knowing that there is no link whatsoever in MoBI).
When import, you could ask " do you want to also import expression profiles" if any are defined.
But when you export, I am failing to understand a use case where this would make sense

**Comment by PavelBal** [comment]
Discussion 11.01.2023: do not export expression profiles together with individuals.
