### ISSUE TITLE
Feature wish: Maximize Button for Data Import Window

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#1927]
The new data import function in v10 is great, it makes my life easier :)

A minor thing that I miss is a maximize button for the Data Import Window. As the data sets I typically import consist of numerous columns I always need this window to be displayed in its largest size:

![image](https://user-images.githubusercontent.com/26541603/139086824-d6757fa8-e5bb-4e51-9ff5-aa005f570f7c.png)

**Comment by georgeDaskalakis** [comment]
in v11 the maximize button exists.
