### ISSUE TITLE
Active transports Lumen<=> Mucosa: too many transports are created in case the transporter direction (Influx/Efflux/...) is not the same in all GI segments.

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#1930]
In the project attached, different transporter directions were defined in GI segments: [Mucosa_MultipleTransportDirections.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7441291/Mucosa_MultipleTransportDirections.zip)

<img width="400" src="https://user-images.githubusercontent.com/25061876/139418935-6de1f087-0966-446d-941d-00cb911aa383.png">

In the created simulation, **each GI-segment gets transports of each direction defined for any GI segment**, which is obviously wrong:
<img width="400" src="https://user-images.githubusercontent.com/25061876/139419390-7c9e6727-6505-446d-8661-4995a80dc2a4.png">

The problem is: transport source/target descriptor conditions are not properly extended:
![grafik](https://user-images.githubusercontent.com/25061876/139419690-39d16c3a-01d1-4692-a80f-93781e40f661.png)

In the **tissue organs** this is done correctly. E.g. in the same project different transporter directions are defined for some tissue organs:
<img width="400" src="https://user-images.githubusercontent.com/25061876/139421022-de244e5d-ff12-49f2-9df2-545af84e22e9.png">
In the simulation exactly 1 transport of selected type is created per organ:
<img width="350" src="https://user-images.githubusercontent.com/25061876/139421193-ede7f35c-2114-4e70-86bc-f59b2425c7f3.png"><img width="350" src="https://user-images.githubusercontent.com/25061876/139421233-162a290a-b9aa-4f99-bf05-3f328988aa50.png"><img width="350" src="https://user-images.githubusercontent.com/25061876/139421279-58e94184-11ad-4357-9f49-6e7f761afb70.png"><img width="250" src="https://user-images.githubusercontent.com/25061876/139422050-e5340205-b67e-4d64-906a-665803327a63.png">

This is because the transport source/target criteria are properly extended:
![grafik](https://user-images.githubusercontent.com/25061876/139421449-a275c02e-05ab-4158-96cf-3f3f7fdfb2f9.png)

Thus the problem exists only for Lumen <=> Mucosa transports

**Comment by msevestre** [comment]
v10.1 or v11? e.g. are we going to release a patch for this?

**Comment by msevestre** [comment]
Looking at this now

**Comment by msevestre** [comment]
This is because of this line
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Core/Mappers/ProcessToProcessBuilderMapper.cs#L375
