### ISSUE TITLE
Bug in Import Observed Data: "Import unit from a column" is case sensitive

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#1931]
Should be case insensitive.
Currently, an error is thrown in case of `µg/L` that this is an unknown unit.

**Comment by Yuri05** [comment]
OSP9 or OSP10? in 10 this should be fixed: https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1298

**Comment by msevestre** [comment]
This feature is only in v10. So it's a bug

**Comment by msevestre** [comment]
@georgeDaskalakis and @abdelr can you check this out?

**Comment by abdelr** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1364](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1364) via [**ZenHub**](https://www.zenhub.com/)

**Comment by msevestre** [comment]
Let's close this when the changes are available in pksim

**Comment by abdelr** [comment]
> Let's close this when the changes are available in pksim

Sure

**Comment by msevestre** [comment]
that should be fixed
