### ISSUE TITLE
Add "Urine compartment emptying" as an event template to PK-Sim

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#1933]
Similar as the gallblader emptying event, an event is required to empty the urine compartment.
The event should be available as a selection in the "Create Event" menu. No parameters needed to be specified by the user. The user should simply remove all compounds from the urine compartment (set all amounts to zero).
The event should then be added to a simulation via the "Events" tab, potentially at multiple times for one simulation.

@Yuri05

**Comment by sfrechen** [comment]
> @sfrechen Do we need a parameter such as for Gallbladder emptying? ![image](https://user-images.githubusercontent.com/1041237/149321953-1efe744a-f10d-46f8-ba2f-ff21175c397e.png)
> 
> @Yuri05 Why do we have this parameter? Is this to turn the event on and off without changing the sim structure?

Yes, we need such an event with such a single parameter. So pretty simple :-)

**Comment by msevestre** [comment]
>No parameters needed to be specified by the user.

That's why I was confused ah ah :)

For gallbladder, it does something a bit funky

There is a parameter called `Time to complete gallbladder refilling`. Do we have something like this for Urine as well?

**Comment by sfrechen** [comment]
> There is a parameter called `Time to complete gallbladder refilling`. Do we have something like this for Urine as well?

No. We just need the option to empty the compartment. Nothing more.

**Comment by msevestre** [comment]
@Yuri05 Can we talk about this when you have time?

**Comment by msevestre** [comment]
@Yuri05 There is this table here (tab_event_molecule)
![image](https://user-images.githubusercontent.com/1041237/149388551-b12e1312-1e63-4832-8d8a-85de6f1db663.png)

5957,EVENT,Urine_Emptying_StartEvent,4914,DRUG,Events,Zero_Rate,1,1

Which creates this

--------------- SWITCHES ----------
Event: Urine_Emptying_StartEvent
	Path: as|Events|PIPI|PIPI_1|Urine_Emptying_StartEvent
	Condition: Urine_Emptying_Enabled AND (Time=StartTime)
		StartTime: as|Events|PIPI|PIPI_1|Start time(120 [min])
		Urine_Emptying_Enabled: as|Events|PIPI|Urine compartment emptying enabled(1)
		Time: as|Time(0 [min])
	Assignments:
		**Path: as|Organism|Kidney|Urine|Alfentanil**
		UseAsValue: True
			Formula: 0

So somehow DRUG is replaced with Alfentanil...but only the first drug...maybe we can build upon this
I tried to apply two drugs but only the first one is added

**Comment by Yuri05** [comment]
>So somehow DRUG is replaced with Alfentanil...but only the first drug...maybe we can build upon this
I tried to apply two drugs but only the first one is added

I was first wondering why... that's why. Lol
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/eb53d542421fbb3c13fad936b547dfbd349c8ebb/src/OSPSuite.Core/Domain/Services/KeywordReplacerTask.cs#L83-L88

Actually this code should have been removed after we stopped support for 4.2 projects.
Also the immediate EHC emptying event should be removed from the PK-Sim database (is not used anymore as well)

So for now I see only Option 1 (Transport to :toilet: ) as solution. Or we need new keywords...

**Comment by msevestre** [comment]
Lol...I am going to remove that now....4.2 shot going on still

**Comment by msevestre** [comment]
>Or we need new keywords...

I am going to try this.... "ALL_FLOATING".
This will only be used for Assignment for now

**Comment by msevestre** [comment]
Seems to work...
![image](https://user-images.githubusercontent.com/1041237/149664520-a6cd05aa-eccc-4725-9b08-32034949c870.png)

![image](https://user-images.githubusercontent.com/1041237/149664556-ab6fa65d-3099-48a7-9954-97c46d8904e1.png)
