### ISSUE TITLE
Expression Profile: How do we deal with species dependent action?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1943]
@PavelBal @Yuri05 @StephanSchaller 
At the moment, the species is known before we create an expression profile which allows us to select the specific "Expression Database" (human, or something else for those lucky enough to have another version working for another species)

Now with the new Expression profile concept, it is somewhat different because we do not have a species 
Suggestion #1
We create an Expression Profile for a given Species (e.g. when we create one, you also need to specify for which species it applies)
Suggestion #2
When loading from database, we need to select the expressions database to pick from (only if there is more than one defined)

Thoughts?

**Comment by msevestre** [comment]
I think we need to specifiy the species at the beginning. 
Because ontogeny etc.. is only available fro Human for instance .

**Comment by StephanSchaller** [comment]
Option 2. But we should still allow to combine it with an individual from another species.

**Comment by msevestre** [comment]
I don't think Option #2 is feasible as we need to carry over many info on the species (such as age dependency etc.. for ontogeny)

**Comment by msevestre** [comment]
see comment here https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1943#issuecomment-959782072

**Comment by StephanSchaller** [comment]
No, I guess I misunderstood you. I thought " need to select the expressions database to pick from" meant also selecting the corresponding species (i.e., e.g., select database (XYZ, if multiple databases per species) for species XYZ)

**Comment by StephanSchaller** [comment]
But I guess you could have a Species Selection menu such as:
![image](https://user-images.githubusercontent.com/25477643/140188510-609f50f3-65e2-42b1-8ab7-937a5af2c570.png)

 and just set the species from a dropdown, either manually, or the selection is pre-set depending on the database you choose

**Comment by msevestre** [comment]
It needs to happen independently from the database as sometimes, profiles are entered by hand
Therefore, species should be a properties to enter when creating the profile (such as in create individual)

**Comment by Yuri05** [comment]
>Suggestion #1
We create an Expression Profile for a given Species (e.g. when we create one, you also need to specify for which species it applies)

Would vote for this. Usually the same profile cannot be used for different species anyway and I assume when creating a profile user always knows for which species.

**Comment by PavelBal** [comment]
Vote for Suggestion 1.
