### ISSUE TITLE
Assigning Expression Profile to a molecule

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1951]
@PavelBal @Yuri05 @StephanSchaller 
An expression profile will be defined for a given molecule and category(or phenotype). 
For example 
* CYP3A4-Healthy
* CYP3A4-Standard 
* etc..

In the individual, does it make sense to assign a profile to another molecule? e.g CYP2D6 will use CYP3A4-Healthy.
I would say no because it is very easy do create a specific profile for CYP2D6 and use it. If we keep it simple like this, the UI in the individual becomes trivial. As a user, you only need to select an Expression Profile and that's it.

Thougths?

**Comment by Yuri05** [comment]
>I would say no because it is very easy do create a specific profile for CYP2D6 and use it. If we keep it simple like this, the UI in the individual becomes trivial. As a user, you only need to select an Expression Profile and that's it.

Agree

**Comment by PavelBal** [comment]
I don't even understand how it should make sense (assigning a CYP3A4 profile to CYP2D6?) - so the answer is simple "no" :D
