### ISSUE TITLE
Adding an indiviudal to a simulation should also add the used expression profiles to the simulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1965]
Right? @Yuri05 @PavelBal ? (or are they implicit in the Simulation because we are using the individual?)

**Comment by Yuri05** [comment]
@msevestre Do you mean, that expression profiles should appear e.g. in the simulation explorer among building blocks used in the simulation? I think no. They cannot be directly replaced (without changing the individual/population), there is no commit to BB, update from BB can be done only via update from the individual/population. So I don't see a reason to add expression profiles to a simulation explicitly.

**Comment by PavelBal** [comment]
I do not clearly understand the question :D But in general I agree with @Yuri05 - the expression profile is already a part of the individual, so no need to show it separately.

**Comment by msevestre** [comment]
Ok next question (and I do not know how to solve this based on what we discussed)

Let say I change the value of a relative expression in a simulation (or Ref. conc) etc... either manually or via optimization
HOW DO I SYNCHRONIZE this value in the expression profile? 

Committing to the individual will update the value in the individual, thus rendering our rule, individual /expression profile always in sync invalid. Updating Ind => expression profile is something we explicitly also excluded 

so..?

**Comment by PavelBal** [comment]
I would say the changes should be committed to the Expression Profile (with a hint/warning, that those values will be valid for all individuals using this profile)

**Comment by msevestre** [comment]
done with done with #1967
