### ISSUE TITLE
Change delimiter to use | instead of -

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1966]

**Comment by Yuri05** [comment]
Might become problematic, because e.g. some protein names contain "-"
![grafik](https://user-images.githubusercontent.com/25061876/142438827-88f0c7e2-a0eb-437e-b1f3-02dceb88e0ad.png)

Should we change the **delimiter** instead, e.g. to "|"? And then we would have something like
`P-gp|Human|Healthy`

**Comment by msevestre** [comment]
Ok. A bit ugly but why not

**Comment by msevestre** [comment]
done with #1967

**Comment by msevestre** [comment]
this is done
