### ISSUE TITLE
Parameter "Fraction of blood for sampling" in PK-Sim

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#1976]
It would be good if the parameter "Fraction of blood for sampling" which is present in each organ is accessible also from PK-Sim. 

(Currently needed for an evaluation plan which works currently only from snapshots generated via PK-Sim). 

At the moment,  there seems to be no really got location for it at the GUI. I would probably add a new category “Tissue Sampling” under the category “Physiology”. But maybe there are better suggestions?

**Comment by msevestre** [comment]
What do we use this parameter for? Is this some kind of placeholder for measured values?

**Comment by Christoph27** [comment]
The parameter determines how much blood (as fraction of total blood in the organ) is used for the "Whole Organ"-Observer. If it is 1, the complete blood from the organ’s vascular space is taken into account for calculating the concentration in the organ (e.g. if your measured concentration is from imaging and you do not correct for blood vessels). If it is 0, the "Whole Organ"-Observer gives the same value as the „Tissue“ Observer. In samples from tissue dissection, you have some residual blood left, i.e. the parameter has a value between 0 and 1.

**Comment by StephanSchaller** [comment]
I agree. Needs to be accessibe in PK-Sim

**Comment by msevestre** [comment]
Oh this parameter is already present...lol easy

**Comment by msevestre** [comment]
here we go
![image](https://user-images.githubusercontent.com/1041237/147769922-f1096ceb-7965-40b9-ba80-cd06e4c2d510.png)
