### ISSUE TITLE
How to deal with default for Enzyme/Transporter when name is entered by hand (Without query)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1979]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1975#discussion_r756431305

Before: USer would enter the name in a modal view and from there, we could match the name to existing molecule, ontogeny etc and set some default, even if the data was not read from the protein expression

Now: Everything happens in the modal view

Option 1: We change the flow. ADding a new only show the view where you can select
Enzyme name, phenotype and Species (similar to clojne) . Then you are in the edit view

Option 2: we do not change anything

Option 3 ?

**Comment by Yuri05** [comment]
Option 3. In Create-Dialog the name of the protein is locked and the new Button "Change/Set name" is added.
Thus the name can be changed either when selecting protein from databse (modal) or clicking on the `Set name` button (modal)

**Comment by PavelBal** [comment]
I never liked the option that something (like ontogeny etc) is queried from somewhere even if I do not add a protein from the DB..

**Comment by msevestre** [comment]
Well this is what we do now:
New => We have this dialog (also prefilled with predefined molecule names from the pksim db)
If the user selects one of our predefined name, then ontogenyh and default parameters (half life and ref conc) will be set

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/144086120-de78feb7-9476-4e1c-918c-502ec82b731e.png)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/144086193-71b94c12-b084-47a4-b65a-b2add6d7458d.png)

**Comment by PavelBal** [comment]
I like.

**Comment by Yuri05** [comment]
yep, looks good 👍
