### ISSUE TITLE
Cat Integration. Integration tests failing

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1983]
PKSim.IntegrationTests.When_checking_the_consistency_of_the_database.the_value_for_small_and_large_intestine_volume_should_be_equal_to_the_default_volume
  Small intestine value not equal to default value for 'Cat'
Large intestine value not equal to default value for 'Cat'
  Expected: 0
  But was:  2

**Comment by msevestre** [comment]
see https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim-g4na9/builds/41670285#L2439

**Comment by Yuri05** [comment]
yep, forgotten to adjust the volume(Default) values in intestine. Easy fix. good that we have the test :)
