### ISSUE TITLE
How can I fix that with version 10, please? I have a problem with unit conversion because molecular weight is not available

### ISSUE THREAD

**Issue by sajabzughoul** [Open-Systems-Pharmacology/PK-Sim#1993]
How can I fix that with version 10, please? I have a problem with unit conversion because molecular weight is not available
![Capture](https://user-images.githubusercontent.com/45569077/144062550-308be195-f41f-4538-9499-1535dc9161b5.JPG)

_Originally posted by @sajabzughoul in https://github.com/Open-Systems-Pharmacology/MoBi/issues/241#issuecomment-982671565_

**Comment by msevestre** [comment]
Please ask your question in the forum. 
https://github.com/Open-Systems-Pharmacology/Forum/discussions
