### ISSUE TITLE
Display name (cat, mouse)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#1994]
@Yuri05 On purpose?
![image](https://user-images.githubusercontent.com/1041237/144073484-bc85e48a-6101-4754-b9f0-295ad9726576.png)

**Comment by Yuri05** [comment]
>On purpose?

Yes. "IN development" will be removed once the sufficient validation/qualification of the new species physiology is provided
(➡️ @StephanSchaller @KirstenBoerngen)
