### ISSUE TITLE
Display name and description for Healthy State

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2013]
This is a TODO for the CKD implementation
What should be displayed for the Healthy State

![image](https://user-images.githubusercontent.com/1041237/145457913-cfcce31c-46fb-4842-8ad0-5e166c1a0339.png)

FYI: Only visible when there is another disease state available such as CKD
![image](https://user-images.githubusercontent.com/1041237/145457960-a58197eb-af88-401f-9890-c65560f3a1f0.png)

/cc @JanSchlender @prvmalik

**Comment by Yuri05** [comment]
Display name: "Healthy", Description - empty?

**Comment by prvmalik** [comment]
Perhaps something to the effect of:

"Healthy individuals in PKSim are representative of the general population of individuals in the specified ethnicity and/or geographic area. These individuals are parameterized under the assumption that they have no chronic or comorbid disease states that would have a relevant effect on anatomy, physiology or drug disposition."
