### ISSUE TITLE
CKD Individual: overwriting parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2014]
Currently, in a CKD individual building block all parameters adjusted by the CKD-algorithm can be modified by user (overwritten with a new value). I think:
* For paramaters which are used to calculate GFR (GFR_spec, Volume Kidney, ...) this should not be possible anymore (because the target GFR is an input parameter of a CKD-individual and it does not make sense to overwrite those parameters which in fact would result in the change of the GFR)
* For all other parameters, which are modified by the CKD-algorithm (hematocrit, etc.): those parameters should be editable by user as before.

Thoughts?
@msevestre @JanSchlender @prvmalik

**Comment by prvmalik** [comment]
Hi Yuri,

I think the ideal way to set it up is that when CKD is activated, all parameters affected by CKD are scaled in real-time by the value of GFRspec*VKid*1.73/BSA, whatever that happens to be even after the target GFR is set (real time eGFR). In this sense the individual's target GFR can be changed after the fact and the parameters would update based on formula similar to how specific intestinal permeability or kcat work.

Alternatively if too complex, lock down the GFR I agree.

**Comment by msevestre** [comment]
>In this sense the individual's target GFR can be changed after the fact and the parameters would update based on formula similar to how specific intestinal permeability or kcat work.

No this is not possible. Similar to BMI, Height etc.. those parameters are INPUT and are used to derived all other parameters, update distributions etc.. This cannot be changed after the fact.

**Comment by Yuri05** [comment]
@prvmalik 

>Down the road I can imagine users wanting to mess with gastric emptying time or small intestinal transit time...

I can imagine this as well :)
