### ISSUE TITLE
Population based on CKD Individual: how to deal with parameters overwritten in the individual-BB by user

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2015]
Assuming that it is possible to modify some of the parameters modified by the CKD-CreateIndividual-Algo (#2014): how should we deal with this use case?

In a (healthy) population: if the user changes a parameter in the individual and then creates a population, then this parameter change is propagated to the population. E.g. in the example below: I created a female 30 yo individual with the default hematocrit (0.41), then cloned it and modified the hematocrit to 0.5.  Then created a population based on those individuals (left: hematocrit 0.41, right: hematocrit 0.5). As you can see, the distribution in the population based on the individual with changed hematocrit was shifted for all individuals accordingly (both males and females)
<img width="400" src="https://user-images.githubusercontent.com/25061876/145567225-ac815ae6-d31e-4bc4-9f36-3d4cb51fc210.png"> <img width="400" src="https://user-images.githubusercontent.com/25061876/145567280-02bb9a81-fde7-4a5c-b4d9-f93566480c68.png">

The CKD population creation algo creates a healthy population first and then applies the "CKD adjustments" to each individual of the healthy population. E.g. it scales the hematocrit of each individual with a factor.

Question: **should we propagate the changes of the CKD adjusted parameters from the base individual in the same way as we do for the healthy population?** 
In the example above it would mean: **hematocrit of each individual is scaled twice**
* first with a factor due to the propagation of the parameter change in the base individual
* and then with a "CKD-factor"

Or should we ignore user changes of CKD-adjusted parameters in the base individual?

Thoughts?
@msevestre @JanSchlender @prvmalik

**Comment by prvmalik** [comment]
A CKD individual should not be allowed to be a base individual for a healthy population. It should only be accepted for a CKD population, where the target GFR range is pre-specified.

My recommendation is to lock down parameters affected by the CKD algorithm in the individual building block. GFRspec would still be modifiable in the individual block if the GFR was wished to be changed - this makes it so the user would not have to make a whole new individual if they wanted to adjust the eGFR and resulting parameters slightly. But for the population, the GFR range should be/will be pre-selected so this is not a problem of propagation.

The exception being fraction unbound/plasma protein scale factor. Any changes in an individual block there should be propagated to a population. There could even be a check box to unlock it saying something like "use observed value in CKD" or something to that effect.

**Comment by msevestre** [comment]
>A CKD individual should not be allowed to be a base individual for a healthy population. It should only be accepted for a CKD population, where the target GFR range is pre-specified.

This is the case.

as far as protein scale factor goes. 

I would not add any more logic with check box etc...this would break encapsulation also. We want to make sure the UI behavior is disease independent otherwise we are in for a lot of pain when adding more diesease stuff.  What we can do is: if the value was changed from default, we take this value otherwise we use the algorithm. ?

**Comment by msevestre** [comment]
This will be solved automatically when we lock parameter in #2014 

What remains to decide is what parameters should we lock in individual
#2014 suggests GFR_spec and v_kid.  Is that all?
