### ISSUE TITLE
Many default observers such as fraction excreted in urine and in feces are missing 

### ISSUE THREAD

**Issue by Sulav1** [Open-Systems-Pharmacology/PK-Sim#2024]
I created a new project in PKSIM 10 for a compound. However, many default observers were missing such as fraction excreted in urine and feces. These observers used to be available in PKSIM 9. Seems to be a bug in PKSIM 10.

**Comment by msevestre** [comment]
@Sulav1 Can you attach a project so that we can reproduce? Thanks

**Comment by msevestre** [comment]
@Sulav1 
I just create a brand new project in v10
![image](https://user-images.githubusercontent.com/1041237/148215598-92c416d2-02aa-4e59-b31a-d1f1bdbb49dd.png)

I can find all fraction excreted as expected. Please explain how to reproduce the issue. Thanks for your feedback

**Comment by Sulav1** [comment]
@msevestre I also checked with a new project and it worked. However, for the project which I was working on, it did not. It seems to be specific to the project. I will clean that project and post the model file soon.

**Comment by msevestre** [comment]
Ok thanks @Sulav1

**Comment by msevestre** [comment]
@Sulav1 I will close this. Please reopen with a project so that we can reproduce. Thanks
