### ISSUE TITLE
CKD population: default eGFR value invalid

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2028]
Create ICRP individual with all values set to default and switch disease state from healthy to CKD:
the default value of eGFR is marked is invalid (however even according to the tooltip it should be valid?)
![grafik](https://user-images.githubusercontent.com/25061876/148237549-0749957a-3c88-4fd2-936b-717fde479b8c.png)

**Comment by msevestre** [comment]
Your dimension file is messed up. Don't forget to update to the latest submodule
