### ISSUE TITLE
PK-Sim 11: Protein expression DB query empty

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2029]
Create CYP3A4 Human protein and click on DB query: 2 entries for CYP3A4 are correctly shown in the first step
![grafik](https://user-images.githubusercontent.com/25061876/148238462-649a2982-3461-435c-a4d3-4313b323a2e5.png)

However when selecting one of them (e.g. CYP3A4) - no values are retrieved:
![grafik](https://user-images.githubusercontent.com/25061876/148238635-681e3a0f-4803-4e06-9223-a8daccacb5f5.png)

**Comment by msevestre** [comment]
And that works in v10!??

**Comment by Yuri05** [comment]
yes :)

**Comment by msevestre** [comment]
Ok I am wondering if this is since the devexpress upate....Going to investigate this

**Comment by msevestre** [comment]
@Yuri05 I have no idea how to fix this.... the binding with pivot grid between chart and the datagrid is not wokring anymore. Do you know how this work? I think this is a  devexpress change.

**Comment by msevestre** [comment]
@Yuri05 Is there any chance you get the code here running
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1995/commits/cfab1a5767abb22671d673aab1d77db22a28c426

This is before the devexpress update. I do not have the old version on my laptop so I don't think I can

**Comment by Yuri05** [comment]
>Is there any chance you get the code here running

Yep, that commit worked.
<details><summary><b> Screenshot</b></summary>
<img src="https://user-images.githubusercontent.com/25061876/149764852-17ed4f6a-971f-422f-8f5e-f6969fb0dc5c.png">
</details>

>Do you know how this work? I think this is a devexpress change.

Not in detail. Might be a DevExpress change indeed. Checked what changed in DevExpress PivotGrid since 20.1.3 - don't see a reason. Guess we need to ask Devexpress for the hint. Alternatively we could dongrade DevExpress back to the previous version.
[DevExpress_PivotGridChanges_since_20.1.3.docx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7881671/DevExpress_PivotGridChanges_since_20.1.3.docx)

**Comment by msevestre** [comment]
I sent a request to devexpress for some help...

**Comment by msevestre** [comment]
If I comment out the line with the custom summary function, I get a chart

**Comment by msevestre** [comment]
v11
![image](https://user-images.githubusercontent.com/1041237/149776869-2b168e60-618d-4dc3-8fc3-e5c7c73c3745.png)

v10
![image](https://user-images.githubusercontent.com/1041237/149776915-993bce1c-9de0-497e-8a34-d1c31bf6306a.png)

Why do we need this custom summary function?!?

**Comment by Yuri05** [comment]
Because of the mapping between GeneDB-Tissue and PK-Sim containers. Sometimes several DB-Tissues are mapped onto the same PK-Sim container. 
E.g. compare the values for LArge Intestine for RT-PCR: without summary they should differ from V10

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/149778155-fba2c114-a7cd-4594-ba1d-359ab6613f3e.png)
Wrong try. DO you have another?

**Comment by Yuri05** [comment]
>Wrong try. DO you have another?

Duodenum
