### ISSUE TITLE
Body Surface Area based dosing

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#203]
Dose is often Scale to BSA instead of Body weight. A frequent request is therefore to use BSA as individual parameters for analysis in Populationsimulations. BSA can be Calculated according to different formulas. The two most common calculations methods should be available:
```
https://en.wikipedia.org/wiki/Body_surface_area
Mosteller-Formula: https://de.wikipedia.org/wiki/Mosteller-Formel
DuBois-Formula: https://de.wikipedia.org/wiki/DuBois-Formel
```

to be Implement as: 
BSA (Mosteller)
BSA (DuBois)

We could implement other BSA methods if requested

**Comment by msevestre** [comment]
Dose is often Scale to BSA instead of Body weight. A frequent request is therefore to use BSA as individual parameters for analysis in Populationsimulations. BSA can be Calculated according to different formulas. The two most common calculationsmethods should be available:
- Mosteller-Formel: https://de.wikipedia.org/wiki/Mosteller-Formel
- DuBois-Formel: https://de.wikipedia.org/wiki/DuBois-Formel

to be Implement as: BSA (Mosteller) and
BSA (DuBois)

**Comment by msevestre** [comment]
@Yuri05  What about the flag `CanBeVaried` and `CanBeVariedInPopulation`. True or false?

**Comment by Yuri05** [comment]
>What about the flag CanBeVaried and CanBeVariedInPopulation. True or false?

Both true

**Comment by msevestre** [comment]
I am actually not sure about CanBeVariedInPopulation = true. BMI cannot be varied in population and is a factor of height and weight, exactly as BSA...

**Comment by msevestre** [comment]
@Yuri05 Well actually a parameter cannot be IsChangedByCreateIndividual and CanBeVariedInPopulation
In order to get the BSA displayed in the Distribution, it needs to be set to IsChangedByCreatedIndiviudal. It does not really make sense to be honest to generate a distribution for BSA that is independent from BW and Height. Going to also go ahead and set  `CanBeVariedInPopulation` to false

**Comment by Yuri05** [comment]
OK, thought you were talking about _DosePerBsa_.
BSA should have `CanBeVariedInPopulation = false`

**Comment by msevestre** [comment]
DosePerBSA CanBeVariedInPopulation =true ?? neither DosePerBW nor Dose are CanBeVariedInPopulation so I think this should also not be the case

**Comment by Yuri05** [comment]
>DosePerBSA CanBeVariedInPopulation =true ?? neither DosePerBW nor Dose are CanBeVariedInPopulation so I think this should also not be the case

OK, agree
