### ISSUE TITLE
eGFR: unit is missing

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2030]
in the create individual dialog as well as in the parameters view: eGFR unit is not displayed
![grafik](https://user-images.githubusercontent.com/25061876/148241212-8dcfb54b-cc9e-4a69-910b-00141aeb0509.png)
![grafik](https://user-images.githubusercontent.com/25061876/148241445-02bd8d70-f831-4856-a5f6-b466199365a2.png)

**Comment by msevestre** [comment]
Same as the other one. Are you using the setup? If yes it's a bug. If it's local, update your dimension submodule
