### ISSUE TITLE
Protein expression: "Blood cells" expression is not properly set

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2039]
Add expression of the enzyme "AADAC" from the database.

V9:

![image](https://user-images.githubusercontent.com/25903040/148965891-702b252e-51ca-4d67-ade4-42ca33a76a52.png)

V10:

![image](https://user-images.githubusercontent.com/25903040/148965980-a02619e9-f3bf-43f2-8f31-5e5e9fd93069.png)

Expression in blood cells is not set.

**Comment by msevestre** [comment]
Interesting. We did not foresee for this values to be updated from the DB (e.g "Localization")
What should be the logic here? If a value is coming != 0, we need to activate some localization? 
Do we have something else than Blood cells?

**Comment by PavelBal** [comment]
> What should be the logic here? If a value is coming != 0, we need to activate some localization?

Yes

> Do we have something else than Blood cells?

Could be vascular endothelium.

**Comment by msevestre** [comment]
We are going to need to specify this. What localization should be turned on automatically based on what parameter values

**Comment by PavelBal** [comment]
If the value for blood cells != 0:
   - If default localization is "Intracellular" -> enable "Blood cells intracellular"
![image](https://user-images.githubusercontent.com/25903040/149299235-6dd6dac6-b896-4982-a837-1731df3811ce.png)
- If default localization is "Interstitial" -> enable "Blood cells membrane"
![image](https://user-images.githubusercontent.com/25903040/149299347-f5610ba3-755c-4638-a748-725cc71c9460.png)

If the value for "Vascular endothelium" != 0:
  - If default localization in PK-Sim9 is "Endosomal" -> enable "Vascular endothelium endosomes"
  - If default localization in PK-Sim9 is "Interstitial" -> enable "Vascular endothelium membrane plasma-side"
  - If default localization in PK-Sim9 is "Extracellular membrane + basolateral" -> enable "Vascular endothelium membrane tissue-side"
  - If default localization in PK-Sim9 is "Extracellular membrane + apical" -> enable "Vascular endothelium membrane plasma-side"


I guess this covers all cases... Or what localization information do we actually have in the DB?

**Comment by msevestre** [comment]
There is none localization info in the db. Only expression values.
So the question should be more: what localization should we turn in automatically based on expression values received from db. This happens only upon enzyme creation/update I guess

**Comment by Yuri05** [comment]
>If default localization is "Interstitial" -> enable "Blood cells membrane"

That's not correct.
* "Interstitial" ➡️ "Blood cells intracellular"
* "Extracellular Membrane" ➡️ "Blood cells membrane"
* "Intracellular" ➡️ "Blood cells intracellular"

**Comment by Yuri05** [comment]
>If default localization in PK-Sim9 is "Interstitial" -> enable "Vascular endothelium membrane plasma-side"

Also not correct. must be "Vascular endothelium membrane tissue-side"

**Comment by msevestre** [comment]
But we have no concept of localization in the protein expression db. We only have expression values....booo

**Comment by Yuri05** [comment]
Ah, ok, finaly I got what this issue is about (thought it was about project conversion V9=>V10 due to the discussion above).

Yep, we don't have localization in the protein expression DB. So from my point of view:
* if relExp in Blood Cells returned by the DB query is not zero: "**Blood cells intracellular**" checkbox must be activated
* if relExp in Vascular Ensothelium returned by by the DB query is not zero: "**Vascular endothelium endosomes**" checkbox must be activated
