### ISSUE TITLE
Exception when optimizing relative expression and transferring to simulation 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#204]
Optimization of relative expression currently only works for "relative expression (normalized)". This is all fine. However, a bug occurs if you click on" transfer to simulation": this is not possible and an exception is thrown.

**Comment by rwmcintosh** [comment]
@sfrechen Can you give some steps to reproduce or a sample project?
(This was an issue originally reported by you, but entered by @msevestre)

**Comment by msevestre** [comment]
@sfrechen, @Yuri05 
Please feedback. We won't be able to fix this issue if we cannot reproduce and do not understand it

**Comment by sfrechen** [comment]
Create a simple PI for an individual expressing an enzyme and estimate one of the "relative expression (normalized)" parameters for an organ of your choice. Then press on transfer to simulations...

**Comment by msevestre** [comment]
@sfrechen As you can imagine, we have tried exactly that and it worked. :)
So please attach a test project if possible and describe exactly what we need to do in order to reproduce the exception

**Comment by sfrechen** [comment]
:-)

Just tried it. Yes, there is no exception thrown anymore. :)
However, the fitted value is not shown in the simulation parameters.
The individual in the simulations is marked with a red sign, however, differences to the building block individual are also not found.

**Comment by msevestre** [comment]
Which parameter (exact location as it worked for me with a param in muscle)
did you try to optimize? Could you attach an example project to reproduce?

**Comment by sfrechen** [comment]
Would need to create a new one as mine are confidential. Could you share yours and let me have a look?

**Comment by msevestre** [comment]
Mine is with 7.2 and won't work with your version
