### ISSUE TITLE
Remove example projects from Setup / Replace with the link to the latest release of PBPK-Model-Library

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2041]
Substance models released as "example projects" with PK-Sim are outdated and not yet part of the (qualified) PBPK library.
<img width="500" src="https://user-images.githubusercontent.com/25061876/148987629-5772c24f-9d5e-42cd-9cc7-a5fa6e47253f.png">

I would suggest:
* remove example projects from the setup completely 
* install with the setup just a small README file (under **C:\ProgramData\Open Systems Pharmacology\PK-Sim\X.Y\Examples** ), explaining that examples can be found under https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/releases/latest )

@msevestre @sfrechen @JanSchlender @StephanSchaller

**Comment by StephanSchaller** [comment]
Fine with me. Won't V11 allow loading template models from GitHub anyway, making this obsolete?

**Comment by msevestre** [comment]
Those are full examples with obs data etc...
V11 only supports building blocks

**Comment by StephanSchaller** [comment]
@PavelBal

**Comment by msevestre** [comment]
@Yuri05 Can you install latest setup on vmware and see if this works as expected? Please reopen if not

**Comment by Yuri05** [comment]
@msevestre 
setup is working as expected. But I would suggest to rename the Readme.md to Readme.txt - otherwise on a system without installed MD-Editor it looks like below:

![grafik](https://user-images.githubusercontent.com/25061876/149623464-201bfdd6-84fe-4f48-a7e5-9b9de9c4ac0a.png)

**Comment by msevestre** [comment]
yeah good point
