### ISSUE TITLE
Remove predefined compound templates from Setup?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2042]
@Yuri05 Now that we have the remote template, should we remove them from the admin db?
![image](https://user-images.githubusercontent.com/1041237/149181507-0783791c-49fc-40ff-9e63-e370507bfae7.png)

**Comment by msevestre** [comment]
At least the one that are duplicated?

**Comment by Yuri05** [comment]
>At least the one that are duplicated? 

That's for sure.

**Comment by msevestre** [comment]
HEre are the one left...what do we do with them?
![image](https://user-images.githubusercontent.com/1041237/149317962-32d89f8d-49da-40de-b57e-e1a50b0448c0.png)

**Comment by Yuri05** [comment]
Delete them.
Some of the models (e.g. Paracetamol) are in redevelopment and we will get the updated state in the future - the current state is outdated.

**Comment by msevestre** [comment]
@Yuri05 We also have 
![image](https://user-images.githubusercontent.com/1041237/149343571-9fe6ab7b-6969-4093-93fc-4d7aed02590b.png)

![image](https://user-images.githubusercontent.com/1041237/149343624-6a29d31a-cac4-45c5-bcb5-319f3d06cfb7.png)

![image](https://user-images.githubusercontent.com/1041237/149343679-7996738e-e767-4ef9-81a4-8eebd3f665aa.png)


Should we remove any of those?

**Comment by msevestre** [comment]
ok letting those guys for now
