### ISSUE TITLE
Default values for Fraction Expressed in Blood Cells and in Endosome not as expected

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2053]
At the moment, the default values of `Fraction expressed in blood cells` and `Fraction expressed in endosomes` parameters are **zero**:
![grafik](https://user-images.githubusercontent.com/25061876/149661449-f583095e-246e-4699-9a6f-f0b90ecfe6ff.png)

I think, both values should be **one** as per default (the expected default localization when setting a relExp value for blood cells is inside blood cells and expected default localization when adding a vasular endo relExp is inside endosomes).

But changing this would require snapshot conversion.
To be discussed.

**Comment by Yuri05** [comment]
@msevestre @PavelBal @sfrechen

**Comment by PavelBal** [comment]
Well, one of the fractions should be 1, so I think your proposal makes sense.

**Comment by Yuri05** [comment]
One of the fractions is 1 per construction, because it's defined as `1 - another fraction` (for BC) or `1 - sum of another fractions` (for vasc endo).
The point is: it's not the fraction you would assume to be set 1 **as per default**. Thus if you e.g. just set `relExpBC>0`: this amount will be placed in **plasma** as per default - unless you explicitely set **Fraction expressed in blood cells** to 1. 
If we [set **Fraction expressed in blood cells** to 1 and **Fraction expressed in endosome** to 1 when importing from GeneDB](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2039#issuecomment-1013754572) - everything will be fine in PK-Sim.
However if setting relExp_BC or relExp_VascEndo in MoBi or via the R-Toolbox: the user would need to know that the corresponding fraction expressed must be set as well.

**Comment by msevestre** [comment]
But the same is to be said if we had rel_exp plasma coming from the DB? Somehow the default only makes sense in some cases

**Comment by Yuri05** [comment]
well, relExpPlasma is always placed in plasma, so we don't have any fractions expressed here..

**Comment by msevestre** [comment]
We are already doing a project conversion for expression profile so we might as well change whatever should be changed

**Comment by StephanSchaller** [comment]
I don't get it yet. Is this a V9 vs V10 issue or a general issue?

Will chat with Pavel on this later.

**Comment by msevestre** [comment]
This is a v10 issue and not of an issue but more of a way of seeing things :)
@Yuri05 I don't think we need project conversion:
1: As soon as a value is clicked (Either BC_membrane or BC_intracellular) the underlying parameter is set automatically and appears to not have been set by the user (is_default = true)

So the json look like so
```
{
  "Type": "Enzyme",
  "Species": "Human",
  "Molecule": "CYP",
  "Category": "toto",
  "Localization": "Intracellular, BloodCellsIntracellular"
}
```
or 
```
{
  "Type": "Enzyme",
  "Species": "Human",
  "Molecule": "CYP",
  "Category": "toto",
  "Localization": "Intracellular, BloodCellsMembrane"
}
```

The only issue would be when a user select BOTH locations (InBloodCells). In that case the default value of the fraction remains unchanged but this is very unlikely since the user should overwrite the value with its own ratio. In this case, the value is saved as used defined parameter

So I don't think we need project conversion but I think it make sense to set the default value as you said to one

**Comment by msevestre** [comment]
An interesting little side effects: The default value of the fraction depends on what is being clicked. I think this is fine 
1: Membrane first and then intracellular
![image](https://user-images.githubusercontent.com/1041237/149938959-eae04621-9b73-481d-8158-6ebf1bacd5fc.png)

2: Intracellular first and then Membrane
![image](https://user-images.githubusercontent.com/1041237/149939444-4b3b378a-1763-4d6d-9682-785c52fb28b0.png)

**Comment by Yuri05** [comment]
The "side effect" is OK for me. If the user selects both, then the fraction expressed value between 0 and 1 must be entered manually anyway. Ofc PK-Sim could e.g. set Fraction expressed to e.g. to 0.5 in this case, but this does not make much sense.
