### ISSUE TITLE
Edit Database Query does not display "old" values correctly?

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#2055]
The Edit Database Query does not show the "old" expression values as normalized relative expression if there are absolute Values >1?
For the "P-gp modified" expression, we have small intestine at 1.41, mit data Edit Database Query does not normalize all other values for the plotted bars with 1.41 but only truncates the 1.41 bars at 1 (i.e. 100%)? Compare here the relative difference between the large and small intestine bars in the BB and the Edit query:
![image](https://user-images.githubusercontent.com/25477643/149735247-5a462bf8-ee0a-4ddb-8693-3a26cff87fb6.png)

Not sure how this is in V10 but may be worthwhile to check.

**Comment by msevestre** [comment]
The proteing expression query does not normalized I believe. Normalization is done in PKSim
so the bug seeems to be that 141 and 100 (or any value >=100) are displayed with the same FULL Bar? Am I correct?
Or am I missing something?

**Comment by StephanSchaller** [comment]
> so the bug seeems to be that 141 and 100 (or any value >=100) are displayed with the same FULL Bar? Am I correct?

Yes, so it seems that everything >100 is shown (or handled) as 100

**Comment by msevestre** [comment]
shown and handled is different
For me it looks like it's just a display bug (Bar is full, progress bar does not make sense with value >100 anyways)
Or do you suspect that values are also wrong? This is what I am trying to understand

**Comment by StephanSchaller** [comment]
> Or do you suspect that values are also wrong? This is what I am trying to understand

Well, not the values, but the corresponding bars are wrong. 
For the "old" expression values in the left column of the Edit Database Query, the bars do not match the values. 
That's why I marked in red where this becomes obvious. 
So the right marking which shows the bars in the background as they are displayed in PK-Sim (here the bars are correct, i.e. have the correct relative difference) vs the bars of the "old" expression values in the left column of the Edit Database Query which should be identical but are not.
The "141.00" bars are "too short" (or rather, all the others are too long. The length of the bars for "56.00" should be less than half of the length of the "141.00" bar.

I hope it is clearer now :-D

**Comment by msevestre** [comment]
How can I reproduce? I don't have those values with pgp ?
I need to know what molecule to select

P-gp modified does not exist in my DB

**Comment by msevestre** [comment]
@StephanSchaller ping

**Comment by StephanSchaller** [comment]
Well, I guess you could use the [digoxin template PBPK model](https://github.com/Open-Systems-Pharmacology/Digoxin-Model/blob/master/Digoxin-Model.pksim5) and then select the P-gp (ABCB1) expression in the individual and, right-click --> edit query:
![image](https://user-images.githubusercontent.com/25477643/150797693-4d7d7bd9-94c0-4766-a330-ff9fa3a87ba8.png)

**Comment by msevestre** [comment]
@StephanSchaller @Yuri05 Do we agree that the value should also be displayed like they are in PKSim after wards (e.g. between 0 and 1) and not between 1 and 100
It took me a while (like a lot of time) but I a managed to understand how the code is working. Fix to come soon

**Comment by Yuri05** [comment]
>Do we agree that the value should also be displayed like they are in PKSim after wards (e.g. between 0 and 1) and not between 1 and 100

As long as old values and new values are displayed on the same scale (either both 0..1 or both 0..100) - fine for me

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/153209233-18e3b158-495d-4da8-8917-3b5bb2a9c649.png)


well a value can be over 1 now. But at least it is the same here and in PKSim
