### ISSUE TITLE
Explanation for Phenotype?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2059]
I am sure people won't understand what's required here.
Should we give an example or add some text explaining ?
![image](https://user-images.githubusercontent.com/1041237/149915546-753d3378-6320-476d-ba08-114afdcd128e.png)

@StephanSchaller @PavelBal @Yuri05

**Comment by Yuri05** [comment]
Metabolizing enzyme is clear I guess, so we would need an explanation only for the phenotype.
By the way: should we prepopulate the Phenotype with some common values as well ("Healthy", "Low metabolizer", whatever)?

**Comment by PavelBal** [comment]
I had to think hard to understand what is required here :D

How about just "Profile name"? With a hint "Name of this specific expression profile. You can define multiple expression profiles for the same protein". The different profiles must not represent only different phenotypes, it could also be e.g. profiles from different sources (e.g. one from RT-PCR, one EST, one "manual").

**Comment by msevestre** [comment]
Ok so we rename phenotype to sthg else? Phenotype was a  proposal from @StephanSchaller but I agree that this might be confusing
It's not really the Profle Name.... Since the name is composed of Species, Molecule and "Category"

**Comment by Yuri05** [comment]
>It's not really the Profle Name

"Description"? 
"Category"? 
"Categorization"?

**Comment by PavelBal** [comment]
Category, subtype..

**Comment by StephanSchaller** [comment]
What is this entry good for. Only as info, or does it have any functional purpose (e.g. as "metabolizing enzyme")?
Call it "Tag" if it is only for info?

**Comment by sfrechen** [comment]
Phenotype is a very general description of waht is exactly needed here and would probably have fit the purpose. If that really confusion (why?), then I would prefer Pavel's suggestion "Profile name".

**Comment by PavelBal** [comment]
I actually also like "Phenotype", it is the matter of proper tooltip to make sure user knows what to enter. E.g.

"Enter a unique name for the expression of this protein. Multiple expression profiles of the same protein are allowed to describe different phenotypes or disease states".

**Comment by msevestre** [comment]
Phenotype it is then.

**Comment by msevestre** [comment]
here we go
![image](https://user-images.githubusercontent.com/1041237/155309808-a84ed5ca-67ab-4e92-9e8f-96cb0e27ee82.png)
