### ISSUE TITLE
Adding different sheets requires same column names 

### ISSUE THREAD

**Issue by CDemeester** [Open-Systems-Pharmacology/PK-Sim#2069]
When importing different sheets from a data file the column names from only the first sheet are shown/selectable. So when you have different column names in another sheets, you can not import them simultaneously. 
![image](https://user-images.githubusercontent.com/96244316/150748848-d2b37bfb-0d5f-4838-9ca6-4d8a29de3a7a.png)

**Comment by msevestre** [comment]
There is now an option to reset the mapping based on the selected sheet. available in upcoming v11
