### ISSUE TITLE
Layout issue with 4k

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2072]
/cc @PavelBal

**Comment by msevestre** [comment]
Pavel: Can you try this
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/builds/42401259/artifacts

**Comment by PavelBal** [comment]
Looks good on the screen where I start it, but a bit blurry when I bring it to another screen with a different resolution. But at least all the elements are scaled properly.

**Comment by PavelBal** [comment]
Some things are still very off...

Start up overlay: 
![image](https://user-images.githubusercontent.com/25903040/151957317-fe093ddc-6ad7-40ba-8c57-0b433f0953e3.png)

Data importer:
![image](https://user-images.githubusercontent.com/25903040/151957434-e103dedb-0949-4f93-8440-b90bfcea6041.png)

Close/minimize/enlarge buttons are really  small
![image](https://user-images.githubusercontent.com/25903040/151957566-e8678d47-81a2-4523-ae4b-c6a1306a3e24.png)

**Comment by msevestre** [comment]
And you don't have this behaviour in the importer with Mobi?

**Comment by PavelBal** [comment]
MoBi (11) just looks great

![image](https://user-images.githubusercontent.com/25903040/151963968-852d7699-3211-4bbb-a970-95b55d9f0afc.png)

**Comment by msevestre** [comment]
Interestng. I realize that MoBi does not use this settings ...but it should. I think our buttons size needs to grow also with the resolution....some more work to be done 
as for the X button...I am not sure what can be done here...we do not even create those

**Comment by PavelBal** [comment]
Screen resolution 3840x2160, scaling 200%.

- Expression Profile -> Add metabolizing enzyme:

![image](https://user-images.githubusercontent.com/25903040/157467441-d23f5bbb-a523-4dd3-b276-19825894a153.png)


Create Individual:

![image](https://user-images.githubusercontent.com/25903040/157467523-805a29a0-40e7-4120-932c-09bce727ab0f.png)

**Comment by msevestre** [comment]
@PavelBal Can you try with the latest nightly 
https://ci.appveyor.com/account/open-systems-pharmacology-ci/projects

Hopefully most of this is fixed

**Comment by PavelBal** [comment]
@msevestre Looks much better now.

Some buttons are still too slow:

Create Individual -> Add Metabolizing Enzyme:
![image](https://user-images.githubusercontent.com/25903040/158987948-d9d373fb-21be-475b-9cdb-cce9a82b1995.png)


Create Individual: value origin drop-down too slim

![image](https://user-images.githubusercontent.com/25903040/158988408-02561a10-3367-48d7-a375-ad8bf6b89b36.png)

Also in create Population, the drop-down looks odd:

![image](https://user-images.githubusercontent.com/25903040/158988510-c258739f-39f3-43dd-88c5-9fa89c27b9ff.png)


I think it is a general problem of the drop-down menus.

**Comment by msevestre** [comment]
>I think it is a general problem of the drop-down menus.

No. I need to remove most places where size is defined statically.

**Comment by msevestre** [comment]
Fixiing this now. Please reopen if there are more issues
