### ISSUE TITLE
PKSIm.CLI => Do not generate outputs ofr simulation not used (support argument)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2081]

**Comment by msevestre** [comment]
@Yuri05 We are also exporting the snapshot file and the project. This definitely takes some times for nothing. Do we need this?

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.CLI.Core/Services/QualificationRunner.cs#L127

and 
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.CLI.Core/Services/QualificationRunner.cs#L131

**Comment by Yuri05** [comment]
>We are also exporting the snapshot file and the project. This definitely takes some times for nothing. Do we need this? 

I would keep this. Both might be helpful for debugging (changes due to BB-inheritance etc.), and projects I use quite often e.g. when creating a new release of Evaluation-Report+Project for PBPK-model-library.

**Comment by msevestre** [comment]
ok but this should be off by default don't you think?

**Comment by Yuri05** [comment]
>this should be off by default don't you think?

ok. https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2082/files#r797557125
