### ISSUE TITLE
The mass balance issue in whole-body PBPK due to the use of blood reservoirs

### ISSUE THREAD

**Issue by intrinsicclearance** [Open-Systems-Pharmacology/PK-Sim#2086]
A recent paper discussed the use of blood reservoirs in full PBPK causing the breaking of the mass balance principle.
Section #5 of A myth of the well-stirred model: Is the well-stirred model good for high clearance drugs?
https://doi.org/10.1016/j.ejps.2022.106134

**Comment by msevestre** [comment]
duplicates https://github.com/Open-Systems-Pharmacology/Forum/discussions/1112
