### ISSUE TITLE
Update SplashScreeen

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2087]
Thoughts:
@Yuri05 @PavelBal @StephanSchaller 
![image](https://user-images.githubusercontent.com/1041237/152509371-0df8cc31-7c8f-440a-99ff-94c2a4e47273.png)

**Comment by PavelBal** [comment]
Nice, I like.

And maybe add an option "Show splash screen on loading" in the option menu?

**Comment by msevestre** [comment]
No this is shown before we load the option. But it won't be on top anymore so you can safely move documents ocer

**Comment by Yuri05** [comment]
Very nice!
