### ISSUE TITLE
PK-Sim 11: DLL missing in setup?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2095]
Trying to initialize ospsuite-R version 11 with PK-Sim portable 11.0.72 results in the error message 
`"BouncyCastle.Crypto, Version=1.8.9.0, Culture=neutral, PublicKeyToken=0e99375e54769942" or one of its dependencies not found.`

```
> initPKSim(pksimFolderPath = "C:/PK-Sim_11.0.72")
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.Reflection.ReflectionTypeLoadException
Message: Mindestens ein Typ in der Assembly kann nicht geladen werden. Rufen Sie die LoaderExceptions-Eigenschaft ab, wenn Sie weitere Informationen benötigen.
Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
Stack trace:
   bei System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   bei System.Reflection.Assembly.GetTypes()
   bei Rclr.ClrFacade.GetType(String typename)
   bei Rclr.ClrFacade.CallStaticMethod(String typename, String methodName, Object[] arguments)

Type:    System.IO.FileNotFoundException
Message: Die Datei oder Assembly "BouncyCastle.Crypto, Version=1.8.9.0, Culture=neutral, PublicKeyToken=0e99375e54769942" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
Method:  
Stack trace:
```

**Comment by msevestre** [comment]
but it works when doing it via the PKSim install somehow.... and even from the package. I just tried.
I am so confused!

**Comment by msevestre** [comment]
The minor updatre from NPOI moves the dep from 1.8.6 to 1.8.9
[Portable.BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle/) (>= 1.8.6)
WTF

this file is in the setup
![image](https://user-images.githubusercontent.com/1041237/153419193-de239df4-4f1a-473b-b331-ea0b26cf8d12.png)

but 1.8.9.0 is trying to be loaded...WHY

**Comment by msevestre** [comment]
this is 1.8.9.1

**Comment by msevestre** [comment]
@georgeDaskalakis Was the update to NPOI required for a bug fix?

**Comment by msevestre** [comment]
can you try with 11.0.74

**Comment by msevestre** [comment]
and I am using
![image](https://user-images.githubusercontent.com/1041237/153442200-1562399d-2210-433c-ae6a-7a3f0cb67573.png)
of ospsuite-r

**Comment by msevestre** [comment]
and even moire confusing~

> library(ospsuite)
Loading required package: rClr
Loading the dynamic library for Microsoft .NET runtime...
Loaded Common Language Runtime version 4.0.30319.42000

> initPKSim("C:/dev/Releases/v11/PK-Sim 11.0.74")
Initializing PK-Sim 11.0.74
> setwd("c:/dev/ospsuite-r/tests")
> source('testthat.R')
Warning - Could not find quantity with path 'Organism|Liver|NOPE|Volume'.                                                                       
**[ FAIL 0 | WARN 3 | SKIP 0 | PASS 1009 ]**                                                                                                        
>

**Comment by Yuri05** [comment]
ok, restarted R and tried with PK-Sim 11.0.74 - worked!
But then: restarted R and tried again with PK-Sim 11.0.72 - worked as well. 
Hmm...

**Comment by Yuri05** [comment]
Finally: if I execute all the testthat unit-tests and AFTER that call **initPKSim**: it fails (both with 11.0.72 and 11.0.74).

**Comment by msevestre** [comment]
Can't reproduce. I'll close for now
