### ISSUE TITLE
newly created blood organ - how to add V and WT in MOBI

### ISSUE THREAD

**Issue by HLyster** [Open-Systems-Pharmacology/PK-Sim#2107]
I have created an extra compartment (blood organ) in MOBI - but cant get the V and WT parameters to be added to the body weight and plasma volume, any help appreciated

**Comment by StephanSchaller** [comment]
Hi @HLyster , how did you structure the new organ and what exact names did you give parameters V and WT?

But it would be easiest to resolve if we had a look at the model, if possible.

Best,
Stephan

**Comment by HLyster** [comment]
Hi @Stephan ***@***.***>

Find attached – the mobi model file– let me know if would be able to discuss via teams/zoom?

Many thanks
Haifa

Haifa Lyster FRPharmS, FFRPS
Consultant Pharmacist - Transplantation & VADs
Pharmacy Directorate Research Lead

Tel: +441895 823737 ext 85087
mobile: +447850592073
___________________________________________________
Royal Brompton & Harefield Hospitals
Part of Guy's and St Thomas' NHS Foundation Trust


***@***.***

**Comment by msevestre** [comment]
Question should be asked in the forum. Closing for now

**Comment by HLyster** [comment]
I have asked in the forum too?

**Comment by msevestre** [comment]
well in that case :) perfect

**Comment by HLyster** [comment]
Great - then can you help me?
I have created an extra compartment (cloning blood organ) in MOBI - but cant get the V and WT parameters to be added to the body weight and plasma volume, any help appreciated

**Comment by msevestre** [comment]
I do not see your question in the forum
https://github.com/Open-Systems-Pharmacology/Forum
