### ISSUE TITLE
Protein Expression: Negative "fraction expressed"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2111]
I did not thoroughly check the use-cases, but it is possible to have negative "fraction expressed" (V10):

![image](https://user-images.githubusercontent.com/25903040/157428222-c158e977-e630-4daf-8b2d-c7a00f0ae1b1.png)

**Comment by PavelBal** [comment]
I think it is only for the vascular endothelium.

**Comment by Yuri05** [comment]
possible because of the 3-sum. However in such a case you should get error when creating or when running a simulation.
Did you try this?

**Comment by PavelBal** [comment]
Simulation can be created and run :D

![image](https://user-images.githubusercontent.com/25903040/157435811-8a83cb11-22e8-4bac-a410-635ca233d89d.png)

**Comment by Yuri05** [comment]
ok, seems the bounds for fraction expressed vasc endo/tissue and for the initial concentration are not properly set in the PK-Sim database

**Comment by msevestre** [comment]
I'd suggest to simply fix the min max in the DB instead of trying to fix the UI

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/160439584-02304363-ece0-4ab7-bff7-9ba81c3e73c0.png)

Cannot reproduce with the latest changes in the DB. closing
