### ISSUE TITLE
Define VolumePlasma as SumFormula

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2118]
see https://github.com/Open-Systems-Pharmacology/Forum/discussions/1174#discussioncomment-2371523

@Yuri05 Do you know why it's still a hard coded formula?
How could we defined it dynamically? Using Plasma as a tag I guess? Thoughts?

**Comment by PavelBal** [comment]
Yes, I was surprised that it is still a hard-coded sum.

I have implemented this in my models with the following criteria:

![image](https://user-images.githubusercontent.com/25903040/158612086-0cebb046-0d1f-4948-998f-8f14b5cd1c85.png)

**Comment by msevestre** [comment]
and what about the rest of the formula ?

**Comment by PavelBal** [comment]
The default:

![image](https://user-images.githubusercontent.com/25903040/158615198-42a6f1af-b294-4158-87ce-60ddcbce4e18.png)

**Comment by Yuri05** [comment]
I wonder why the condition is "In Container" Plasma and not "Tagged with" Plasma?

**Comment by StephanSchaller** [comment]
I thought we implemented this a long time ago (last year) based on our specifications.. I remember marco albrecht sending a document specifying all left-over hard-coded sums as a sum formula... anyway...

**Comment by msevestre** [comment]
Better late than never

**Comment by PavelBal** [comment]
> I wonder why the condition is "In Container" Plasma and not "Tagged with" Plasma?

Could you explain the main differences between "Tagged" and "In Container" and why you think "Tagged with" would be more appropriate here?

**Comment by Yuri05** [comment]
`"Tagged"` = container itself.
`"In container"` = container itself **or any direct or indirect parent container**

Now imagine you define in Mobi a new subcontainer of e.g. Bone/Plasma and reduce the Bone/Plasma/Volume by the volume of this new subcontainer.
`"Tagged with 'Plasma'"` will return for Bone `Bone/Plasma/Volume` - as expected
`"In container 'Plasma'"` will return for Bone `Bone/Plasma/Volume + Bone/Plasma/Subcontainer/Volume` - wrong

**Comment by msevestre** [comment]
@Yuri05 
yes
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Core/Model/PKSimSpatialStructureFactory.cs#L90

We are adding the tag of the parent container to all children. that's why the "TAGGED TissueOrgan" works. I don't think this is a good way of doing things. But of course, example above would create a problem (that's why we have to remove Periportal and Pericentral)

**Comment by PavelBal** [comment]
>  I don't think this is a good way of doing things. 

I agree, I do not like this at all. I actually think that "In Container: Plasma" is a better solution. For Yuris use case - well the user would have to take care of manually excluding the sub-compartment.

**Comment by Yuri05** [comment]
>We are adding the tag of the parent container to all children. that's why the "TAGGED TissueOrgan" works. I don't think this is a good way of doing things. But of course, example above would create a problem (that's why we have to remove Periportal and Pericentral)

Yep. I think  all this comes from the time before **(NOT) In Container** criteria were introduced. That's why we have this for parameters and also for containers:
![grafik](https://user-images.githubusercontent.com/25061876/159685837-f8b0ea0e-ec4b-4f74-b5fd-d3c21e8e0d3d.png)

Ideally we should go through all our formulas and replace **(NOT) Match** condition with **(NOT) In Container** condition; and when done for all formulas - remove all those unnecessary "parent containers" tags.
But would take some time and not high prio for me.
