### ISSUE TITLE
Default value for the "Phenotype"-field in the expression profile

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2121]
I propose to have a default value, e.g. "Healthy", for the "Phenotype"-field. This would give a user a better understanding of what is required here, and contribute to some consistency of the naming across different models.

**Comment by PavelBal** [comment]
@msevestre @Yuri05 @StephanSchaller Any comments?

**Comment by msevestre** [comment]
It feels to me like a list with some predefined values instead that we would fetch in the project instead with some suggested one such as "Healthy" etc.. instead of writing this as a default value

**Comment by PavelBal** [comment]
I just realized that it annoys me entering "Healthy" (or anything else, I ma just using "Helathy" as a default value) every time I create an expression profile. As I user, I would like to skip this step unless I really want to something else (or create multiple expression profiles of the same enzyme).

**Comment by Yuri05** [comment]
I think the combination of both suggestions would be good: provide the list AND set Healthy as predefined value

**Comment by msevestre** [comment]
I disagree with setting Healthy as the predefined value. RIght now I Am modelling CKD and I would hate to always have to OVERWRITE the Healthy with something else.

What I proposed in the PR #2174 is slightly different and I believe better :)

1 - There is a list of suggestion taken from the project "Phenotypes" 
2 - Added to that list, a list of predefined entires always available (right now only Healthy but we could add more)
3 - The default value is the first entry in the list

Example

### Create an expression profile and no other profile was defined

![image](https://user-images.githubusercontent.com/1041237/161865759-d6633467-ca74-4571-87db-fc3f9e83481d.png)

=> Healthy is selected

### Create an expression profile and other profiles were defined in the project

![image](https://user-images.githubusercontent.com/1041237/161865834-b5680cd3-a53b-488e-ac85-170a4ec51788.png)


The list contains 

![image](https://user-images.githubusercontent.com/1041237/161865869-aab42b76-97d2-4a91-a5ca-0ee7eb73419c.png)

Start typing will select Healthy 

![Uploading image.png…]()

**Comment by PavelBal** [comment]
> 1 - There is a list of suggestion taken from the project "Phenotypes"

What do you mean by "Project Phenotypes"? So the very first time I create an expression, there are no suggenstions (defaults) and I HAVE to enter something (e.g. "Healthy"), but after that I will always see "Healthy" in suggestions (and as a default)? If so - I like the proposal.
