### ISSUE TITLE
Selecting an expression profile in an individual is too slow

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2122]
PK-Sim freezes for several seconds when selecting a protein expression OR selecting another view (e.g. select "CYP3A4" -> freeze, select "Metabolizing Enzyme" -> even longer freeze!)

![image](https://user-images.githubusercontent.com/25903040/159275064-577be408-0ed8-439b-b45c-ea5fe31baabe.png)

**Comment by msevestre** [comment]
I can't reproduce
