### ISSUE TITLE
Formulas: Repalce C*V with M

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2132]
In some formulas, where **amount** of drug or protein is used, it is written in the form `Concentration*Volume`
Because internally concentration is always calculated as `Amount/Volume`, this results in the calculation of `Amount/Volume*Volume`, which is inefficient.

So C*V should be replaced with M (amount). Will also make the formulas more readable 

calculation_method | formula_rate | formula
-- | -- | --
LinksCommon | BrainPgPToPlasma_Hill | Min(**CP * f_int * V** * kcat * (fu   * max(C_pls;0))^alpha / ( Km^alpha + (fu * max(C_pls;0))^alpha) ;   P_endothelial * SA * fu * C_pls) + **CP * f_int * V** * kcat * (K_water_int *   max(C_int;0))^alpha / (Km^alpha + (K_water_int * max(C_int;0))^alpha)
LinksCommon | BrainPgPToPlasma_MM | Min(**CP * f_int * V** * kcat    / ( Km + C_pls * fu) ; P_endothelial * SA)* C_pls * fu + **CP * f_int *   V** * kcat * K_water_int * C_int / (Km + K_water_int * C_int)
LinksCommon | LiverActiveEffluxToBile_Hill | (1-EHC_ContinuousFraction) * **CP * f_cell * V** * kcat *   (K_water_cell * max(C_cell;0))^alpha / (Km^alpha + (K_water_cell *   max(C_cell;0))^alpha)
LinksCommon | LiverActiveEffluxToBile_MM | (1-EHC_ContinuousFraction) * **CP * f_cell * V** * kcat *   K_water_cell * C_cell / (Km + K_water_cell * C_cell)
LinksCommon | LiverActiveEffluxToDuodenum_Hill | EHC_ContinuousFraction * **CP * f_cell * V** * kcat *   (K_water_cell * max(C_cell;0))^alpha / (Km^alpha + (K_water_cell *   max(C_cell;0))^alpha)
LinksCommon | LiverActiveEffluxToDuodenum_MM | EHC_ContinuousFraction * **CP * f_cell * V** * kcat * K_water_cell   * C_cell / (Km + K_water_cell * C_cell)
LinksCommon | MetabolizationSpecific_MM | **** kcat *** V** * K_water * C / (Km + K_water * C)
LinksCommon | PgpSpecific_Hill | Min(**CP * f_cell * V** * kcat * (K_water_int *   max(C_int;0))^alpha / ( Km^alpha + (K_water_int * max(C_int;0))^alpha) ;   PA_int_cell * K_water_int * C_int) + **CP * f_cell * V** * kcat * (K_water_cell *   max(C_cell;0))^alpha / (Km^alpha + (K_water_cell * max(C_cell;0))^alpha)
LinksCommon | PgpSpecific_MM | Min(**CP * f_cell * V** * kcat    / ( Km + C_int * K_water_int) ; PA_int_cell )* C_int *K_water_int + **CP   * f_cell * V** * kcat * K_water_cell * C_cell / (Km + K_water_cell * C_cell)
Observer_PKSim_2Poren | OBS_Concentration_liv_bc | (C_bc_prp * V_bc_prp + C_bc_prc *   V_bc_prc)/(V_bc_prp+V_bc_prc)
Observer_PKSim_2Poren | OBS_Concentration_liv_cell | (C_cell_prp * V_cell_prp + C_cell_prc *   V_cell_prc)/(V_cell_prp+V_cell_prc)
Observer_PKSim_2Poren | OBS_Concentration_liv_end | (C_end_prp * V_end_prp + C_end_prc *   V_end_prc)/(V_end_prp+V_end_prc)
Observer_PKSim_2Poren | OBS_Concentration_liv_int | (C_int_prp * V_int_prp + C_int_prc *   V_int_prc)/(V_int_prp+V_int_prc)
Observer_PKSim_2Poren | OBS_Concentration_liv_pls | (C_pls_prp * V_pls_prp + C_pls_prc *   V_pls_prc)/(V_pls_prp+V_pls_prc)
Observer_PKSim_2Poren | OBS_InterstitialUnbound_liv | (C_int_prp * K_water_int_prp * V_int_prp + C_int_prc *   K_water_int_prc * V_int_prc)/(V_int_prp+V_int_prc)
Observer_PKSim_2Poren | OBS_IntracellularUnbound_liv | (C_cell_prp * K_water_cell_prp * V_cell_prp + C_cell_prc *   K_water_cell_prc * V_cell_prc)/(V_cell_prp+V_cell_prc)
Observer_PKSim_2Poren | OBS_Tissue_liv | (C_int_prp * V_int_prp + C_int_prc * V_int_prc + C_cell_prp *   V_cell_prp + C_cell_prc * V_cell_prc + C_end_prp * V_end_prp + C_end_prc *   V_end_prc)/(V_int_prp+V_int_prc+V_cell_prp+V_cell_prc+V_end_prp+V_end_prc)
Observer_PKSim_2Poren | OBS_WholeOrgan | (fBloodForSampling*(V_pls*C_pls + V_bc*C_bc) + V_end*C_end +   V_int*C_int + V_cell*C_cell)/(fBloodForSampling*(V_pls+V_bc) + V_end + V_int   + V_cell)
Observer_PKSim_2Poren | OBS_WholeOrgan_incl_FcRn_Complex | (fBloodForSampling*(V_pls*(C_pls+C_pls_Complex) + V_bc*C_bc) +   V_end*(C_end+C_end_Complex) + V_int*(C_int+C_int_Complex) +   V_cell*C_cell)/(fBloodForSampling*(V_pls+V_bc) + V_end + V_int + V_cell)
Observer_PKSim_2Poren | OBS_WholeOrgan_incl_FcRn_Complex_liv | (fBloodForSampling*((C_pls_prp + C_pls_prp_Complex) *   V_pls_prp + (C_pls_prc + C_pls_prc_Complex) * V_pls_prc +  C_bc_prp * V_bc_prp + C_bc_prc * V_bc_prc)   +  (C_int_prp + C_int_prp_Complex) *   V_int_prp + (C_int_prc + C_int_prc_Complex) * V_int_prc + C_cell_prp *   V_cell_prp + C_cell_prc * V_cell_prc + (C_end_prp + C_end_prp_Complex) *   V_end_prp + (C_end_prc + C_end_prc_Complex) *   V_end_prc)/(fBloodForSampling*(V_pls_prp+V_pls_prc+V_bc_prp+V_bc_prc)+V_int_prp+V_int_prc+V_cell_prp+V_cell_prc+V_end_prp+V_end_prc)
Observer_PKSim_2Poren | OBS_WholeOrgan_liv | (fBloodForSampling*(C_pls_prp * V_pls_prp + C_pls_prc *   V_pls_prc + C_bc_prp * V_bc_prp + C_bc_prc * V_bc_prc) + C_int_prp *   V_int_prp + C_int_prc * V_int_prc + C_cell_prp * V_cell_prp + C_cell_prc *   V_cell_prc + C_end_prp * V_end_prp + C_end_prc * V_end_prc)/(fBloodForSampling*(V_pls_prp+V_pls_prc+V_bc_prp+V_bc_prc)+V_int_prp+V_int_prc+V_cell_prp+V_cell_prc+V_end_prp+V_end_prc)
Observer_PKSim_4Comp | OBS_Concentration_liv_bc | (C_bc_prp * V_bc_prp + C_bc_prc *   V_bc_prc)/(V_bc_prp+V_bc_prc)
Observer_PKSim_4Comp | OBS_Concentration_liv_cell | (C_cell_prp * V_cell_prp + C_cell_prc *   V_cell_prc)/(V_cell_prp+V_cell_prc)
Observer_PKSim_4Comp | OBS_Concentration_liv_end | (C_end_prp * V_end_prp + C_end_prc *   V_end_prc)/(V_end_prp+V_end_prc)
Observer_PKSim_4Comp | OBS_Concentration_liv_int | (C_int_prp * V_int_prp + C_int_prc *   V_int_prc)/(V_int_prp+V_int_prc)
Observer_PKSim_4Comp | OBS_Concentration_liv_pls | (C_pls_prp * V_pls_prp + C_pls_prc *   V_pls_prc)/(V_pls_prp+V_pls_prc)
Observer_PKSim_4Comp | OBS_InterstitialUnbound_liv | (C_int_prp * K_water_int_prp * V_int_prp + C_int_prc *   K_water_int_prc * V_int_prc)/(V_int_prp+V_int_prc)
Observer_PKSim_4Comp | OBS_IntracellularUnbound_liv | (C_cell_prp * K_water_cell_prp * V_cell_prp + C_cell_prc *   K_water_cell_prc * V_cell_prc)/(V_cell_prp+V_cell_prc)
Observer_PKSim_4Comp | OBS_Tissue_liv | (C_int_prp * V_int_prp + C_int_prc * V_int_prc + C_cell_prp *   V_cell_prp + C_cell_prc * V_cell_prc)/(V_int_prp+V_int_prc+V_cell_prp)
LinksCommon | ClearanceKidneyPls | V * CLspec * C_pls * fu

**Comment by msevestre** [comment]
on it
