### ISSUE TITLE
Liver zonation: wrong observer formula

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2133]
In the small molecules model, the formula of the liver tissue observer is wrong (`+V_cell_prc `is missing in the denominator).
In the default case (liver zonation deactivated) V_cell_prc=0 anyway, but if the liver zonation is activated, the observer value is wrong.

calculation_method | formula_rate | formula
-- | -- | --
Observer_PKSim_2Poren | OBS_Tissue_liv | (C_int_prp * V_int_prp + C_int_prc * V_int_prc + C_cell_prp * V_cell_prp   + C_cell_prc * V_cell_prc + C_end_prp * V_end_prp + C_end_prc *   V_end_prc)/(V_int_prp+V_int_prc+V_cell_prp+V_cell_prc+V_end_prp+V_end_prc)
Observer_PKSim_4Comp | OBS_Tissue_liv | (C_int_prp * V_int_prp + C_int_prc * V_int_prc + C_cell_prp * V_cell_prp   + C_cell_prc * V_cell_prc)/**(V_int_prp+V_int_prc+V_cell_prp)**

**Comment by msevestre** [comment]
Hum this is already like this. Did you fix this already?

**Comment by msevestre** [comment]
Oh sorry. I thought you had written the correct one.
