### ISSUE TITLE
Remove unused endothelial surface area calc method from the database

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2134]
In the PK-Sim database we still have the endothelial surface area calculation method "Inverse residence time", which was discussed at the beginning and then discarded.
Can we finally delete it from the database or is there any probabilty that it could be reactivated in the future?
![grafik](https://user-images.githubusercontent.com/25061876/159899970-058eb673-2c41-49dc-9a94-7319f3ee3d7d.png)

@Christoph27 @JanSchlender

**Comment by Christoph27** [comment]
I would not say it was discarded but the vascularization method was favored given limited data.  I don’t know if there is meanwhile a better database to clearly discard the residence time method …

**Comment by Yuri05** [comment]
Well, ok, let's keep it in then.
