### ISSUE TITLE
PK-Sim database: rename column "rate"=>"formula_rate"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2135]
In the most tables, the formula rate column is named "formula_rate":
![grafik](https://user-images.githubusercontent.com/25061876/160121910-9d117a2b-d3e5-4d8c-bffd-4e3c81b7a3ce.png)

However in the 4 tables it's called just "rate":
![grafik](https://user-images.githubusercontent.com/25061876/160122076-5e6dcaa5-040e-43f3-8aaf-7bbda64a91bd.png)

For consistency reason it would be good to rename the column in these 4 tables to "formula_rate" as well

**Comment by msevestre** [comment]
@Yuri05 Do you think you could do this? I have troubles renaming column in DataGrip

**Comment by msevestre** [comment]
This should not change the VIEW results so only DB Cahnges reaally

**Comment by Yuri05** [comment]
can do

**Comment by msevestre** [comment]
ping :)

**Comment by Yuri05** [comment]
Also removing the garbage columns
![grafik](https://user-images.githubusercontent.com/25061876/182358383-5513a83e-b45a-4b82-a61f-ec8f468bfca0.png)
