### ISSUE TITLE
A simulation which was running in V10 does not run in V11 anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2140]
[DDI_Treatment-Rifampicin_Midazolam-Backman1998.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8357967/DDI_Treatment-Rifampicin_Midazolam-Backman1998.zip)
Loading this snapshot works in V10:
![grafik](https://user-images.githubusercontent.com/25061876/160289283-3199f295-3422-421a-9044-1c509603ee2a.png)

In V11 the error message "Variables became negative" comes:
![grafik](https://user-images.githubusercontent.com/25061876/160289302-7954de17-96fe-440c-aa22-a04782e42822.png)

Also interesting: when loading the pkml exported for this simulation by the qualification runner in MoBi and running the simulation, 
the same error message comes - but at *different time point* 
![grafik](https://user-images.githubusercontent.com/25061876/160289385-e480ac1e-ba3f-43fa-8828-7bb1f6c999b7.png)

After reducing the absolute tolerance from 1E-10 to 1E-11: simulation runs in V11.
However the simulation result is also slightly different.

Attached is a MoBi project with 2 simulations:
[DDI_Treatment-Rifampicin_Midazolam-Backman1998.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8357977/DDI_Treatment-Rifampicin_Midazolam-Backman1998.zip)
![grafik](https://user-images.githubusercontent.com/25061876/160289787-6cdb5273-998f-49d4-861b-6f3e3245c0e3.png)
* Simulation **_DDI...** exported from V10 (after importing the snapshot in PK-Sim 10)
* Simulation **DDI...** was created by the Qualification Runner (as part of the CYP3A4-DDI Quali workflow) and in MoBi AbsTol was reduced from 1E-10 to 1E-11 to be able to run the simulation

V10-Simulation results (_DDI...):
![grafik](https://user-images.githubusercontent.com/25061876/160289692-ee91ee15-2384-4d9d-812d-1c567f5bba7b.png)

V11-Simulation results (DDI)
![grafik](https://user-images.githubusercontent.com/25061876/160289719-1de29419-997a-40ad-8cc6-e60b81fa23b9.png)

**Comment by Yuri05** [comment]
P.S. just to be sure: I rerun the V10 simulation with reduced AsTol: 1E-11
Did not change the result
![grafik](https://user-images.githubusercontent.com/25061876/160290170-5e203841-5769-4f42-9acc-95d42dee1d9b.png)

**Comment by msevestre** [comment]
Looks like the new changes in SimModel might have introduce the change no? 

Or maybe this is due to the new svg icons?😃

**Comment by Yuri05** [comment]
>Looks like the new changes in SimModel might have introduce the change no?

Don't think so. Both simulations above (V10 and V11) were imported and run in MoBi 10.

**Comment by msevestre** [comment]
Are you saying it runs in Mobi but not in PKSim?? What?

**Comment by msevestre** [comment]
And Mobi and pksim returns different values? I can't quite believe this

**Comment by Yuri05** [comment]
no no.
* Snapshot=>PK-Sim 11: cannot import simulation because it does not run
* Simulation 1: Snapshot=>PK-Sim10=>Export to PKML => Import in MoBi 10 => Runs AS IS 
* Simulation 2: Snapshot=>QualificationRunner 11 =>Export to PKML => Import in MoBi 10 => Does not run AS IS but runs with reduced AbsTol (and result is sligthly different from Sim1)

MoBi project with Simulation 1 and Simulation 2 is what is attached above.

**Comment by Yuri05** [comment]
OK... so now I imported both simulations ([Sim1_Sim2_pkmls.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8358490/Sim1_Sim2_pkmls.zip)) into MoBi 11 project: [MoBi11_DDI_Treatment-Rifampicin_Midazolam-Backman1998.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8358487/MoBi11_DDI_Treatment-Rifampicin_Midazolam-Backman1998.zip)

And here the V11-simulation runs with the predefined AbsTol=1E-10 (??). But the result is the same as in MoBi 10 with absTol=1e-11 (and again, different from the result of V10-simulation).

Hmm, hmm, hmm...

**Comment by msevestre** [comment]
I am so confused right now. Let's discuss this tomorrow :)

**Comment by Yuri05** [comment]
OK, one reason is: some protein start amounts are different between PK-Sim 10 and PK-Sim 11.

Path | Start Amount PK-Sim 10 | Start Amount PK-Sim 11
-- | -- | --
Bone\|Interstitial\|P-gp | 0,40414 | 0
Gonads\|Interstitial\|P-gp | 0,00099 | 0
Heart\|Interstitial\|P-gp | 0,02469 | 0
Stomach\|Interstitial\|P-gp | 0,00620 | 0
SmallIntestine\|Interstitial\|P-gp | 0,23021 | 0
LargeIntestine\|Interstitial\|P-gp | 0,05136 | 0
Lung\|Interstitial\|P-gp | 0,11259 | 0
Muscle\|Interstitial\|P-gp | 0,59072 | 0
Pancreas\|Interstitial\|P-gp | 0,00383 | 0
Spleen\|Interstitial\|P-gp | 0,02167 | 0

All other protein start amounts are the same between V10 and V11

**Comment by Yuri05** [comment]
And the reason for the difference of the start amounts is: **fraction expressed basolateral is 1 in V10 and 0 in V11**
So the fraction expressed basolateral is obviously wrong in V11.

Here how the formulas for e.g. **Bone|Interstitial|P-gp|Initial concentration** look like in V10 and V11

```
Parameter: Sim1_V10Organism|Bone|Interstitial|P-gp|Initial concentration
	Value: 0.34195064649 [µmol/l]
	Formula: f_int > 0 ? RC * rel_exp_org * f_exp_org_basolatateral * 1 / f_int : 0
		f_exp_org_basolatateral: Sim1_V10Organism|Bone|Interstitial|P-gp|Fraction expressed basolateral(1)
		f_int: Sim1_V10Organism|Bone|Fraction interstitial(0.1)
		RC: Sim1_V10P-gp|Reference concentration(1.41 [µmol/l])
		rel_exp_org: Sim1_V10Organism|Bone|Intracellular|P-gp|Relative expression(0.0242518189)

```
```
Parameter: Sim2_V11Organism|Bone|Interstitial|P-gp|Initial concentration
	Value: 0 [µmol/l]
	Formula: f_int > 0 ? RC * rel_exp_org * f_exp_org_basolateral * 1 / f_int : 0
		f_exp_org_basolateral: Sim2_V11Organism|Bone|Interstitial|P-gp|Fraction expressed basolateral(0)
		f_int: Sim2_V11Organism|Bone|Fraction interstitial(0.1)
		RC: Sim2_V11P-gp|Reference concentration(1.41 [µmol/l])
		rel_exp_org: Sim2_V11Organism|Bone|Intracellular|P-gp|Relative expression(0.0242518189)

```

**Comment by Yuri05** [comment]
Here a very simple example to reproduce (just individual with a transporter, no simulations): 
[Individual_with_Transporter.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8361573/Individual_with_Transporter.zip)

When importing the snapshot in V10: initial concentrations are correct:
![grafik](https://user-images.githubusercontent.com/25061876/160373188-40028bc6-bfb6-49ad-befd-a4734e7f38eb.png)

And in V11:
![grafik](https://user-images.githubusercontent.com/25061876/160373346-cf368bff-2107-4af4-989c-b2f11bd4d152.png)
