### ISSUE TITLE
Remove unused observers from the database

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2142]
The observers in the table below, which are part of the PK-Sim database, seems to be unused.
<details><summary><b>unused observers</b></summary>

observer
--|
Fraction dissolved particles
Fraction dissolved particles1
Fraction dissolved particles10
Fraction dissolved particles11
Fraction dissolved particles12
Fraction dissolved particles13
Fraction dissolved particles14
Fraction dissolved particles15
Fraction dissolved particles16
Fraction dissolved particles17
Fraction dissolved particles18
Fraction dissolved particles19
Fraction dissolved particles2
Fraction dissolved particles20
Fraction dissolved particles3
Fraction dissolved particles4
Fraction dissolved particles5
Fraction dissolved particles6
Fraction dissolved particles7
Fraction dissolved particles8
Fraction dissolved particles9
Fraction insoluble particles
Fraction insoluble particles1
Fraction insoluble particles10
Fraction insoluble particles11
Fraction insoluble particles12
Fraction insoluble particles13
Fraction insoluble particles14
Fraction insoluble particles15
Fraction insoluble particles16
Fraction insoluble particles17
Fraction insoluble particles18
Fraction insoluble particles19
Fraction insoluble particles2
Fraction insoluble particles20
Fraction insoluble particles3
Fraction insoluble particles4
Fraction insoluble particles5
Fraction insoluble particles6
Fraction insoluble particles7
Fraction insoluble particles8
Fraction insoluble particles9
Fraction solid particles
Fraction solid particles1
Fraction solid particles10
Fraction solid particles11
Fraction solid particles12
Fraction solid particles13
Fraction solid particles14
Fraction solid particles15
Fraction solid particles16
Fraction solid particles17
Fraction solid particles18
Fraction solid particles19
Fraction solid particles2
Fraction solid particles20
Fraction solid particles3
Fraction solid particles4
Fraction solid particles5
Fraction solid particles6
Fraction solid particles7
Fraction solid particles8
Fraction solid particles9
</details>

There are no entries in **tab_model_observes** for them; in PK-Sim code we have only one place where the names of those observers are used - but the breakpoints are never hit when creating a simulation with particles dissolution formulation(s).
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/61c5946911b05a84fa8220d23e20b55c8b688b94/src/PKSim.Core/Services/SimulationPersistableUpdater.cs#L119-L137
![grafik](https://user-images.githubusercontent.com/25061876/160409861-0364ea51-ec5a-4012-8d48-a91f5b54d0a7.png)

I assume those observers were created in the past somewhere in the code (in **ParticleApplicationCreator** or so), but were dropped when the implementaion of particles dissolution was improved some years ago.

So I think it is safe to delete them.

@msevestre FYI

**Comment by msevestre** [comment]
lol if yo usay so...happy to delete
