### ISSUE TITLE
Protein expression: Ontogeny-Like not shown in comparison

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2151]
I created a CYP3A4 profile, then cloned it (changed phenotype) and changed "Ontogeny like" in the cloned profile from CYP3A4 to CYP1A2.
[ProfilesCompare.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8382440/ProfilesCompare.zip)

When comparing those 2 profiles: the ontogeny change does not appear in the comparison overview

**Comment by msevestre** [comment]
@Yuri05 Yeah. I think we'll have a few bugs regarding this new BB. Good catch
