### ISSUE TITLE
Renaming Protein Expressions Building Block corrupts it

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2175]
In the project attached some strange things happen with the protein expressions
[Pgp_Only.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8426343/Pgp_Only.zip)

I have created a transport protein expression BB, changed the (global) transporter type to PgP and cloned this transporter 3 times
(more precisely, I cloned P1=>P2, P2=>P3, P3=>P4 (or P2 => P4))
Then I also renamed all created Protein expressions BBs.

Now I face different problems in the project:
1) In the individual BB, where I added all those transporter, they are all shown as Efflux (and if I export to MoBi - yes, they are all efflux). Only the "global" direction setting is shown as pgp
<details><summary><b>Screenshot</b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/161963932-ec4f35b2-fb06-4a65-8c21-bf86a64fc8fb.png)

</details>

2) When I open a Protein expression-BB: only the vascular system part is shown - nothing else
<details><summary><b>Screenshot</b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/161964127-0d33df1d-90f9-4fb9-a01b-6cc2d68e3ca5.png)

</details>

After some playing around: it's a renaming which corrupts the building block. E.g. if I do the following in a new empty project:
* Create Transporter Protein expression Building Block `T1|Human|Healthy`
* Set global transporter type to PgP and close the Protein Expression View
* Rename the Building Block to `T2|Human|Healthy`
* Create human individual and add `T2|Human|Healthy` to it

Then I observed both problems from above: Transporter type in the individual is Efflux in every organ (only the global transporter type is shown as PgP) and reopening the Transporter-BB view shows only the vascular system, no organs.

Cloning works, so if I clone `T1|Human|Healthy` to `T2|Human|Healthy` - everything works as expected

**Comment by msevestre** [comment]
I can reproduce
