### ISSUE TITLE
Rename PgP Transporter to "Deprecated PgP Transporter"

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2176]

**Comment by msevestre** [comment]
Should we add it also in each organ? (at least the Deprecated part)
![image](https://user-images.githubusercontent.com/1041237/162024230-a2d0af22-1d06-4380-94e5-5e903f0b8249.png)

**Comment by Yuri05** [comment]
>What about sthg like this

Looks good for me

> Should we add it also in each organ? (at least the Deprecated part)

Yes please
