### ISSUE TITLE
Cannot create protein expression (same enzyme, different phenotype)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2185]
I created CYP3A4/Healthy expression in my project
![grafik](https://user-images.githubusercontent.com/25061876/162769673-892c24ad-6052-4fea-847b-e9e961a719eb.png)

Now when creating CYP3A4 for **another phenotype**: if I change the **phenotype first** and enter the enzyme name **after that** - I can create it as expected:
<img width="300" src="https://user-images.githubusercontent.com/25061876/162770495-6424f8f1-4945-4528-9f15-cb2156edbb0f.png"> <img width="300" src="https://user-images.githubusercontent.com/25061876/162770598-731d43a2-9218-4863-bc70-f8023c8f23bb.png"> <img width="180" src="https://user-images.githubusercontent.com/25061876/162770166-3a025c43-8e17-416f-a05e-5cd88fafa40c.png">

However if I do it in the opposite order - first the Enzyme and then the Phenotype - 
<img width="300" src="https://user-images.githubusercontent.com/25061876/162770794-e91825a7-2864-4bdf-91b9-e224aca066ff.png"><img width="362" src="https://user-images.githubusercontent.com/25061876/162771280-0eb711e8-814e-40e2-b04f-c5e9e9327c3d.png">

**Comment by msevestre** [comment]
Does the UI look that ugly on your screen or did you resize it on purpose?
