### ISSUE TITLE
Investigate differences in batch files

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2186]
```
Comparing files 'DDI_MultipleCombinations-05_MM_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations-07_MM_Competitive_Competitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations-09_MM_Noncompetitive_Noncompetitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations-21_1st_Competitive_Competitive.json'...Invalid
Comparing files 'DDI_MultipleCombinations-25_1st_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations-27_1st_Competitive_Competitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations-29_1st_Noncompetitive_Noncompetitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'European_SingleORAL_Age_0_CYP3A4-European_SingleORAL_Age_0_CYP3A4.json'...Invalid
Comparing files 'European_SingleORAL_Age_0_GFR-European_SingleORAL_Age_0_GFR.json'...Invalid
Comparing files 'European_SingleORAL_Age_1_CYP3A4-European_SingleORAL_Age_1_CYP3A4.json'...Invalid
Comparing files 'European_SingleORAL_Age_1_GFR-European_SingleORAL_Age_1_GFR.json'...Invalid
Comparing files 'Human_MultiORAL_6_12_12_Dissolved-Human_MultiORAL_6_12_12_Dissolved_solubility.json'...Invalid
Comparing files 'Human_MultipleIV_Efflux-Human_MultipleIV_Efflux.json'...Invalid
Comparing files 'Human_MultipleIV_EffluxBasolateral-Human_MultipleIV_EffluxBasolateral.json'...Invalid
Comparing files 'Human_MultipleIV_Influx-Human_MultipleIV_ActiveInflux.json'...Invalid
Comparing files 'Human_MultipleIV_InfluxBasolateral-Human_MultipleIV_InfluxBasolateral.json'...Invalid
Comparing files 'Human_MultipleIV_PGP-Human_MultipleIV_PGP.json'...Invalid
Comparing files 'Human_MultipleIV_PGPBasolateral-Human_MultipleIV_PGPBasolateral.json'...Invalid
Comparing files 'Human_Oral_BiDaily_TableFormulation-S2_NoSuspension.json'...Invalid
Comparing files 'Human_SingleORAL_Dissolved_PlasmaClearance-Human_SingleORAL_Dissolved_PlasmaClearance.json'...Invalid
Comparing files 'Human_SingleORAL_Dissolved_PlasmaClearance-Human_SingleORAL_Dissolved_PlasmaClearance_MW_200_fu_0.2_LogP_5.json'...Invalid
Comparing files 'Human_SingleORAL_Weibull-Human_SingleORAL_Weibull_MW_200_fu_0.2_LogP_5.json'...Invalid
Comparing files 'Rat_MultiORAL_6_6_12_Dissolved-Rat_MultiORAL_6_6_12_Dissolved.json'...Invalid
Comparing files 'Rat_MultiORAL_6_6_6_6_Dissolved-Rat_MultiORAL_6_6_6_6_Dissolved.json'...Invalid
Comparing files 'Rat_MultiORAL_8_8_8_Dissolved-Rat_MultiORAL_8_8_8_Dissolved.json'...Invalid
Comparing files 'Test 18.1_I1_C1_A1_Config1-Test 18.1_I1_C1_A1_Config1.json'...Invalid
Comparing files 'Test 18.1_I2_C1_A1_Config2-Test 18.1_I2_C1_A1_Config2.json'...Invalid
Comparing files 'Test 18.1_I2_C3_A1_Config2-Test 18.1_I2_C3_A1_Config2.json'...Invalid
Comparing files 'Test 18.1_I3_C3_A3_Config2-Test 18.1_I3_C3_A3_Config2.json'...Invalid
```

Probably an issue with batch conversion

**Comment by msevestre** [comment]
Rat_MultiORAL_6_6_12_Dissolved

Is a very simple project and should not lead to any difference

**Comment by msevestre** [comment]
@Yuri05 
Did we change sthg in the effective concentration in lumen parameter?

I am exporting the ODE and it does not look the same for those parameter

Example
V11

P_2604 = (IIf((y(31) > 0),(IIf(P_1217,(y(32)/y(31)),(min((P_2417/P_1198),(y(32)/y(31)))))),0));  % Rat_MultiORAL_6_6_12_Dissolved|Organism|Lumen|Duodenum|drug|Effective concentration in lumen

v10

P_2604 = (IIf(P_1217,(y(32)/y(31)),(min((P_2417/P_1198),(y(32)/y(31))))));  % Rat_MultiORAL_6_6_12_Dissolved|Organism|Lumen|Duodenum|drug|Effective concentration in lumen

This is the only difference I can spot

e.g. (IIf((y(31) > 0 was added and returns 0 otherwise. I guess this was NaN before and the solver was working but behaves a bit differently?

**Comment by msevestre** [comment]
and there is also Volume Plasma change 

P_2764 = (P_1261+P_1264+P_1269+P_1276+P_1283+P_1290+P_1297+P_1304+P_1395+P_2626+P_2444+P_2451+P_2458+P_2465+P_2472+P_2662+P_2481+P_2488+P_2495+P_2502+P_2509+P_2516+P_1513+P_1520+P_1527+P_1534+P_1539+P_1544+P_1551);  % Rat_MultiORAL_6_6_12_Dissolved|Organism|Volume (plasma)


P_2764 = (P_1264+P_1269+P_1276+P_2481+P_2488+P_2502+P_2509+P_2495+P_2444+P_1283+P_1290+P_1297+P_1304+P_2662+P_2472+P_2458+P_1520+P_1527+P_1534+P_1911+P_1904+P_1539+P_2516+P_1544+P_2626+P_1551+P_1395+P_2465+P_2451+P_1261);  % Rat_MultiORAL_6_6_12_Dissolved|Organism|Volume (plasma)

but I think this is just an order of formula difference

**Comment by msevestre** [comment]
Hum no the formula is different
We have P_1513 on the one and P_1911+P_1904 on the other (probably liver ). might still be good and this parameter is not used anywhere anyways in the system

**Comment by msevestre** [comment]
this is the diff
v10

Formula: EnableSupersaturarion ? M/Liquid : min(Solubility/MW ; M/Liquid)
vs

Formula: Liquid>0 ? (EnableSupersaturarion ? M/Liquid : min(Solubility/MW ; M/Liquid)) : 0

I do not see any other difference. The difference in output is however quite signfiicant

**Comment by msevestre** [comment]
does not explain `'Human_MultipleIV_Efflux-Human_MultipleIV_Efflux.json`

**Comment by msevestre** [comment]
Human_multi_Efflux
![image](https://user-images.githubusercontent.com/1041237/162837548-29f923f4-30ab-4279-bdc9-0dc2850bf65a.png)

**Comment by Yuri05** [comment]
Yes, `Liquid > 0 ` check was added here: 
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1960/files#r750612764
(because there we had Liquid volume = 0 due to "inactivated" GI tract, and Amount=0 , so the intestinal concentrations were NaN).
In fact this should just increase stability and don't produce significantly different values...

**Comment by msevestre** [comment]
I believe this is due to a difference in Clearance in Kidney 

v10
```
Transport: Renal Clearances-Lab
	Source: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Plasma|C1
	Target: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Urine|C1
	Formula: V * CLspec * C_pls * fu
		V: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Volume(0.397758495628895 [l])
		C_pls: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Plasma|C1|Concentration(0 [Âµmol/l])
		fu: Test 18.1_I1_C1_A1_Config1|C1|Fraction unbound (plasma)(0.85)
		CLspec: Test 18.1_I1_C1_A1_Config1|Neighborhoods|Kidney_pls_Kidney_ur|C1|Renal Clearances-Lab|Specific clearance(1.57 [1/min])
```

v11
```
Transport: Renal Clearances-Lab
	Source: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Plasma|C1
	Target: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Urine|C1
	Formula: CLspec * M_pls * fu
		M_pls: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Plasma|C1(0 [Âµmol])
		fu: Test 18.1_I1_C1_A1_Config1|C1|Fraction unbound (plasma)(0.85)
		CLspec: Test 18.1_I1_C1_A1_Config1|Neighborhoods|Kidney_pls_Kidney_ur|C1|Renal Clearances-Lab|Specific clearance(1.57 [1/min])
```

in v10, C_pls was multiplied by Volume kidney and not volume plasma

V: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Volume(0.397758495628895 [l])
C_pls: Test 18.1_I1_C1_A1_Config1|Organism|Kidney|Plasma|C1|Concentration(0 [Âµmol/l])

**Comment by msevestre** [comment]
finally understood
