### ISSUE TITLE
fBlood for sampling: Organs/Mucosa several times

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2187]
In the newly visible Sampling/Fraction of Blood parameter group the categories Organs and Mucosa appear several times instead of only once
![grafik](https://user-images.githubusercontent.com/25061876/162799378-c7f05506-5865-4ff8-ad20-b066eaf7444f.png)

**Comment by msevestre** [comment]
probasbly sequence of parmeters is not set properly in DB

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/163463340-a0bb286d-3b7d-42ea-820e-8b9a64778f85.png)

However I realize that the icons for Liver and Liver Periprotal etc.. are corrupted. I asked for them to be  sent again
