### ISSUE TITLE
Program menu shortcuts not working

### ISSUE THREAD

**Issue by hdiedam** [Open-Systems-Pharmacology/PK-Sim#219]
After flawless installation and successful validation, the generated program menu shortcuts do not work correctly and trying to start PK-Sim/MoBi or opening the manual fails with the following error message. Starting the programs directly from the installation directory by hand or using a manually created shortcut on the desktop works without issues.

![shortcut](https://user-images.githubusercontent.com/26765701/26937621-267ffc1a-4c72-11e7-90fb-1cd07fafd206.PNG)

**Comment by Yuri05** [comment]
Please stop and restart the Explorer.exe process using Task Manager.
After that, try the installed shortcuts once again

**Comment by msevestre** [comment]
Worked fine on fresh VM install

**Comment by hdiedam** [comment]
Restarting the computer worked, apparently it was the initialization that occurs during first start up that was not working properly.
