### ISSUE TITLE
(Minor) project conversion issue with protein expressions

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2190]
[V10.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/8473935/V10.zip)
The project attached (created with V10) has an Individual **Healthy** with CYP3A4.
* Open the project in V11 (don't open the individual)
* Create Enzyme expression profile **CYP3A4|Human|Healthy**
* Try to create a simulation: the message below is shown and it's not possible to create a simulation with this individual
![grafik](https://user-images.githubusercontent.com/25061876/162989369-9e3e7913-5979-4835-b802-9ce67a2e40da.png)

After the manually created Enzyme expression profile is removed from the project (or renamed) - everything works as expected.

**Comment by msevestre** [comment]
Hum... Expression profiles are created when the individual is loaded. Probably we should rename the expression profile if one already exists during conversion
