### ISSUE TITLE
Calculate PK-parameters for popSim based on individual values and not on aggregated curves

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2211]
PK-parameters for population simulations are currently calculated for the selected aggregated curves. I.e., when selecting "arithmetic mean" as an output, the AUC is calculated for the curve that is generated from the individual results.

However, I would expect to have the arithematic mean of all individual AUC values instaed. The same goes e.g. for "5th percentile" - what we get now is the AUC of the curve but not really the 5th percentile of all AUC values.

So I suggest to re-implement this. Good news - we already have all individual PK parameter values as they can be shown e.g. in a BoxPlot. This approach would also allow to calculate the body-weight scaled parameters that are currently shown as `NaN` 

•	AUC_inf_norm
•	AUC_tEnd_norm
•	C_max_norm
•	Total body clearance/F (not quite clear what it is, documentation missing)
•	Vd(plasma)/F
•	Vss(plasma)/F

and to also calculate ranges like "arithmetic standard deviation" or the "geometric standard deviation".

@Yuri05 @msevestre @sfrechen @StephanSchaller 

@abdelr FYI

**Comment by msevestre** [comment]
>So I suggest to re-implement this. 

I disagree with this. I think we could offer something else but I would not change this. I remember that we had raised the point back then and it was deemed perfectly acceptable to have the PK over the aggregated curves

**Comment by PavelBal** [comment]
27.04.2022 - do not re-implement.

Instead: In pk-analyses view, show two tabs - pk parameters calculated from the curves (as it is implemented now, do not change anything), and pk-parametes based on individual values.

Separate task - documentation.

**Comment by StephanSchaller** [comment]
Do we have an example to show how much the outcomes may differ (PK Property of aggregated curve vs calculating it from mean/percentiles of the individual PK Properties)?

**Comment by PavelBal** [comment]
02.05.2022:

- Remove rows containing `NaN` from "Calculated based on curves"
- Two tabs - "Calculated based on aggregated curves" and "Calculated based on individual value"
- "Export to excel" exports the currently selected tab

**Comment by msevestre** [comment]
>Remove rows containing NaN from "Calculated based on curves"

Why? Also note that you can have NaN is one cell but.not on the next one.

**Comment by PavelBal** [comment]
> Why? Also note that you can have NaN is one cell but.not on the next one.

No, for population simulations actually not. The bw-normalized values are not calculated for observed data.

**Comment by PavelBal** [comment]
So these rows are always showing `NaN`

![image](https://user-images.githubusercontent.com/25903040/168091781-85edccf8-b4d8-4f94-b096-fa23458fd793.png)

**Comment by PavelBal** [comment]
No :) https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1406#issuecomment-1002219676

**Comment by msevestre** [comment]
Ok  Ithink this is implemented
