### ISSUE TITLE
Border for the splash screen

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2212]
Is it possible to add the border to the splash screen?
At the moment, when started e.g. with the Windows Explorer in the background, it does not look good, e.g.
<img width="600" src="https://user-images.githubusercontent.com/25061876/165491835-7b3110a6-d726-4d3a-91c3-8646d5b16d5f.png"><br><br>

With a border:<br>
<img width="600" src="https://user-images.githubusercontent.com/25061876/165492360-e25e77e0-4623-405c-a32f-b628c9737921.png">

**Comment by StephanSchaller** [comment]
Not sure this looks better? a better solution might be to grey-shade the white background of the splash screen?
I could edit the image file accordingly :-)

**Comment by msevestre** [comment]
I would not change anyhting. Same behavior as before

![image](https://user-images.githubusercontent.com/1041237/165752883-6527c25c-64e3-434a-a254-c7b27139f4b6.png)

**Comment by msevestre** [comment]
and it looks ugly with the border...

**Comment by Yuri05** [comment]
>and it looks ugly with the border...

well, it's a matter of taste 😄 

>I would not change anyhting. Same behavior as before

Before we did not have the highlighted part. Somehow I always missed the border, but with this new part much more than before.
![grafik](https://user-images.githubusercontent.com/25061876/165790280-427fd213-9a8c-4a5e-ab5e-fcebaae450be.png)

>a better solution might be to grey-shade the white background of the splash screen?

mmm maybe... How it would look like?

**Comment by Yuri05** [comment]
anyway, it's low prio. I can live with the status quo.
