### ISSUE TITLE
Liver icon missing in PK-Sim 11

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/PK-Sim#2217]
In PK-Sim 11 the liver icon is not displayed (at any location):
![image](https://user-images.githubusercontent.com/63294872/166243382-667d5626-3a20-4d14-b0c7-ceccf736e1ca.png)

**Comment by msevestre** [comment]
This has been fixed already in the upcoming build. Thanks for reporting it
