### ISSUE TITLE
PK-Sim 11: Calculated values in molecule building block show an error symbol

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/PK-Sim#2218]
In PK-Sim 11 calculated values in the molecule buidling block like the specific intestinal permeability show an error symbol. It doesn't have an impact since the value is still there but it is  confusing.
![image](https://user-images.githubusercontent.com/63294872/166244402-b404c3f9-6a16-4e66-9cab-eacb2501423f.png)

**Comment by AnnikaRPS** [comment]
Same for distribution calculation:
![image](https://user-images.githubusercontent.com/63294872/166244522-c629a894-82a0-4507-bf92-4473f604ce41.png)

**Comment by msevestre** [comment]
This is fixed in v11 latest build
