### ISSUE TITLE
"Run simulations" option disappeared from Import snapshot?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2223]
In PK-Sim 11.0.139 I don't have the option anymore:
![grafik](https://user-images.githubusercontent.com/25061876/166925146-1c9e2033-082a-4ade-8b10-142273c3b213.png)

Some time ago it looked like this:
![grafik](https://user-images.githubusercontent.com/25061876/166925242-91ab9b22-21fa-435e-959f-7d7437a3a29c.png)

**Comment by msevestre** [comment]
using the develop version
![image](https://user-images.githubusercontent.com/1041237/166926122-5c393926-90aa-49a8-8e81-175e6b17169e.png)

Can't reproduce

**Comment by Yuri05** [comment]
and using the CI-version?
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/branch/develop/artifacts

**Comment by msevestre** [comment]
only visible in dev mode. Are you in dev mode? :-)

**Comment by Yuri05** [comment]
ah ok. you are right, I am not. closing
