### ISSUE TITLE
Color group option prevents observed data to be added to simulation

### ISSUE THREAD

**Issue by AnnikaRPS** [Open-Systems-Pharmacology/PK-Sim#2226]
When enabeling the "Color group observed data from same folder when dropping to chart" option in PK-Sim 11, dropping data does add the data to the chart but not to the simulation anymore, meaning it is not listed together with the other building blocks of the simulation and it cannot be selected and matched to outputs in parameter identifications.

**Comment by msevestre** [comment]
Nice find!
@georgeDaskalakis this needs to be fixed ASAP. Show stopper for release

**Comment by msevestre** [comment]
Starting with this because of release pressure

**Comment by msevestre** [comment]
In fact it is also broken when not adding via color grouping

**Comment by msevestre** [comment]
Correction. It is not broken when adding is color grouping but the code to add via color grouping does not always work

**Comment by msevestre** [comment]
correction #2. It is by design after call with @PavelBal
