### ISSUE TITLE
Observer "Intracellular unbound" only shown for liver?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2240]
Why is that?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/25903040/172613508-15e9bb0f-0680-45c5-b995-f9770d291346.png">

The same simulation in MoBi:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/25903040/172613618-4f947d6f-0157-4704-bd42-4ac6165d02b3.png">

**Comment by PavelBal** [comment]
Same in V9, so nothing we introduced recently.

**Comment by Yuri05** [comment]
"He who seeks, finds" :)
![grafik](https://user-images.githubusercontent.com/25061876/200400914-2b7b77fe-5ff8-470a-b25b-f08537bb14af.png)

**Comment by PavelBal** [comment]
"Compartment" is "Intracellular unbound" and "Name" is "Concentration"? This is...  strange?

And I cannot find this in MoBi.

**Comment by msevestre** [comment]
In PK-Sim we are making sure every observer matches the structure. If it's in PK-Sim, it's also in Mobi...

**Comment by Yuri05** [comment]
MoBi:
![grafik](https://user-images.githubusercontent.com/25061876/200406013-d277efc8-3c46-4200-a0e4-f1f6b288c708.png)

**Comment by PavelBal** [comment]
Found.
