### ISSUE TITLE
UI: Empty entry in "Create Individual" -> "Calculation methods"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2248]
![image](https://user-images.githubusercontent.com/25903040/176616133-534432b6-1a92-402e-b502-71b561e1efdd.png)

When clicking on the marked "down"-button, an empty line becomes visible, which is not required. If removed, maybe the "up - down" buttons can be removed too?

![image](https://user-images.githubusercontent.com/25903040/176616398-33e2bf69-3b57-47a4-9f5f-05e6d82250e4.png)

**Comment by msevestre** [comment]
Yeah...it's not there normally :)
![image](https://user-images.githubusercontent.com/1041237/176688221-73f86471-f08d-4232-821f-f68a99319745.png)
The calculation of dynamic heights is corrupted for such resolutions...

**Comment by PavelBal** [comment]
Somehow the empty line is added on certain resolution... weird.

**Comment by msevestre** [comment]
Yep. We use a method from devexpress to calculate the optimal height. It does not work with scaling. I need to open an issue with devexpress

**Comment by msevestre** [comment]
I have created an issue with devexpress support.
And I could reproduce on a small example too
https://supportcenter.devexpress.com/ticket/details/t1105773/function-calculating-the-optimal-size-of-a-table-does-not-work-with-high-scaling-or-4k
