### ISSUE TITLE
UI: "Scale" button in "Anatomy and Physiology tab" in "Create Individual"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2249]
The button "scale", the input field, and the button "reset" are too close to each other. Also the input text field could be a bit smaller.

![Uploading image.png…]()

**Comment by msevestre** [comment]
@PavelBal Can't see the image and I have no idea what we are looking at

**Comment by PavelBal** [comment]
Lol

<img width="557" alt="image" src="https://user-images.githubusercontent.com/25903040/177127284-97fd83be-3677-4b5a-92aa-168e0865a21a.png">

**Comment by msevestre** [comment]
I don't understand the problem. Do you expect space between the buttons and the input field? 

This is v9
![image](https://user-images.githubusercontent.com/1041237/177188036-4ae2d9ef-611f-43a8-9c6d-49f3dc88b3bf.png)

**Comment by PavelBal** [comment]
I think some space would make it look nicer, yes. Actually, I am very surprised that you don't care about the fact that the text field is one pixel higher than the buttons! :D

**Comment by msevestre** [comment]
oh yeah I did not even see it :) Now that you are mentioning it...horrible

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/181855478-9cf9f50e-3a1e-4b9f-9091-19a841398122.png)

**Comment by PavelBal** [comment]
Using 11.1 Build 2:

![image](https://user-images.githubusercontent.com/25903040/182327349-df95029f-d6d2-4cae-88a9-f6a54c262a5e.png)

**Comment by msevestre** [comment]
Nightly are not turned on yet. That's why
