### ISSUE TITLE
When loading a compound from github, "Also load metabolites?" is always shown

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2251]
Even if the compound does not have any metabolite in the data base.

**Comment by msevestre** [comment]
Yes. We do not know before end if there is a metabolite associated with it. So this needs to happen unless we decide to add this information as metadata.  This is not really an error. We could rename to "Also load metablites if any?"
Thoguhts @Yuri05 ?

**Comment by Yuri05** [comment]
Yep, let's rename.

We could also introduce additional application setting "Load metabolites when loading compound from template" with the options _Yes_ (**default**), _No_ and _Ask_

**Comment by msevestre** [comment]
done
