### ISSUE TITLE
Initial concentration overwritten with a value in Protein Expression BB not propagated into simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2253]
E.g. here:  [P1.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9046585/P1.zip)

* Protein Expression BB: overwriting C0 in Bone/Intracellular:
![grafik](https://user-images.githubusercontent.com/25061876/177334376-99203588-97f5-4ad4-8b71-1ddd09ddaecd.png)

* Creating an Individual with this Protein Expression: initial concentration value is correct
![grafik](https://user-images.githubusercontent.com/25061876/177334722-6b870263-9391-45a5-bb55-074126ee8d7e.png)

* Creating simulation with this individual: C0 in Bone/Intracellular is 0 now!
![grafik](https://user-images.githubusercontent.com/25061876/177335008-b1751ea9-921f-4e91-9c85-e1096738fac1.png)

In the simulation export we can see that the formula of C0 was not overwritten with the value:
```
Parameter: S1|Organism|Bone|Intracellular|CYP|Initial concentration
	IsFixed: False
	Value: 0 [µmol/l]
	Formula: RC * rel_exp_org * f_exp_org_cell * 1 / f_cell
		f_exp_org_cell: S1|Organism|Bone|Intracellular|CYP|Fraction expressed intracellular(1)
		f_cell: S1|Organism|Bone|Fraction intracellular(0.866)
		rel_exp_org: S1|Organism|Bone|Intracellular|CYP|Relative expression(0)
		RC: S1|CYP|Reference concentration(1 [µmol/l])
```

Interestingly: if I change ANY parameter in the Individual-BB (even not protein-related, like organ volume) and update the individual in the simulation from BB: initial concentration value is properly set:
![grafik](https://user-images.githubusercontent.com/25061876/177336127-4e568650-95e2-446b-889d-e882f1d235d4.png)

(we also have a Refresh problem when updating the Individual from BB: initial concentration value is updating only after I click another node and then click again on the CYP node in the simulation) ▶️ #2254

**Comment by Yuri05** [comment]
indeed :)

**Comment by msevestre** [comment]
This looks like an issue in the PSV

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/177422916-c6553f27-bb08-4b96-b3fd-701010697aa9.png)

**Comment by msevestre** [comment]
ok so this is not the problem. The problem is that we have in the PSV a formula AND a constant value
The logic is the following: if there is a formula use the formula. Otherwise use the StartValue constant

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/develop/src/OSPSuite.Core/Domain/Services/QuantityValuesUpdater.cs#L58

@Yuri05 Do you see a problem if I DELETE the formula in the PSV ? 

It will be better once we only create the value to overwrite in the PSV but for this version..I feel like this is what needs to be done

**Comment by Yuri05** [comment]
>Do you see a problem if I DELETE the formula in the PSV ?

Should be ok I think

**Comment by msevestre** [comment]
I check for a normal similation. It's always NULL normally
