### ISSUE TITLE
Resetting initial concentrations in the simulation and is not propagated to BB after commit

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2255]
In the example from https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2253 I click on the Reset button in the initial concentration **in the simulation**
<img width="450" src="https://user-images.githubusercontent.com/25061876/177336127-4e568650-95e2-446b-889d-e882f1d235d4.png">
Then I commit the Individual from the simulation back to the BB.
* In the **Individual**-BB the value is correctly resetted to 0 (btw, suddenly I see an entry for Endosome initial concentration which was not shown before. Why?)
![grafik](https://user-images.githubusercontent.com/25061876/177338601-1d463e37-6204-4831-8477-961adabcec36.png)
* But in the Protein-Expression-BB the value is still 1. Closing/Reopening the Protein-Expression-BB does not help, so it's not a refresh progress. And also here I suddenly get the entry for Endosome...
![grafik](https://user-images.githubusercontent.com/25061876/177338982-9624fff7-9670-4adf-9bd9-9829eb443977.png)

**Comment by msevestre** [comment]
@Yuri05 
I don't understand what you mean with Endosome
![image](https://user-images.githubusercontent.com/1041237/181853058-3447d835-50de-4d77-9677-5b373cb42f23.png)

it's always their as soon as you show initial concentration in expression profile

**Comment by msevestre** [comment]
@Yuri05 
I do not have a reset button in the simulation
![image](https://user-images.githubusercontent.com/1041237/181853371-cc949b67-25b3-4f49-987b-fcc0beb31d75.png)

it is now a constant with value 1. Probably because of the fix in #2253

**Comment by msevestre** [comment]
and in fact I would expect this behavior

**Comment by Yuri05** [comment]
OK, Endosome is always shown now. Pretty sure it was not the case before - anyway, now it's consistent, so all good.

Regarding the rest of the issue: now the behaviour is different. There is no reset button in the simulation indeed.
But what happens after committing changed initial conc value from simulation to individual - not sure if it is correct.

E.g. in the project attached [P1_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9232375/P1_2.zip):
* I have set Bone|Intracellular|CYP|Initial Concentration = 2 in the Protein Expression BB, then created an Individual and a simulation with it
* In the simulation I have ovewritten this initial concetration with 20 and commited the individual into the BB
* After that I have the following situation
  * In the Expression Profile BB, the value is 2 and the **Reset** button is active. If I click on it: the value is resetted back to NaN and the button disappears (correct bahaviour I guess)
![grafik](https://user-images.githubusercontent.com/25061876/182111893-0e116ce3-a7fd-41af-b98b-b4a718ae8454.png)
  * In the individual BB, the value is 20 (correct) and the **Reset** button is active. If I click on it: **nothing happens (value remains =20, Reset button remains active)**
  ![grafik](https://user-images.githubusercontent.com/25061876/182111417-5c27f9c7-6e58-4940-82a3-4140b4d7d5c1.png)
  * OK, just noticed: the situation with non-working Reset button in individual is already after adding the enzyme to it. So if create another individual and add my enzyme: the value of the initial concentration is the one from the expression profile BB (correct) and the Reset button is active without any effect. I have created another issues for this: #2270

**Comment by msevestre** [comment]
Please reopen and explain if this is not desired

**Comment by PavelBal** [comment]
@Yuri05 so you do not miss it.

**Comment by Yuri05** [comment]
At the moment (PK-Sim 11.1.110) the behaviour is different from described here(https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2255#issuecomment-1239790234)

E.g. in this project [P10_IC.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10309318/P10_IC.zip) I set all relExp=1 in the protein-expressions-BB (thus the initial concentrations in all intracellular compartments have some non-zero values), then added the enzyme to an individual nad created a simulation:

![grafik](https://user-images.githubusercontent.com/25061876/209687167-10eba21b-e134-4e55-9ece-27f1a83d2c02.png)

After this, I have overwritten some intracellular initial concentrations **in the simulation** with the value 10 and commited the individual from the simulation back to the building block (the result is in this project: [P10_IC_changed_in_Sim.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10309348/P10_IC_changed_in_Sim.zip)

![grafik](https://user-images.githubusercontent.com/25061876/209687640-ac3bf450-580e-42ea-933e-0714bfc3d831.png)

This changed the values to 10 in the individual: 

![grafik](https://user-images.githubusercontent.com/25061876/209688709-1e4458f1-8316-4fc5-91b6-0f8b3fc3dc1b.png)

But not in the expression profile used:
![grafik](https://user-images.githubusercontent.com/25061876/209688805-a4237e92-34b7-4352-be23-2c001e94ae0b.png)

**Comment by PavelBal** [comment]
> This changed the values to 10 in the individual:
> But not in the expression profile used:

I would say this is the correct behavior.

> P.S. If after that I change any value in my expression profile: all intracellular initial concentrations in the individual jump from 10 to another values.

This I consider as a bug. The values in the individuals should only jump when explicitely updating from Expressions BB.

**Comment by msevestre** [comment]
@Yuri05 I have tried yesterday and today to reproduce the issue but I can't
Can you show me how to reproduce? I don't even see a refresh problem

So I am not sure with which version you tried. But  I can't reproduce and I have spent just too much time trying lol.

**Comment by Yuri05** [comment]
Tricky indeed :) I could finally reproduce with the latest nightly 11.1.126. Below the steps to reproduce.
The interesting part: if I save the project after step 5 ("Create simulation"), reopen it and continue with the step 6 - everything works fine. 
Thus I could not reproduce the problem with the project which I attached above as well :)
But if you create everything from scratch as described below - here we go :)

1. Add enzyme **CYP** and set all relative expressions = 1

<details><summary><b>Screen</b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/212309638-bed44802-ef5f-40c1-a702-e27db003baab.png)
</details>

2. Add Individual and add **CYP** to individual
3. Add arbitrary compound
4. Add arbitrary application
5. Create simulation

6. In the simulation: set intracellular initial concentration of all tissue organs = 10

<details><summary><b>Screen</b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/212310301-65eeb980-dadf-4d72-995a-46b2164a029a.png)
</details>

7. Commit Individual from the simulation to BB

8. Go to the Expression profile and check intracellular initial concentrations: they are not set

<details><summary><b>Screen</b></summary>

![grafik](https://user-images.githubusercontent.com/25061876/212310700-8b7fd1c4-f7fc-403c-bc06-e51c60a0c170.png)
</details>

If I save the project NOW and reopen it: initial concentrations in the expression profile are still not set, so it's not just a refresh issue.

**Comment by msevestre** [comment]
I spent so much time on this....
Ok doest not feel like such a bad bug after all

**Comment by Yuri05** [comment]
>doest not feel like such a bad bug after all 

Not sure about this. Seems we create some corrupted state here - no idea what other side effects this could have.
For example, if I save the project at the end of the whole workflow above, reopen it and change anything in my expression profile: all initial concentrations in the individual become resetted etc.

Can you reproduce with the steps above?

**Comment by msevestre** [comment]
I'll try in the afternoon today. It's good to have at least a way to reproduce
And I didn't read that the state was corrupted when the project was saved to I might be able to see what's missing

**Comment by msevestre** [comment]
@Yuri05 This with saving project was key to understand what's going on. this had to be a registration issues
After good 5 hours of debugging in two days, I think I understand. Even debugging visually because it was so hard to understand lol

![image](https://user-images.githubusercontent.com/1041237/212430113-73d6f2c7-da67-4bf9-9f57-9b035dc2ae47.png)
