### ISSUE TITLE
Snaphot including individual with uder-defined initial concentrations for protein expression cannot be reloaded

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#2256]
We have set indvidual concentrations, e.g.:
![image](https://user-images.githubusercontent.com/26569320/177748976-a8a99e6e-849a-4cf8-9d8d-df4e2d371cb8.png)

Then export snapshot. Reloading snapshot stops with error (though warning is given but actually nothing is loaded):
`Warning: Cannot evaluate formula for Initial concentration
Cannot evaluate formula for 'Initial concentration' with path '..|..|..|Fraction intracellular'`

**Comment by msevestre** [comment]
Can we have a snapshot to reproduce? thanks

**Comment by msevestre** [comment]
Snapshot received :)

**Comment by msevestre** [comment]
looking at this

**Comment by msevestre** [comment]
done
