### ISSUE TITLE
How to use PK-SIM to set the genotype of enzyme or transporter？

### ISSUE THREAD

**Issue by noxavier** [Open-Systems-Pharmacology/PK-Sim#2259]
Dear Community,
I am working on a PBPK model I have a problem. As shown in the picture, how to set the genotype of enzyme or transporter as in the picture？
Thank you in advance :)
![微信截图_20220718154823](https://user-images.githubusercontent.com/109507330/179472502-d3a0b728-48c9-4b46-a6ec-16e5e0ada93b.jpg)

**Comment by Yuri05** [comment]
Phenotype is just a free-text descriptor. It helps you to differentiate between different profiles of the same enzyme/transporter in case you have more than 1 (e.g. "healthy" vs. "disease 1" vs ...). 
s. https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-profile#definition-of-new-expression-profile-in-pk-sim-r

**Comment by msevestre** [comment]
Please ask questions in the forum next time @noxavier
