### ISSUE TITLE
including "Global" PK-Parameters into the box-plot/scatter plot

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/PK-Sim#2260]
Derived from #2227

**Comment by msevestre** [comment]
I have no idea what this is about. 
@PavelBal Can you clarify?

**Comment by PavelBal** [comment]
Add the "new" pk parameters 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/25903040/182132906-2c3b6828-9256-46db-9786-641214c6d966.png">

to box whisker/scatter plots:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/25903040/182133104-81b9065b-6331-4119-9492-0241d2ba3a01.png">



To also see the distribution of e.g. AUC ratio.

**Comment by msevestre** [comment]
not a simple task. 
PArameters are not serialized (only one aggregated value is saved in the simulation)
