### ISSUE TITLE
Trigger nightly build

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2261]
We desperately need an 11.1 version with the updated Core...

**Comment by msevestre** [comment]
Why?!?

**Comment by PavelBal** [comment]
To use the most recent version of the R package..

**Comment by msevestre** [comment]
oh you want to use in in production? Not just add features...
Ok I'll work on this  very soon

**Comment by PavelBal** [comment]
Awsome, thank you!!

**Comment by PavelBal** [comment]
Somehow the versions do not match :(

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1017

**Comment by PavelBal** [comment]
False alarm.
