### ISSUE TITLE
Simulation serialization error?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2262]
Load the project from snapshot: [Erythromycin-Model.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9167832/Erythromycin-Model.zip) The (only) simulation runs without problems. 

Save the project, close and reopen it. Run the simulation again. The error below comes:
![grafik](https://user-images.githubusercontent.com/25061876/180442390-4a81d702-369f-4ec3-9007-668b9b6e9bb4.png)

The same erro comes if after importing from snapshot I send the simulation to MoBi (or save it as pkml and open in moBi)

**Comment by Yuri05** [comment]
OK, it seems to be a purely numerical issue.

This is the SimModel-XML generated directly after loading from the snapshot: [01_BeforeSave_250mg_Birkett1990_MD.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9219335/01_BeforeSave_250mg_Birkett1990_MD.zip)
And this one after saving and reloading the project: [02_after_Save_250mg_Birkett1990_MD.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9219347/02_after_Save_250mg_Birkett1990_MD.zip)

The differences are almost non-existent (s. [this PR](https://github.com/Yuri05/Test20/pull/20/files): here I pushed first the xml 01, and then overwritten it with xml 02)

Loading the xml 01 directly from C++ works, xml 02 produces negative values.

In V10 it worked. Tracking it back: it works with SimModel 4.0.46 and it does not work with SimModel 4.0.47 anymore (which was the bugfix [jacobian calculation of the product formula wrong](https://github.com/Open-Systems-Pharmacology/OSPSuite.SimModel/pull/135))

**The issue can be solved by reducing the absolute tolerance of the simulation from 1E-10 to 1E-11**
Comparing the problematic output in V10 vs. V11 (in MoBi after allowing negative values) vs. V11 with reduced absolute tolerance: there is just one problematic data point in V11. [V10_V11_V11reducedAbsTol.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9219475/V10_V11_V11reducedAbsTol.xlsx)
We set `[-100 * AbsTol .. 100 * AbsTol]` as the range for the "numerical noise" - thus for this simulation negative values bigger than 100*1E-10 = 1E-8 are accepted - and we have this one point -1.4E-8 slightly below.

![grafik](https://user-images.githubusercontent.com/25061876/181747388-c61a0626-6338-47a9-826a-d238d4fac9af.png)

So I don't see a bug here. We could just think about if we could give to the users in PK-Sim to switch the negative values check on and off (either globally for the whole simulation, or per quantity like in moBi).

@msevestre @PavelBal Thoughts?

**Comment by PavelBal** [comment]
> We could just think about giving the users in PK-Sim the possibility to switch the negative values check on and off (either globally for the whole simulation, or per quantity like in moBi).

YES YES YES!! Globally, and also make this parameter available in MoBi. Technically, the simulation run options already has this parameter, it is just not accessible.

**Comment by msevestre** [comment]
yes agreed. It should be done globally  in the settings

**Comment by Yuri05** [comment]
ok, created an issue for the new option: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2265
Closing
