### ISSUE TITLE
When overwriting initial protein concentration in Expression Profile BB: Reset button is active in Individual with no effect

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2270]
[P2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9232503/P2.zip)
E.g. here:
* Created expression profile **CYP** and set `Bone|Intracellular|Initial Concentration = 2`
* Created an individual and added CYP. Now the reset button for the initial conc in bone is activated in the individual, clicking on it does not have any effect
![grafik](https://user-images.githubusercontent.com/25061876/182114809-91738c48-ad07-467e-9855-f5d7ddf21630.png)

If after that I go back to the Expression Profile BB and reset the init cocn value to NaN: nothing changes in the individual BB: the value is still 2, the Reset button is still active, without effect.

**Comment by msevestre** [comment]
The button should be gone

**Comment by Yuri05** [comment]
@msevestre Checked it: when chanigng the initial concentration in the simulation and commiting to the BB: the initial concentration value in the Expression Profile BB is not updated, also after closing and reopening the project.

**Comment by msevestre** [comment]
@Yuri05 Oh yes. it needs to be gone. it is not yet :)
