### ISSUE TITLE
Expression profile: why are some default initial concentration values 0?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2272]
When creating a new expression profile: the most default values for the initial concentrations are NaN.
However some of them are 0:
* Blood cells in every organ
* Lumen segments

Why is this like that?
<img width="350" src="https://user-images.githubusercontent.com/25061876/182121718-4ede97f9-7984-4c85-8f63-f62432ca300a.png"> <img width="350" src="https://user-images.githubusercontent.com/25061876/182121841-b2599478-ab01-43b6-8bd6-b99541cc7b7e.png">

**Comment by msevestre** [comment]
This is because of the formula we are using. 


![Image](https://user-images.githubusercontent.com/1041237/189194648-8830f26c-7505-4cf9-8bf1-53b98727e390.png)
