### ISSUE TITLE
UI: "About"-window

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2273]
- The logo is shown four times
- "Check for Updates" does not fit
- Text not readable

![image](https://user-images.githubusercontent.com/25903040/182316026-16578cd7-a7ad-42d6-8014-ce142861ed68.png)

**Comment by Yuri05** [comment]
Lol. we should forbid this 4K 200% combo 😉

**Comment by PavelBal** [comment]
"Check for updates" button still too small for the caption:

![image](https://user-images.githubusercontent.com/25903040/183373094-ff25d2d2-278a-4032-bc45-aa6aaa2de2e3.png)

**Comment by Yuri05** [comment]
seems to be fixed. @PavelBal please reopen if not

**Comment by PavelBal** [comment]
11.1 build 121 - "Check for updates" button still too small for the caption:

**Comment by PavelBal** [comment]
Build 122 too.

**Comment by rwmcintosh** [comment]
To my knowledge no one has addressed this specifically in v12, but I tried with 4k @ 200%.
- V11 Udpate 1: button too small
- V12 : button works ok

![image](https://user-images.githubusercontent.com/261477/229489623-1ceebf5a-da4d-4b4c-9865-54cb2a9c0619.png)

![image](https://user-images.githubusercontent.com/261477/229489384-c59c7c5a-7831-424a-89e5-d0361e593553.png)
