### ISSUE TITLE
UI: Ontogeny data window - x axis missing

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2274]
When opening ontogeny data preview in the expression BB, the x axis (ages) is not shown.

![image](https://user-images.githubusercontent.com/25903040/182316487-7b7840f1-b367-4123-aaca-89aa91ff456f.png)

**Comment by PavelBal** [comment]
4K, 200% scaling.

**Comment by msevestre** [comment]
good catch
