### ISSUE TITLE
UI: Create individual -> Individual parameters are hidden if CKD disease state is selected

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2277]
With "Healthy":

![image](https://user-images.githubusercontent.com/25903040/182325841-16d0cc92-5101-4864-b09d-25cb17e4e2e9.png)

With "CKD":

![image](https://user-images.githubusercontent.com/25903040/182325911-680c23bb-e84f-4298-81c4-91bafc0112a9.png)

**Comment by msevestre** [comment]
Can you try and let me know. Works for me on 250% scaling

**Comment by PavelBal** [comment]
"Value origin" is not there:

![image](https://user-images.githubusercontent.com/25903040/183373624-e88eb087-45b3-434c-9cde-3453d85406af.png)

**Comment by msevestre** [comment]
This is so annoying. Same stuff as before. we will have to experiment

**Comment by Yuri05** [comment]
seems to be fixed. @PavelBal please reopen if not

**Comment by PavelBal** [comment]
"Value origin" is now not shown with and without CKD :D

**Comment by msevestre** [comment]
Well I don't have a solution for you. I am giving up on this. @rwmcintosh has a 4k and can fix it. Impossible to fix a bug that you can't reproduce

**Comment by Yuri05** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2506
