### ISSUE TITLE
UI: Creating population - "Stop" button too small

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2278]
When creating a population, the "Stop" button looks like this:

![image](https://user-images.githubusercontent.com/25903040/182326475-0546c910-dabc-4313-9adc-2072cbbf4928.png)

**Comment by msevestre** [comment]
evne you cancel button is weird.
I'd love to know if what I changed fixed this

![image](https://user-images.githubusercontent.com/1041237/182983379-1dee8555-2386-45cc-8221-a26bf32858ed.png)

**Comment by msevestre** [comment]
225% 
![image](https://user-images.githubusercontent.com/1041237/182984460-9f3ad84e-77f7-4dc3-8aed-4358837d75d8.png)

Please try and let me know

**Comment by PavelBal** [comment]
Much better, but some pixels for padding between the stop-icon and the button edge would be even better:

![image](https://user-images.githubusercontent.com/25903040/183372718-fc9cefdf-155b-41b6-8d74-c6bb74013430.png)


I can live with the current state, but I am wondering if icons are scaled differently from button size? I have 200% scaling.

**Comment by msevestre** [comment]
We are not scaling the icons. We are only scaling the sizes. It seems that something is still not perfect

**Comment by msevestre** [comment]
@PavelBal In order to fix this, I would need to spend one or two hours with you so find the right balance of things..
