### ISSUE TITLE
PK-Sim DB: unused tables

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2281]
* tab_properties
* tab_dts_properties
* tab_distribution_values

I think those tables can be safely removed. They are empty, not referenced by other tables, not used in any query and not used directly in PK-Sim.
@msevestre The first two tables were required for objectiF and/or for DTS and will be never used for sure. The last one (**tab_distribution_values**) - any idea what was the motivation to introduce it?

**Comment by msevestre** [comment]
nope. Let's remove
