### ISSUE TITLE
PK-Sim DB: unused table in the query

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2282]
The table **tab_species** seems to make no sense in the query below - it is used neither for table linking nor for the data selection.
![grafik](https://user-images.githubusercontent.com/25061876/182422741-30251930-edf3-4401-8b0e-d62087aa1f60.png)

Result is just the duplication of the output entries:
![grafik](https://user-images.githubusercontent.com/25061876/182423289-6e6475ed-fcc3-4deb-8226-d54289f56cdb.png)

@msevestre Or can you think about any  meaningful reason for having the species in the query?

**Comment by msevestre** [comment]
nope
