### ISSUE TITLE
UI: Parameter disappears when trying to edit another parameter

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#2285]
For a compound in PK-Sim I added an parameter for the “Specific organ permeability” at the “Distribution Calculation” tab (cf. attached Fig. 1). 
When trying to edit the added parameter (changing the value or rename it) the other parameter “Calculated” disappears (cf. attached Fig 2). If one leaves the “Distribution Calculation” tab and returns again, the parameter “Calculated” is shown again but this is unhandy if one wants to look e.g. at the value for the parameter “Calculated”. This happens in the same way at the “Specific Intestinal Permeability” tab. 

![Fig1](https://user-images.githubusercontent.com/26439150/182572208-a1c3c0c9-44e2-453f-adca-6404a16f6113.jpg)

![Fig2](https://user-images.githubusercontent.com/26439150/182572255-a60d72bd-d601-4fae-9935-3971898eb8b4.jpg)

**Comment by msevestre** [comment]
Can you try and let me know. Works for me on 250% scaling after the latest changes
Fixed with #2294
