### ISSUE TITLE
Software logo and name of splash screen somewhat pixelated in v11 

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#2289]
When launching the software, the logo and name are somewhat blurry whereas in previous versions they were pin sharp.
I use a 27'' full HD monitor with a resolution of 1920 x 1080 and have the Windows option of `Fix scaling for apps` enabled

**Comment by msevestre** [comment]
Yes this is because this is not a SVG but a png. WE do not have a SVG for this...

**Comment by AndreDlm** [comment]
Why don't create one?

**Comment by msevestre** [comment]
Well someone needs to design it from scratch again :) => $$

**Comment by StephanSchaller** [comment]
Yes, we actually do have them. Didn't know you did not... let me load them up

**Comment by StephanSchaller** [comment]
[Uploading OSP Logos vector.zip…]()

Does this help?

**Comment by msevestre** [comment]
Hum..... where from? 
It's not a PNG converted in svg today. It's a real svg. But if you have it... awesome

**Comment by StephanSchaller** [comment]
It might be that this was created when our marketing partner created our digital content... but it looks like the PK-Sim Vector Graphic is a bit off... I will check it

**Comment by StephanSchaller** [comment]
[Uploading OSP Logos Vector.zip…]()

Vector Graphics Glitches corrected

**Comment by msevestre** [comment]
Upload failed. No files attaached

**Comment by StephanSchaller** [comment]
[OSPS Logos Vector.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9257730/OSPS.Logos.Vector.zip)
 now?

**Comment by msevestre** [comment]
better but 
![image](https://user-images.githubusercontent.com/1041237/182964549-44529987-1ffe-4ac9-b5a1-961a907bf8f4.png)

One section does not seem to be valid, at least not for dev express svg component
Any idea what's so special abou thtis?

**Comment by StephanSchaller** [comment]
hm, yes, it is a gradient colour fill, I will see what I can do :-)

**Comment by StephanSchaller** [comment]
[PKSim_logo_vector.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9264098/PKSim_logo_vector.zip)

Try V3 or V2... if these don't work take V1

**Comment by msevestre** [comment]
yeah aspect ratio is clear. I just wanted to try.
v1 did not work. V2did.
The edges of the PK-Sim symbol are not very round .But this is better I think that what we had before

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/182981758-621d491d-2d90-4125-943a-63c82e956423.png)

**Comment by msevestre** [comment]
@StephanSchaller The R from registered is a bit cut, can you add a little bit of padding top somehow?
![image](https://user-images.githubusercontent.com/1041237/182982248-9110e80f-1ca1-4eea-bfb2-67fb97ac5444.png)

**Comment by StephanSchaller** [comment]
[PKSim_logo_vector_white.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9267863/PKSim_logo_vector_white.zip)
 Try V2 here. Indeed it as a bit cropped

**Comment by msevestre** [comment]
yeah perfect
![image](https://user-images.githubusercontent.com/1041237/183082431-224d70f0-1cee-4740-92ec-e0f9a2d392c2.png)
