### ISSUE TITLE
Link to manual

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/PK-Sim#229]
In order to facilitate the use of the software and to encourage the use of the manual, I would purpose to restructure the manual and directly link it to the software tool. On every screen or pop-up window in the software, an icon should directly forward the user to the manual page of interest. This may allow the user to solve not only the most easiest questions but also to help him understand the software

**Comment by msevestre** [comment]
Isn't it was the F1 button does? It should jump to the page in the manual
describing the use of the active view or screen.

**Comment by JanSchlender** [comment]
Great feature :) Haven't discovered it before. How can every user be aware of it when navigating within the software? The question mark at the top right also leads to the manual but can only be used when no pop-up window is there.

**Comment by msevestre** [comment]
F1 is a typical shortcut for Help. 
Maybe try to do something like what Excel is doing for modal window

![image](https://user-images.githubusercontent.com/1041237/27491744-8b51e162-5811-11e7-88a8-ae6f556c5a95.png)
