### ISSUE TITLE
V11 Bug: OCT1 Influx expression profile populates on apical side of liver rather than basolateral

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/PK-Sim#2302]
Other influx transporters may also be affected.  Can be fixed manually of course, but the autopopulate from the Genedb may be misleading.

**Comment by prvmalik** [comment]
Also affects OATP1B1. Probably affects all Influx transporters.

**Comment by Yuri05** [comment]
>Probably affects all Influx transporters. 

Seems to affect only **known** (stored in the PK-Sim DB) Influx transporters. 
![grafik](https://user-images.githubusercontent.com/25061876/183510661-dd357594-9d0a-4afe-874d-ca37c4a5aae5.png)

**Comment by Yuri05** [comment]
@msevestre DB entries are correct, so it's during the transport creation where the fraction basolateral is not properly set - interestingly only if the transporter is available in the PK-Sim DB. When creating an influx transporter which is unknown - fractions are set correctly (like in the screen above)
![grafik](https://user-images.githubusercontent.com/25061876/183634358-bf743cd8-3ea8-4b43-88c7-3d2157246ab3.png)

**Comment by prvmalik** [comment]
Affects both Liver and kidney. I don't recall the proper default for influx at BBB.

**Comment by msevestre** [comment]
I don't understand from the screenshots above, what the problem is.

**Comment by prvmalik** [comment]
When you do a database query and import the expression profile for an influx transporter e.g. OCT1, OATP1B1, the "Fraction Apical" in the liver and kidney populates as 1.00 when it should be 0.00. BBB may also be affected.

**Comment by Yuri05** [comment]
The problem is that when creating those transporters, they are defined as basolateral but created as apical.
So all fraction_expressed_apical below  must be 0, not 1
![grafik](https://user-images.githubusercontent.com/25061876/183643755-e39dc5d1-de7c-4f95-ad6e-6189d6ca4fe7.png)

**Comment by msevestre** [comment]
Well not surprising. We are not using the membrane anymore. The concept of basolateral, apical etc.. was completely removed from PKsim in favor of the fraction expressed. I guess this part was not properly understood during the migration
