### ISSUE TITLE
Quality of Life UI: Value Origin

### ISSUE THREAD

**Issue by prvmalik** [Open-Systems-Pharmacology/PK-Sim#2304]
I used to really like how when setting the value origin, you could click away from the box and it would save your entries. Now you must press "OK" for it to save, and if you click away the value origin goes blank. Not a necessity to have this feature again but I did appreciate the efficiency and versatility in the previous version.

**Comment by msevestre** [comment]
lol. I have to agree with you on this. But this behaviour was frowned upon by a few that did not expect this from a modal view( e.g. clicking away from a modal always cancels normally). So we changed it to follow UX expectations. 
That being said, I preferred it also as it used to be :)

**Comment by msevestre** [comment]
no change required here as this is By Design
