### ISSUE TITLE
The OSPS Expression Database: loaded unsuccessful

### ISSUE THREAD

**Issue by miyayayayaa** [Open-Systems-Pharmacology/PK-Sim#2305]
Dear all, I had a question about "The OSPS Expression Database loaded".

After I donwloaded “The OSPS Expression Database” from Github and and uploaded  it to the PK-sim, I still could not find the "Add Metabolizing Enzyme... (Database query)". I only found the"Add Metabolizing Enzyme". And the whole uploading process had no errors.  
I also restarted the software and computer, but these did not work. 

I want to know whether anyone meet the same question and how to solve it？

**Comment by miyayayayaa** [comment]
Have solved. I refered the lesson for version10 but version 11 is different from verison 10, so the button is at another location.

**Comment by Yuri05** [comment]
@miyayayayaa If you have questions, you should post them in the [OSP forum](http://forum.open-systems-pharmacology.org/). The forum is read by far more people than repository issues here.
