### ISSUE TITLE
Question for autoinduced compound 

### ISSUE THREAD

**Issue by miyayayayaa** [Open-Systems-Pharmacology/PK-Sim#2308]
Dear All, I recently did the PBPK model for a compound which is the autoinduced for CYP3A4. But after dosing for 14 days, its expourse did not decrease, but instead accumulated. I wonder why it happened. And the parameters were following:

1. metabolism-metabolizing enzymes- CYP3A4 - in vitro metabolic rate in the presence of liver miscrosomes（Michaelld-Menten）- Vmax=100 pmol/min/mg  mic protein & Km=1 umol/L
2. transport & excretion-induction-CYP3A4 - EC50=20umol/h &Emax=5

These were all paramets related to induceing. Why is there no autoinduced reduction in drug exposure?

**Comment by StephanSchaller** [comment]
Dear @miyayayayaa , this can only be answered by knowing the exact parameterization of the model, or ideally by haveing a copy of the model.
One reason might be, that you do not reach the required >= 29 µmol t the location of induction for it to have any effect.

Best,
Stephan

**Comment by miyayayayaa** [comment]
Dear @StephanSchaller,  I have solved this question  beacuse I did not choose the interation process in compound. Thank you.
