### ISSUE TITLE
PKSim DB: tab_transport_directions.global

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2310]
What is the column **global** in the table **tab_transport_directions** used for?
It has the value 0 for all entries. 

![transport_directions](https://user-images.githubusercontent.com/25061876/184865739-c197906e-0112-4d05-8c82-cd1f8f62d0c5.png)

**Comment by msevestre** [comment]
hum. If this is not used in any mapping ,this is not used at all/.Let's delete
