### ISSUE TITLE
Specific intestinal permeability from Caco-2 experiment 

### ISSUE THREAD

**Issue by miyayayayaa** [Open-Systems-Pharmacology/PK-Sim#2313]
Dear All, When entering specific intestinal permeability in the compound absorption section, if I have Caco-2 experimental data results, do I need to enter A-B or B-A data or efflux ratio?

**Comment by StephanSchaller** [comment]
@miyayayayaa, if at all, use the A-B direction in case of passive permeability (no transporters involved). But a lot depends on the assay & lab conditions (see e.g. https://doi.org/10.1016/j.ejps.2016.09.027 ) and the translation to Peff should be calibrated per lab (https://pubmed.ncbi.nlm.nih.gov/9165541/ )

**Comment by msevestre** [comment]
Please ask questions in the forum in the future/ Thanks
