### ISSUE TITLE
Unable to load templet for compounds in pk sim version 11

### ISSUE THREAD

**Issue by nirav3223** [Open-Systems-Pharmacology/PK-Sim#2314]
Hi,

I am getting the error while loading the templet for compound in PK SIM  version 11. It showing like TPI/TSP channel error something like this. Further I want to run DDI simulation of cimetidine and midazolam in which i have added ki value of CYP3A4 but while simulating the model I am not getting the option add interaction tab as it available in previous version 7.1. 

Thanks in advance.

**Comment by msevestre** [comment]
This looks like an issue with your firewall. Please check your configuration
For the second question, please ask in the forum
