### ISSUE TITLE
new to PK-Sim: how to expand options in calculation methods variation?

### ISSUE THREAD

**Issue by xyschvrie** [Open-Systems-Pharmacology/PK-Sim#2317]
[](url)
![Screenshot 2022-09-06 064929](https://user-images.githubusercontent.com/112945005/188617285-12d186b3-9ac3-4060-9fd9-6dfb243db5f4.png)
I'm new to using PK-Sim and trying to increase my number of optimisations by selecting all the options on the bottom (cellular permeabilities and partition coefficients) as seen in the screenshot. However, there are no options for me to do so. How do I get past this problem?

**Comment by msevestre** [comment]
Please ask your questions in the forum 
https://github.com/Open-Systems-Pharmacology/Forum/discussions
