### ISSUE TITLE
PK-Sim Standard Method for Partition Coefficient Calculation

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/PK-Sim#232]
Hello,

I found equations used for PK-Sim standard method for partition coefficient calculations in the manual. However, I am wondering about impact of trying different methods for partition coefficient on plasma concentration time profiles and trying to figure out if there is any basic rule for when to use which method. For my small molecule, I am getting good fit to observed data using PK-sim standard method, but conc-time plots following other methods for partition coefficient is quite different than observed. 

So, my question is whether there are any publications that you can refer me describing more about PK-Sim standard method (other than manual)? Any publications for comparing different partition coefficient methods?

Many thanks,
Krina

**Comment by Aedginto** [comment]
Hi Krina,
My go-to method is Rodgers and Rowland in 90% of cases. 
All of the algorithms for partition coefficients (both tissue composition based and correlation based) depend heavily on the lipophilicity value. Lipophilicity can be measured in many ways or can be estimated in silico. Regardless of how lipophilicity is measured, within a partition coefficient algorithm, it tends to be the most uncertain value. As a result, using IV data for optimization of both the partition coefficient algorithm and  lipophilicity is reasonable. Curve shape following IV is extremely sensitive to partition coefficients. You can do this in the optimization toolbox by selecting lipophilicity to optimize and then selecting the partition coefficient algorithms for which you want to optimize lipophilicity. The program will then optimize lipophilicity for your data using each selected partition coefficient algorithm and you can select which is best to move forward with. If you don't have IV data, this becomes much more difficult as the absorption phase tends to hide distribution, which is sensitive to partition coefficients.

Also, remember that no one partition coefficient algorithm is best all the time. They are simply different. 
I think the ref for the PK-Sim method is in: Expert Opin Drug Metab Toxicol. 2005 Jun;1(1):159-68.
From physicochemistry to absorption and distribution: predictive mechanistic modelling and computational tools.

Take care,
Andrea

**Comment by krinaj** [comment]
many thanks, Andrea. Very useful.
