### ISSUE TITLE
PopSim: PK-Parameters for range 2.5%-97.5% are, only 2.5% is shown

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2323]
Selected ouputs are "Range 5-95%" and "Range 2.5-97.5%". For the range 5-95%, two columns for PK-paramter values are shown - one for 5%, one for 95%, as specified. For the range 2.5-97.5%, only one columen is shown with the caption "range 2.5% to 97.5%", showing the values for 2.5% only.

![image](https://user-images.githubusercontent.com/25903040/189088149-10b1d37e-bf3b-4a8b-b0b6-dc801f283efc.png)

![image](https://user-images.githubusercontent.com/25903040/189088601-ea6a389a-2cf7-470b-ab68-064c40c5c67d.png)

**Comment by msevestre** [comment]
The feature that keeps on giving.....

**Comment by msevestre** [comment]
indeed
![image](https://user-images.githubusercontent.com/1041237/190197412-b23fa444-135f-4dde-b4f5-43ce67b24405.png)

**Comment by msevestre** [comment]
USe project from #2324

**Comment by PavelBal** [comment]
It is now correct for "Aggregated PK values":

![image](https://user-images.githubusercontent.com/25903040/191243902-a46d4158-76d7-4478-8886-06d0d1f165b1.png)


For Individual PK values, still only one column per range with only lower % is shown:

![image](https://user-images.githubusercontent.com/25903040/191244030-61a34022-6e4b-4cb5-8d19-8a169d9affce.png)

**Comment by PavelBal** [comment]
11.1 Build 41

**Comment by rwmcintosh** [comment]
@PavelBal more consistently wrong in this case!

**Comment by msevestre** [comment]
I like consistency

**Comment by PavelBal** [comment]
I don't like wrong :D

Michael Sevestre ***@***.***> schrieb am Di., 20. Sept. 2022,
15:15:
