### ISSUE TITLE
PopSim: PK parameters On Individuals are shown only for one compound, even if multiple are selected

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2324]
I selected two compounds for the output, and the "On Curves"-tag shows pk parameter values for both compounds:

![image](https://user-images.githubusercontent.com/25903040/189099587-c9143b32-5586-4d17-978c-1aec49c7ef40.png)

The "On Individuals" tab, however, shows only values for "Esomeprazole"

![image](https://user-images.githubusercontent.com/25903040/189099733-d712198d-d74b-4b80-a239-820f472381cc.png)

**Comment by Yuri05** [comment]
Should we rename "On curves" and "on individuals" to something like "Aggregated PK values" / "Individual PK values"?

**Comment by PavelBal** [comment]
Hmmm... I agree that "on curves" and "on individuals" are not the best namings. But "Individual PK values" are also agregated at the end (we are not showing the individual values), so it might be a bit confusing...

**Comment by msevestre** [comment]
[2324.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9567752/2324.zip)
