### ISSUE TITLE
PKSim.R.dll in portable Version 11.0.150 is broken

### ISSUE THREAD

**Issue by onwhenrdy** [Open-Systems-Pharmacology/PK-Sim#2325]
The portable version 11.0.150 of PK-Sim has (likely) a broken PKSim.R.dll shipped and the assembly cannot be loaded by the R package rClr. The PKSim.R.dll version installed by the corresponding Installer (OSP-Suite) works as intended.

**Comment by onwhenrdy** [comment]
> Thos version is very high probability (close to 100% the same) as one is created from the other (the portable) Can you paste the error that you are getting? I think we had a similar issue in the past. @Yuri05 Do you recall?

Error is:
Error in rClr::clrLoadAssembly(pksimR) : 
  Failure in rclr_ms_call_static_method, but could not retrieve an error message

Tried it on 2 machines. Fix was to copy the dll from the Suite-Version.

**Comment by msevestre** [comment]
Copying the dll worked?!? WHAT? Well I am glad I said it was close to 99%. 
I honestly do not know how this is possible..hum

**Comment by onwhenrdy** [comment]
> Copying the dll worked?!? WHAT? Well I am glad I said it was close to 99%.
> I honestly do not know how this is possible..hum

Tried it 10 minutes ago with fresh download of the portable. Teammates tried it too and assembly loading failed as well. As I wrote ... dll from Suite fixes the issue.

**Comment by onwhenrdy** [comment]
FYI: Compared both versions of the dll (Suite and portable) with fc and found **NO** differences in file payload.  No idea why the portable version does not work on any machine tested with ospsuite R package and works after patching the dll.

**Comment by PavelBal** [comment]
This is windows defender blocking DLLs that you downloaded from being loaded. Right-click on PK-Sim portable folder and select "unlock" before extracting.

**Comment by Yuri05** [comment]
@PavelBal Good hint! We should add it to the release notes of **PK-Sim** (https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/tag/v11.0.150).
With other security software it's even worse (e.g. Norton Antivirus deletes every single DLL from the extracted PK-Sim portable file, and you can only undo it within few seconds, otherwise it's lost forever.

**Comment by onwhenrdy** [comment]
> This is windows defender blocking DLLs that you downloaded from being loaded. Right-click on PK-Sim portable folder and select "unlock" before extracting.

Thanks Pavel for the hint. Do you know by chance if this could be prevented if the dll is signed?

**Comment by PavelBal** [comment]
> Do you know by chance if this could be prevented if the dll is signed?

No idea honestly :D

**Comment by msevestre** [comment]
What I don't understand: why copying the exact same DLL from somewhere else solve the problem. E.g. why is the antivirus then happy?

**Comment by PavelBal** [comment]
Installing a software marks the DLLs als unlocked, there are not "trustworthy" when extracting from archives.
