### ISSUE TITLE
PDF report creation fails

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#233]
When I try to create a PDF-report of a simulation, it fails

"Report could not be created. Please see log for detailes located under "SelectedPath"".

However, I cannot find any report in the specified folder. I attached the contents of the output folder.
[Report.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1101936/Report.zip)

**Comment by msevestre** [comment]
Does it happen with all projects or simulations?

**Comment by PavelBal** [comment]
Yes.

**Comment by msevestre** [comment]
@PavelBal There is probably something that went wrong with your installation. 
Does the `oops` exception window pops-up or simply a message box? Can you copy paste the entire message (you can do CTRL+C on a message box to copy the entire message)

Last, I am presuming that you are using 7.1?

**Comment by PavelBal** [comment]
Yes, 7.1. No exception, just the message box. Copying the message box content does not work as I get an exception trying to do so:
Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.Threading.ThreadStateException: Für den aktuellen Thread muss der STA-Modus (Single Thread Apartment) festgelegt werden, bevor OLE-Aufrufe ausgeführt werden können. Stellen Sie sicher, dass die Hauptfunktion mit STAThreadAttribute gekennzeichnet ist.
   bei System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   bei DevExpress.XtraEditors.XtraMessageBoxForm.CopyContent()
   bei DevExpress.XtraEditors.XtraBaseForm.ProcessCmdKey(Message& msg, Keys keyData)
   bei System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   bei System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   bei System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   bei System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

**Comment by msevestre** [comment]
What about a screenshot then?

**Comment by PavelBal** [comment]
![unbenannt](https://user-images.githubusercontent.com/25903040/27542202-e0743ad8-5a86-11e7-8a3f-e35cda9167ce.JPG)

**Comment by msevestre** [comment]
@PavelBal It feels like a problem with your MikTex installation. 
Can you create pdf report from MoBi at all?

**Comment by PavelBal** [comment]
No, no reports are possible. It also fails with the SBSuite Validation Tool.

This could be because of the fact that I have my own MikTex installation.

**Comment by msevestre** [comment]
OK so your installation of our `MikTex` package is corrupted for some reason. Clearly MikTex is found otherwise we would get another error. Very weird

**Comment by msevestre** [comment]
Could you create reports with 7.0? Also did you install your `own` MikTex install after installing 7.0 or before? Same question with 7.1

**Comment by msevestre** [comment]
What's the content of this file on your installation?

![image](https://user-images.githubusercontent.com/1041237/27689134-2e264890-5cab-11e7-9324-a0d77c73ecfa.png)

**Comment by PavelBal** [comment]
> Could you create reports with 7.0? Also did you install your own MikTex install after installing 7.0 or before? Same question with 7.1

Cannot say, I never used to create reports before. The separate MikTex installation was performed before installing OSPS 7.1.

> What's the content of this file on your installation?

[Paths]
CommonInstall=C:\Program Files (x86)\Open Systems Pharmacology\MikTex 2.9.3\
CommonData=C:\ProgramData\Open Systems Pharmacology\MikTex 2.9.3\
CommonConfig=C:\ProgramData\Open Systems Pharmacology\MikTex 2.9.3\

**Comment by msevestre** [comment]
I have no idea. This all looks ok to me....

**Comment by msevestre** [comment]
On a fresh VM:
I have installed Suite 6.3
Updated to OSP 7.0
Updated to OSP 7.1

I could generate reports with each of these Versions. So there is somethign going on with your current setup. If you do not need your own miktex install, my suggestion would be to remove it

**Comment by msevestre** [comment]
Cannot reproduce issue on VM with and without previous install.
