### ISSUE TITLE
Should we rename "On curves" and "on individuals" to something like "Aggregated PK values" / "Individual PK values"?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2331]
Should we rename "On curves" and "on individuals" to something like "Aggregated PK values" / "Individual PK values"?

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2324#issuecomment-1241695896_

**Comment by PavelBal** [comment]
> Hmmm... I agree that "on curves" and "on individuals" are not the best namings. But "Individual PK values" are also agregated at the end (we are not showing the individual values), so it might be a bit confusing...

But if there no better suggestions, I agree on the proposal.
