### ISSUE TITLE
Population PK Values: aggregate with median instead of arithmetic mean

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2338]
Please extend the caption with the type of the mean which is used for the calculation (_arithmetic_ or _geometric_)

![grafik](https://user-images.githubusercontent.com/25061876/190368824-a65707fc-5261-46cb-a42e-69d535b6e394.png)

**Comment by PavelBal** [comment]
I think it is arithmetic, but please double-check in the code.

**Comment by rwmcintosh** [comment]
Individual curves are aggregated using arithmetic mean

**Comment by msevestre** [comment]
Can you paste the ref to the line where this happens for future reference?

**Comment by rwmcintosh** [comment]
This line here determines the type

https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/ce001607590c64f7c953cc2aa95f83cc8c0b7ddf/src/PKSim.Core/Model/PopulationSimulation.cs#L283

**Comment by Yuri05** [comment]
Actually isn't it better to calc the PK values from the **median** population curve and not from mean?

**Comment by PavelBal** [comment]
Actually yes, but it should be done for all PK-parameters to stay consistent.

**Comment by Yuri05** [comment]
>but it should be done for all PK-parameters to stay consistent. 

Do you mean that for individually calculated PK parameters the **median** should be shown then as well? (which I would answer with 'Yes')

**Comment by Yuri05** [comment]
> Sorry, this did not really make sense what I wrote. Just the parameters that are shown in the upper part should be calculated for the median
> 
> ![image](https://user-images.githubusercontent.com/25903040/191238608-08cc0f2c-4e73-41da-8d66-8256cbf3901c.png)
> 
> For "Individual PK Values", the user selects which type of aggregation he wants to have.

ok, so let's calc them for the median then! (and change the caption accordingly :)

**Comment by Yuri05** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/OSPSuite-603bcc85609ed100156b295e/issues/Open-Systems-Pharmacology/PK-Sim/2338?planning-poker) with Zenhub @PavelBal @georgeDaskalakis @rwmcintosh
