### ISSUE TITLE
PK-Sim 11.1 Global Pop PK-Analysis: why is re-run simulation  required?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2339]
Open the project https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/raw/v11.0.1/Alfentanil/Alfentanil-Pediatrics.pksim5 and then the (pop) simulation `Meistelman 1987 children` in PK-Sim 11.1

Go to the time profile and click on PK-Analysis.

Global PK-Analysis requires to re-run the simulation even though Peripheral Venous Blood Plasma - Arithmetic Mean was calculated in the original simulation. Why?

Original project was created with PK-Sim 11.0.

![grafik](https://user-images.githubusercontent.com/25061876/190393996-e047cb43-fd80-4211-b2a2-8ba0b217a56b.png)

**Comment by msevestre** [comment]
The calculation is required because we need some f abs values as well which requires another output that is probably not saved in your population?

**Comment by msevestre** [comment]
It's because you are missing venous blood
![image](https://user-images.githubusercontent.com/1041237/190411470-b11175fb-c956-40d6-9659-b7939600d5aa.png)

**Comment by Yuri05** [comment]
>It's because you are missing venous blood

Could be. I thought it would be always calculated in the background (even if not selected by user as an output), but maybe not.

**Comment by msevestre** [comment]
it was for individual simulation but not for population simulation
it is now :)

**Comment by Yuri05** [comment]
OK, I see. Then nothing to do here :)
