### ISSUE TITLE
Blood to plasma concentration ratio

### ISSUE THREAD

**Issue by mlcraig** [Open-Systems-Pharmacology/PK-Sim#234]
As a follow-up to issue #232, when using Rodgers and Rowland, the manual states: "...additional input parameters are therefore necessary for the calculation of partition coefficients: the blood to plasma
concentration ratios BPratio, as a measure for electrostatic interactions of drugs with acidic phospholipid..." and I'm just wondering where to input the BPratio when entering the compound's parameters?

**Comment by msevestre** [comment]
@mlcraig Would you be ok to move that questions to the forum? This will help further users in the future.
Closing for now. Thanks
