### ISSUE TITLE
Make sense of the AggregatePKAnalysis function

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2341]
```
      public IReadOnlyList<PopulationPKAnalysis> AggregatePKAnalysis(Simulation simulation, IEnumerable<QuantityPKParameter> pkParameters, IEnumerable<StatisticalAggregation> selectedStatistics, string captionPrefix)
      {
         var pkParametersList = pkParameters.ToList();
         var matrix = new FloatMatrix();
         var names = pkParametersList.Select(x => x.Name).Distinct().ToList();
         pkParametersList.Each(pkParameter => matrix.AddValuesAndSort(pkParameter.ValuesAsArray));

         var results = new List<PopulationPKAnalysis>();
         selectedStatistics.Each(statisticalAnalysis =>
         {
            var aggregated = _statisticalDataCalculator.StatisticalDataFor(matrix, statisticalAnalysis).ToList();
            aggregated.Each((agg, index) =>
            {
               var name = correctNameFromMetric(_representationInfoRepository.DisplayNameFor(statisticalAnalysis), aggregated.Count > 1, index == 0, captionPrefix);
               var pkAnalysis = buildPopulationPKAnalysis(buildCurveData(pkParametersList[index], name), agg, names, simulation);
               results.Add(pkAnalysis);
            });
         });
         return results;
```

@rwmcintosh I see a lot of stuff is based on index and I am wondering if we can rewrite this. Specifically, the distinct surprises me here. Let see if we can make it better

**Comment by Yuri05** [comment]
@msevestre You mean, till now it did not have any sense? 😉

**Comment by msevestre** [comment]
More or less. This is a new function introduce with the new pop feature and I missed it during code review. I cannot tell if this is doing the right thing and specifically I believe it's not really tested

**Comment by rwmcintosh** [comment]
I think it's not a coincidence that the indexes match up, but this isn't obvious. A more cohesive representation would make it better.

The DISTINCT is not necessary now since the presenter is not supplying a list of all pk parameters for all compounds, but only the pk parameters for the compound identified in the captionPrefix. Previously, the names would be repeated for each compound when you do this SELECT.

**Comment by msevestre** [comment]
Yes. There is no reason to create arrays on one place and that another functions assumes that they are the same length.
The distinct for me is a killer because it meant that ONLY after distinct, are the array the same length?!?

**Comment by Yuri05** [comment]
I assume this issue can be closed now?

**Comment by msevestre** [comment]
Yep
 Code is gone
