### ISSUE TITLE
Implement "Parameter Value Export" for Expression Profiles BB in PK-Sim

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2344]

**Comment by PavelBal** [comment]
Available in "DevMode" only.

**Comment by msevestre** [comment]
This is (I believe) the entry point
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Presentation/Presenters/Simulations/ParameterValuesDebugPresenter.cs#L30

In ExpressionProfile. GetAllChildren should be `overridden`.
