### ISSUE TITLE
Calculation of median global PK parameters

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#2358]
As I implement calculation of global PK values for each individual for use in population analyses, the task of scaling for individual body weights has to be considered.

For these calculations, it's fine because we can perform the scaling for each individual just like any other PK Analysis. However, what's already been implemented for median curves does not have any weight scaling associated. That means that PK values using body weight in units are potentially incorrectly calculated.

```
         var vssPlasma = createParameter(CoreConstants.PKAnalysis.VssPlasma, bloodPlasmaPK[Constants.PKParameters.Vss], CoreConstants.Dimension.VolumePerBodyWeight);
         var vssPlasmaOverF = createParameter(CoreConstants.PKAnalysis.VssPlasmaOverF, bloodPlasmaPK[Constants.PKParameters.Vss], CoreConstants.Dimension.VolumePerBodyWeight);
         var vdPlasma = createParameter(CoreConstants.PKAnalysis.VdPlasma, bloodPlasmaPK[Constants.PKParameters.Vd], CoreConstants.Dimension.VolumePerBodyWeight);
         var vdPlasmaOverF = createParameter(CoreConstants.PKAnalysis.VdPlasmaOverF, bloodPlasmaPK[Constants.PKParameters.Vd], CoreConstants.Dimension.VolumePerBodyWeight);
         var vssPhysChem = createParameter(CoreConstants.PKAnalysis.VssPhysChem, calculateVSSPhysChemFor(simulation, compoundName), CoreConstants.Dimension.VolumePerBodyWeight);
         var totalPlasmaCL = createParameter(CoreConstants.PKAnalysis.TotalPlasmaCL, bloodPlasmaPK[Constants.PKParameters.CL], CoreConstants.Dimension.FlowPerWeight);
         var totalPlasmaCLOverF = createParameter(CoreConstants.PKAnalysis.TotalPlasmaCLOverF, bloodPlasmaPK[Constants.PKParameters.CL], CoreConstants.Dimension.FlowPerWeight);
```

@PavelBal @msevestre We are calculating first the median curve for all individuals, then we are calculating these PK values from the median curve. Would it be more correct to calculate all PK values for each individual (with scaling) and then take the median of the values for this aggregated PK value?

**Comment by rwmcintosh** [comment]
See #2260

**Comment by msevestre** [comment]
@PavelBal @Yuri05 
I think calculating those values based on the median curve and using the default individual BW does not make sense
I think the global PK should be the median of VSS instead of the VSS of the median

**Comment by StephanSchaller** [comment]
> @PavelBal @msevestre We are calculating first the median curve for all individuals, then we are calculating these PK values from the median curve. Would it be more correct to calculate all PK values for each individual (with scaling) and then take the median of the values for this aggregated PK value?

Yes

> @PavelBal @Yuri05 I think calculating those values based on the median curve and using the default individual BW does not make sense I think the global PK should be the median of VSS instead of the VSS of the median

and yes

**Comment by msevestre** [comment]
excellent. Thanks @PavelBal  (I meant @StephanSchaller )
And thanks @rwmcintosh for pointing this out

**Comment by Yuri05** [comment]
Agree, median of PK makes more sense than PK of the median curve.
