### ISSUE TITLE
Optimizing Relative Expressions

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#236]
See #204

How are we going to handle the following two scenarios when optimizing relative expressions:
1.  When the user has selected all normalized 100% values
2.  When the user has optimized a normalized value whose optimized value is greater than 100%.

Probably the second case should be handled by limiting the minimum and maximum of normalized values to 0 and 1, but at the moment, it's possible to apply larger boundaries.

First scenario is tricky because if you were to normalize all 100% values then what constitutes 100%? Maybe that should be a validation failure for the optimization. There must be at least one normalized 100% remaining which is not included in the PI.

**Comment by msevestre** [comment]
@sfrechen @Yuri05 
Please feedback

**Comment by sfrechen** [comment]
Why not optimising the un-normalized values and normalize in background as usual?

**Comment by msevestre** [comment]
@sfrechen This is pretty hard to do with the current infrastructure. un-normalized value are not used at all in the model. e.g. normalized value is not a function of un-normalized, at least not explicitely. That would mean that after each iteration of the optimizer, we would have to inject some PK-Sim specific logic to update some parameters implicitly. 

Plus looking at #204, the parameters that you optimized were Normalized Parameters so the problem remains

**Comment by StephanSchaller** [comment]
Why don't you just allow values greater 100% an re-normalize after/during "transfer to simulation"?

**Comment by Yuri05** [comment]
will be obsolete after relExp-Redesign

**Comment by msevestre** [comment]
Hum. Let's leave it open as an issue that will be fixed with the upcoming release ok?

**Comment by msevestre** [comment]
This is now implemented
