### ISSUE TITLE
Export Expression Profile domain object

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#2364]
1. Right click on Expression BB
2. Show Context Menu
3. Select 'Export'
4. Select the file
5. Save on disk as PKML

**Comment by georgeDaskalakis** [comment]
Since the functionality already exists for observed data, I suggest we use the same caption and icon:

![image](https://user-images.githubusercontent.com/37107428/203290048-bb734738-4cf6-4d61-8b91-55d9feb441e8.png)

so instead of "Export", "Export to pkml..."

@rwmcintosh what do you say?
