### ISSUE TITLE
same color coding when using PC or permeability calculation methods and observed data

### ISSUE THREAD

**Issue by Chrizsly** [Open-Systems-Pharmacology/PK-Sim#2368]
during parameter fitting, one can select multiple methods to estimate partition coefficients or permeability values -> when looking at the results and plotting the model simulations with observed data, the color coding seems messed up and it is very difficult to identify what model simulation belongs to what PC method and data color.
any way to make this more streamlined?

Best,
C

**Comment by StephanSchaller** [comment]
Can you paste a figure so we know what you mean? This has not been an issue before
