### ISSUE TITLE
Reword global PK Analysis description

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#2377]
Everything makes sense until you write the documentation

@msevestre @Yuri05 

https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/79620b6cafa272b5030583a4e18682b8169cb6c6/src/PKSim.Assets/PKSimConstants.cs#L2229

Should this be:

> The median value calculated from all individual values

instead of:

> The median value calculated from all curves

**Comment by Yuri05** [comment]
yes!!
