### ISSUE TITLE
11.1: Observed data mapping / Delete Entry

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2380]
The tooltip for **X** says "Delete entry", but it just clears the mapping to the simulation output.
Under "Delete Entry" I would usually understand that the entry is completely removed from the table (meaning the observed data set is removed from the simulation).
So we should either change the tooltip to something like "Clear mapped simulation output" or the click on **X** should trigger "Remove observed data set from the simulation" use case.
I would vote for the latter ("Remove obs data set")
![grafik](https://user-images.githubusercontent.com/25061876/199517476-2ab69051-d1b2-4204-9c33-46c69ebfe3d2.png)

**Comment by Yuri05** [comment]
@msevestre @PavelBal @rwmcintosh FYI

**Comment by PavelBal** [comment]
- Delete entry
- "Unmapping" should be done via selecting "<None>" from the "Simulation Ouputs"-drop-down
- ONLY implement if max. 1 days

**Comment by georgeDaskalakis** [comment]
The existing way of removing observed data from the simulation (right click on the list and remove), should still be available, right?

**Comment by PavelBal** [comment]
> The existing way of removing observed data from the simulation (right click on the list and remove), should still be available, right?

Yes

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1763](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1763) via [**Zenhub**](https://www.zenhub.com/)

**Comment by georgeDaskalakis** [comment]
reopening to commit relevant changes in PK-Sim

**Comment by georgeDaskalakis** [comment]
fixed, code in Core
