### ISSUE TITLE
11.1 PRedicted vs Observed Plot in a Simulation: wrong observed data caption

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2384]
[01_Alfentanil.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9927659/01_Alfentanil.zip)

I opened a project which had one observed data set in the  simulation.
I added a 2nd observed data set to the simulation and mapped it to the (only) simulated output
![grafik](https://user-images.githubusercontent.com/25061876/199701415-3a88114b-f9be-4d2b-afbd-a81fde99da1e.png)

After that, I created Predicted vs Observed plot. There are 2 problems with the newly added observed data set here:
1) somehow it got the caption from the first data set!
2) it is not displayed in the legend as per default
![grafik](https://user-images.githubusercontent.com/25061876/199702349-df20a29d-30e0-4992-9f38-1154b59d5dea.png)

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1757](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1757) via [**Zenhub**](https://www.zenhub.com/)
