### ISSUE TITLE
11.1 Inherit observed data weights in a PI from simulation?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2386]
If I define weight !=1 for an observed data set in a simulation and add this simulation to a PI: should this weight be set in the PI as well?
At the moment it is still 1.

![grafik](https://user-images.githubusercontent.com/25061876/199705860-60dcea68-663a-44d8-a11f-145719137089.png)

![grafik](https://user-images.githubusercontent.com/25061876/199705994-a1838fd6-8d83-4fc6-ad9a-46305367e0dc.png)

**Comment by georgeDaskalakis** [comment]
fixed through https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1743

now the weights are set according to the mapping in Simulation, the Scaling same way too.
