### ISSUE TITLE
11.1 Rename "Add deviation lines"?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2391]
Should we name it "Add X-fold deviation lines" or "Add X-fold deviation range" instead?
![grafik](https://user-images.githubusercontent.com/25061876/199766339-794a66b5-f905-4293-bcf1-59a832dfdf42.png)

**Comment by georgeDaskalakis** [comment]
@Yuri05 to me the x-fold part is too much information, since it is specified in the next step anyway, but no big objections if everyone else is for it. @PavelBal what do you think?

**Comment by msevestre** [comment]
I don't think it's needed

**Comment by PavelBal** [comment]
I also think it's ok the way it is.

**Comment by Yuri05** [comment]
Well, if everybody is ok with it - let's keep AS IS
