### ISSUE TITLE
11.1 Predicted vs Observed plot 

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2392]
If my default output unit differs from the observed data unit: predicted vs. observed plot is created with those 2 different units on the X- and Y-axis.
![grafik](https://user-images.githubusercontent.com/25061876/199767642-23c5fa84-fea2-45eb-94b9-56b9853acec4.png)

Should in such a case change one of the axis units in order to match the other one?
E.g. change the unit of the simulated data:
![grafik](https://user-images.githubusercontent.com/25061876/199768394-8dcb1a3c-8172-461f-b495-b82e8688cc54.png)

**Comment by georgeDaskalakis** [comment]
Hmm...this seems like something we had during the development phase and I had at some point fixed. I ll take another look.

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1802](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1802) via [**Zenhub**](https://www.zenhub.com/)
