### ISSUE TITLE
11.1 Clone GOF Plot: deviation lines disappear

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2393]
When cloning a GOF plot with added deviation lines - cloned plot does not have them anymore
<img width="350" src="https://user-images.githubusercontent.com/25061876/199768987-a50282be-499a-4a7b-ad16-794db2fce731.png">   ▶️   <img width="350" src="https://user-images.githubusercontent.com/25061876/199769191-34cde65f-3c1c-4d29-ba75-c41cbfa362e2.png">

**Comment by rwmcintosh** [comment]
This has been fixed
