### ISSUE TITLE
11.1 Residuals vs. Time plot: no unit displayed for residuals in linear scale

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2397]
e.g.: 
![grafik](https://user-images.githubusercontent.com/25061876/199778073-2537da33-fd91-475d-b310-fdd7ffe47df7.png)

![grafik](https://user-images.githubusercontent.com/25061876/199778131-022d568b-cd5d-445b-9723-99fde33b9d4b.png)

**Comment by msevestre** [comment]
What should be the unit here?

**Comment by msevestre** [comment]
And why should it be different for Log and Lin. Why do we expect LOG to have NO unit? It is still a difference of two values...

**Comment by Yuri05** [comment]
>What should be the unit here? 

e.g. the **display unit of the first simulated output**

**Comment by Yuri05** [comment]
> And why should it be different for Log and Lin. Why do we expect LOG to have NO unit? It is still a difference of two values...

`log(predicted) - log(observed) = log(predicted/observed)`
`predicted/observed` is dimensionless, so `log(predicted/observed)` as well

**Comment by msevestre** [comment]
Ok

**Comment by msevestre** [comment]
sorry I was looking at the log in the axis settings. All clear

**Comment by msevestre** [comment]
It is not a  straight forward change. WIth the residuals, we do not have access to how it was calculated (see OutputResiduals object)
We also do not have access to the output mapping or the output (could be done for sim vs observed somehow, harder for PI)
last, it's possible to have mixed outputs (fraction and concentration at least in theory). So this unit would not make sense
I am suggesting to not implement this for this release

**Comment by Yuri05** [comment]
>last, it's possible to have mixed outputs (fraction and concentration at least in theory).

It's a bug and should be prevented (https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2399)

>I am suggesting to not implement this for this release

ok. at least having concentration residuals in log scale (the most common case) is displayed correctly so far.

**Comment by Yuri05** [comment]
after our discussion last week: closing the issue.
Created another one in the documentation for the better explanation: https://github.com/Open-Systems-Pharmacology/docs/issues/211
