### ISSUE TITLE
11.1 Different dimensions in the Residuals vs time plot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2399]
Related to #2398 
Similar to the predicted vs observed plots, it would be good to have the possibility to select between different dimensions (and different scalings!) for Residuals vs Time plot.
In the project attached, 3 outputs are mapped [02_Alfentanil.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9931442/02_Alfentanil.zip)
* concentration, linear
* concentration, log
* fraction, linear
![grafik](https://user-images.githubusercontent.com/25061876/199787974-bf7e546a-8e44-4441-9c0e-f8e8d130e9d6.png)

when creating residuals vs time plot, only 1 of them can be displayed in the same plot.
But what happens: 
![grafik](https://user-images.githubusercontent.com/25061876/199790881-7ee6cd1a-5202-4827-a33f-abebb9ed8fc5.png)

* 1st problem: dimensions and scalings are mixed, so that I get 2 different dimensions and 2 different scalings in 1 plot
* 2nd problem: **simulated** output name is taken as the curve name. This is problematic, because we can have N observed data sets mapped to 1 simulated output (like in my example: 2 observed data sets are mapped to 1 output). So here **observed** data set name should be taken
![grafik](https://user-images.githubusercontent.com/25061876/199791521-dedec240-b1c0-459a-8b0f-4c808f7913d2.png)
* 3rd problem: for some unclear reason 1 of the 3 added datasets is not displayed as per default in the legend (probably a followup of the previous problem)
![grafik](https://user-images.githubusercontent.com/25061876/199792783-a3bd3bfa-de01-4f60-836d-a7cf9b9320de.png)

1 is definitly a bug
2+3 - bug or feature?

**Comment by PavelBal** [comment]
> 1st problem: dimensions and scalings are mixed, so that I get 2 different dimensions and 2 different scalings in 1 plot

No. Residuals are always `Dimensionless`, so they definitely can be "mixed" within one plot. E.g. in PI, the total error is just a sum of all residuals, disregarding their initial dimension/scaling.

2+3: here we inspect residuals for a specifif simulation output and not for a data set. So all data sets mapped to one simulation output are lumped together. I agree that having it the other way around would make more sense. In this case, I would suggest the following:

- Legend entries are the names of the data sets
- Tooltips of the symbols in the plot show the name of the data set and the mapped simulation output path (is it possible?)
- All data sets mapped to the same simulation output share the same color but have different symbols.

**Comment by Yuri05** [comment]
>Residuals are always Dimensionless, so they definitely can be "mixed" within one plot. 

**Logarithmic** residuals are dimensionless.
**Linear** residuals clearly have the dimension of the quantites which are compared - and cannot be mixed with logarithmic residuals or with residuals of quantites in a different dimension.

**Comment by Yuri05** [comment]
> 2+3: In this case, I would suggest the following:...

I like your proposal

**Comment by PavelBal** [comment]
> Linear residuals clearly have the dimension of the quantites which are compared - and cannot be mixed with logarithmic residuals or with residuals of quantites in a different dimension.

Hmmm kinda makes sense.. But how is it handled in the PI then?

**Comment by Yuri05** [comment]
Seems in the same (wrong) way as here...

**Comment by Yuri05** [comment]
After our discussion last week: Problem 1) is not a problem.
Created an issue in the documentation for the better explanation: https://github.com/Open-Systems-Pharmacology/docs/issues/211
