### ISSUE TITLE
"Expression" tab in population creation dialogue

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2400]
I am confused what the intended purpose of the "Expression" tab in the population creation step is:

![image](https://user-images.githubusercontent.com/25903040/199944229-9399babb-5183-4501-894d-a7f4aacdc71b.png)

Expression definition is done in individual and not population. Here, the expression can be changed in V10 but no in V11, and the tab is not even mentioned in the documentation. I suggest to completely remove it from here as it is confusing.

**Comment by Yuri05** [comment]
>I am confused what the intended purpose of the "Expression" tab in the population creation step is:

Same purpose as of the "Expression" tab during the **individual** creation. It's absolutely symmetrical

>Expression definition is done in individual and not population. 

Both. E.g. you can have a population without any based individual (loaded from template etc.)
![grafik](https://user-images.githubusercontent.com/25061876/199966473-1366fc63-0b27-459a-91c3-885cabfe45e4.png)

Or you might want to remove a protein from the population for performance reasons (e.g. if none of the used compounds interacts with it).

And so on. There are many use cases where adding/removing protein in a population is useful.

>and the tab is not even mentioned in the documentation.

is a TODO: https://github.com/Open-Systems-Pharmacology/docs/issues/31
