### ISSUE TITLE
11.1 Residuals vs. Time plot: no refresh

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2401]
If I change the settings on the observed data tab in a simulation (scaling or weight): Residual vs. time Plots are not refreshed.
I have to close and reopen the simulation to see the changes.

And if I clear the mapping of observed data set: it is not removed from the plot even after reopening the simulation, so I need to create a new plot (this also applies to Predicted vs Observed plots)

**Comment by msevestre** [comment]
Those are two issues here that I think we should split. 
/1 is not too much of a problem. It's a small bug but why not
/2 needst to be fixed for sure

**Comment by PavelBal** [comment]
tbd, but if implementing 2., the residuals error must be updated, too.

**Comment by georgeDaskalakis** [comment]
accidentally closed. reopening.

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1794](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1794) via [**Zenhub**](https://www.zenhub.com/)
