### ISSUE TITLE
11.1 Observed data tab in a simulation not refreshed if previously mapped simulation output was removed

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2402]
If I map a simulation output, then re-run the simulation via "Define settings and run" and remove this simulation output: it is still shown as mapped in the Observed Data Tab.
After Closing and Reopen the simulation: the mapping is set to <None> (as expected)

**Comment by msevestre** [comment]
This needs to be done via Pub Sub events.
