### ISSUE TITLE
11.1 Observed data mapping in a simulation getting resetted during Clone or Configure

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2405]
Original simulation:
![grafik](https://user-images.githubusercontent.com/25061876/200076152-db44f90c-7d3e-4850-a74d-2504c2e187c4.png)

Cloned Simulation:
![grafik](https://user-images.githubusercontent.com/25061876/200076087-80e4091f-8ad8-4f90-87b2-3c32833138d4.png)

**Comment by Yuri05** [comment]
same problem if a simulation is being **configured**: all observed data mapping settings are resetted

**Comment by Yuri05** [comment]
[002_Configure.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10309738/002_Configure.zip)

There are still some scenarios where it does not work. E.g. try to clone/configure the simulation S1
* Clone without any changes: works
* Replace the administration protocol during Clone/Configure: works
* Replace the individual BB during Clone/Configure: settings are resetted
* Replace the compound BB during Clone/Configure: settings are resetted

**Comment by msevestre** [comment]
>Replace the compound BB during Clone/Configure: settings are resetted

this makes sense to me. If the output is not available anymore...
