### ISSUE TITLE
11.1 GoF plots in a simulation disappear if simulation is cloned

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2406]
Original simulation:
![grafik](https://user-images.githubusercontent.com/25061876/200076275-363945c0-3e18-436b-93a1-4d13d7931b36.png)

Cloned simulation:
![grafik](https://user-images.githubusercontent.com/25061876/200076325-8360191f-4c9a-4496-842b-97d7799c92bb.png)

**Comment by msevestre** [comment]
no this should be implemented for sure

**Comment by rwmcintosh** [comment]
This has been fixed along the way somewhere.
