### ISSUE TITLE
11.1 Global PK-Analysis in population simulation wrong?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2410]
[Pop_global_PK_Fluconazole-Midazolam-DDI.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9944375/Pop_global_PK_Fluconazole-Midazolam-DDI.zip)
* I created a population with 10 individuals, then extracted all Individuals from the population
* Then created a simulation with the population and cloned this simulation 10 times, each time replacing the population by one of the extracted individuals
* Then calculated and exported global pk analyis values from each individual simulation to excel
* Finally, calculated the median value of each global pk-parameter in excel

Expectation: value calculated in Excel is the same as the global pk analysis value shown in the population simulation in PK-Sim
Reality: the values do not match

[global_pk_analysis_Ind0_Ind9_Ahonen_midazolam_po_7.5mg_fluconazole_400mg_i.v_DDI.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9944394/global_pk_analysis_Ind0_Ind9_Ahonen_midazolam_po_7.5mg_fluconazole_400mg_i.v_DDI.xlsx)

That's the result of the calculation in Excel:

Parameter | Compound | Unit | **MEDIAN** | Value | Value | Value | Value | Value | Value | Value | Value | Value | Value
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AUC Ratio (AUCR) | Midazolam |   | **4,50** | 5,10 | 3,12 | 3,94 | 4,24 | 4,65 | 6,62 | 6,69 | 4,34 | 6,53 | 4,24
C_max Ratio (C_maxR) | Midazolam |   | **2,26** | 2,49 | 1,59 | 2,17 | 2,21 | 2,30 | 2,53 | 2,92 | 2,04 | 2,81 | 2,02
Vss (plasma) | Midazolam | ml/kg | **1321,10** | 1135,20 | 1089,44 | 1757,32 | 1167,40 | 1358,00 | 1300,75 | 1297,42 | 1341,46 | 1503,11 | 1527,08
Vss (plasma) | Fluconazole | ml/kg | **686,23** | 741,88 | 705,22 | 651,63 | 717,76 | 748,16 | 667,25 | 719,31 | 584,39 | 654,82 | 650,28
Vd (plasma) | Midazolam | ml/kg | **1128,81** | 934,25 | 1040,85 | 1691,81 | 987,52 | 1210,17 | 1125,58 | 1132,03 | 1123,41 | 1317,98 | 1325,13
Vd (plasma) | Fluconazole | ml/kg | **688,78** | 748,79 | 707,61 | 653,79 | 722,12 | 753,07 | 669,95 | 722,63 | 586,55 | 657,84 | 654,98
Total plasma clearance | Midazolam | ml/min/kg | **2,59** | 2,94 | 1,21 | 2,39 | 2,58 | 3,51 | 2,46 | 3,02 | 2,48 | 2,60 | 2,80
Total plasma clearance | Fluconazole | ml/min/kg | **0,20** | 0,38 | 0,13 | 0,13 | 0,24 | 0,26 | 0,16 | 0,19 | 0,14 | 0,21 | 0,30
Bioavailability | Midazolam |   | **0,63** | 0,75 | 0,73 | 0,59 | 0,63 | 0,53 | 0,60 | 0,56 | 0,74 | 0,63 | 0,67
Fraction absorbed | Midazolam |   | **1,00** | 1,00 | 1,00 | 1,00 | 1,00 | 1,00 | 1,00 | 1,00 | 1,00 | 1,00 | 1,00
Vss (phys-chem) | Fluconazole | ml/kg | **661,67** | 715,33 | 682,84 | 613,56 | 685,68 | 721,07 | 640,51 | 691,27 | 542,24 | 619,36 | 616,15

That's what calculated in the population simulation in PK-Sim:
![grafik](https://user-images.githubusercontent.com/25061876/200133782-61440388-0f6e-4b7e-9367-6ac8b94c875a.png)

**Comment by Yuri05** [comment]
P.S. I checked the **individual PK-Values** for one of the output curves (Fluconazole-Peripheral Venous-Plasma) in the same way - and here the values between PK-Sim and Excel calculation were identical (except 2 very small deviations in AUC_inf - will create a separate issue for that).

Excel:
<img width="500" src="https://user-images.githubusercontent.com/25061876/200177577-7e67246f-c361-4336-acd8-9941f3d97166.png">

PK-Sim:
<img width="700" src="https://user-images.githubusercontent.com/25061876/200177657-5cc36f84-5278-4b73-8029-b88a20240706.png">

Thus I can exclude errors in other steps (individual extraction, cloning, etc.) - so the bug must be indeed in the calculation of the global pk parameters.
[Ind0_Ind9_Peripheral_Plasma.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9946102/Ind0_Ind9_Peripheral_Plasma.xlsx)

[Pop_global_PK_Fluconazole-Midazolam-DDI_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9946105/Pop_global_PK_Fluconazole-Midazolam-DDI_2.zip)

**Comment by Yuri05** [comment]
Rechecked with the project from the issue:
All values but one are exactly the same now in PK-Sim and in the Excel calculation (with 3 decimal places).
One value (`VSS(plasma)` for one of the 2 applied compounds) has slight difference:

![grafik](https://user-images.githubusercontent.com/25061876/200594754-b7b451dd-3f56-4c4d-b111-1eb7efcd481d.png)

![grafik](https://user-images.githubusercontent.com/25061876/200595001-7c301b83-84c8-4621-a3f7-b4b3efc3ba2b.png)

**Comment by msevestre** [comment]
Are you using two digits in excel? Because PKsim is not

**Comment by Yuri05** [comment]
Reattaching my test project 
[Pop_global_PK_Fluconazole-Midazolam-DDI.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9962403/Pop_global_PK_Fluconazole-Midazolam-DDI.zip)

**Comment by Yuri05** [comment]
>Are you using two digits in excel? Because PKsim is not 

I format the view with 2 digits, but for the calculation the value exported from PK-Sim is used.

**Comment by rwmcintosh** [comment]
When you calculate BioAvailability that value is used to change some of the other parameters. Eg. Total plasma clearance/F is removed after you calculate BioAvailability. All the 'over F' parameters get recalculated with BioAvailability when it's calculated.

**Comment by rwmcintosh** [comment]
The individual values from PK-Sim. I think the calculations are using single precision all the way through.

![image](https://user-images.githubusercontent.com/261477/200604033-41f459e3-f1e0-4f23-ba18-438428840c48.png)

**Comment by Yuri05** [comment]
>When you calculate BioAvailability that value is used to change some of the other parameters. Eg. Total plasma clearance/F is removed after you calculate BioAvailability. All the 'over F' parameters get recalculated with BioAvailability when it's calculated.

OK, I see. 
Not sure why we are hiding the /F parameters then, but that's another issue.
https://github.com/Open-Systems-Pharmacology/Forum/issues/1064#issuecomment-1002202119

**Comment by msevestre** [comment]
This is the logical way of doing this
IF YOU HAVE F, then you do not need to show /F
/F is when you do not have F

**Comment by msevestre** [comment]
I actually think they should be hidden lol

**Comment by msevestre** [comment]
ok so looking at the comment, the sentence is out of of context.
The parameter should only be hidden for compound where F was calculated. This is just by definition
Parameter/F = Value
Parameter = Value * F

I don't see a problem here

**Comment by rwmcintosh** [comment]
What about the precision of the calculation? I guess this is relevant to #2411 as well.

**Comment by Yuri05** [comment]
>What about the precision of the calculation? I guess this is relevant to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2411 as well.

Could be...
Comparing the calculations between the population (individual with the biggest deviation in Vss(plasma)) and corresponding individual simulation:

Simulated curve (Midazolam/PeripheralVenous/Plasma) is identical.
PK-Values are also almost identical - except once again for AUC_inf (and derived values). 
Because AUC_Inf is used both in the calculation of VSS and bioavailability - the deviation in AUC_inf seems to be the major reason for the deviation in VSS (plasma).

Because it's exactly the issue #2411 - closing this one now. Think the calculation of global PK is good now.

POP
![grafik](https://user-images.githubusercontent.com/25061876/200642030-b39d5daa-507a-4d91-9e03-3ab50510c362.png)

Individual
![grafik](https://user-images.githubusercontent.com/25061876/200642376-73cd92f0-1fb2-4528-b751-3d46b67a5191.png)
