### ISSUE TITLE
11.1 Population PK Analysis / Individual curves: deviations in AUC_inf

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2411]
I checked the **individual PK-Values** for one of the output curves (Fluconazole-Peripheral Venous-Plasma) in the same way as in #2410 - all values are as expected, except 2 small deviations in AUC_inf

Excel:
<img width="500" src="https://user-images.githubusercontent.com/25061876/200177577-7e67246f-c361-4336-acd8-9941f3d97166.png">

PK-Sim:
<img width="700" src="https://user-images.githubusercontent.com/25061876/200177657-5cc36f84-5278-4b73-8029-b88a20240706.png">

[Ind0_Ind9_Peripheral_Plasma.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9946102/Ind0_Ind9_Peripheral_Plasma.xlsx)

[Pop_global_PK_Fluconazole-Midazolam-DDI_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9946105/Pop_global_PK_Fluconazole-Midazolam-DDI_2.zip)

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2410#issuecomment-1304819729_

**Comment by msevestre** [comment]
Why do you believe your calculations are accurate? We check those values against precalculated values .

**Comment by Yuri05** [comment]
>Why do you believe your calculations are accurate?

Well, all other values are identical between PK-Sim and manual calculation. So I think the calculations are correct.
I debugged it a little bit, and it turned out, that AUC_Inf calculated for extracted individuals and AUC_Inf calculated for the individuals within a population have deviation in 2 individuals: Ind0 (small deviation) and Ind8 (bigger deviation). 

AUC_Inf | Ind0 | Ind1 | Ind2 | Ind3 | Ind4 | Ind5 | Ind6 | Ind7 | Ind8 | Ind9
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Extracted Individuals | 78985,148 | 125548,547 | 150721,422 | 78576,59 | 74460,9141 | 148028,547 | 122185,047 | 176133,938 | 125183,273 | 68344,89
Individual Data in Population | 78985,140 | 125548,547 | 150721,422 | 78576,59 | 74460,9141 | 148028,547 | 122185,047 | 176133,938 | 125182,078 | 68344,89

When comparing other PK values calculated for the extracted individuals and for individuals within population sim: they are identical. E.g. AUC_tEnd. Partuclarly for the Individual 8 (the one with the bigger AUC_inf deviation), AUC_tEnd is identical with 4 decimal places:

AUC_tEnd   [µmol*min/l] | Ind0 | Ind1 | Ind2 | Ind3 | Ind4 | Ind5 | Ind6 | Ind7 | Ind8 | Ind9
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Extracted Individuals | 32943,57 | 21849,76 | 28341,7559 | 23489,90 | 23295,5957 | 34146,4023 | 29997,3145 | 38811,30 | 36668,0977 | 26571,418
Individual Data in Population | 32943,57 | 21849,76 | 28341,7559 | 23489,90 | 23295,5957 | 34146,4023 | 29997,3145 | 38811,30 | 36668,0977 | 26571,418

So the problem with AUC_inf is at least worth investigating it.

**Comment by Yuri05** [comment]
P.S. Comparing the peripheral venous blood curve for Fluconazole (which was used in all calculations above) for the Individual 8 between extracted individual simulation and population simulation: the deviations are negligible.
![grafik](https://user-images.githubusercontent.com/25061876/200297671-424e7bc8-6227-4869-a808-a96651c52526.png)

**Comment by rwmcintosh** [comment]
Whoo boy this is debugging right here!

The difference comes in this code here

https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/884c391b5c9bf87a4df82a978bbf8a30d8260a9a/src/OSPSuite.Core/Domain/Services/PKValuesCalculator.cs#L349-L362

Comparison details on the relevant values
![image](https://user-images.githubusercontent.com/261477/200661998-6275dff3-dcbd-4ba6-856a-b65cd5a45fc3.png)

calculations of intercept and lambda: 
https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/blob/884c391b5c9bf87a4df82a978bbf8a30d8260a9a/src/OSPSuite.Core/Domain/Services/PKValuesCalculator.cs#L414-L448

Conclusion : small differences in the concentration curves are affecting the intercept and lambda, and those are affecting AUC_Inf
