### ISSUE TITLE
for multiple LLOQ values, the smallest should be used and displayed in simulations, etc.

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#2416]
Currently, when uploading an observed data set that contains multiple LLOQ values, it seems that the largest value is used and displayed in the simulations. Per definition (LOWER limit of quantification!), the lowest of the LLOQ values should be used and displayed.

**Comment by Yuri05** [comment]
duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1524

**Comment by Yuri05** [comment]
duplicate of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1524
