### ISSUE TITLE
11.1 Inconsistent naming in time profile plots and GOF plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2420]
E.g. simulated Arterial Blood/Plasma curve is displayed like this in a time profile plot:
![grafik](https://user-images.githubusercontent.com/25061876/201339591-10012307-98da-42aa-b02a-2e3569fe280f.png)

And in Predicted vs. Observed and Residuals vs. time like this:
![grafik](https://user-images.githubusercontent.com/25061876/201339967-3033f64f-2c47-45f4-865d-aad2570e4d0e.png)

**Comment by rwmcintosh** [comment]
Should be checked if the same behavior is observed for PI and Simulation

**Comment by rwmcintosh** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1785](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1785) via [**Zenhub**](https://www.zenhub.com/)
