### ISSUE TITLE
11.1 Chart Editor default grouping

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2421]
At the moment the default grouping is **Repository/Category**
<img width="700" srC="https://user-images.githubusercontent.com/25061876/201340206-4ca82f2b-4326-415b-b868-6e83b19bd18f.png">

I suggest to make it other way around: **Category/Repository**
<img width="700" srC="https://user-images.githubusercontent.com/25061876/201340374-468e44f4-2dfc-4480-b14d-eaa78be70c46.png">

**Comment by Yuri05** [comment]
@georgeDaskalakis @PavelBal @msevestre @rwmcintosh

**Comment by Yuri05** [comment]
>actually do we need repository as a grouping at all?

I asked myself the same question :)
We need the info about the repository (otherwise it would be hard to distinguish between different obs data sets or e.g. between different simulations in the simulation comparison charts) - but this info could be shown just as a column, and not as grouping.

So I would prefer:
* group by category only
* show repository as the first column in the table

**Comment by msevestre** [comment]
In the picutre above, it woild be very hard to find the curve. The group span over the whole row so you can actually see what obs data and sim you are using . I'd like to see a picture without grouping by data repo to see how it looks like
I am pretty sure you CANNOT differentiate between the first 4 entries
If you have multiple simulation starting with the same 8-10 name, this would be the same

**Comment by Yuri05** [comment]
>  I'd like to see a picture without grouping by data repo to see how it looks like

![grafik](https://user-images.githubusercontent.com/25061876/201346386-598255c7-c69d-49d8-be0f-45362f2c28d3.png)

The repo still should be shown (as column) - so you can differentiate. Just not as grouping

**Comment by msevestre** [comment]
yes but look how wide it is. I am asking for the SAME width as above.

**Comment by Yuri05** [comment]
sure, with the small(er) width you will not see the full repo name immediately.
The question is, what more convenient for the user. If e.g. I have 20 repos with observed data sets, each repo with 2 data sets, and I need to select just one data set from each repo: 
* without grouping, I need e.g. to make my chart window wider (1 drag action) and/or make the repo column wider (1 click)
* with grouping: I need to expand all 20 repos (20 clicks)

**Comment by msevestre** [comment]
I don't mind your change. I am just saying that with the default UI, this example will be very hard to use because each line will look the same. This a a trade off

**Comment by PavelBal** [comment]
@georgeDaskalakis Default grouping by category is what we already agreed on, right? I don't understand why this is not the case any more...

**Comment by georgeDaskalakis** [comment]
Issue moved to [Open-Systems-Pharmacology/OSPSuite.Core #1781](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/1781) via [**Zenhub**](https://www.zenhub.com/)
