### ISSUE TITLE
OutputMapping is missing for PopulationSimulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2422]
@PavelBal @georgeDaskalakis @Yuri05 
This is not by design I am assuming?

**Comment by msevestre** [comment]
Individual SImulation
![image](https://user-images.githubusercontent.com/1041237/201384038-f8283395-2eff-4aac-807b-7de549f4bdd8.png)

Population Simulation
![image](https://user-images.githubusercontent.com/1041237/201384135-5f110d9e-c93f-4a4a-8882-8701f4bf1066.png)

**Comment by PavelBal** [comment]
It is, we did not specify this for population simulations as the plots there are totally different and follow some other logic.

**Comment by msevestre** [comment]
the obs data mapping has nothing to do with the plots right?

**Comment by msevestre** [comment]
it's easy to add
![image](https://user-images.githubusercontent.com/1041237/201385682-a442e3fa-1139-4f2f-a866-55c9987586a6.png)

but I don't understand why this would not be something we want...can you explain?

**Comment by PavelBal** [comment]
> but I don't understand why this would not be something we want...can you explain?

If it is an easy fix - then why not ;) We did not do it as it was not clear which implications it would have resp. we did not spent time on thinking of it... But yeah, if it is a quick fix - we should do it.
