### ISSUE TITLE
Mechanistic IVIVR using Lumen dissolution

### ISSUE THREAD

**Issue by adinizbe** [Open-Systems-Pharmacology/PK-Sim#2429]
Helo
In the Gastroplus software, they consider as mechanistic deconvolution the estimation of in vivo dissolution.
In the PK-Sim, if a formulation is added as Weilbull function and the lumen dissolution fractions are evaluated, the relation between dissolution in vitro and dissolution into the lumen could  be done?
Are there some mechanistic process to calculate the lumen dissolution or the values come from the Weilbull function of de formulation exclusively?
Is the rational the same for PK-Sim and Gastroplus?
Thank you

**Comment by Yuri05** [comment]
@adinizbe Please ask question in the [forum](https://github.com/Open-Systems-Pharmacology/Forum/discussions)
