### ISSUE TITLE
11.1 Wrong icon for Residual vs. Time plot tab

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2437]
![grafik](https://user-images.githubusercontent.com/25061876/203107844-b9f1afb9-4a00-44c4-863a-1f4dd5ac9ad4.png)

**Comment by rwmcintosh** [comment]
@georgeDaskalakis The PR Is closed, but the issue is open. I assume the issue is also fixed?

**Comment by Yuri05** [comment]
yes, is fixed now
