### ISSUE TITLE
How to make change in the parameter of P (interstitial->intracellular)?

### ISSUE THREAD

**Issue by ngolienvp** [Open-Systems-Pharmacology/PK-Sim#2447]
Hello,
I want to apply a developed PBPK model of midazolam for our DDI prediction purpose using PKsim.
I picked up all the necessary materials including the compound, ID, and formulation of midazolam. However, our simulation results for PK of midazolam were different from the published one. I found that the reason for the difference came from the change in the P (interstitial->intracellular) and P (intracellular->interstial)  (attached picture), which were applied in the published model but were not reflected in our simulation cause I could not find the parameter anywhere in PKsim.
Please let me know how to edit the parameters in PKsim or how just to simply copy the change from the published PKsim model for midazolam.
Thank you!

![image](https://user-images.githubusercontent.com/102349083/204431782-3950ea4f-2b24-4622-8539-d1bc4799cd00.png)

**Comment by AndreDlm** [comment]
Hi @ngolienvp,
you can find this parameter in the simulation parameters tab; you need to switch from `Simple` to `Advanced` view (drop-down menu in the lower left corner) and navigate to the paths highlighted here:
![image](https://user-images.githubusercontent.com/26541603/204589142-3875fa13-d873-4ec3-a219-f6acb77970e5.png)

**Comment by ngolienvp** [comment]
Hi @AndreDlm 
Thank you very much for your answer. 
I found it!!!
