### ISSUE TITLE
Batch update multiple simulations from BB at once

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#2449]
I'd love to see the feature of updating from the BB a given parameter used in multiple simulations at once. Currently, when changing a parameter value in a BB (e.g. `reference concentration`, `solubility`, `dissolution shape` etc.), I have to update each simulation separately. Having a batch update option would greatly facilitate this.

**Comment by Yuri05** [comment]
agree.
I think it's the duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/11 
@incei FYI

**Comment by msevestre** [comment]
This could easily be done at least when a quick update is possible (e.g no user interaction such as when adding a process etc..)

**Comment by AndreDlm** [comment]
Thanks, yes seems to be a duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/11
I'll close this one
