### ISSUE TITLE
PI: Export parameter history / Initial Error

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2453]
[03_Alfentanil_11.1_Tests_TotalError.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10126211/03_Alfentanil_11.1_Tests_TotalError.pksim5.zip)
In the project attached, the total residual error in the simulation is shown as **0.600**
This value is correct (have recalculated it in Excel).

![grafik](https://user-images.githubusercontent.com/25061876/204880423-e75f5bd4-34f9-4185-b721-ee23e3ca1b7b.png)

I created a PI with this simulation where I optimize just one parameter. The setttings of the observed data (scaling, weights) and the initial value of the identification parameters were not changed (is in the attached project as well).
Thus I would expect that the initial total error would be the same as in the simulation.

However when exporting the parameter history to Excel from the PI-Feedback window, the initial total error is exported as **0.553**
![grafik](https://user-images.githubusercontent.com/25061876/204882713-1f2ed9c1-7a87-4348-a0da-59044a0a9e85.png)

This is also what is shown in the Error History plot:
![grafik](https://user-images.githubusercontent.com/25061876/204883723-391c22e8-af27-4def-86e6-676d68acb4ec.png)

**Comment by Yuri05** [comment]
P.S.
When transfering the PI-result back into the simulation, the total error (after rerun simulation) differs as well:
* PI: **0.480**
* Simulation: **0.526**

Something is wrong...

**Comment by Yuri05** [comment]
OK, I think I know why.
If there is no simulated time value corresponding to an observed time value:
* in a PI we **insert additional time point** which are exactly the same as the time value of the observed data
* in a simulation we just make **linear interpolation** for the simulated values

So it's not a bug, but might lead to questions.
@rwmcintosh @msevestre @georgeDaskalakis @PavelBal FYI

**Comment by PavelBal** [comment]
This should be statend in the documentation. @georgeDaskalakis can you add this information to the description of the new residuals-vs-time plot? Or point me to where in the documentation it is located.

**Comment by georgeDaskalakis** [comment]
@PavelBal PR on documentation created here:

https://github.com/Open-Systems-Pharmacology/docs/pull/214
