### ISSUE TITLE
Simulation comparison does not show relevant formula differences

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2469]
[NoyesWhitney_TID_Events.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10195256/NoyesWhitney_TID_Events.zip)
PK-Sim 11.1.94: when comparing 2 simulations shown in the screenshot: no differences are shown
![grafik](https://user-images.githubusercontent.com/25061876/206713824-fc1445f5-732b-42ab-889c-55eca253f884.png)

However there are relevant differences in some formulas (export simulations to the text report or to MoBi to check):

```
Parameter: NEW|Organism|Lumen|Duodenum|Absorption of liquid
	IsFixed: False
	Value: -0.858761430689952 [1/min]
	Formula: alpha*V > 0 ? (k_p*alpha_p*V_p+inflow-k*alpha*V)/(alpha*V) : 0
```

```
Parameter: TID_NoyesWhitney_Events|Organism|Lumen|Duodenum|Absorption of liquid
	IsFixed: False
	Value: -0.858761430689952 [1/min]
	Formula: (k_p*alpha_p*V_p+inflow-k*alpha*V)/(alpha*V)
```

**Comment by Yuri05** [comment]
even when deactivating the option "only compare properties relevant to simulation results": the formula differences are not shown (only things like name/description/icon/...)
![grafik](https://user-images.githubusercontent.com/25061876/206715079-3837a401-9991-4cb8-8b6b-b15d3e8daf6d.png)

@msevestre FYI

**Comment by msevestre** [comment]
I love thosr bugs

**Comment by msevestre** [comment]
@Yuri05 Those parameters are hiddden
If you click "compare hidden entities", you'll see them

![image](https://user-images.githubusercontent.com/1041237/206735906-3ec42416-3cb2-4cb9-9464-8e1acd428f54.png)

**Comment by msevestre** [comment]
IT's hard to sya. Maybe we compare everything all the time and we remove this property. Hidden are always parameters
so they are always relevant. But if the user do not see the parameter, we did not want to show the parameter in the diff (e.g. we change the formula between two versions). 

How did the user manage to change the formula ?

**Comment by Yuri05** [comment]
The user didn't :)
The simulation was created with an older PK-Sim version. In the meanwhile, the equation was adjusted in the PK-Sim DB.

When opening the project now, the previously created simulation keeps the old equation, but when recreating it from BBs (or cloning/reconfiguring) - the equation is updated.

**Comment by msevestre** [comment]
Ok. This flag is exactly meant for this.
But maybe we should just not use it anymore if this an issue. Otherwise, this behaves as expected

moBI does not care and shows everything obviously

**Comment by Yuri05** [comment]
>But maybe we should just not use it anymore if this an issue. 

maybe... or at least set "show hidden"=true as per default
