### ISSUE TITLE
Define solubility as a table (X=pH, Y = Sol)

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#248]
* Values can be edited by hand
* Values can be loaded from file

similar to Table Formulation UI

**Comment by msevestre** [comment]
@Yuri05 How is this supposed to work with the
![image](https://user-images.githubusercontent.com/1041237/28783391-399d2e86-75de-11e7-8ea3-d1a66f32cdcd.png)

Also is this kind of feature supported in core (defining Solubility as a function of pH)?  I know we can define a table, but how can we specify, that a specific pH value should be used (e..g the pH of duodenum for example). A bit baffled . Let's have a chat

**Comment by Yuri05** [comment]
>Also is this kind of feature supported in core (defining Solubility as a function of pH)? 

Not yet. We will need to extend the table formula with something like _ArgumentObject_ (similar to the _OffsetObject_ in the _TableWithOffset_ formula). 
I would make it optional. If not defined, it's the Time (the current situation).

**Comment by Yuri05** [comment]
Another issue: during simulation creation we will have to replace the solubility formulas in GI segments with
`TableFormula(ArgumentObject = pH_in_GI_segment)`

**Comment by msevestre** [comment]
probably we could define the path relative to object as well
Something line 
`ArgumentObject = ..\ph`

**Comment by msevestre** [comment]
all in all we need a concept for that. Let's postpone to 7.3

**Comment by msevestre** [comment]
@Yuri05 Do you plan to work on that ? There are some serious changes to be made and we should decide if this is going to be part of 7.3 soon

**Comment by Yuri05** [comment]
let's take it into 7.3
