### ISSUE TITLE
Bug when exporting population simulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2484]
### Discussed in https://github.com/Open-Systems-Pharmacology/Forum/discussions/1411

<div type='discussions-op-text'>

<sup>Originally posted by **moPellowe** December 15, 2022</sup>
I have found an issue with the population simulation export in PK-Sim. I have a simulation that has been run in PK-Sim and I can see the upper and lower values of the confidence interval via the plot.
![image](https://user-images.githubusercontent.com/57540473/207830721-a64c02cd-f5f2-4431-a2e3-6f3147cb559e.png)
![image](https://user-images.githubusercontent.com/57540473/207830763-a4f9dfe4-996a-459d-9e62-36b2181af85d.png)

But when I export the results of the population simulation, the results for the lower and upper values of the CI are sometimes different.
![image](https://user-images.githubusercontent.com/57540473/207831100-a7fe3ff0-b5b0-4689-87f0-e2ce7145d10e.png)

It seems that it is an issue that occurs only if you have more than one compound in the plot and you use a non-molar unit. (thanks, @tobiasK2001, for figuring that out.)</div>

**Comment by msevestre** [comment]
@moPellowe Can you please attach a project to reproduce?

**Comment by moPellowe** [comment]
Here's a PK-Sim file with a population simulation. I then exported the results to Excel by right-clicking the plot area and saving to Excel. I've also included the resulting Excel sheet with the discrepancy as shown in the figures above.
[generic.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10239549/generic.zip)

**Comment by msevestre** [comment]
ok looking at this now
