### ISSUE TITLE
Compare Results: add new comparison via the context menu

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2490]
Add 2 context menu items to every comparison folder and to the root "Comparisons" node:
* "Add compare results: Individual simulations"
* "Add compare results: Population simulations"

![grafik](https://user-images.githubusercontent.com/25061876/208302776-b8850b7b-56a2-414c-9b24-06291acd458d.png) ![grafik](https://user-images.githubusercontent.com/25061876/208302491-c1f9a662-64f3-43cb-9fc3-dcb3789a2e23.png)

**Comment by Yuri05** [comment]
(partly included in https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1042)

**Comment by msevestre** [comment]
Easy for root, requires significant chnages for subfolder. So only root

**Comment by msevestre** [comment]
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/868a4050-9096-4afe-bb06-1d4d6f00fd71)
