### ISSUE TITLE
Adding simulation without results to "Compare results"

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2493]
When I select several simulations and try to add them via drag&drop to a results comparison chart: if **at least 1 simulation** has no results (was not run yet) - nothing happens.
I would suggest to
* add all simulations which have results AND
* show the info message with the list of simulations which must be run first before adding
![grafik](https://user-images.githubusercontent.com/25061876/208303292-4a6d73ed-ea64-4b8d-b754-0018f783794c.png)

**Comment by msevestre** [comment]
This will create issues with datarepository null etc
Instead we can the one with results and show a message for all the other one. Too much work otherwise for not much gain
