### ISSUE TITLE
an unhandled exception when open pksim11 and Mobi11

### ISSUE THREAD

**Issue by zjupharma** [Open-Systems-Pharmacology/PK-Sim#2505]
I was just trying to open pksim11 software after completing installation, an unhandled exception was occurred as shown in following picture. Also, the same problem still exists when I try to install and open the earlier version, such as Pksim10.0 and Pksim9.1. Dose someone know how to solve this problem, please let me know.
Best regards,
Yu Wang

![the problem](https://user-images.githubusercontent.com/109033288/211200200-f38c65a5-c8c4-481f-849c-fd085a0359b3.png)

**Comment by Yuri05** [comment]
It seems that your Windows installation is corrupted - particularly your Arial font.
Try to repair/replace your arial font with the valid version.

**Comment by zjupharma** [comment]
Thank you so much, it's wonderful. I  solved this problem  by installing the arial font in the computer and could open mobi11 and pksim11.

**Comment by Yuri05** [comment]
Great! Closing the issue
