### ISSUE TITLE
Metabolizing Enzymes

### ISSUE THREAD

**Issue by he-kadry** [Open-Systems-Pharmacology/PK-Sim#2511]
I am working with an ADC model and I added two metabolizing enzymes for the ADC to produce two payloads(toxophore) and I selected the two compounds that I created as the produced metabolites. Is there a way to simulate the release the of the payloads? Currently, I am able to simulate only the ADC profile.

**Comment by Yuri05** [comment]
dear @he-kadry 
Please ask all question in the [**forum**](https://github.com/Open-Systems-Pharmacology/Forum/discussions)
