### ISSUE TITLE
Loading project from snaphot: observed data which was previously added to a simulation is plotted but not added to the curves browser

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2536]
Seems to happen with any project in 11.1
Example: [P1.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10700161/P1.zip)

![grafik](https://user-images.githubusercontent.com/25061876/217897466-535f26bf-5054-456e-b2cc-761728449261.png)

**Comment by msevestre** [comment]
Probably due to the change performed in core with the obs data mapping.
