### ISSUE TITLE
Weird column names when exporting ontogeny table to excel

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2537]
<img width="400" src="https://user-images.githubusercontent.com/25061876/217899543-a93b254e-462a-44c0-93cb-b6ae5fc0555b.png">

When exporting ontogeny data to excel, exported file looks like this:

Post   menstrual age [year(s)] | Ontogeny for CYP3A4 | Ontogeny for CYP3A4_1
-- | -- | --
0,01 | 13,99 | 0,0011
0,03 | 5,87 | 0,0086
0,53 | 1,67 | 0,23
0,59 | 1,63 | 0,25
0,77 | 1,52 | 0,32
1,08 | 1,45 | 0,41
1,44 | 1,45 | 0,5
... |... | ...

The column named **Ontogeny for CYP3A4** is in fact the geoSD, and the column **Ontogeny for CYP3A4_1** is the (geo)Mean value.
The columns should be named properly (and the order changed: first mean, then SD)

**Comment by msevestre** [comment]
Probably we can fix some ;-)
