### ISSUE TITLE
My blocks and simulations disappear 

### ISSUE THREAD

**Issue by jdtchkn1unc1edu** [Open-Systems-Pharmacology/PK-Sim#2538]
Hello,
Something strange happens.
My blocks and simulations disappear in PK-Sim. 
Did someone have that issue in the past, how to recover them?
Thank you!

**Comment by msevestre** [comment]
Hi there,

Go to user settings. There is an option at the bottom called reset layout or something like this. Click, restart pksim, and you should be good to go

**Comment by jdtchkn1unc1edu** [comment]
Thank you so much for your response.
Please, where can I find the “User setting?”
Sincerely,
JK

**Comment by rwmcintosh** [comment]
You go to the Utilities tab, then Options button.
![image](https://user-images.githubusercontent.com/261477/218187881-92edccfe-1e4a-410b-98f1-940fbf51a5cc.png)

Then in the bottom left is 'Reset Layout...'
![image](https://user-images.githubusercontent.com/261477/218187997-3ad20f08-3a64-4a00-9554-eda3e8ce5959.png)
