### ISSUE TITLE
PKSimStarter: Two instances of Shell

### ISSUE THREAD

**Issue by georgeDaskalakis** [Open-Systems-Pharmacology/PK-Sim#2540]
When starting the PKSimStarter a new LookAndFeel gets resolved (probably through a call from the PKSim Shell ). This results in the change of theme for MoBi on the start of the PKSimStarter. This should ot be happening. Right now we are passing the MoBi Shell (MainView) whihc results in having gtwo shells, which is not an ideal solution. Ideally we should find the place where the Shell gets registered and prevent that for PKSimStarter.

**Comment by rwmcintosh** [comment]
Closed with [#2526](https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2526)
