### ISSUE TITLE
Duplicated formulas

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2545]
These formulas in the SS-BB seem to be exactly the same and can be replaced by one:

- PARAM_InverseLITT_Factor_Caecum
- PARAM_InverseLITT_Factor_ColonAscendens
- PARAM_InverseLITT_Factor_ColonDescendens
- PARAM_InverseLITT_Factor_ColonSigmoid
- PARAM_InverseLITT_Factor_ColonTransversum
- PARAM_InverseLITT_Factor_Rectum

Other group:

- PARAM_InverseSITT_Factor_Duodenum
- PARAM_InverseSITT_Factor_LowerIleum
- PARAM_InverseSITT_Factor_LowerJejunum
- PARAM_InverseSITT_Factor_UpperIleum
- PARAM_InverseSITT_Factor_UpperJejunum

**Comment by Yuri05** [comment]
true

**Comment by Yuri05** [comment]
Duplicate of https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2714 + https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2715
