### ISSUE TITLE
Large molecules model: Use sum formulas

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2549]
Following parameters can (and should) be defined by sum formulas. Extension of the organ structure would be then much easier.

**EndogenousIgG|Fluid recirculation flow rate:**
	`J_iso_bon+J_iso_brn+J_iso_fat+J_iso_tes+J_iso_hrt+J_iso_kid+J_iso_lin+J_iso_liv+J_iso_lng+J_iso_mus+J_iso_pan+J_iso_skn+J_iso_sin+J_iso_spl+J_iso_sto`

Replace by sum formula with
```
	Tagged with: Fluid recirculation flow rate
	Not in container: EndogenousIgG
	Not in container: Pericentral
	Not in container: Periportal
```
	
**EndogenousIgG|Lymph flow rate:**
	`Q_lymph_bon+Q_lymph_brn+Q_lymph_fat+Q_lymph_tes+Q_lymph_hrt+Q_lymph_kid+Q_lymph_lin+Q_lymph_liv+Q_lymph_lng+Q_lymph_mus+Q_lymph_pan+Q_lymph_skn+Q_lymph_sin+Q_lymph_spl+Q_lymph_sto`

Replace by sum formula with
```
	Tagged with: Lymph flow rate
	Not in container: EndogenousIgG
	Not in container: Pericentral
	Not in container: Periportal
	Not in container: PortalVein
```
	
**EndogenousIgG_int_EndogenousIgG_pls|Surface area (plasma/interstitial):**
	`SA_pls_int_bon+SA_pls_int_brn+SA_pls_int_fat+SA_pls_int_tes+SA_pls_int_hrt+SA_pls_int_kid+SA_pls_int_lin+SA_pls_int_liv+SA_pls_int_lng+SA_pls_int_mus+SA_pls_int_pan+SA_pls_int_skn+SA_pls_int_sin+SA_pls_int_spl+SA_pls_int_sto`

**_QUESTION_**: Mucosal tissue have not been considered??? https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2547

Replace by sum formula with
```
	Tagged with: Surface area (plasma/interstitial)
	Not in container: EndogenousIgG_int_EndogenousIgG_pls
	Not in container: Pericentral_pls_Pericentral_int
	Not in container: Periportal_pls_Periportal_int
```
	
**EndogenousIgG|Endosome|Volume:**
	`V_bon+V_brn+V_fat+V_tes+V_hrt+V_kid+V_lin+V_liv+V_lng+V_mus+V_pan+V_skn+V_sin+V_spl+V_sto+V_duo+V_uje+V_lje+V_uil+V_lil+V_cae+V_colasc+V_coltrans+V_coldesc+V_colsigm+V_rect`

Replace by sum formula with
```
	Tagged with: Volume
	In container: Endosome
	Not in container: EndogenousIgG
	Not in container: Pericentral
	Not in container: Periportal
```
	
**EndogenousIgG|Interstitial|Volume:**
	`V_bon+V_brn+V_fat+V_tes+V_hrt+V_kid+V_lin+V_liv+V_lng+V_mus+V_pan+V_skn+V_sin+V_spl+V_sto+V_duo+V_uje+V_lje+V_uil+V_lil+V_cae+V_colasc+V_coltrans+V_coldesc+V_colsigm+V_rect`

Replace by sum formula with
```
	Tagged with: Volume
	In container: Interstitial
	Not in container: EndogenousIgG
	Not in container: Pericentral
	Not in container: Periportal
```
	
**EndogenousIgG|Plasma|Volume:**
	`V_bon+V_brn+V_fat+V_tes+V_hrt+V_kid+V_lin+V_liv+V_lng+V_mus+V_pan+V_skn+V_sin+V_spl+V_sto+V_duo+V_uje+V_lje+V_uil+V_lil+V_cae+V_colasc+V_coltrans+V_coldesc+V_colsigm+V_rect`

Replace by sum formula with
```
	Tagged with: Volume
	In container: Plasma
	Not in container: EndogenousIgG
	Not in container: Pericentral
	Not in container: Periportal
        Not in container: BloodOrgan
```

**Comment by msevestre** [comment]
@PavelBal nice work!

**Comment by StephanSchaller** [comment]
> @PavelBal nice work!

Indeed!

**Comment by msevestre** [comment]
@Yuri05 i can implement this

**Comment by Yuri05** [comment]
@msevestre 👍

**Comment by Yuri05** [comment]
- [ ] EndogenousIgG|Fluid recirculation flow rate
- [ ] EndogenousIgG|Lymph flow rate
- [ ] EndogenousIgG_int_EndogenousIgG_pls|Surface area (plasma/interstitial)
- [ ] EndogenousIgG|Endosome|Volume
- [ ] EndogenousIgG|Interstitial|Volume
- [ ] EndogenousIgG|Plasma|Volume
