### ISSUE TITLE
PK-Sim changes molecule name while importing a project from a snapshot file 

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#2553]
In the attached original PK-Sim file "7E3_original.pksim5" (see zip file)  and the corresponding snapshot file "7E3.json", the molecule name in the metadata of the observed data is "7E3". After loading the project from the snapshot file, the name is 7000 (see file "7E3_importedFromSnapshot.pksim5").
   
![original](https://user-images.githubusercontent.com/26439150/222086006-0fcf67a7-a76e-44a0-91c1-7ef8c59e76cd.jpg)
![imported](https://user-images.githubusercontent.com/26439150/222086022-15027a89-3918-45fd-bac6-3fbe01c8ae57.jpg)

[files.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10858790/files.zip)

**Comment by msevestre** [comment]
WHAT??

**Comment by msevestre** [comment]
oh...7E3 => 7000 lol

**Comment by msevestre** [comment]
good news, the json looks good. This is just a loading problem it seems

**Comment by msevestre** [comment]
@Yuri05 We retrieve the type based on the value. In this case, we won't be ableot parse it properly. Going to add a type when we export the property.

**Comment by Yuri05** [comment]
PK-Sim 11.2.142 - the error is still there

**Comment by msevestre** [comment]
that's can't be fixed in this project
The info is missing and therefore the problem will still be there in outdated snapshot

**Comment by Christoph27** [comment]
That means one has to newly define the molecule in PK-Sim 11.1? I had already reloaded the experimental data to the project using PK-Sim 11.1 ....

**Comment by msevestre** [comment]
That means that once 11.2 is out, you can simply export to snapshot and this will be good. Or the snapshot should be modified by hand, which is also trivial
