### ISSUE TITLE
Projects created with <= V10 are sometimes not properly exported to snapshot with >= V11

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2558]
The problem is: if an individual or a population in the V10 was containing a protein expression **and this individual/population was not converted (loaded once)** in V11 before exporting to the snapshot: the corresponding protein expressions are not exported to the snapshot.
E.g.
1. Open the project [V10.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10969168/V10.zip) in V11. Do not open the individual or population BB.
2. Export it to snapshot: the snapshot does not contain any protein expression and crashes during loading [V11_1.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10969206/V11_1.zip)
3. Export to snapshot again: now the snapshot is valid (because individual/population BBs were loaded and converted during the 1st snapshot export) [V11_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/10969224/V11_2.zip)

### Workaround for V11: 
when opening an older project (<= V10) - make sure to load all individual/populations once before exporting the project to snapshot.

**Comment by Yuri05** [comment]
Hope it can be fixed just by changing the snapshot export order: export protein expressions **after** exporting of individuals and populations.

**Comment by msevestre** [comment]
Or we do a first path by loading all building blocks first and then exporting

**Comment by msevestre** [comment]
Do you want to create a patch for this?

**Comment by Yuri05** [comment]
>Or we do a first path by loading all building blocks first and then exporting

Or this.

>Do you want to create a patch for this?

Thinking about the patch: there is another problem with snapshots: 
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2536 
Should be fixed then as well...

**Comment by msevestre** [comment]
Why would it work with v11? Isn't it the same problem?

**Comment by msevestre** [comment]
oh because there was no expression profile I see
