### ISSUE TITLE
 CLI for PKSim.BatchTool

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#256]
Looking at this issue here 
https://github.com/Open-Systems-Pharmacology/Forum/issues/64

I think a lot of people could benefit from a simple CLI that would allow them to run the batch tool in a slightly different way. Probably this will overlap highly with what we have to do anyways for the requalification but I think this would be  great place to start discussing what we would need

The CLI (Command line interface) should:

* be able to load a project file and create the corresponding json representation
* be able to create a project file from a json representation
* be able to load a project file, export each simulation artifacts such as
  * population csv
  * simulation xml
  * optionally run simulations and export the csv for the simulation as well along with all pk parameters

What else?

**Comment by msevestre** [comment]
This should look a bit like what modern cli are doing. Especially regarding output on console so that user can see right away what's wrong 

For example something like

```
PKSim.BatchTool batch --input xxx --output xxx --option1 -- option2
PKSim.BatchTool create --input xxx --option1 -- option2
...
```

**Comment by msevestre** [comment]
A full CLI has been implemented:
```
PKSim.BatchTool --help

PKSim
Copyright c 2017 - Open Systems Pharmacology Community

  comparison    Start project comparison by loading a set of projects, running all simulations and exporting old and new results

  run           Start batch run by loading a set of batch json files, running all simulations and exporting the results

  overview      Generate project overview by loading a set of projects and exporting a file containing a description of all building blocks and observed data used

  help          Display more information on a specific command.

  version       Display version information.
```

Here is how the run command will look like
```
 PKSim.BatchTool run --help

PKSim
Copyright c 2017 - Open Systems Pharmacology Community

  -i, --input      Required. Input folder containing all batch json files to run

  -o, --output     Required. Output folder where calculated values will be exported

  -l, --log        Full path of log file where log output will be written. If not defined, it wil be exported in the output folder

  -c, --csv        Export simulation outputs to csv

  -x, --xml        Export the simulation model xml

  -j, --json       Export simulation outputs to json

  -d, --debug      Show debug notifications in log file

  -w, --warning    Show warning notifications in log file

  --help           Display this help screen.

  --version        Display version information.
```

so in order to start the batch run exporting to json, xml and csv as well as showing warning, the following will be required

```
PKSim.BatchTool run -xcjw -i C:\Tests\inputs -o C:\Tests\inputs\outputs
```

**Note:**
This call however returns immediately in the console prompt. 
If this is not ok, the following call can be made instead

```
start /WAIT PKSim.BatchTool run -xcjw -i C:\Tests\inputs -o C:\Tests\inputs\outputs
```

**Comment by lamnvcnsh** [comment]
Could you please explain more about json format, which information we shout input if I have a PBPK model and I would like to simulate PK of an individual. I tried to find in the manual guide but it is not too much.
Thank you very much

**Comment by msevestre** [comment]
Please ask question in the forum @lamnvcnsh 
Also explain exactly what you are trying to achieve because I have no idea how to help you just based on the one line you wrote earlier. The more information the merrier
