### ISSUE TITLE
PI reloaded from journal has no simulations

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#257]
When a PI is reloaded from journal, it has no simulations - therefore, not dapa mapping etc.

How to reproduce:
1) Open the "Aciclovir.pksim5" example project.
2) Create a PI with any simulation (e.g. Laskin_1982_GroupA)
3) Add the PI to journal (create a new journal).
4) Remove the PI from the project and reload it from the journal entry.
5) No simulation is present in the PI - no data are matched, selected parameters report "Invalid object"

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/MoBi/issues/157

**Comment by msevestre** [comment]
Duplicates https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/569 which will be fixed in 7.3

**Comment by Yuri05** [comment]
fixed in #569
