### ISSUE TITLE
Move IndividualToIndividualBuildingBlockMapper from presentation to core

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2570]
I missed this during review but the interface should definitely be in core and I'd argue that the implementation as well
Right now, some DTO are being used to convert one model object to another which is very surprising (and scares me a bit...hopefully no nightmare tonight)

Can you move that to core? 

`ExpressionProfileToExpressionProfileBuildingBlockMapper` is where it belongs

**Comment by rwmcintosh** [comment]
Does that mean the PKSim building blocks ```Individual``` and ```ExpressionProfile``` have to move as well?

**Comment by rwmcintosh** [comment]
oh, nvm. they should be in PKSim.Core. I thought you meant OSPSuite.Core.
