### ISSUE TITLE
Aging Data. Should they be in PSV or Individual?

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2574]
@Yuri05 Right now, we are creating those overrides in the PSV I think, But should that be done in fact in the new Individual?

**Comment by PavelBal** [comment]
Didn't we want to define aging parameters as tables?

**Comment by PavelBal** [comment]
Agree.

**Comment by Yuri05** [comment]
yep, should be in the individual
