### ISSUE TITLE
Histograms in PK-Sim

### ISSUE THREAD

**Issue by hamayer** [Open-Systems-Pharmacology/PK-Sim#258]
When one creates a population in PK-Sim, some histograms (e.g. for many but not all organ volumes and ontogeny factors) look strange. This was not the case in PK-Sim 6.4. Please have a look at the attached screenshots.

![histogramspksim](https://user-images.githubusercontent.com/31309962/29704089-8ca4bc68-8978-11e7-8d65-ab12bc0c8bf8.PNG)
![histogramspksim2](https://user-images.githubusercontent.com/31309962/29707146-898b6e08-8984-11e7-8adf-34f0e5cd32e9.PNG)

[example_population.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1251151/example_population.zip)

**Comment by msevestre** [comment]
Hi @hamayer 

Thanks for reporting the bug. We have fixed it already and the fix will be available in the next version 7.2
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/177 for reference

Cheers
