### ISSUE TITLE
Distribution of t1/2  for different enzymes

### ISSUE THREAD

**Issue by hamayer** [Open-Systems-Pharmacology/PK-Sim#259]
When creating a population in PK-Sim, the standard deviation for t1/2 (liver) for CYP1A2 is set to 24 hours for a normal distribution by default. This results in non-constant values for this parameter as default. After switching to a log-normal distribution and back to a normal distribution it is set to 0 as for the other enzymes.
In all cases switching to a uniform distribution creates a range from 0 to the mean value and thereby a distribution of the correponding parameter. As far as I know the t1/2 value should remain constant as long as the user does not explicitly want to change this. 

![distribution_enzymes](https://user-images.githubusercontent.com/31309962/29708151-fd88a7dc-8987-11e7-9dd9-11aff963b148.PNG)
![uniform_distribution_cyp3a4_t05](https://user-images.githubusercontent.com/31309962/29708154-ff41fa88-8987-11e7-9877-b2caed7d3d78.PNG)

[example_population.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1251441/example_population.zip)

**Comment by msevestre** [comment]
Hi @hamayer 
>As far as I know the t1/2 value should remain constant as long as the user does not explicitly want to change this.

These values are defined in the PK-Sim database and are used by default when the enzyme are selected

![image](https://user-images.githubusercontent.com/1041237/29717601-c440793c-897d-11e7-9cbb-73345fb53502.png)

Why would you expect the value to be zero?
