### ISSUE TITLE
Observed data mappings get duplicated in a simulation

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2592]
When I try to add observed data to a simulation 2nd time - it does not happen (correct behaviour).
It happens just at some time point while working with PK-Sim projects, and I did not yet figure out when.
Example attached
[ObsData_LLOQ_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/11222458/ObsData_LLOQ_2.zip)
![grafik](https://user-images.githubusercontent.com/25061876/231767084-e49b42d2-b15b-4f0a-86cc-cc42043ddfd5.png)

**Comment by Yuri05** [comment]
The bug becomes really problematic when adding simulations with "duplicated" mappings to a PI.
E.g. if time profiles where created in the PI: such a PI cannot be opened anymore after the project was closed.
Not sure why the error below comes only after closing and reopening the PI (and not directly after creation of time profiles there), but the first place error is the mapping duplication in the simulation
```

System.ArgumentException: An item with the key 'Avg' has already been added ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Presentation.Presenters.Charts.DataBrowserPresenter.<AddDataColumns>b__15_0(DataColumn
```

**Comment by msevestre** [comment]
My guess is that an event is being thrown that adds it but does not refresh the view

**Comment by georgeDaskalakis** [comment]
@Yuri05 I cannot reproduce unfortunately.  When adding the observed data a second time, the duplication is detected and never happpens:

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/37107428/de22ed1f-2477-4661-8447-d14d6c1da656)

neither is any kind of event triggered. The duplicate then probably gets added some other way, although I cannot say how and this is indeed a bit worrying.

**Comment by msevestre** [comment]
Someone just posted a bug . Looks very similar

**Comment by georgeDaskalakis** [comment]
This has to do indeed with cloning. Hope to have a solution soon.
