### ISSUE TITLE
Re-import population after cutting the number of subjects

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/PK-Sim#2603]
Hi all,
After creating a population in PK-Sim, I exported the population as csv and deleted a number of subjects. When re-importing the truncated population into PK-Sim, I received an error note in the population import window: 
'Error: Input string was not in the correct format'

Looks like it is less an issue of the population size but rather the file format although I saved the file in csv-format after the modification

**Comment by Yuri05** [comment]
Can you attach the modified population file?
Did you modify it with Excel? Excel often changes the CSV formatting of the files, making them unreadable for the OSP

**Comment by JanSchlender** [comment]
Correct. Has been done in Excel. Is this a general incompatibility following Excel-based processing or can this be circumvented by changing the separator formatting of Excel?

**Comment by Yuri05** [comment]
As far as I know it's not possible in Excel directly.
You would need to close excel, change the windows language settings (decimal separator, columns separator), then open Excel and export your csv file(s). After this you can reset your windows language settings back again

**Comment by Yuri05** [comment]
EDIT: seems possible in Excel directly
![grafik](https://user-images.githubusercontent.com/25061876/234020610-52f80935-ea9d-41d5-be0e-8d570c9e35b3.png)
