### ISSUE TITLE
Overriding Ref Conc and applying HI should use the updated RefConc

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2615]
Right now, it's using the default one. Problaby one flag is not set as expected

**Comment by msevestre** [comment]
@Yuri05 @PavelBal @StephanSchaller 
Question for you: At the moment, Expression profile in Individual is a pure copy of the individual building block. 
With HI implementation, we are introducing a perturbation to this model and I'd live to have an opinion

Say we are using HI, CYP3A4 and Child Pugh Score B. Accoding to implementation, we need to change Ref Conc by multiplying the default value by 0.4

Here is what I have now:
* Expression Profile is not changed (building block)
* I overwrite the value of Ref Conc in the individual ( say 4 * 0.4 => 1.6)

Now, when we create a simulation, we are right now exporting the Expression Profile (building block) and the value 1.6 is forgotten (this is this issue that I just created).

Multiple options

* the expression profile that we create (the MOBI BuildingBlock) has the value 1.6
* The individual building block that we create (the MoBi building block) gets a new entry for the expression profile value that was changed (an entry for the molecule in the individual building block)
* Or we create an entry in the PSV. That would mean that the Individual will look like a standard HI Child Pugh b, the expression profile would look like the default one and only via the PSV would we synchronize everything


I am not sure what makes more sense . Feedback please :)

**Comment by Yuri05** [comment]
I think, HI should not modify RefConc in the individual at all.
Instead, when creating an **Expression profile**, the HI-scaling should be applied.
At the moment we have only "Healthy" as predefined state for Expression profiles. This list should be extended with HI. When selected, the predefined RefConc in the Expression profile is scaled.
Then no other changes of how Expression profiles are used in Individuals/Simulations are required

**Comment by msevestre** [comment]
I have no idea what you are talking about

**Comment by msevestre** [comment]
The expression profile is created outside of the individual
The disease state is applied to an individual. Selection of expression profile happens after the fact. Or do you want to ask the user to apply this scaling by hand? Or we apply a disease state that is more than just a string? This would require serious changes in expression profile to support real disease state based on our db. In this cases those are 3 brew diseases state. Hi -A, hi-B etc..

**Comment by PavelBal** [comment]
> the expression profile that we create (the MOBI BuildingBlock) has the value 1.6

This option makes the most sense to me. This also makes sense for the concept of having a "phenotype" assigned to an expression profile. So one phenotype would be "healthy" with reference concentration of 4, the other would be "Child Pugh 4" with reference concentration 1.6.

The other two options proposed to you will be mixing protein properties with other building blocks and I am strongly against it.

**Comment by msevestre** [comment]
I'd like to discuss this tomorrow. Creating a new expression profile building block completely would solve some problems downstream. But I am not sure how user friendly this would be

**Comment by msevestre** [comment]
but otherwise, option 1 is the only that makes sense to me also

**Comment by Yuri05** [comment]
> The expression profile is created outside of the individual
> The disease state is applied to an individual. Selection of expression profile happens after the fact. Or do you want to ask the user to apply this scaling by hand? **Or we apply a disease state that is more than just a string? This would require serious changes in expression profile to support real disease state based on our db. In this cases those are 3 brew diseases state. Hi -A, hi-B etc..**

Actually yes, this would be the most accurate solution. Disease state would be defined **not only for Individual but also for the expression profile**, e.g. like this:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/fe608f1c-d4e6-498e-b17b-c46bf5a727c1)

Then the RefConc-Scaling would **automatically** take place **in this Expression Profile BB**:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/97996c4a-31a7-41c4-bc4b-fa01f05d2e98)

After that, when addin an Expression profile to the diseased individual - nothing happens with the expression profile anymore.
Of course it usually would only make sense to add a HI-PughScoreB expression profile to a HI-PughScoreB individual (which is the responsibility of the user)

**Comment by msevestre** [comment]
>E.g. at the moment, when using a diseased individual in a simulation: the scaling is lost

lol yes. THis is this ISSUE :)

I am trying to think about the best workflow if we implement something like this
Specifically, DiseaseType does not exist at all at the expression profile level. It's just a string. When we create it, it's empty and ONLY then  do we load from DB and scaling can happen. So this is somewhat backward.

A potential workflow could be
1-We have an expression profile for healthy 

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/d7c863f4-7c39-4004-88d8-9a5ebddbda18)

In my individual, I select HI-CPSB
And I select this Expression PRofile. In this case PKSim does a check
1-Is this a enzyme for which we have know scaling for HI? No, do nothing
2-Yes: Is the selected EP marked as created from disease state (here we need to save this somehow)
3-if yes, use as IS (scaling was done already)
4-no, create a new one, mark it as created from disease state, set a name automatically  (adding HI - CPB for instance at the end of the phenotype or replacing the phenotype with this for instance)
5-Add this new expression profile in the project 
6-use this one instead. 

This is very complicated and probably error prone but that's the only way I can see it working.

Or we just overwrite the ExpressionProfile BB....

**Comment by msevestre** [comment]
but you are right. Messing around with  expression profile bb makes uddate commit logic impossible

**Comment by Yuri05** [comment]
>4-no, create a new one, mark it as created from a disease state, and set a name automatically (adding HI - CPB for instance, at the end of the phenotype or replacing the phenotype with this, for instance)
5-Add this new expression profile to the project

I wouldn't make it so complicated. Instead:
* In the protein expression selection Combobox: mark all protein expressions which are created NOT for the disease state of the individual/population with the warning icon ⚠️
* If the user selects one of these expressions: show warning ("Disease state does not match... Are you sure...?")
* If after that user adds the protein expression: add AS IS: no new expression BB, no scaling

**Comment by msevestre** [comment]
>mark all protein expressions which are created NOT for the disease state of the individual/population with the warning icon ⚠️

Ok but how do we create an expression profile for a disease state. See my ordering problem from before

1-The phenotype is just a string, not a state. Now we could string match and say well if you change what we gave you , than too bad 
2-The expression profile is created empty AND THEN data are loaded. So when do we apply the scaling. After loading from DB only mostly/probably. ?

I think if we solve 1, then this is the cleanest way to go. But I am not sure how to CLEARLY mark an expression profile as Disease state

**Comment by msevestre** [comment]
WHat about sthg like this

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/cd6ae686-8293-4cc6-8b1f-e341d7b0dffa)

WE cannot use the phenotype entry as a marker of disease state since we have parameters etc.. So we might have to tweak the description a bit. The list of options comes dynamically based on the species and molecule type. For instance, we only have for human and enzyme for now. Using another species or another type would show nothing

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/b2ff1d29-b148-4e54-94c1-1158bf78b72f)


we don't have anything for CKD so it does not show up either
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/09d61809-5b24-4f50-bbae-17c7ded47e1e)

SCaling will only be APPLIED AFTER selecting from data base. Anything else does not make sense

Thoughts @PavelBal @Yuri05 @StephanSchaller

**Comment by Yuri05** [comment]
>WE cannot use the phenotype entry as a marker of disease state since we have parameters etc.. 

I wonder if we still could use phenotype combo for the disease state selection.
It could be **prepopulated** with "Healthy" and the disease states.
If the user selects one of the predefined disease states - state-specific parameters (like pugh score for HI) are shown.
If the user selects "Healthy" OR enters free text - all disease parameters are hidden and no scaling happens later on.

**Comment by Yuri05** [comment]
>SCaling will only be APPLIED AFTER selecting from data base. 

You mean Gene-DB? Because RefConc is currently read from PK-SIM DB, not from Gene-DB

**Comment by msevestre** [comment]
Hum yes you are right. Assuming this is the only thing we would vary, we could apply right after creation indeed.

Your suggestion would work but is very brittle. As soon as I am selecting this entry, and renames (for instance to shorten it or whatever), this won't be recognized as kidney state (or even healthy state but in this case, we can assume anything else is healthy). 
Drawback is also that we cannot really rescue the same control and we have to implement here something special.
What happens upon rename? Or clone etc...i find personally, that basing Logic on string matching can become very brittle

**Comment by StephanSchaller** [comment]
@AnnikaRPS, @VanessaBa

**Comment by msevestre** [comment]
No this is too complicated. The phenotype is what makes it unique.

**Comment by msevestre** [comment]
I think this is really the user's job to make sure they do not name the stuff healthy if they use HI (in fact, we could even prevent it or warn the user )
=> If I want HI-CPA, I can enter as phenotype HI-CPA and select Heaptic Impairement, Child Pugh A
=> If I want HI-CPA, I can enter as phenotype HI-CPB and select Heaptic Impairement, Child Pugh B etc..

so phenotype and disease state are linked somehow . I think we should just warn users that using HEalthy as a phenotype when Healthy is not the disease state will be hard to understand
