### ISSUE TITLE
HI: check if the "double scaling" of Q_liver is correct

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2621]
s. the discussion https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2620/files?w=1#r1194943507

**Comment by msevestre** [comment]
FYI @aedginto @sdubinsk

**Comment by msevestre** [comment]
Apparently hepatic arterial and liver blood flow is not the same....FYI

**Comment by Aedginto** [comment]
yes, arterial increases. is the LIVER in the spreadsheet above, the arterial component only or the summation of portal + arterial?

**Comment by Yuri05** [comment]
>is the LIVER in the spreadsheet above, the arterial component only or the summation of portal + arterial?

Arterial to Liver only, without portal vein.

**Comment by Aedginto** [comment]
we have a plan...coming really soon:-)

**Comment by sdubinsk** [comment]
Hi all
We have adjusted a few parameters and out standing questions:

1)Hematocrit (HCT)
To prevent using an absolute value for HCT we have created a scaling factor to reach the target absolute values across the disease for the "average" individual. In PK-Sim the default HCT for a healthy individual was 0.47, however in Edginton et al the healthy HCT was set at 0.43. We have taken the average (0.45) as the base to formulate the scaling factor. Please see below:
**Scaling Factors for HCT**
Child-Pugh A: 0.866
Child - Pugh B: 0.822
Child - Pugh C: 0.778

2)Liver blood flow
It is indeed correct to "scale" liver blood flow twice per se to account for 1)increases in hepatic arterial blood flow and 2)reduction in overall liver mass. We have adjusted the scaling factors and methods as to how to reach the final value. As such, we have adjusted the ratio of healthy:disease to achieve an absolute hepatic arterial blood flow that matches a typical male with Child-Pugh A,B or C as reported by Johnson et al (See below)

 ![Screenshot (836)](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/80400115/eb4f501c-544c-4557-a379-78943c927f00)

Therefore healthy:disease hepatic arterial blood flow should be as follows:
Child-Pugh A: 0.466
Child-Pugh B: 0.538
Child-Pugh C: 0.635

 As for implementation into the algorithm, when scaling the liver it will need to be adjusted by: 1)scaling liver volume, then 2) applying scaling factor to Liver Blood flow. 

These changes have downstream effects on the "other organs" as the Disease Factor for Other Organs (Disease Factor Other) will change. 

However, after making these changes the disease factors and other organ blood flows changed by values of 0.01-0.2 (very minor). Ultimately giving confidence into the previous method and will not effect the overall results.

**Comment by msevestre** [comment]
ok going to give this a good old college try

**Comment by msevestre** [comment]
@Yuri05 
>We have decided not to follow the scaling factor from Edginton 2008 anymore. We have now set a scaling factor to match the absolute values of Johnson et al. 

So liver blood flow in the individual should match:

CPA - 28L/h or 0.466 L/min
CPB - 32.3 L/h or 0.538 L/min
CPC - 38.1 L/h or 0.635 L/min
