### ISSUE TITLE
Create Individual: change Disease State selection label

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2624]
Would suggest to change the label "Select" to "Disease state":
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/af20026a-85dc-463c-a9ef-871936a462e6)

Like it's already the case in the Expression Profile
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/5a9ccd07-6bac-473a-89d8-1f133d75cb86)

**Comment by msevestre** [comment]
I disagree with this. The grouping already says Disease state. Is this not weird?

**Comment by Yuri05** [comment]
Then at least after creation it should be modifyed. Having the label "Select" without any selection possibility is strange
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/4702d1fb-84ae-4627-99c1-61f81b0fbdbc)
