### ISSUE TITLE
No expression profiles created when exporting a simulation from PK-Sim to MoBi.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2627]
When importing a pkml created with V11.2, no expression profiles are created. Though it is an expected behavior, expression values should still be somewhere, e.g. in the PSV.

**Comment by rwmcintosh** [comment]
If you create and export a simulation, all the expressions are present in the transfer.

If you save/load the PK-Sim project, then the individual referenced by the simulation no longer has any expressions. When you transfer, the resulting MoBi building blocks will also not have any expressions.

In the case of a project building block, the expressions are applied in the ```ProjectMetaDataToProjectMapper``` from ```SimulationSubjectMetaData```.

There's no analogous step for an individual in a simulation.

**Comment by PavelBal** [comment]
1. Open a V11.2 project in PK-Sim v12
2. Save a simulation as pkml
3. Load in MoBi

No expression profiles are created, and the expression values are also not in any PV BB.

I think in this case, expression profiles should be created, as the simulation is coming from PK-Sim 12.
