### ISSUE TITLE
On going Project conversion. 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2646]
- [ ] Add expression profiles to individuals

see https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2645#discussion_r1209575839

I don't think this is as easy at it seems. Really only doable when the individual is in GREEN STATE. Otherwise, there is potentially a difference between the Exp Profile Template and the one theoretically used in the simulation

- [x] Maybe update due to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2660
- [x] https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2849

**Comment by rwmcintosh** [comment]
Closing with this open issue as the only remaining issue for project conversion

https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2627
