### ISSUE TITLE
Should we name the STD column "**Geometric standard deviation**" instead of just "Standard Deviation" to become more clear?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2666]
Should we name the STD column "**Geometric standard deviation**" instead of just "Standard Deviation" to become more clear?

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2636#discussion_r1239645115_

**Comment by msevestre** [comment]
done in #2672
