### ISSUE TITLE
Expression profiles comparison: same ontogeny shown as different

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2687]
Import the project from snapshot [Expr_Digoxin_Pediatrics.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/12162082/Expr_Digoxin_Pediatrics.zip) and compare 2 expression profiles.
Ontogeny is shown as different - but it's the same
(I also compared the ontogeny name with the text search in json - it's the same)
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/88c8a108-13ac-4bc9-a58a-71078a7a9c0f)

**Comment by msevestre** [comment]
Yeah but they are imported from Excel (user defined). Do you want to compare the table in this case?

**Comment by msevestre** [comment]
Ok I can make it a bit better I think
However, there is an interesting bug. Saving the snapshot from above as project and load => crash
