### ISSUE TITLE
Comparison: wrong error message when selecting >2 building blocks

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2688]
When I occasionally select 3 or more BBs (or Simulations) for comparison, the wrong error message below is shown.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/6de0b49b-6414-4510-bb76-199da6463438)

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/84895265-1344-49b9-b41d-ebfba866db1f)

**Comment by msevestre** [comment]
intersting. In fact the menu should not even be available for 2
