### ISSUE TITLE
PKSimDB: unused container names?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2692]
<details><summary><b>Executing this SQL query retrieves some containers which seem to be unused in the database.</b></summary>

```
select * from tab_container_names 
where container_name not in 
(
select distinct container_name from tab_containers
union
select distinct ref_container_name from tab_object_paths
union
select process from tab_processes
)
order by container_name 
```
</details> 

Can we delete them, or is any of them used elsewhere?

container_type | container_name | display_name | description
-- | -- | -- | --
FORMULATION | \<FormulationName\> | \<FormulationName\> | \<FormulationName\>
COMPOUND | \<PROCESS\> | \<PROCESS\> | Template for Compound process in simulation
GENERAL | AdvancedParameters | User Defined Variabilities | User Defined Variabilities
PROCESS | BrainActiveEffluxToPlasma_Hill | Brain specific active efflux - Hill | The transmembrane efflux transporter actively transports the   compound from the interstitial compartment to the plasma in brain
PROCESS | BrainActiveEffluxToPlasma_MM | Brain specific active efflux - Michaelis-Menten | The transmembrane efflux transporter actively transports the   compound from the interstitial compartment to the plasma in brain
PROCESS | BrainActiveInfluxFromPlasma_Hill | Brain specific active influx - Hill | The transmembrane influx transporter actively transports the   compound from the plasma into the interstitial compartment in brain
PROCESS | BrainActiveInfluxFromPlasma_MM | Brain specific active influx - Michaelis-Menten | The transmembrane influx transporter actively transports the   compound from the plasma into the interstitial compartment in brain
COMPOUND | COMPOUND | Compound | Compound
COMPARTMENT | ExtracellularMembrane | Extracellular Membrane | Extracellular Membrane
FORMULATION | Formulations | Formulations | Formulations
ORGAN | GI-Tract | GI-Tract | GI-Tract
COMPARTMENT | IgG_Interstitial | IgG_Interstitial | IgG_Interstitial
COMPARTMENT | IgG_Plasma | IgG_Plasma | IgG_Plasma
COMPARTMENT | Liquid | Liquid | Liquid
ORGAN | PlasmaMetabolization | Plasma | Plasma organ used to manage metabolization processes taking   place into plasma
COMPARTMENT | Proteins | Proteins | Template for proteins
GENERAL | REACTION | REACTION | Global reaction properties container
GENERAL | ReactionProperties | Reaction Properties | Global reaction properties container
COMPARTMENT | VascularEndothelium | Vascular Endothelium | Vascular Endothelium

**Comment by Yuri05** [comment]
ok, "AdvancedParameters" and "VascularEndothelium" are used, the rest can be safely delted

**Comment by msevestre** [comment]
I'd delete and run all integrations test and see :)

**Comment by msevestre** [comment]
back to you alter
