### ISSUE TITLE
IndividualParameterBySpeciesRepository=>UsesForAllSpecies returns wrong value for distributed paramters

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2705]
@Yuri05 
They are all exported as true but this is clearly wrong ?

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/4c66edef-321c-4489-bdeb-bede3f6f2368)

and

```
_commonParametersRepository.UsedForAllSpecies(parameterMetaData)
true

```

**Comment by msevestre** [comment]
I am going to push what I have done now so that you can build off this if you want @Yuri05

**Comment by msevestre** [comment]
Yeah I think this is a problem to have parameter of different types being returned as same for all species (Hematocrit for instance). Let's discuss

**Comment by Yuri05** [comment]
I don't get it from the example. 
Specific blood flow rates are used by all species, so `UsedForAllSpecies=true` is the expected result here(?)

**Comment by msevestre** [comment]
See my comments
They are different parameter Structure. That means we can't create the parameters in the spatial structure ahead of Time

**Comment by msevestre** [comment]
So I am not sure if I should also check what the formula stuff is doing? In this case, the the knowledge that a parameter exists for all species is useless as an API for me

**Comment by Yuri05** [comment]
> See my comments They are different parameter Structure. That means we can't create the parameters in the spatial structure ahead of Time

What about const vs. formula - is this problematic as well?
E.g. `Lumen|Duodenum|Length` is defined by formula for human and by const. value for other species.
So the queries will return `UsedForAllSpecies=true`  `isSameFormula=false`  `isSameValue=false`
