### ISSUE TITLE
Metabolite does not get updated

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2709]
* Open the project attached [UpdateMetaboliteError.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/12378690/UpdateMetaboliteError.zip)
* Edit compound C1 and change the metabolite from empty to C2
  <img width="450" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/77117cad-a700-4338-91f5-bacc30e3c4a2">
* Update C1 from simulation
  <img width="300" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/c07ebb9a-ec6b-44e5-bd40-010d897d1aa5">
* Open C1 - the metabolite is still set to C2. Is not a refresh problem - if I close C1 and reopen - still no changes

**Comment by msevestre** [comment]
It should be marked as a structure change but looks like it's not. Therefore, only parameters are updated. Here a full reconfigure is required

**Comment by msevestre** [comment]
ok I just need an issue to remove orphan object in the diagram
