### ISSUE TITLE
Fix appveyor-nightly.yml

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2732]
I think we should just define the schedule in the AppVeyor project configuration (as before) and remove the `schedule` section from **appveyor-nightly.yml**
The rest of the new code seems to work (at least when I try it locally):

<details><summary><b>Testing time from the last commit locally</b></summary>

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/138288f3-4ec7-41ab-8b7c-c3e855e692c5)

</details> 

_Originally posted by @Yuri05 in https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2731#issuecomment-1707908019_

**Comment by msevestre** [comment]
Interesting. I am wondering if this schedule option actually exists lol

**Comment by msevestre** [comment]
ok updated
