### ISSUE TITLE
12.0 project conversion issue

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2733]
When opening a project which contains an individual created with $\le$ v11 and creating a simulation with this individual in v12: some parameters in the simulation become NaN, e.g.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/1c737efd-dad2-4cea-aa10-a84b0e45d433)

**Comment by msevestre** [comment]
Interesting

**Comment by rwmcintosh** [comment]
Recheck

**Comment by rwmcintosh** [comment]
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2946
