### ISSUE TITLE
Cloning a simulation deletes turnover reaction icons?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2750]
Simulation **NEW_S1...** was cloned from **S1...**
When comparing both simulations: icon property of the **CYP3A4 Turnover** reaction is resetted in the cloned simulation.
Happens only for this reaction: icons of other reactions show no difference in the comparison
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/bbc1e498-d207-497e-9330-b7775c9da5e0)

**Comment by msevestre** [comment]
Can you attach a project please? It just takes too much time to reproduce

**Comment by msevestre** [comment]
same with expot to Mobi. Going to forget this as well until we can reproduce
