### ISSUE TITLE
Cloning a simulation changes display unit for "Undefined Liver Transporter" parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2751]
Seems to happen only for this particular transporter; not for other enzymes/transporters.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/c1318276-edd6-4b5e-a388-d55b61362043)

**Comment by msevestre** [comment]
I can't repdoruce. CAn you please attach a project?

**Comment by msevestre** [comment]
@Yuri05 Ping :)

**Comment by Yuri05** [comment]
OK could not easily reproduce with the new project, but with this older one (create with PK-Sim 12.0.73 or so)
[CloneTest.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/13349082/CloneTest.zip)

I wanted to recreate the project from snapshot, but this failed (s. https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2831)

Cloned the simulation **S1_Adult_4comp** to **Clone_S1_Adult_4comp** and compared the m with the settings below:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/ab53d295-4b89-456c-950c-3ab411817aee)

then I see several problems (some of them seem to be new):
1. Display unit changes, described in the issue
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/3815efd3-12e4-493e-bcbf-67f9fed6579a)
2. Lot of descriptions disappeared in the cloned simulation
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/0efc534c-f74a-41d8-82ed-15182b18503e)
3. Some Icons disappeared in the cloned simulation
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/d0b139b5-9dc2-44b1-9ba0-8cf2d79cf408)
5. Event property moved?
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/252199c7-5eea-4ab5-b304-70f6eb48600c)

**Comment by msevestre** [comment]
this is also clearly not accurate
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/55ea70c5-09b6-4861-85bd-7c37c5dc183f)

**Comment by msevestre** [comment]
ok so as far as description is concerned. I realized that we are modifying the simulation being exported when exporting to MoBI by adding icons and descriptions to it (they are not saved in the object in PKSim that's why) we have so many differences
I soon as I export to MoBi it's ok (at least for descriptions and icons)

**Comment by msevestre** [comment]
a solution would be to change the flag `shouldCloneModel` to true when exporting to MoBi instead of reusing it 
`var moBiSimulation = _simulationMapper.MapFrom(simulation, configuration, shouldCloneModel: false);` 

This is probably cleaner to be honest

**Comment by msevestre** [comment]
I don't even know why those parameters would change. They are not visible in PKSim
When we clone we recreate from scratch and update the values. WE do not synchronize units whatsoever
I cannot also reproduce setting this clone property to true
So I am going to update the code like this, submit a PR and we should merge and try to reproduce
