### ISSUE TITLE
No expression profiles created when opening a simulation exported from PK-Sim

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2753]
https://github.com/Open-Systems-Pharmacology/OSMOSES/blob/examples/UseCases/V11.2/Fluvoxamine-Omeprazole-DDI.pksim5

- A PK-Sim project has been created with PK-Sim V11.2 by loading from snapshot
- V11.2 project has been opened in PK-Sim V12 and a simulation has been exported to pkml.
- Opening this simulation in MoBi V12 does not create any expression profiles. Information about proteins is completely lost, re-creating a simulation from Building Blocks creates a simulation without proteins.

**Comment by rwmcintosh** [comment]
The issue here is that after save/reload, the individual in the simulation does not have a reference to any expressions. When you create the simulation fresh, then export everything is in place, but after save and open, the **individual in the simulation** does not reference any expressions.

**Comment by rwmcintosh** [comment]
There is an issue open for this. It's being tracked in #2646 as one of the todo's.

There are questions how this could be implemented (or if!)
