### ISSUE TITLE
New path keywords not resolved in individual building block?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2760]
E.g. try to start PK-Sim with this database: [PKSimDB.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/12586008/PKSimDB.zip)

Here, the paths for `ORGAN|Volume (endothelium)` were changed using the `<NBH>` keyword.
This worked when tested in MoBi:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/993978cd-cabe-4e75-b857-6cb243f34d6c)

However, when trying to create an individual in PK-Sim the error comes

```
Unable to resolve path '..|Plasma|<NBH>|..|Interstitial|<NBH>|Surface area (plasma/interstitial)' 
for entity 'Volume (endothelium)' with path 'ROOT|Organism|Bone|Volume (endothelium)'
```
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/8a8337ba-a617-4c22-b8aa-89ffd62c1ede)

**Comment by msevestre** [comment]
Ok I didn't think we would need this outside of simulation resolution. I need to promote this feature to the reference resolver somehow
