### ISSUE TITLE
Changing transpor direction in the expression is not applied in the simulation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2761]
1. Add a transporter protein with direction "Efflux"
2. Add a transport process using the new transporter protein to a molecule
3. Create a simulation and send to MoBi:

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25903040/218e0585-d248-4cd1-adba-9dcc02cd29c7)

4. In the Expression Profile, change the direction of the transporter protein to "Influx". Simulation becomes "Red" and the comparison with building block correctly shows the difference in direction:
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25903040/906b00d7-0225-468d-a42f-fa074e8d49d1)

5. Right click on individual BB in the simulation and select "Update from BB"
6. Send the updated simulation to MoBi -> Direction of the transport is still "Efflux":

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25903040/1578de90-1870-41e7-bcce-f1341f34cbf7)

**Comment by PavelBal** [comment]
Version 11.2

**Comment by msevestre** [comment]
It's because this is not seen as a structural change of the BB and the update will only be seen as a parameter update (which is quick update)
