### ISSUE TITLE
Unify formulas for Partition coefficient (interstitial/water)

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2766]
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/95c50fce-2570-4869-92cd-adb0dbc078df)

**Comment by Yuri05** [comment]
@PavelBal This should also solved the eternal problem of missing `Partition coefficient (interstitial/water)` in the new organs added in MoBi

**Comment by msevestre** [comment]
Oh my goodness
Let's party 🥳🥳🥳🥳🥳🎉🎉🎉🎉
