### ISSUE TITLE
V12: Aging simulations do not work anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2767]
When trying to run a simulation with aging: errors below come.
Reproducible with arbitrary individual/compound.

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/a445df62-8a45-457d-a31e-4672b244406c)

**Comment by msevestre** [comment]
How are all our tests running? WTF?
