### ISSUE TITLE
V12: Renal Clearance processes sometimes not created

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2768]
If we have several compounds with the same renal systemic process (e.g. GFR) - it is not created for some compounds in the simulation.
[12_C1_C2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/12641509/12_C1_C2.zip)
E.g. in the attached project compound C2 is a clone of compound C1 and processes for both compounds are configured identically in the simulation:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/e895891b-8965-4b59-848d-717c85443a74)

When exporting the simulation to MoBi:
Renal clearance transports are created for C2 but not for C1:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/53dd1ae1-8777-411f-820a-aebd36729cdf)

Biliary clearance transports and liver plasma clearance reactions are created properly:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/bb16062f-7db2-4eb8-894b-c3deb5de96c6)![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/7f7f063a-f2e9-40b6-bc41-eb4de54cc3d2)

**Comment by msevestre** [comment]
That's new ?

**Comment by Yuri05** [comment]
> That's new ?

yes, this worked in V11

**Comment by msevestre** [comment]
ok checking this...sounds like a fun one

**Comment by msevestre** [comment]
@Yuri05 Are you sure this worked in v11 ??

**Comment by msevestre** [comment]
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/df12d371-435d-4786-801c-42c9cdfdc76c)

even in MoBi. The processes are defined multiple time with the same name!!

**Comment by msevestre** [comment]
@Yuri05 What should be the correct way?
Add all molecules to the molecule list ? or create a compound specific process ?e -g Rena Clearance-Kid-C1 nad Renal Clearance-Kid C2

**Comment by msevestre** [comment]
(same with GFR in fact).

**Comment by Yuri05** [comment]
This worked in V11
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/dad163fb-534d-4fe4-af5d-5a1c895e6c8e)

Apparently we created a process with the same name - one per molecule
<img width="350" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/7b275304-71ba-4074-86dd-356b61828149">) <img width="400" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/5c44e457-5c25-4b98-89d0-9af495fd5766">

**Comment by msevestre** [comment]
I have no idea how this could have worked lol. Maybe we changed sthg in core internals but this worked just by coincidence

**Comment by Yuri05** [comment]
Anyway, with the fix it works now - well done 👍

**Comment by PavelBal** [comment]
Related to this: https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2550

**Comment by msevestre** [comment]
Yep exactly this.  Your suggestion would be much better indeed. Let's discuss to see if this is doable
