### ISSUE TITLE
V12: Ontogeny factors AGP/Albumin wrong in SIMULATIONS

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2770]
E.g. create ICRP 0-years old male and a simulation with this individual.

In the individual BB ontogeny values are correct:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/0690d00a-ecc6-4361-96e1-dec22adea8d0)

But in the created simulation ontogeny values are all set to 1:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/72bfc365-5aed-45bd-8004-7ae3c12b8ab9)

**Comment by msevestre** [comment]
Ontogeny as a table: Probably the worst idea of @PavelBal  so far :)

**Comment by msevestre** [comment]
Looks like for some reason, the tables are not taken over in the simulation
![Uploading image.png…]()

**Comment by msevestre** [comment]
seems like the parmaeter is not found as an individual parameter that is  not global
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/774b66bb-4737-49ac-868b-7f62043a947c)


@Yuri05 ?? :)

**Comment by msevestre** [comment]
ok
 ```
_sameFormulaOrValueForAllSpeciesRepository.IsSameFormulaOrValue(parameter)
true
```
where the parameter was replaced dynamically by a table.. This is a special case indeed :)

**Comment by PavelBal** [comment]
> Ontogeny as a table: Probably the worst idea of @PavelBal so far :)

Oh I had worse, believe me :D
