### ISSUE TITLE
Parameter identificaiton - outputs are added multiple times

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2775]
When I start a PI from a simulation with mapped outputs, outputs are added multiple times.

Cannot share the project, will share with @rwmcintosh and @georgeDaskalakis

**Comment by msevestre** [comment]
This is probably in core so moving

**Comment by msevestre** [comment]
@PavelBal Can't reproduce. Just tried with the latest PK-Sim
Please attach a project and the steps to reproduce

**Comment by msevestre** [comment]
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/afe567c4-5711-4189-b715-7c7a2f8e1b14)

This was created from the simulation

**Comment by msevestre** [comment]
ASsuming this was done in v11. Cannot reproduce. Please try again in v12 and letus know

**Comment by PavelBal** [comment]
It actually happened on the simulation level - somehow, the observed data were present multiple times in the "Observed Data" tab and this was propagated to the PI. But no idea how this could happen.

**Comment by Yuri05** [comment]
happened due to https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2592
