### ISSUE TITLE
PK-Sim Batch runner does not save units

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2787]
<img width="450" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/062ee293-1f5e-46ef-8b8e-0c28f3aa02ed">

E.g. in my example, the times values are stored in [h] in the output file of the Batch Runner, but then interpreted as [min] by the Simulation Output Comparer.
Then in the report a plot looks like this:
<img width="450" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/19dba7f6-e2e0-4ec9-81c1-7a86b30ecd86">

But in the original project:
<img width="450" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/24e7a859-c9a0-45dd-954c-7a7baf4c10dd">

So either the Batch Runner should always save the values in the base unit of the dimension, or the units must be stored as part of the output (like in the snapshots)

**Comment by msevestre** [comment]
so we save in display value indeed but we don't specify what the display value is in those values
