### ISSUE TITLE
V12: Delete simulation folder submenu disappeared?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2840]
In V11:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/eb90976b-8024-40cc-b1ef-7abf1ffb3372)

In V12:
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/2470e3f3-a221-4e22-b411-dee8de9609eb)

**Comment by msevestre** [comment]
But you have Add simulation 
Life is a matter of compromise sometimes

**Comment by Yuri05** [comment]
> But you have Add simulation Life is a matter of compromise sometimes

I know, one cannot have _everything_ But...

**Comment by msevestre** [comment]
interestingly this has moved to the wrong place..
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/12089272-94b1-40bf-9cbc-6dd8b4f51ff7)
