### ISSUE TITLE
Define parameter `Volume (endothelium)` with a single formula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2841]
In all organs, parameter `Volume (endothelium)` can be defined by a formula `VOLUME_VascularEndo = SA_pls_int * d_endo` with 
- `d_endo = Organism|Thickness (endothelium)`
- `SA_pls_int = ..|Plasma|<NBH>|..|Interstitial|<NBH>|Surface area (plasma/interstitial)`

**Comment by Yuri05** [comment]
is already implemented
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/d6e5d3f4-62af-4385-b2ad-396c79333b2b)
