### ISSUE TITLE
Unit of t1/2 in individual enzyme expression is not updated when changing unit in Expression profile

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#2847]
Steps to reproduce:
Individual was loaded from template and opened. CYP3A4 expression profile was opened and value and unit of t1/2 were changed.
-->value was updated in individual, but not unit!

**Comment by Yuri05** [comment]
I can confirm that it's not just a refresh problem. 
When using the individual in a simulation - the simulation results are wrong.
Removing the expression profile from the individual and adding it again, fixes the problem

The problem still exists in V12. It seems that only `t1/2 (intestine)` is affected, not other parameters.
E.g. before the change:
<img width="300" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/9edfda1d-0ded-4940-b2e6-524ee7dcc7e2">   <img width="400" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/030b58c9-2d22-41ae-b75e-6006a8fe8363">
After the change:
<img width="300" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/ab01872b-f1be-4287-ae25-d29a1ce00b36">  <img width="400" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/e7428a2c-f2d0-4e05-80a0-4b530968882e"> 

@msevestre FYI

**Comment by msevestre** [comment]
I can reproduce with all paramters

**Comment by msevestre** [comment]
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/34899180-8c98-48dc-b55b-5cec9cd17f26)

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/726c55e5-db9d-443e-9415-0cf5fb870f06)

**Comment by msevestre** [comment]
adding and removing updates
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/56351a21-683f-4e91-aad1-5c595d9d74e9)

**Comment by msevestre** [comment]
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/fc8dd88d-8061-464b-a7da-0210425c425c)

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/e5e57cbd-1f31-4bb5-b491-1c220fd7c7fd)

**Comment by msevestre** [comment]
I think the sync is not triggered for unit change that's all
