### ISSUE TITLE
Project export for Matlab reporting engine

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#286]
For each simulation,  a structure will be exported to allow the reporting engine to run automatically 

### Inputs
* Simulation-XML
* Calculated time profiles. If exported, reporting engine can use them instead of recalculating the model. Otherwise new simulation will be performed in Matlab
* Observed data in NONMEM format (spec. s. #402)
### Outputs (export of Matlab code for creating output figures and tables via reporting engine)
* Time profile plots (spec. s. #403)
    **_Reporting Engine currently only supports 1 time profile (and unlimited number of data sets) per plot_**
* PK-Analysis tables (spec s. #404) (should we export Matlab code for the calculation here or just export calculated values?)

### Inputs
* Simulation-XML
* Population-CSV
* Calculated time profiles. If exported, reporting engine can use them instead of recalculating the model. Otherwise new simulation will be performed in Matlab
* Observed data in NONMEM format (spec. s. #402)
### Outputs (export of Matlab code for creating output figures and tables via reporting engine)
* Time profile plots (spec. s. #405)
    **_Reporting Engine currently only supports 1 time profile (and unlimited number of data sets) per plot_**
* Box-Whisker plots (spec. s. #406)
* Scatter plots (spec. s. #407)
* Range plots (spec. s. #408)

### Inputs
Same as inputs for individual simulations, exported for all used simulations
### Outputs
Same as individual time profiles 

### Inputs
Same as inputs for population simulations, exported for all used simulations
### Outputs
Same as population time profiles

**Comment by msevestre** [comment]
Specifications required 
/CC @KatrinCoboeken:

**Comment by KatrinCoboeken** [comment]
I'm not sure what was meant here . The only export that I'm missing for the reporting engine is an export for the sensitivity analysis. Ideal would be a table with all selected parameters, n steps and variance.

**Comment by msevestre** [comment]
Use case: 
* Open PK-Sim Project
* For a given simulation (or a whole project) select "Export to MatlabXXX"

Expected Output
* The action should create all required folder and files as well as matlab code required to start the reporting engine in Matlab without having to change anything. (e..g in Matlab you should only have to call the init Script and everything will work automatically)

Now we need to define
1. What needs to be exported (csv, xml, plots definition that will be created)
2. Expected folder structure
3. Matlab scripts that will do the actual work

**Comment by msevestre** [comment]
@KatrinCoboeken @Yuri05 
Any news on that?

**Comment by msevestre** [comment]
@Yuri05 Inputs, Outputs
Are those the expected subfolders?
so if the simulation name is S1, should we 
S1/Inputs, 
S1/Outputs
?

**Comment by Yuri05** [comment]
I think it's not mandatory for Reporting Engine, but would make sense

**Comment by KatrinCoboeken** [comment]
For individual simulation the time profiles are not saved only for population simulations.

**Comment by KatrinCoboeken** [comment]
The Reporting engine is intended to generate a set of default plots for a set of Mean Model or Population simulations.  
The main goal was not to reproduce a specific individualized plots.

**Comment by msevestre** [comment]
@KatrinCoboeken What do you mean by that? Export is only for population simulations?

**Comment by Yuri05** [comment]
obsolete
