### ISSUE TITLE
Example projects

### ISSUE THREAD

**Issue by zt1947** [Open-Systems-Pharmacology/PK-Sim#2860]
Please provide the link I should follow to download the example projects that can be used in tutorials with PKSim Version 11.2

**Comment by zt1947** [comment]
I would still be grateful if you provide the link I should follow to
download the example projects that can be used in tutorials with PKSim
Version 11.2

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/releases/latest

You can find the link in the Windows Menu under `Open Systems Pharmacology Suite/PK-Sim examples`
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/052ca301-b0c0-44e7-9b0a-a9325ba9beaf)
