### ISSUE TITLE
Organ volumes not distributed as per default in a pregnancy population

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2865]
When creating a pregnancy population, some organ volumes with predefined variability are not distributed as per default, but appear under "User defined variability"
<img width="550" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/4978b849-7012-4834-9d7f-3d230f175f4e">

The bug was introduced in **v. 11.0**; in v. 10 organ volumes are correctly distributed as per default:
<img width="550" src="https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/e118b47d-dc3c-411e-a6ca-287a51537a8c">

**Comment by nina-nauwelaerts** [comment]
What is the best way to deal with this issue? Should we define the distribution manually? If so, can we somehow obtain the right distribution? Or is it not recommended to use these pregnancy/postpartum population in V11?

**Comment by PavelBal** [comment]
@Yuri05 this is still open for v12.

**Comment by Yuri05** [comment]
I know :)
