### ISSUE TITLE
Code coverage does not work anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2866]
The same happens for MoBi and OSPSuite.Core.

Starting with the build 12.0.76 (10-Dec-2023) the code coverage stopped working.
![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/06f66c03-7894-42b9-89ae-61ed5a9c70dd)

When looking at the last codecov build on AppVeyor for PK-Sim:
https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim-y8yi5/builds/49160051

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/06a64cfb-6c89-4f9f-aeda-0c74276d63df)

In the last successful build (12.0.75 03-Dec-2023) it looked like this:

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/4c53e7f7-49f2-498d-aa98-35d938b7247e)

**Comment by rwmcintosh** [comment]
I believe this is fixed now from the AppVeyor side

https://help.appveyor.com/discussions/questions/65061-nunit3-console-runner-has-changed
