### ISSUE TITLE
Project conversion - cannot run the Aciclovir model

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2871]
https://github.com/Open-Systems-Pharmacology/Example_Aciclovir

Open in PK-Sim 12 and try to run the simulation:

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25903040/84d2bc9b-4ee2-433b-959a-42776c74c945)

**Comment by rwmcintosh** [comment]
@PavelBal can you check it again? It may have been fixed along the way and I cannot reproduce any errors. I can open in PK-Sim and run the simulations.

**Comment by PavelBal** [comment]
Yes, seems to be fixed.
