### ISSUE TITLE
Having issues on single dosing administration on day 7

### ISSUE THREAD

**Issue by shbae1211** [Open-Systems-Pharmacology/PK-Sim#2877]
Hello.

I have an issue for simulations to evaluate DDI.
If a victim drug is administered the first dosing on day 7, it did not work.
The same compound file worked well in the first dosing on day 1. 

This error seems prominent when the administered dose is higher and the lag time is applied to formulations.

![20240301_200145](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/48671465/161deff4-7e45-443b-be74-d545de8a0ed7)
![20240301_200246](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/48671465/c7b982ac-6cdd-4ec0-b3e8-75ed0209cfed)

**Comment by Yuri05** [comment]
You apply on day 7, but your time profile graph goes only up to 1 hour (??)
What are you time settings (start/end times, etc.) for the simulation?

**Comment by shbae1211** [comment]
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/48671465/f7717549-4d65-436b-85e4-f7d5664685e9)

**Comment by shbae1211** [comment]
I deleted the lag times in  WB formulation, it does work.
