### ISSUE TITLE
Allow / enable multiple formulations per a single Advanced Administration Protocol

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#2883]
Allow to mix two different formulations for a single advanced admin protocol which could look like this:
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25477643/10cbf4df-9fed-4f1f-bbec-3ee8850ca88d)

1. either this is defined in the protocol where we assign 2 or multiple different placeholder for the formulations, or
2. For each separate dosing group in the adv. protocol, a specific formulation has to be selected during simulation creation

Thoughts?
@PavelBal

**Comment by msevestre** [comment]
at least I think :)

**Comment by msevestre** [comment]
YEAH

![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/158658f0-67f1-4e85-b4f7-9f97b86fed9b)


![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/1041237/2ff45b1d-ec86-414d-af47-9db50cf84529)

**Comment by PavelBal** [comment]
YOU CAN RENAME THESE THINGS???

Because it is a drop-down, I never got an idea to try to type something in that field!

**Comment by msevestre** [comment]
It's one of those list that you can select from existing entries
The idea is that you don't make a typo if you want to reuse F1 in 3 different places (similar to the list of enzymes etc.)

**Comment by msevestre** [comment]
Can I get the implementation fee for this :)

**Comment by PavelBal** [comment]
> Can I get the implementation fee for this :)

Paying by time spent -> 2 minutes -> I'll buy you a beer next time ;)

**Comment by msevestre** [comment]
deal
