### ISSUE TITLE
Cannot download compound template 

### ISSUE THREAD

**Issue by gulugululee** [Open-Systems-Pharmacology/PK-Sim#2890]
When I loaded compound template for DDI simulation, the error was described as follow:
Cannot download template located at 'https://raw.githubusercontent.com/Open-Systems-Pharmacology/Cimetidine-Model/v1.1/Cimetidine-Model.json'lThe remote name could not be resolved: 'raw.githubusercontent.com'

**Comment by rwmcintosh** [comment]
Could you try this link:
https://raw.githubusercontent.com/Open-Systems-Pharmacology/Cimetidine-Model/v1.1/Cimetidine-Model.json

It may have been a temporary server issue of some kind.
