### ISSUE TITLE
Migrate to .NET 8

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2905]
To be used with `rSharp` in `ospsuite` R package.

- [x] Enable `test-utilities-individual` in `ospsuite` R package
- [x] Enable `test-utilities-population` in `ospsuite` R package
- [x] Move `create-individual` and `create-run-population` vignettes back from WIP folder.
- [x] Uncomment entries in pkgdown.yml

**Comment by Yuri05** [comment]
* convert ospsuite.R and below to .net8 (if .net framework 4.x)
* create additional nuget package with all dependencies required for ospsuite-R (incl. PK-Sim dlls and 'OSPSuite.Core dlls)
* use that nuget package in ospsuite-R (and remove the copies of ospsuite.core dlls from hte ospsuite-R repo)

**Comment by rwmcintosh** [comment]
| Issue  | Description | Status |
| ------------- | ------------- | ------------- |
| https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2912 |convert ospsuite.R and below to .net8 (if .net framework 4.x)| - [ ] |
#2909 | create additional nuget package with all dependencies required for ospsuite-R (incl. PK-Sim dlls and 'OSPSuite.Core DLLs) | |
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1422 | use that nuget package in ospsuite-R (and remove the copies of ospsuite.core dlls from hte ospsuite-R repo) | |
