### ISSUE TITLE
Add metabolizing enzyme MonoAminoOxydase A

### ISSUE THREAD

**Issue by abderrahmanemeslouh** [Open-Systems-Pharmacology/PK-Sim#2907]
Hello,
I am modeling an antidepressant drug mainly metabolized by MAO-A, I am not familiar with PK-Sim, I cant find MAO-A in the metabolizing enzyme list, could you please help me to insert it.
Thank you

**Comment by Yuri05** [comment]
You can find expression data of MAO-A in the PK-Sim Gene Expression database.
S. documentation for details:
https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-profile#definition-of-new-expression-profile-in-pk-sim-r

https://docs.open-systems-pharmacology.org/working-with-pk-sim/pk-sim-documentation/pk-sim-expression-profile#editing-protein-expression-by-querying-the-expression-database

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/5eb7ecf2-9abc-4176-b47b-8bc59a8ddac8)

![grafik](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/25061876/b4a45c45-641f-4dcb-af06-8dd2f06ca4db)

**Comment by abderrahmanemeslouh** [comment]
Thank you for your prompt response!

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________
