### ISSUE TITLE
Create "dependency resolver project" and publish an artifact

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#2909]
Implement a new resolver project in PK-Sim. It should depend on PKSim.R only.

From there we can retrieve all the dependencies required for OSPSuite-R and publish them as an artifact.

https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2905

**Comment by rwmcintosh** [comment]
find source of dependencies
OSPSuite.Presentation
OSPSuite.Presentation.Serializtion
Devexpress.Data

**Comment by rwmcintosh** [comment]
Create a 'versioning' scheme.

**Comment by benjaperez1983** [comment]
> find source of dependencies OSPSuite.Presentation OSPSuite.Presentation.Serializtion Devexpress.Data

PKSim.Infrastructure depends on OSPSuite.Presentation.Serialization. 
![image](https://github.com/Open-Systems-Pharmacology/PK-Sim/assets/108261271/0b30afbe-aa00-4332-9ab8-9aa66861426e)

**Comment by msevestre** [comment]
Can you see why? Delete the dep and see

**Comment by rwmcintosh** [comment]
We did. Build fails.

**Comment by msevestre** [comment]
Yes of course 
But what depends on it

**Comment by rwmcintosh** [comment]
```
public class ParameterGroupsPresenterSettingsXmlSerializer : DefaultPresentationSettingsXmlSerializer<ParameterGroupsPresenterSettings>, IPKSimXmlSerializer
```

**Comment by rwmcintosh** [comment]
There are a few other things also. Extension

`AddPresentationSerializers` used in InfrastructureRegister.

**Comment by msevestre** [comment]
`ParameterGroupsPresenterSettingsXmlSerializer` 
Probably because we say serialization is an infrastructure concern. I wonder if we can move this somewhere else. not a big deal but a bit weird.

**Comment by rwmcintosh** [comment]
> `ParameterGroupsPresenterSettingsXmlSerializer` Probably because we say serialization is an infrastructure concern. I wonder if we can move this somewhere else. not a big deal but a bit weird.

I created an issue to keep it separate for now.
