### ISSUE TITLE
"Add Metabolizing Enzyme … (Database query)" icon is not displayed on the screen

### ISSUE THREAD

**Issue by Kokitake** [Open-Systems-Pharmacology/PK-Sim#2927]
I would like to add information about metabolic enzymes, however "Add Metabolizing Enzyme (Database query)" icon  is not displayed on the screen. 
"GENEDB_human .expressionDb" has been linked.
I would like to know how to solve this problem.

![PK-Sim® 11 Update 3 2024_07_19 1_09_06](https://github.com/user-attachments/assets/55ab5bbc-59cb-42f4-9672-6fb6aaee7ec4)
![PK-Sim® 11 Update 3 2024_07_19 1_17_42](https://github.com/user-attachments/assets/d3b94581-b685-4323-9238-4d5e2cdf6b7f)

**Comment by Yuri05** [comment]
s. here: https://github.com/Open-Systems-Pharmacology/Forum/discussions/1359#discussioncomment-3952973

**Comment by Kokitake** [comment]
It's solved thank you so much!!!
