### ISSUE TITLE
Remove PKSim.Matlab

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#2929]
@Yuri05 I don't think we need to continue maintaining this component anymore. DO you agree? I vote for removing this

**Comment by Yuri05** [comment]
Is PKSim.Matlab used only for individual/population creation from Matlab (obsolete) or for anything else?
Particularly, is it required for exporting a PI to Matlab? (I think no?)
![grafik](https://github.com/user-attachments/assets/85ee0928-d2d6-47d1-9aab-55ec0eb3e592)

If it's only individual/population creation from Matlab - we can remove.

**Comment by msevestre** [comment]
no not for export, just for the interface.

**Comment by msevestre** [comment]
ok will do
