### ISSUE TITLE
Add physiology data for the species Cat

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#293]
see https://github.com/Open-Systems-Pharmacology/Forum/issues/66

This would be a great contribution from the community to the open source platform.

**Comment by msevestre** [comment]
if someone is interested in contributing to this feature request, I could definitely help defining which parameters are required

**Comment by StephanSchaller** [comment]
Not cats, but in general, is there a "how-to" that helps you along the way (file/database format required, also json?)
Same for integration of a new population...

**Comment by Yuri05** [comment]
Based on the data from https://github.com/Open-Systems-Pharmacology/Forum/discussions/953 cat was created as a copy of beagle in the first step. Now cat-specific parameters must be set, which are summarized in the table below:
[4upload_CatSpecificParameters.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/7544430/4upload_CatSpecificParameters.xlsx)

**Comment by Yuri05** [comment]
@StephanSchaller @KirstenBoerngen FYI
