### ISSUE TITLE
"Add protein binding partner" view missing components

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2943]
New compound -> ADME -> Protein Binding Partners -> Add Protein binding partner:

![image](https://github.com/user-attachments/assets/8b7f76f9-714e-4691-88c3-0a3ebe9d4bfe)

This is how it used to look like:

![image](https://github.com/user-attachments/assets/627e6c68-f622-4150-8877-ac36211b79a1)

**Comment by benjaperez1983** [comment]
@PavelBal 
Not able to reproduce it, since when I open this window I get:
![image](https://github.com/user-attachments/assets/e7de6016-3f26-4ab3-9678-4829809a43f8)

**Comment by msevestre** [comment]
@PavelBal Can you change the theme to see if this due to this?

**Comment by PavelBal** [comment]
![image](https://github.com/user-attachments/assets/bded29d3-4b77-4ded-9173-047400178047)
Indeed, it is a theme's issue.
