### ISSUE TITLE
`Ontogeny factor table` and `Ontogeny factor GI table` - molecule or expression property?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#2949]
The `Ontogeny factor table` and the `Ontogeny factor GI table` are now present in different places.

- Directly in the molecule, where they are not tables but constant values. When exporting from PK-Sim, I assume that the first value is the table is taken, so the value in the molecule-BB for CYP3A4 is 1e-3:

![image](https://github.com/user-attachments/assets/53fd1fe6-45ef-4682-987f-bd0e399b2466)

- In the expression profile:

![image](https://github.com/user-attachments/assets/dad38f7f-3987-4037-950f-c99ccf267a20)

When creating a simulation WITH the expression profile, the correct values are applied because the parameter is overwritten from the expression BB:

![image](https://github.com/user-attachments/assets/92184944-6dda-452e-a514-945cdc80320d)

But it is also possible to create a simulation without the Expression, e.g., when the spatial structure has been exported and the expression profile has been selected to create the Parameter Values BB. In this case, the ontogeny table is not updated but the value from the molecules BB is used:

![image](https://github.com/user-attachments/assets/3c89c341-bd7d-4155-b539-6dde922d5520)

And the value is obviously wrong.

To fix this, I propose the following:

- [ ] `Ontogeny factor table` and the `Ontogeny factor GI table` in the Molecules BB are ALWAYS 1
- [ ] Exporting from a spatial structure container and selecting an expression profiles also creates the entries for the ontogeny tables in the PV BBs of the export (disregarding of what organ is exported)
- [ ] PV BB: "Add Protein Expression": also create the entries for the ontogeny tables from the selected expression.

**Comment by msevestre** [comment]
All right so here is what I have with the PR coming to PK-Sim

# HUMAN

## Expression Profile
![image](https://github.com/user-attachments/assets/c3f3cae4-d9bf-4d94-9d21-8dca6f42a45e)

(I changed the ontogeny by hand to another molecule so do not worry about the enzyme name not matching)
![image](https://github.com/user-attachments/assets/f781e1c3-f322-4f94-8b04-563ca9b9420d)

## Molecule
Two parameters: Ontogeny Factor and Ontogeny Factor GI with value 1
![image](https://github.com/user-attachments/assets/5badfef1-c5ef-4a82-9ddb-159668c40b6e)
