### ISSUE TITLE
Crash due to locked exported observed data file

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#2965]
[Digoxin-Model-2.0.zip](https://github.com/user-attachments/files/16837294/Digoxin-Model-2.0.zip)

`QualificationRunner.exe -i "C:/0/Digoxin-Model-2.0/Evaluation/Input/evaluation_plan.json" -o "C:/0/Digoxin-Model-2.0/Evaluation/re_input" --norun -n "report-configuration-plan" -f`
When executing the qualification runner like above with the attached inputs: reproducibly crashes:
```
fail: QualificationRunner[0]
      Project configuration for 'Digoxin' is invalid. Please check the log file at 'C:/0/Digoxin-Model-2.0/Evaluation/re_input\temp\Digoxin\log.txt' for details. 
```
[log.txt](https://github.com/user-attachments/files/16837323/log.txt)

The error in the log file:
`The process cannot access the file 'C:\0\Digoxin-Model-2.0\Evaluation\re_input\ObservedData\Gurley 2008b - Control (Perpetrator Placebo) - Digoxin - PO - 0.25 mg - Serum - agg. (n=18).csv' because it is being used by another process.`

**Comment by msevestre** [comment]
ADding check for building blcoks and all other entities. 
An error will be added to the log and duplicated by name will be ignored

**Comment by msevestre** [comment]
Error: Another Observed Data named 'Gurley 2008b - Control (Perpetrator Placebo) - Digoxin - PO - 0.25 mg - Serum - agg. (n=18)' already exists in the project. Snapshot file is corrupted.
Error: Another Observed Data named 'Belz et al. 1983 - Digoxin control - Digoxin - PO - 0.125 mg - Plasma - agg. (n=12)' already exists in the project. Snapshot file is corrupted.
Error: Another Observed Data named 'Gurley 2006 - day 1 plasma - Digoxin - PO - 0.4 mg - serum - agg. (n=16)' already exists in the project. Snapshot file is corrupted.
Error: Another Observed Data named 'Gurley 2007 - control - Digoxin - PO - 0.5 mg - serum - agg. (n=20)' already exists in the project. Snapshot file is corrupted.
Error: Another Observed Data named 'Gurley 2008b - Control (Perpetrator Placebo) - Digoxin - PO - 0.25 mg - Serum - agg. (n=18)' already exists in the project. Snapshot file is corrupted.

**Comment by Yuri05** [comment]
> I can check it out but I don't understand why this is prior high. For me this is a typical user error

Agree, it's a user error (I have set it to prio high before I further investigated the issue and found the initial reason).
But seems to be a common practice when mass-importing observed data - so it's good that we have the check now :)
