### ISSUE TITLE
Behavior when importing a snapshot containing unknow parameter

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#297]
See discussion here
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/296#discussion_r136382658

The current implementation throws an exception with the name of the unknown parameter.

Another option would be to show the information in some kind of a log file. I favor the exception as loading a snapshot with parameters that are unknown can only lead to issues and wrong expectation. The end user should NEVER trust a snapshot that does not conform to what PK-Sim is expected

**Comment by msevestre** [comment]
@Yuri05 With the new log implementation from #384 fixed in #389 , we could also log to console, file, presenter what ever and continue . No problem anymore :)

**Comment by msevestre** [comment]
Let me know how you want it

**Comment by msevestre** [comment]
(That being said, the load from snapshot in PKSim would require more work in that case as w would need to show a dialog... this is probably not a bad idea but this might be more difficult than we expect since a lot of UI Stuff is happening when loading from snapshot)

**Comment by msevestre** [comment]
@Yuri05 Should it be Warning or Debug? 
The log systems works like so:

Debug, Info, Warning, Error

if the log level is Info, only Info, Warning, Error are displayed

if the log level is Debug, everything is being displayed

Right now, for old projects with a tone of parameter that have moved, the list of Warnings is quite impressive ...

**Comment by Yuri05** [comment]
>Should it be Warning or Debug?

I would say warning
