### ISSUE TITLE
Behavior of Add All Constants in Sensitivy Analysis

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#303]
It is at the moment possible to add all constants parameters at once .This is a great feature. However, if a parameter is a formula and the formula was OVERWRITTEN in the simulation, the parameter will not be taken into account and I think this is not accurate.

I would suggest to also add those parameters automatically to the sensitivity

**Comment by Yuri05** [comment]
@KatrinCoboeken FYI

**Comment by KatrinCoboeken** [comment]
Michael is right.

**Comment by msevestre** [comment]
This has been fixed
