### ISSUE TITLE
GOF plot for model evaluation

### ISSUE THREAD

**Issue by vbalbas** [Open-Systems-Pharmacology/PK-Sim#306]
Dear all,

I just would like to suggest the possibility of implementing in PKSim a way obtaining a plot for predicted concentration vs observed (similar to the plot that can be obtained after estimating a parameter):
  
![image](https://user-images.githubusercontent.com/16211975/30033090-6bd86286-9199-11e7-8910-41ccf7c27017.png)

I think that it would be interesting to to have the possibility of collecting all the individual data (observed) and the simulated mean concentration (predicted) for model evaluation.

Thank you in advance.

Kind regards
Violeta

**Comment by Yuri05** [comment]
implemented in V11.1
