### ISSUE TITLE
Should Ontogeny factor, ontogeny factor GI be visible and editable in a simulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#309]
Right  now, those molecule specific parameters are hidden explicitly in the simulation.
also they are set as Editable = false in the database. My suggestion would be to make them visible at least in advanced mode and maybe even editable

**Comment by StephanSchaller** [comment]
Agree!

**Comment by msevestre** [comment]
Visible and editable under Advanced Parmaeters
