### ISSUE TITLE
Batch functionalities to merge with Snapshot

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#320]
There is a lot of duplication and same behavior. Probably a good idea would be to keep the batch structure but use functionalities from the snapshot component instead

**Comment by msevestre** [comment]
/cc @Yuri05 
That would require a one time conversion of all batch file that we have. This can be done automatically by loading the file with the current batch structure and exporting them again to snapshot structure

**Comment by Yuri05** [comment]
Sounds reasonable

**Comment by msevestre** [comment]
That should also be taken into consideration in our estimate
