### ISSUE TITLE
Cannot restore nuget packages

### ISSUE THREAD

**Issue by stcmz** [Open-Systems-Pharmacology/PK-Sim#328]
Many nuget packages are out of date and the version specified by packages.config cannot be found on nuget.org which results in failure of compilation.

**Comment by msevestre** [comment]
Which branch are you trying to build? The tag version 7.1 should be without any problem.

If you want to use the develop branch (which has not been released yet)  you need to add our appveyor sources as nuget sources. See for example PKSim appveyor.yml for the syntax.

Does this help?
Cheers,

**Comment by stcmz** [comment]
Hi, thanks for you response. It was on the develop branch by default. Now I switch to master but it still fails for the infrastructure package which targets an older v7.1.0.79 version and it still doesn't exist on nuget.org. I look into the appveyor.yml file and none of the ten sources seem to be for the infrastructure package.

**Comment by msevestre** [comment]
Which infrastructure package are you talking about?
OSPSuite.Infrastructure is in nuget
https://www.nuget.org/packages/OSPSuite.Infrastructure/

And the version used in master should be the one available on nuget

**Comment by msevestre** [comment]
This is also the package version references by for example PKSim.Infrastructure in master
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/master/src/PKSim.Infrastructure/packages.config#L18

**Comment by stcmz** [comment]
No, they are different. It's 7.1.0.99 in https://www.nuget.org/packages/OSPSuite.Infrastructure/ while it's 7.1.0.79 in https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/master/src/PKSim.Infrastructure/packages.config#L18 which is the problem. Both PKSim and PKSim.Infrastructure on master have this issue.

**Comment by msevestre** [comment]
@stcmz you are absolutely right. I am going to update 7.1.0.99 right away and you should be good to go
If you add the source as mentioned above however, you should be able to run develop for example (This is what the ci is doing on each commit so that works for sure)

**Comment by msevestre** [comment]
@stcmz correction. The wrong package is referenced for some reason in infrastructure. 7.1.0.99 should be referenced as well. I am not sure how this happened but here is it. 
The Version 7.2 will be released in the next few weeks so this will be solved. In the meantime, I'd suggest to change your local to use 7.1.0.99 instead of 7.1.0.79 (those 7.1.0.xx dll should always have the same version anyways as they come from the save project)

**Comment by msevestre** [comment]
@stcmz I have created #331 to avoid this kind of problem in the future
Thanks for reporting it

**Comment by stcmz** [comment]
Cool. By manually targeting the version to v7.1.0.99 it compiles without dependency errors. However, the post-build event command line defined for csproj PKSim failed to run:
`call "$(VS140COMNTOOLS)vsvars32.bat"
editbin /largeaddressaware "$(TargetPath)"`
I am using Visual Studio Community 2017 which doesn't ship with the vsvars32.bat tool. Seems the two lines are for limiting the output assembly to use no more than 4GB memory so I guess I should be good to go without it. So I commented-out the two lines and it now compiles without any error. If it's safe without the two lines then shall we remove them?

**Comment by msevestre** [comment]
@stcmz great news.
We added the post-build event so that we could support some very edge cases scenario simulating very big populations. 

I think you can safely remove them in your instance but it needs to stay at the moment in the build until we implement a 64bit version of the suite (in the pipeline)

As far as I understood this command, it is to specify that the app can handle addresses larger than 2 GB...I am not sure if it also limits the usage to no more than 4GB.

**Comment by PavelBal** [comment]
Was this actually ever fixed?

The master branch of OSPSuite.SimModel refers to

```
  <package id="OSPSuite.Utility" version="2.0.0.1" />
  <package id="OSPSuite.BDDHelper" version="2.0.0.1" />
  <package id="NUnit" version="3.5.0" />
  <package id="OSPSuite.SimModelSolver_CVODES282" version="3.0.0.7" />
  <package id="OSPSuite.FuncParser" version="3.0.0.6" />
```

while, e.g., OSPSuite.Utility has only version 2.0.0.5 and 2.0.1.4 on nuget.

**Comment by msevestre** [comment]
This is a PK-Sim repo so this issue has been fixed yes. Why SimModel is referencing Utility is unclear. However If you have issue with SimModel please open an issue in the appropriate repository
