### ISSUE TITLE
export individual parameters

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/PK-Sim#350]
Hi,
I was just wondering if there is a way to export the individual parameters as a csv file or another convenient format. I know that this is possible for populations but I don't see an "export as csv" with the individual.

**Comment by msevestre** [comment]
There is nothing like that at the moment. Probably a useful feature to see at once glance parameter values

**Comment by msevestre** [comment]
A workaround for now:
Go to advanced => All. Copy the whole Table and paste in excel

![image](https://user-images.githubusercontent.com/1041237/30877046-6eda7148-a2c6-11e7-8e09-f775820bb20e.png)

**Comment by aelmokadem** [comment]
That works beautifully. Thanks a lot Michael.
