### ISSUE TITLE
Set population age range does not allow for age >80years

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/PK-Sim#351]
When crating a population, the interface does not allow to enter an age >80years although the underlying individual was created with the ICRP database for which individuals up to an age of 100years can be generated

**Comment by msevestre** [comment]
isn't it the same as the entry you already defined a few weeks ago?
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/70?

**Comment by msevestre** [comment]
@JanSchlender Is it the same issue or another one?

**Comment by msevestre** [comment]
@JanSchlender : Closing the issue for now as I believe this is the same as the other one. Please reopen if this is not the case
