### ISSUE TITLE
PK-Sim PK Parameters

### ISSUE THREAD

**Issue by vbalbas** [Open-Systems-Pharmacology/PK-Sim#354]
Good day everyone,

I am validating a PBPK model built in PKSim using different data sources. I would like to compare the predicted PK Parameters, such as **Total CL** and **Vss**, with the parameters from the trial of reference. 

I had simulated each clinical trial with 200 id per clinical trial.  Looking at the PK parameters in the simulation output, I have not been able to obtain this Two PK Parameters in the population simulation, but I can obtain the if I simulate only one ID. Example: figure below:

![image](https://user-images.githubusercontent.com/16211975/30922299-053d6220-a3a9-11e7-97df-1e4217cac9d9.png)

Is there any way to obtain the average PK parameters for the population simulation? 

Thank you in advance.

Kind regards,
Violeta Balbas-Martinez, Ghent University

**Comment by msevestre** [comment]
This is at the moment not possible. The reason is that theses PK Parameters require the dose in order to be calculated. We do not track at the moment the APPLIED_DOSE per individual in a population

I think this would be a good enhancement however

**Comment by vbalbas** [comment]
Hi @msevestre , 

Thank you for your answer. I understand, yet in my specific case, the APPLIED_DOSE is the same for every individual (mg instead of mg/kg). Moreover, I am constraining the population generation to a specific age, weight and height. The reason is that I am simulating clinical trials from the literature and I do not have every patient characteristics for the reference trial, I only have the average population characteristics.

Best
Violeta

**Comment by msevestre** [comment]
You could calculate this values easily in your case:

```
CL = Dose / AucInf;

Vss = CL * MRT
```

**Comment by msevestre** [comment]
on second thought, those parameters are available for analyses
![image](https://user-images.githubusercontent.com/1041237/30964703-8b11f83a-a420-11e7-9f6e-e82641b3a75e.png)

you can just export the PK Analysis for your population and you will be able to see the value for each individual where mean etc.. can also be calculated
![image](https://user-images.githubusercontent.com/1041237/30964776-c5fdd7e8-a420-11e7-8a5e-ec93ad79039c.png)

You will get in this case the mean VSS for the population as opposed to the VSS for the mean individual  (those values will be close but not equal)

**Comment by vbalbas** [comment]
I was calculating them with **CL = Dose / AucInf**; and **Vss = CL * MRT** as you mentioned. But for oral administration, I need the oral F, which I do not know by performing a population simulation, but I can compare them with the relavive ones **CL/F** or **Vss/F**. 

Thanks @msevestre !

**Comment by vbalbas** [comment]
Hi @msevestre,

I have been exporting the PK Analysis for the population I mentioned last week and I had calculated the mean CL and VSS without any problem throug the formula. 

Surprisingly, I am trying to do the same with a different population from an _in-house_ clinical trial, and I am not able to obtain an "MRT" value for any of my ID, as a consequence, I can not calculate the mean Vss. 

Any idea about why I have this issue?

![image](https://user-images.githubusercontent.com/16211975/31070874-520ddee2-a762-11e7-834d-f517527fa399.png)

Thank you in advance
Violeta

**Comment by msevestre** [comment]
@vbalbas 
Good question. This should actually be available. What looks suspicious is the fact that AUC_inf_tD1 is 0. MRT is using this value so this is probably the reason.

AUC_inf calculation can go wrong in general if the number of points in the terminal phase is low. What is your resolution (Simulation -> Settings?). I would suggest to increase the #pts/h at the end of the dosing interval to see if this solves the issue

Can you share that project somehow?

**Comment by vbalbas** [comment]
Resolution was 20 pts/h for the first 2 h and 4 pts/h for the following. I had increased the second interval up to 60pts/h and now it works!
Thank you :)

**Comment by msevestre** [comment]
@vbalbas great to hear. Cheers

**Comment by vbalbas** [comment]
Hi @msevestre , 

I just would like to know If you could tell me hoy PKSim calculates MRT after PO administration.

**Comment by vbalbas** [comment]
Hi @msevestre ,

I just would like to know If you could confirm me know how PKSim calculates MRT after PO administration.

I have found on the help file how MRT is calculated for IV adm: 

![image](https://user-images.githubusercontent.com/16211975/31538725-be20e848-b006-11e7-863b-95e1b7c22f00.png)

In the case of the PO administration, I have calculated  CL/F and Vss/F as previously discussed (_CL = Dose / AucInf; and Vss = CL * MRT_), but the CL/F and Vss/F parameters are far from the "reference" value (comparing them with a popPK). In addition, the PKSim prediction for PO is similar in accuracy to the IV administration prediction (which Vss and CL parameters are not as far from the "reference" value). 
 Therefore, I have thought that maybe there is an issue with the MRT calculation, or is my model instead. 

Thank you again. 
Best,
Violeta

**Comment by msevestre** [comment]
@vbalbas The calculation for MRT is the same for PO and IV (with the exception of infusion time as stated in the manual that is substracted for IV only).  

AucInf, MRT etc....are calculated using an interpolation of the last 10% points. Make sure that you have enough points at the end of your simulation.

Also what do you consider *far from*?

**Comment by vbalbas** [comment]
Thank you @msevestre. Then my model overpredicts those parameters, so we should figure out why. 

I consider far from the reference value: 

**IV**
- Vss PBPK model= 83.90 L  
- Vss popPK model = 34.60 L

- CL PBPK model=11.41 L/h
- CL popPK model =9.72 L/h

**PO** 
- Vss/F PBPK model= 335.16 L 
- Vss/F popPK model = 35.47 L

- CL/F PBPK model=17.41 L/h
- CL/F popPK model =10.32 L/h

In my case, the CL is splitted in three different processes: Enzymatic: CYP1A2, Bile, and Renal (GFR + TS). I would like to know if there is any way in which I can know the CL prediction per CL pathway.

**Comment by msevestre** [comment]
@vbalbas 

The modelling context is quite different between PopPK and PBPK. Here is my understanding, and please anyone could chime in if what I say is nonsensical :)

* PopPK estimates clearances based on data
* PBPK on the other hand uses clearance as INPUT to simulate the model. So there is no prediction of clearance available because the clearance is what you, as user of the tool, input into the model. The only clearance that we estimate is the one a-posteriori using the simulated curve and simple PK Calculation. But in that case, this is also based on data (simulated data in that case)

How do the curve look? Does the model predict mean and variability accurately?

**Comment by vbalbas** [comment]
@msevestre 

I totally agree with you. In PBPK, CL is given as an input to simulate the model. You give the value of the CL for a specific population and PKSim will allow to scale that value to different populations, am I right?

In my specific case, I am trying to extrapolate the adult model to pediatric population. The adult data is well predicted by the model (IV and PO), but the pediatric data is underpredicted. I wanted to check where the model fails and try to improve it, for that reason I wanted to compare the parameters for (CLtot or the Vss) with the PopPk values (taking those values as reference) for my specific population.  

I show you below the _Pred vs observed_ plots for the adult and for the pediatric population (dashed line refers to the twofold time prediction interval)
**ADULT** 

![image](https://user-images.githubusercontent.com/16211975/31832198-70c35d0e-b5c6-11e7-89ab-663287c4656d.png)

**CHILDREN**

![image](https://user-images.githubusercontent.com/16211975/31832100-05cbcc52-b5c6-11e7-9156-b521d3d221c0.png)

According to the parameters form the last message, it seems that there is a problem in Vss. Would you agree? Any suggestions?

Thank you in advance
Violeta

**Comment by msevestre** [comment]
@vbalbas My suggestion would be to close this issue and open one in the forum so that other get a chance to comment on that. PK-Sim issues are really for bug/problem with the tool itself as opposed to modeling questions.

Can you create a new entry in the forum and  copy paste your last entry. Also please reference this issue (https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/354) so that we know where it's coming from.

See you there :)

**Comment by msevestre** [comment]
@vbalbas let me know when this is done so that we can continue the discussion there. Cheers

**Comment by vbalbas** [comment]
@msevestre 

It has been done, apologies for the delay. Issue #89
Best, 
Violeta
