### ISSUE TITLE
Draft Watermark

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#399]
Introduce application option "_Not QCed watermark_". Default value: FALSE.

If the option is activated: all output plots and grids should become watermark _Not QCed_

Implementation alternatives:
1. Permanent watermark
2. Watermark inserted only during _CopyToClipboard_ process.

Useful links

#### Chart 
* https://documentation.devexpress.com/CoreLibraries/DevExpress.XtraCharts.XYDiagramPaneBase.BackImage.property
* https://www.devexpress.com/Support/Center/Question/Details/Q327121/chart-watermark

#### Grid 
* ~~https://www.devexpress.com/Support/Center/Question/Details/Q318243/watermark-in-gridcontrol~~
* https://www.devexpress.com/Support/Center/Question/Details/DQ13076/background-image-in-gridcontrol

**Comment by msevestre** [comment]
The link https://www.devexpress.com/Support/Center/Question/Details/Q318243/watermark-in-gridcontrol is not for WinForm

**Comment by msevestre** [comment]
Question:
Why not use a different power point template (with DRAFT Watermark) instead of implementing the feature in the suite?

**Comment by msevestre** [comment]
>Introduce application option "Not QCed watermark". Default value: FALSE.

Application option or project option? The Draft status belongs more to a project than to the application in my opinion

**Comment by Yuri05** [comment]
>>Application option or project option?

Application option

**Comment by msevestre** [comment]
yes but why?

**Comment by msevestre** [comment]
if it's a project option, it is consistent throughout the users using the project as opposed to having everyone having to set the option all the time

**Comment by msevestre** [comment]
Implementation:

In ApplicationSettings, following flag will be saved
```
 bool?  UseDraftWatermark {get;set;}
```

Default is `null`. If the value is null, the user will be ask upon application start if draft is required or not. This will only be done once and saved then in the ApplicationSettings

Text of watermark as well as option Draft on/off will be changed in ApplicationSettings

This option will only affect charts copy to clipboard option as well as export to pdf draft default value option

Annotation will be used for Chart to display the DRAFT text

**Comment by msevestre** [comment]
See proposed text when starting the app with the option not defined (name of app as well as location will be defined per application. This comes from the TestProject)

Note: I have change the default button to be NO as this feature should definitely be turned off by default

![image](https://user-images.githubusercontent.com/1041237/31827471-d619d2a0-b585-11e7-8d52-9179176d43db.png)

**Comment by msevestre** [comment]
This is how it looks in PK-Sim
![image](https://user-images.githubusercontent.com/1041237/31830069-270c47ea-b58d-11e7-890f-f800e5aa01a3.png)
