### ISSUE TITLE
Time profile settings export (individual simulation) for reporting engine

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#403]
tbd: Matlab code example

**Comment by KatrinCoboeken** [comment]
Within the  MeanModel Workflow of the reporting engine a Task for timeprofile generation "doVPC is included". If the input Task.doVPC is set to true, this task generates for each output plots and files them in figures/timeprofile as figure and the numerical content as csv table. For a single application one plot for the total simulated time range will be generated. For a multiple application, 3 plots will be generated: the total simulated time range, the time range of the first application and the time range of the last application.
•	Simulated time profile in linear and logarithmic scale (if available with data).
And if data are available in the range selected in the output definition
•	Predicted vs observed 
•	Residuals vs time
•	Residuals vs simulated output
For all outputs together
•	Histogram of residuals
•	qq-Plot
If the model is based on parameter identification, add the list of the optimized parameters to the input variable VPC e.g.:
VPC.optimizedParameters = {'Theophylline-CYP1A2-adjusted|CLspec/[Enzyme]',...
        'Theophylline|Specific intestinal permeability (transcellular)',...
        'Theophylline|Lipophilicity'};

Then the time profile plot is generated in 3 versions
•	with uncertainty range based on the uncertainty in the parameters
•	with uncertainty range based on the uncertainty in the data
•	with uncertainty range based on both, in the parameters and data
It is possible to configure this plotting by adjusting the input variable VPC see the function getDefaultVPCSettings of the reporting engine

**Comment by msevestre** [comment]
@KatrinCoboeken This looks more like documentation of the report engine than specification of what needs to be generated by pksim. 

What should PK-Sim generates?

**Comment by Yuri05** [comment]
obsolete
