### ISSUE TITLE
PK-Analysis export (individual simulation) for reporting engine

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#404]
tbd: Matlab code example

**Comment by KatrinCoboeken** [comment]
Not implemented in Reporting Engine 1.0
I would suggest to add this as a new Task to the MeanModel workflow 
Output would be an exported table

**Comment by msevestre** [comment]
@KatrinCoboeken Please describe format of table that should be exported

**Comment by Yuri05** [comment]
obsolete
