### ISSUE TITLE
Box-Whisker plots settings export (population simulation) for reporting engine

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#406]
tbd: Matlab code example

**Comment by KatrinCoboeken** [comment]
The Reporting engine (1.0) uses Box whisker plots to visualize the distribution of PK Parameter of one or more population simulations
For each PK Parameter and each output one Box whisker plot is generated. On the x-Axes differnet population simulations (to compare the influence of age or a disease) is displayed.

**Comment by msevestre** [comment]
@KatrinCoboeken Same remarks as https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/403.
What should PK-Sim export?

**Comment by Yuri05** [comment]
obsolete
