### ISSUE TITLE
Scatter plots settings export (population simulation) for reporting engine

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#407]
tbd: Matlab code example

**Comment by KatrinCoboeken** [comment]
The reporting engine 1.0 uses scatter plots only to display predicted vs. observed.

**Comment by msevestre** [comment]
@KatrinCoboeken Same remarks as https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/403.
What should PK-Sim export?

**Comment by Yuri05** [comment]
obsolete
