### ISSUE TITLE
Range plots settings export (population simulation) for reporting engine

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#408]
tbd: Matlab code example

**Comment by KatrinCoboeken** [comment]
The Reporting engine (1.0) uses Range plots to visualize the distribution of PK Parameter or Physiological Parameters. For each Parameter and each output one Range plot is generated.

**Comment by msevestre** [comment]
@KatrinCoboeken Same remarks as https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/403.
What should PK-Sim export?

**Comment by Yuri05** [comment]
obsolete
