### ISSUE TITLE
Meropenam

### ISSUE THREAD

**Issue by moulirc** [Open-Systems-Pharmacology/PK-Sim#412]
[Meropenam.pdf](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1398398/Meropenam.pdf)
I am trying to build a PBPK model for meropenem. 
70% of the drug is excreted unchanged in urine. I would like to know if I am missing anything?

Thanks in advance.
kind regards
Mouli

**Comment by msevestre** [comment]
@moulirc If you want help from the community, please use the forum. Issues in PKSim should be seen more as bug/feature enhancements
