### ISSUE TITLE
Parameters missing in Sensitivity Analysis

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/PK-Sim#415]
When selecting "Add ALL Constants" in order to add them to the Sensitivity Analysis, at least the Intestinal Permeability (transcellular) is not added to the list of selected parameters. One can only run this parameter separately. 
Furthermore, the number of parameters tested in the sensitivity analysis is less than the number of parameters selected. You can see this in the attached pictures. There, 135 Parameters have been selected for the run, but only 94 parameters appeared in the results.
![grafik](https://user-images.githubusercontent.com/26056951/32093451-9d2f059c-bafc-11e7-8ea4-890982376ee9.png)
![grafik](https://user-images.githubusercontent.com/26056951/32093485-b800eaca-bafc-11e7-8524-704b8bba110e.png)

**Comment by Yuri05** [comment]
>When selecting "Add ALL Constants" in order to add them to the Sensitivity Analysis, at least the Intestinal Permeability (transcellular) is not added to the list of selected parameters. One can only run this parameter separately.

_Intestinal Permeability (transcellular)_ is a formula; "Add ALL Constants" adds only non-formula (constant) parameters.

>Furthermore, the number of parameters tested in the sensitivity analysis is less than the number of parameters selected. 

Some parameters are excluded from sensitivity analysis:
* Sensitivity cannot be calculated for simulation parameters with initial value = 0 (to prevent accidental structural model changes during sensitivity calculations)
* Parameters having a table formula are not available for sensitivity calculations.

S. OSP Suite manual chapter _**35.5.1.** Selection of interesting input parameters_ for more information.

**Comment by Yuri05** [comment]
Closing. Please reopen if there are still questions on this issue
