### ISSUE TITLE
Reformulate Lymph and recirculation flow rates in model for proteins/large molecules

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#44]
In the future protein model the lymph and recirculation flow rates should scale organ specific and not be absolute values (within a species) or scale with body weight (between species).

The parameter "Lymph flow rate" for each organ:
[“Lymph flow rate (incl. mucosa)” for LargeIntestine and SmallIntestine] should be written proportional to the plasma flow:

`Lymph flow rate = f_lymph*Q*(1-HCT)`

With
Q: blood flow in organ
HCT: hematocrit
f_lymph: new parameter (Name: “lymph flow proportionality factor”, Description: “proportionality factor linking lymph flow to plasma flow”)

The parameter “Fluid recirculation flow rate” for each organ
[“Fluid recirculation flow rate (incl. mucosa)” for LargeIntestine and “SmallIntestine] should be written as:

`Fluid recirculation flow rate = f_Jiso*(1-alpha_L)*L * (Vorg,species / Vorg.mouse)^(exp_Jiso_scale - 1)`

With:
alpha_L: "Flow fraction via large pores" in each organs
L: Lymph flow rate (from above)
Vorg,species : Organ volume in model species
Vorg.mouse: Organ volume mouse
exp_Jiso_scale: scaling exponent for Fluid recirculation flow rate (value = 0.667)
f_Jiso: new parameter: (Name: “fluid recirculation flow proportionality factor”, Description: “proportionality factor linking fluid recirculation flow to lymph flow via small pores”)

For now the following parameters can be used which should reproduce the current values for mouse.
Refine parameters will be provided later.

Organ|f_lymph|     f_Jiso
---------|-----------|---------------
Bone|    6,24E-03 |    5,32E-05
Brain|    5,74E-09 |    5,01E-02
Fat|     4,57E-03 |    3,47E-02
Gonads |   3,65E-03   |  5,20E-02
Heart|    6,75E-03 |    2,54E-01
Kidney|    3,76E-04  |   3,22E-01
LargeIntestine|    1,59E-03 |    2,16E-03
Liver|     6,07E-02  |   9,15E-01
Lung |   2,13E-03|     6,26E-05
Muscle |   1,41E-03 |    2,73E-01
Pancreas |   2,92E-02  |   1,39E-01
Skin |    2,91E-03|     6,97E-01
SmallIntestine |    2,80E-04  |   3,64E-02
Spleen  |  2,07E-01 |    5,93E-05
Stomach  |   1,39E-03  |   8,59E-02

=================================================================
To prevent NaN in the start amounts for FcRn and the complex endogenous IgG - FcRn in the new parameterization of the protein model (endosomal uptake & recycling only from plasma), the respective equations should be extended for the interstitial space. Correspondingly, I would also extend the equations for plasma.
That means:

Extend the respective current equation:

STARTAMOUNT_FcRn_Interstitial krint <= 0 ? 0 : current_equation
STARTAMOUNT_LigandEndoComplex_Interstitial krint <= 0 ? 0 : current_equation

STARTAMOUNT_FcRn_Plasma krpls <= 0 ? 0 : current_equation
STARTAMOUNT_LigandEndoComplex_Plasma krpls <= 0 ? 0 : current_equation

**Comment by Christoph27** [comment]
In the attached xlsx-file the final parameters for f_lymph and f_Jiso can be found together with the other new (literature) parameters of the refined protein model. 

[NewParameterValues_V7p1.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/854211/NewParameterValues_V7p1.xlsx)
