### ISSUE TITLE
Support for dimension generated by MoBi automatically

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#440]
MoBi generates "per time" dimensions automatically when adding an RHS variable if not present already. Adding a simulation using this dimension back to PK-Sim is not supported and this should be fixed

**Comment by UlrichSi** [comment]
One of the most interesting dimension is "time per time". Shall this be added to the black list?

**Comment by msevestre** [comment]
Proposed implementation here https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/pull/712#pullrequestreview-350437878

**Comment by msevestre** [comment]
@Yuri05 FYI
