### ISSUE TITLE
Copy2Clipboard missing Sensitivity Analysis/Sensitivity plot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#456]
Copy2Clipboard context menu is missing under Sensitivity Analysis/Sensitivity plot

**Comment by msevestre** [comment]
This is a core implementation

**Comment by msevestre** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/279
