### ISSUE TITLE
Draft in pdf reports

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#460]
If **Use watermark** option is active, pdf reports should be automatically produced in the draft mode.

**Comment by msevestre** [comment]
We had discussed about that and said we would do it if it was easy. It's not easy!

**Comment by msevestre** [comment]
Especially changing the watermark text would require a lot of work. Also draft woul appear everywhere and all the time not only on charts.
Since no one uses it I'd suggest not to touch it

**Comment by msevestre** [comment]
as dscussed
