### ISSUE TITLE
SBML Import in MoBi

### ISSUE THREAD

**Issue by lkuepfer** [Open-Systems-Pharmacology/PK-Sim#472]
MoBi-Import of [BIOMD0000000528](http://www.ebi.ac.uk/biomodels-main/BIOMD0000000528) and [BIOMD0000000489](http://www.ebi.ac.uk/biomodels-main/BIOMD0000000489) Biomodels fails due to wrong import of model equations

[SBML_Import.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1495512/SBML_Import.zip)

Steps to reproduce:
1. Create new MoBi project
2. Import one of the SBML models attached
3. Create empty Observers building block
4. Create empty Events building block
5. Create default simulation settings
6. Try to create a simulation - it fails with errors

(MoBi projects created in step 5 also attached for both models)

**Comment by msevestre** [comment]
This is a MoB bug here.
