### ISSUE TITLE
Feedback User Training: Bug #1: PI match observed output data

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#476]
If you do a parameter identification, and "Add Output" and then start the PI without mapping any observed data: ...
![image](https://user-images.githubusercontent.com/25477643/33096769-7538616c-cf08-11e7-8815-1fbe0651b15f.png)
(obviously not feasible, but) you get an error message which is not "catched" ( Exception has been thrown by...blablabla...)!

**Comment by msevestre** [comment]
@StephanSchaller Thanks. This should not happen

**Comment by msevestre** [comment]
This has already been fixed in 7.2 that will be released in the next few days
