### ISSUE TITLE
Grapics error for displaying Distributions in Populations

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#477]
Let the picture speak for itself (file "Ex_ADP_8.pksim5" form the Age-Dependence exercise):
![image](https://user-images.githubusercontent.com/25477643/33097435-778e3872-cf0a-11e7-8ee6-fd214e2f60c9.png)

**Comment by msevestre** [comment]
good news. This is fixed in upcoming 7.2. Thanks for reporting the issue
