### ISSUE TITLE
IVIVE Workflow in PKSim

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#479]
recently gave a Training and received some user feedback on usability (and as far as I remember, this was a topic for almost all trainings):

In general it was about scaling/calibrating in vitro results for Peff (via CACO2) for intestinal permeability or intrinsic clearance rates for CYPs etc.

Even though PKSim provides all the infrastructure to implement measured in vitro values, it is sometimes hard to understand how my in vitro value should be (if at all) scaled to be entered for the different calculation methods I can choose from (in vitro in presence of microsomes or per g liver biopsy, ...). An additional level of complexity is added when loading relative expression values and defining reference concentrations.

So, is there someone in this community with a strong IVIVE focus and also using PKSim who would like to generate / provide a workflow guide (and maybe even a set of exercises for self-training) for this? ;-)

**Comment by msevestre** [comment]
@StephanSchaller My suggestion would be to move this entry into the forum. PK-Sim issues are for bugs and tasks etc.. and won't be checked by so many people.

**Comment by StephanSchaller** [comment]
By moving you mean reposting, or can you move it?

**Comment by msevestre** [comment]
Yes reposting and closing this one. Thanks
