### ISSUE TITLE
Using the PK-Sim Test version 7.2:  Creating comparison plot of compound with different molecular weights

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/PK-Sim#488]
Using the PK-Sim Test version 7.2: It was possible to create a comparison plot of a 2 population simulations where the molecular weight of the compound was differently set. This should not have been possible.

[bug_31.7.5.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1518723/bug_31.7.5.pksim5.zip)

**Comment by msevestre** [comment]
@Incei Is this a new behavior or can you reproduce with 7.1?

**Comment by msevestre** [comment]
@Incei It is too late anyways for this version as we are about to release Version 7.2. It is very important to post issues arising during the test phase as early as possible

**Comment by Incei** [comment]
Same issue with 7.1 with this project. (as mentioned only when the same molecule building block is used with different weights. It is not possible to compare 2 different molecule building blocks) Added here a quick random example.

[test_pksim7.1.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1520877/test_pksim7.1.pksim5.zip)

**Comment by msevestre** [comment]
Awesome. Thanks.

**Comment by Incei** [comment]
Issue fixed, and working in 7.3, thanks!
