### ISSUE TITLE
Using the PK-Sim Test version 7.2: Parameter optimization 'faulted'

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/PK-Sim#489]
Using the PK-Sim Test version 7.2: Parameter optimization did not perform as expected, based on the exercise 4.46 the PI should have been successful performed. Instead all runs were faulted:

![grafik](https://user-images.githubusercontent.com/25530079/33443798-ca392fba-d5f8-11e7-8a62-747972bcc7c2.png)

[Theophylline_4.46_bugged.pksim5.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1518713/Theophylline_4.46_bugged.pksim5.zip)

**Comment by msevestre** [comment]
@Incei Is this a new behavior or can you reproduce with 7.1?

**Comment by msevestre** [comment]
@Incei It is too late anyways for this version as we are about to release Version 7.2. It is very important to post issues arising during the test phase as early as possible

**Comment by Yuri05** [comment]
Same issue with 7.1 with this project

**Comment by PavelBal** [comment]
Outdated. Please re-open if disagree.
