### ISSUE TITLE
Update vcredist to use newer package 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#500]
see issues
https://github.com/Open-Systems-Pharmacology/Forum/issues/107
and 
https://github.com/Open-Systems-Pharmacology/Forum/issues/90

We have updated the .NET framework so know is the time to make it happen

**Comment by msevestre** [comment]
@Yuri05 Not sure what is required so I am assigning you :)

**Comment by msevestre** [comment]
@Yuri05 This has happen again. What is the problem?

**Comment by Yuri05** [comment]
in 7.3 we will move to VC++2017, so this issue and related problems will become obsolete

**Comment by msevestre** [comment]
What package should be used in the setup for 7.3?

**Comment by Yuri05** [comment]
[Microsoft Visual C++ Redistributable for Visual Studio 2017](https://aka.ms/vs/15/release/vc_redist.x86.exe)

**Comment by msevestre** [comment]
This needs to be done in setup

**Comment by msevestre** [comment]
done with https://github.com/Open-Systems-Pharmacology/Suite/pull/16
