### ISSUE TITLE
Mol weight not set in observed data if the excel file contains a columnn named Molecule

### ISSUE THREAD

**Issue by JanSchlender** [Open-Systems-Pharmacology/PK-Sim#502]
When adding several datasets for one output, the PI only considers one of the datasets for the optimization.

**Comment by msevestre** [comment]
In order to reproduce the issue please provide us with a sample project and also explain why you think that only one data set is being used.
Also which version are you using?

**Comment by JanSchlender** [comment]
Reference project is not feasible right away. I am using the new PK-Sim release 7.2. When adding multiple datasets to the parameter identification and mapping them to a certain output, only one of these datasets will be considered in the subsequent PI run and displayed later on in any analysis plot.

**Comment by JanSchlender** [comment]
I will try to mimic this but it may take a while

**Comment by msevestre** [comment]
What do you mean with "considered"? Is it only a problem of the output selection or does it have anything to do with the optimization itself (e.g. only one output is used for optimization?)

**Comment by msevestre** [comment]
prio high if this is really the case.

**Comment by msevestre** [comment]
@JanSchlender @Yuri05 Cannot reproduce with the Theophyline project
I just started a brand new PI and all works as expected

![image](https://user-images.githubusercontent.com/1041237/33890185-77fc5b7e-df20-11e7-85a7-97d1c936478b.png)

![image](https://user-images.githubusercontent.com/1041237/33890198-808c0a6e-df20-11e7-9eaf-0e8e66df86de.png)

**Comment by msevestre** [comment]
@JanSchlender Please do not hesitate to send me the project directly if you have one where the issue can be reproduced

**Comment by JanSchlender** [comment]
Tried to reproduce and it worked out. Seems to be a naming issue since it only happens, when the Observed Data added are to the building block are assigned to a longer naming pattern. 
![grafik](https://user-images.githubusercontent.com/26056951/33891062-33178990-df55-11e7-8e84-23512c336b32.png)
![grafik](https://user-images.githubusercontent.com/26056951/33891172-6f8176fc-df55-11e7-97ed-923134d6125b.png)
When I then drag and drop the observed data to the Concentration Time Profile, one dataset can not be converted to the default concentration unit (from ng/ml to umol/L)
![grafik](https://user-images.githubusercontent.com/26056951/33891290-c8b98d7c-df55-11e7-8fb8-d4be89261abb.png)
Switching the default concentration to a mass per volume helped to move forward. Then I have two datasets in this simulation and initiate the PI with the right click on the simulation. Only dataset appears as a match to the output. 
![grafik](https://user-images.githubusercontent.com/26056951/33891388-188198ae-df56-11e7-9406-8a8d81a601f9.png)
After selecting the second dataset and starting the PI run, only a single dataset is considered

**Comment by JanSchlender** [comment]
[Testrun.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1552044/Testrun.zip)

**Comment by JanSchlender** [comment]
I just recognized that "apply to All" function is not considering the "Molecule". With this the Molecular Weight is only added to one dataset. That might explain, why the other datasets are not used for the PI.
![grafik](https://user-images.githubusercontent.com/26056951/33892025-ffe78f72-df57-11e7-88b2-0e8239c05862.png)

**Comment by msevestre** [comment]
Yes this is the bug. Molweight should be set automatically in PKSim *(Apply to All) not required

**Comment by msevestre** [comment]
@JanSchlender But I cannot reproduce that problem either with test datasets.
Can you attach the excel file and describe how you imported the data? I am going to change the title here as it has nothing to do with the PI

**Comment by JanSchlender** [comment]
Added the data by right click on building block "observed data". Then "Add Observed Data...". In the interface I selected "Import all"
[Data.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1552267/Data.xlsx)

**Comment by msevestre** [comment]
Ok this is because there is a Column called MOLECULE in the dataset. This is a reserved keywords in the importer. THe importer however happily complies and overwrites the information in that case. 
So this is an importer bug: Molweight not imported if a column is called Molecule in the excel file

**Comment by JanSchlender** [comment]
Now I renamed the column in the Excel File and tagged that Column again with Molecule. However, the error occurred again.  Maybe another issue with the importer for Molecule
![grafik](https://user-images.githubusercontent.com/26056951/33897279-4af0b540-df65-11e7-89a1-07ee3ea642aa.png)

**Comment by msevestre** [comment]
Do not map the molecule property. This should not be used and I am not sure why this is visible :)

**Comment by msevestre** [comment]
@Yuri05 Another reason why we need to update the Importer...

**Comment by msevestre** [comment]
relates to https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/361

**Comment by msevestre** [comment]
Bug was fiixed in Core. Fix will be available in 7.3

**Comment by JanSchlender** [comment]
I tried to mimic the issue in 7.3. Therefor I used the same PK-Sim file attached here, deleted the PI and the observed data from the Simulation and the respective Building Block. Afterwards, I re-imported the same dataset, and mapped the suggested Source and Target Columns (including Molecule, since this was suggested), mapped the Molecule, Species, Organ and Compartment request on the Import tab and clicked "apply to all". The attached error occurred with which the project crashed. Changing the Column header in the xls File from Molecule to an arbitrary name, causes the same issue when mapping this Column with Molecule in the Importer.
![error_molecules](https://user-images.githubusercontent.com/26056951/41524479-f76b279a-72dd-11e8-97a3-011984b5e2b7.JPG)

**Comment by msevestre** [comment]
>and mapped the suggested Source and Target Columns (including Molecule,

This is what can be found above
**Do not map the molecule property. This should not be used and I am not sure why this is visible :)**

So Mapping molecule name should not crash but this also does not make much sense

**Comment by JanSchlender** [comment]
Then it should be blocked or not visible for user entry :) 
Can you reproduce the crash?

**Comment by msevestre** [comment]
Agreed. This should not crash which was what was supposed to be fixed . Don't have time to see if I can reproduce. I just reopened the bug and will check when we work on 7.4

**Comment by Yuri05** [comment]
obsolete with the new data import
