### ISSUE TITLE
Suite 7.2: Error loading compound from template

### ISSUE THREAD

**Issue by krinaj** [Open-Systems-Pharmacology/PK-Sim#506]
Hello,

I switched to (uninstalled 7.1 and installed 7.2) 7.2 recently. I am trying to load midazolam compound that was in the template for 7.1. When I click on Compound --> load from template, it gives me error message (screen shot attached).

I tried uninstalling and re-installing 7.2 as well, but still same error.

Thanks,
Krina
![capture](https://user-images.githubusercontent.com/21271517/34073879-eb574aa8-e258-11e7-95a1-927e104307e9.PNG)

**Comment by msevestre** [comment]
@krinaj 
This problem typically occurs when the template database selected is not a PK-Sim database template but something else (For example the model database that happens to be also a *.mdb file)

Can you go to your user settings (under Utiltiies => Options). Scroll down a bit. You should see a section containing a path to a template database. Could you let us know what this path is? 

Cheers,
Michael

**Comment by krinaj** [comment]
Hello Michael,

In utilities => options => scroll down to template path, the path is as
below. The same path is in utilities => options => Application tab in human
row.

C:\Users\kmehta\Documents\My_Programs\GENEDB_human.mdb

Are we not supposed to download GENEDB_human.mdb
<https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.2.0/GENEDB_human.mdb>
 file from github page? I downloaded OSPSuite-Full.7.2.0.exe
<https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.2.0/OSPSuite-Full.7.2.0.exe>
 and GENEDB_human.mdb
<https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.2.0/GENEDB_human.mdb>
 files.

thanks,
Krina

**Comment by msevestre** [comment]
@krinaj 
The GENEDB_human.mdb contains expression data for different enzymes / transporters etc.. and should indeed be used for the section Expression Database

The template database however is a user defined template where you can save your OWN building blocks and reused them from project to project for example. THIS IS NOT the expression database.

![image](https://user-images.githubusercontent.com/1041237/34107300-bed2e38a-e3c9-11e7-84ca-5197349acf22.png)
If you want to use an existing one, click on "..." and select one that you have already
If you want to create a new one, click the + button and select a location where the database will be created

Hope that helps

**Comment by krinaj** [comment]
thanks, Michael. It works now.
