### ISSUE TITLE
charachteristic of individual: wrong body weight

### ISSUE THREAD

**Issue by dzianism** [Open-Systems-Pharmacology/PK-Sim#508]
Mistake in formula for weight of blood organs and weight of tissue organs calculations:

Parameter: ..|Organism|Weight of blood organs
	IsFixed: False
	Value: 0 [kg]
	Formula: 0

Parameter: ..|Organism|Weight of tissue organs
	IsFixed: False
	Value: 0.0103 [kg]
	Formula: P_1 + P_2
		P_1: w3e4r1|Organism|Liver|Periportal|Weight (tissue)(0.0103 [kg])
		P_2: w3e4r1|Organism|Liver|Pericentral|Weight (tissue)(0 [kg])

Version:
7.2.0, build 143

As a result wrong dose is calculated.

**Comment by msevestre** [comment]
@dzianism Can you attach the project. Especially, how old is the project?
