### ISSUE TITLE
scale individual failure

### ISSUE THREAD

**Issue by dzianism** [Open-Systems-Pharmacology/PK-Sim#509]
![untitled](https://user-images.githubusercontent.com/27948704/34116267-64a6b6e4-e418-11e7-8bea-7d2cdf02ff43.png)
version info:
7.2.0 - build 143

**Comment by msevestre** [comment]
is this using the project from #508 ?

**Comment by dzianism** [comment]
Hi Michael,

It is the same project. Opened an old project with the latest pk-sim version.

Best Regards,
Denis

**Comment by msevestre** [comment]
How old is the project?

**Comment by dzianism** [comment]
it traces back at least to 6.x

**Comment by dzianism** [comment]
I have just created a dummy project from scratch and it does not have these issues.
