### ISSUE TITLE
allometric scaling in pksim

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/PK-Sim#514]
Hi,

I was curious about how the scaling of a typical individual physiologic parameters is done in pksim. I traced back the literature to an excellent paper by Willmann et al in 2007 that states that allometric scaling is being adopted. For example, scaling of organ weights (OW) follows:

OW_target = (Height_target/Height_mean)^0.75 * OW_mean

From what I understood, the Height_mean and OW_mean belong to a mean adult individual. So for example, the liver weight for a 5 year old with a height of ~109 cm would be:
OW_target = (109/176)^0.75 * 2.35
with 176 and 2.35 being the adult mean height and liver weight, respectively.

The thing is that when I apply this equation, the organ weights I get are way off the values mentioned in the measured ICRP database. Also, the results I get from the equation are very different than the results I get from the generated individuals in pksim. Furthermore, the generated results from pksim agree well with the ICRP data for some parameters but differ greatly for others.

So, I guess the short version of my question is: how is the scaling done in pksim? 

Thanks and regards,
Ahmed.

**Comment by msevestre** [comment]
@aelmokadem Would you please be so kind and move your question to the forum?
Thanks
Michael
