### ISSUE TITLE
Load default metabolic enzyme expressions 

### ISSUE THREAD

**Issue by VKEkbote** [Open-Systems-Pharmacology/PK-Sim#515]
Dear Team,
Kindly let me know how to load the default enzyme (Protein) expression during modelling rather than manually placing the values in the Building block called - Individual.
I downloaded the Recent version of OSPSuite-Full.7.2.1.exe and GENEDB_human.mdb. 
The GENEDB_human.mdb, whcih is Microsoft Access format was asking for password when i tried to open it.
Pl resolve the same.

Thank you.

Regards,
Vineeth KE

**Comment by PavelBal** [comment]
Please refer to PK-Sim Manual Part III, Chapter 10.

Go to "Utilities"-ribbon, select "Options" -> "Application"-Tab -> selecthe the "..." located next to "Human", and select the GENEDB_human.mdb. After that, you cann add an enzyme from the database as described in the manual, Part III, Chapter 14.5.

**Comment by msevestre** [comment]
@VKEkbote 
Please ask questions in the forum if possible.
Especially, your question was already answered [here](https://github.com/Open-Systems-Pharmacology/Forum/issues/8).

Cheers

**Comment by VKEkbote** [comment]
Thank You So much PavelBal..I got it.

@msevestre 
Ya i will do further on case to case basis.
Thank you.
