### ISSUE TITLE
No windows displaying after version update

### ISSUE THREAD

**Issue by jgg1822** [Open-Systems-Pharmacology/PK-Sim#518]
None of the windows are displaying upon opening PK-Sim, and none of the buttons under the Show/Hide section of the Views tab are doing anything.  This problem is still occurring after uninstalling and reinstalling the previous version.

![screenshot](https://user-images.githubusercontent.com/35234695/34686053-612cd6c2-f478-11e7-8149-881d69f14071.PNG)

**Comment by msevestre** [comment]
Hi @jgg1822,

The screenshot shows that you are using version 7.1.0. Please update to version 7.2.1
Then do the following:
- go to Utilities -> Options
- click on `Reset Layout` at the bottom left corner of the window
![image](https://user-images.githubusercontent.com/1041237/34694264-707ef30a-f494-11e7-9c9b-9101b007314c.png)

- Click on `Reset`
- Restart PK-Sim (e.g. close PK-Sim and start PK-Sim again)

Let me know if the problem persists.

Background: It seems that somehow your application layout is corrupted (the way views are being displayed_ This may happen in very rare cases for example when the application was opened on a laptop screen then moved to a bigger screen and the application was closed.

Hope that helps

**Comment by jgg1822** [comment]
Hi Michael,

Thank you so much for your quick reply – it’s much appreciated!  This solution successfully fixed the problem.  I’ll keep this in mind in case I run into this problem again.

Thanks again,
Jackie
(jgg1822)

**Comment by msevestre** [comment]
@jgg1822 Awesome. Cheers
