### ISSUE TITLE
fm (fraction metabolized) observer that sums up fm observer of all compartments

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#521]
It would be very helpful to have a fraction metabolized observer that sums up the fm observer in all compartments such that the total fraction metabolized via a certain enzyme is calculated.

**Comment by tobiasK2001** [comment]
Plus it maby be good to devide it up in fraction metabolized in liver and fraction metabolized in gut.

**Comment by Yuri05** [comment]
already implemented
