### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by VKEkbote** [Open-Systems-Pharmacology/PK-Sim#523]
Dear Team,

Kindly let know, Is there any Licence related concerns or Prior approvals are required from the OPS Suite (http://www.systems-biology.com/sb/) team and/or related organization; to get the software installed and use. 
This is a general query, considering the Bio-pharmaceutical industries involved in Drug discovery & development.

Thank you.

**Comment by Yuri05** [comment]
OSP Suite is distributed under [GNU General Public License, version 2](https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/LICENSE)
There are no further restrictions and no approvals are required to install and use the software.
