### ISSUE TITLE
Suite Setup

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#524]
Suite setup should not fail af a newer version of VC runtime is installed.

For this, add the statement below to vcredist ExePackage:
`<ExitCode Value="1638" Behavior="success"/>`

(s. https://stackoverflow.com/questions/37396773/wix-burn-vcredist )

**Comment by msevestre** [comment]
We are going to update to newer vcr anyways right?

**Comment by Yuri05** [comment]
Yes, but still we should make the adjustment to avoid such problems in the future

**Comment by msevestre** [comment]
not below but as sub node of  <ExePackage>

**Comment by msevestre** [comment]
Implemented in PR Suite https://github.com/Open-Systems-Pharmacology/Suite/pull/17
