### ISSUE TITLE
Adding new metabolization process - metabolite selection ignored

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#529]
1) Open the "Paracetamol"-example, or any other PK-Sim project with metabolizing enzyme expression and at least two compounds (in the latter case, open the respective compounds in the next steps)
2) Open the "Paracetamol"-compound and navigate to the tab "ADME"
3) Select "Add metabolizing Enzyme". Select any expressed enzyme, and some other compound under "Metabolite". As "process type", select "In vitro clearance - First Order" (important step to reproduce).

![image](https://user-images.githubusercontent.com/25903040/34944879-8a0f2890-fa01-11e7-8407-b394f42ef014.png)

4) After pressing "OK", no metabolite is selected.
![image](https://user-images.githubusercontent.com/25903040/34944891-9bc306c4-fa01-11e7-9d5a-051aa8ddb685.png)

**Comment by msevestre** [comment]
Good find!

**Comment by msevestre** [comment]
Ok I could reproduce with the steps described above.
