### ISSUE TITLE
Change case of parameter_name Reference Concentration in tab_molecule_parameters

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/PK-Sim#533]
In database table tab_molecule_parameters the parameter_name column uses capitalized 'Concentration' instead of the preferred 'concentration' when parameter name is 'Reference concentration'

**Comment by msevestre** [comment]
@rwmcintosh Let's add here in other parameters that do not have the right case

**Comment by msevestre** [comment]
@Yuri05 Let's implement that guy now since you are working on the database. There is an "access" inconsistency with case for the parameter mentioned above/
