### ISSUE TITLE
Possible Bug: Cloning a simulation 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#534]
From @vbalbas

See original [here](https://github.com/Open-Systems-Pharmacology/Forum/issues/124)
 
Hello, 

I think I have found a little bug: 
When I clone a simulation (ID13) and I change the ID and the administration protocol (to ID14), the generated plot leaves in the simulated concentration legend, the name of the original Individual (from the cloned simulation), but the plasma concentration or fraction excreted to urine in the simulation are updated: 

**CLONED SIMULATION (ID 13) UPDATED TO ID 14**
![image](https://user-images.githubusercontent.com/16211975/34978778-a6bc95a6-fa9f-11e7-93e3-3b73b254b6bd.png)

Thanks you

Violeta

**Comment by msevestre** [comment]
@vbalbas 
Which version of PK-Sim are you using? I cannot reproduce the issue with a brand new project using 7.2.1

Thanks

**Comment by vbalbas** [comment]
Hi @msevestre, 
It happened with version 7.1.0. I have updated to 7.2.1 version and it was not reproduced! 
Thank you!

**Comment by msevestre** [comment]
I could not reproduce the issue. Please let us know if it happens again

**Comment by vbalbas** [comment]
Ok, I will, but I have updated to 7.2.1 version and it was not reproduced.  
Thank you anyway!

**Comment by msevestre** [comment]
ok. Closing the issue then
