### ISSUE TITLE
Unable to scale from adult to preterm baby

### ISSUE THREAD

**Issue by nmidde** [Open-Systems-Pharmacology/PK-Sim#538]
The individual parameters input: age - 29 weeks, Weight - 1.2 kg, Height 45 cm, BMI (calculated) - 5.93 kg/m2.

Application:
PK-Sim® 7.2.1 - Build 2

Object reference not set to an instance of an object.

Stack trace:
```
at PKSim.Presentation.Presenters.Individuals.IndividualScalingConfigurationPresenter.ConfigureScaling(Individual sourceIndividual, Individual targetIndividual)
   at PKSim.Presentation.Presenters.Individuals.ScaleIndividualPresenter.CreateIndividual()
   at PKSim.Presentation.Presenters.Individuals.ScaleIndividualPresenter.WizardNext(Int32 previousIndex)
   at OSPSuite.UI.Views.WizardView.<InitializeWizard>b__27_1()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```
![image](https://user-images.githubusercontent.com/29755212/35103835-0fd2f9e0-fc35-11e7-879c-4c3da39b1d0b.png)

Thank you,
Narasimha

**Comment by msevestre** [comment]
@nmidde This is probably because such an individual cannot be created (I believe) out of the ICRP population. Can you select the preterm population instead?

**Comment by msevestre** [comment]
Indeed:
![image](https://user-images.githubusercontent.com/1041237/35104354-955d02b2-fc36-11e7-9a72-9bc57cbef86e.png)

**Comment by nmidde** [comment]
I tried with preterm population too but didn't work. 
![image](https://user-images.githubusercontent.com/29755212/35104555-2ed5c41a-fc37-11e7-85ce-8b2d5537f40b.png)
It worked when I have weight and height as shown in the above screen shot, which is not reasonable for a preterm baby.

**Comment by nmidde** [comment]
It works if I don't adjust height and weight manually and stick to mean values provided. Thanks!

**Comment by msevestre** [comment]
>I tried with preterm population too but didn't work.
Can you explain what did not work?

**Comment by msevestre** [comment]
>It worked when I have weight and height as shown in the above screen shot, which is not reasonable for a preterm baby.

@nmidde Postnatal age of 29 weeks and GA of 32 weeks for a weight of 1.2kg is simply not possible. That's why PK-Sim does not allow you to create such an individual
Postnatal age of 29 weeks means that the baby is 7 months old.... 

What exactly are you trying to model here?

**Comment by nmidde** [comment]
Yes, that is right. When I changed Postnatal age to 3 days, it worked. Thanks for your input.
