### ISSUE TITLE
CSV: Export parameters using "" 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#540]
I know this will raise a lot of discussions regarding compatibility with older scripts but I think we should discuss the issue anyways. 

At the moment, exporting a population to csv and re-importing it in PKSim is just a **massive pain** because our csv are separated with ";" and not with "," which is how excel works.

We cannot move to "," because we have some parameters with "," in names

My suggestion would be to look at parameter name systematically and 
* replace , with _
* replace " " with _

so a parameter like `logP (oil/water,pKa)` would be renamed to `logP_(oil/water_pKa)`

This would ensure that we can always export to csv without any issues in excel and also prevent empty space in path.

Display name would be adjusted so that _ is repalced with " " 
so `logP (oil/water,pKa)` would become `logP (oil/water pKa)`

With simple logic, it should be possible to propose an error message if a parameter is not found and also it would allow a user to systematically know how a parameter is named in MoBi or in Matlab from its display value in PKSim (simply replace " " with _)

**Comment by Yuri05** [comment]
I would suggest another solution for that:
* Don't allow quotes in parameter names (I think currently we don't have any parameters containing quotes, so should not be a problem)
* For CSV exports in PK-Sim/MoBi: add an option **Export in Excel-conform format** or thsg like that
* If the option is activated:
  *  Ask for column separator before export (it depends on regional settings, what excel accepts as default column separator)
  *  Ask for decimal separator
  *  **_Take all parameter names in quotes before export_**. Then it doesn't matter if parameter names contain commas, semicolons or whatever

If those exported CSV files needs to be reimported in PK-Sim/MoBi: also add an option for **Export in Excel-conform format**. 
* If activated: remove quotes and ask for column/decimal separator
* Otherwise: assume default CSV format (=current CSV format with point and semicolon)

**Comment by msevestre** [comment]
>it depends on regional settings, what excel accepts as default column separator

Interesting. Default should be , in that case

>Ask for decimal separator

Why would we export in anything else than ,?

>ake all parameter names in quotes before export. Then it doesn't matter if parameter names contain commas, semicolons or whatever

That I don't understand. How does it solve the problem if the separator is used in the name? Is excel in that case bypassing the character if in quote?


What I don't like with your proposed workflow is that there are many decisions that need to made while importing, exporting etc...  Having a consistent and ubiquitous way of exporting and importing would just insure a better user experience all along

**Comment by Yuri05** [comment]
>That I don't understand. How does it solve the problem if the separator is used in the name? Is excel in that case bypassing the character if in quote?

Yes. 

>What I don't like with your proposed workflow is that there are many decisions that need to made while importing, exporting etc... Having a consistent and ubiquitous way of exporting and importing would just insure a better user experience all along

If we want that CSV exports are read by Excel automatically, we must match decimal separator and list separator defined in the language settings **_on the target system_**. 
In the most cases, target system = OSP Suite system. Then both separators could be just read from the current language settings. However if your target system has different language settings, you have to ask user.

In any case, we will not have just **_one_** CSV format (like now). We will have different formats.
**_And this apply both for your and for my proposal._**
Means, during import either the files to import must be analyzed to figure out what the used separators are.
Or the user must be explicitly asked for this.
Or the used separators must be saved as part of the export (e.g. in separate ExportSettings file)

**Comment by msevestre** [comment]
>And this apply both for your and for my proposal.

How does this apply for my proposal? What I propose would never export , in name, never export space etc.. One and only format

**Comment by Yuri05** [comment]
Those are 2 different things.

1. If we quote all names during export, we don't have to change anything in naming. All parameter names can contain space, comma or whatever. And I would strongly vote for this - independently of what kind of separators and what kind of import/export workflow we will use.

2. Selection and usage of separators. Here I see 2 possibilities:
  a) Either we use **different** formats according to the target language settings.
  b) Or we use **"one and only format"**. In this case we must select the most commonly used separators    (which would probably be "." for decimal separator and "," for list separator). Means: those exported CSV files would be automatically read by Excel on the majority of systems. But not on all

The second alternative (2b) is much easier to implement and to use. With the drawback, that not all target systems are supported. But well, currently exported CSV files cannot be automatically opened on any system (it can be daone only via Excel Text import wizard)), so it still would be an improvement :-)

**Comment by msevestre** [comment]
I still don't see how my proposal would results in two different formats :-)

>If we quote all names during export, we don't have to change anything in naming.

I like that and I did not know about this feature. That would also be super easy to check by import

>Either we use different formats according to the target language settings.

I vote against this proposal. This will be a nightmare when people start to exchange file on different systems and we CANNOT rely on user to know what they have to select

> Or we use "one and only format". In this case we must select the most commonly used separators (which would probably be "." for decimal separator and "," for list separator). Means: those exported CSV files would be automatically read by Excel on the majority of systems. But not on all

I agree that this would be a **significant** improvement. I like this proposal a lot to be honest

**Comment by Yuri05** [comment]
@KatrinCoboeken FYI

**Comment by KatrinCoboeken** [comment]
I really want to have a "one and only format".  In a very early PK-Sim version it depended at the language settings and that lead to a lot of confusion and problems.

A lot of Matlab scripts working with the exports are expecting list separator ";" and decimal separator '.' .
Especially if the function readtab is used.  So if we change the format, that will cause some effort and confusion, if new code and old tables or old tables and new code get mixed.

The reporting engine code 2.0 uses now the function readtable instead of readtab. This function detects the delimiter automatically and is therefore able to import both list separators ";" and ",".
But it expects a "." as decimal separator. It can also work with the quotes around the parameter names.

So for every change of format users have to adjust the project specific code. That would include all code compiled for our cluster.

The Reporting Engine could live with a format change of the list separator, and quotes but not with a change of the decimal separator.

**Comment by msevestre** [comment]
>A lot of Matlab scripts working with the exports are expecting list separator ";" and decimal separator '.' .
Especially if the function readtab is used.

Cannot we change those scripts to use readtable instead? Hopefully the actual reading of a csv file is not duplicated everywhere but encapsulated in its own file so this should be easy don't you think? 

>So for every change of format users have to adjust the project specific code.

Old project won't need to be changed. This is only for newer project. 

So I don't see any problem there really. As long as we stick with "." for decimal separator, we should be good to go

Suggestion
* Export all parameter names in ' '
* Use . (point) as decimal 
* Use , (comma) as separator

in PK-Sim, MoBi
* Forbid usage of ' in names  (in Core)
* Loading of csv should support ; (semi colon) if , (comma) is not found (for compatibility reason)
* '' should be removed from parameter during csv read

Agreed?

**Comment by Yuri05** [comment]
Agreed. Only one remark: export parameter names in " " (not in ' ')

**Comment by msevestre** [comment]
so it's not quote but double quote? does it work with quote as well?

**Comment by msevestre** [comment]
Suggestion

    Export all parameter names in " " (double quotes)
    Use . (point) as decimal
    Use , (comma) as separator

in PK-Sim, MoBi

    Forbid usage of " (doublequotes) in names (in Core)
    Loading of csv should support ; (semi colon) if , (comma) is not found (for compatibility reason)
    " should be removed from parameter during csv read

**Comment by KatrinCoboeken** [comment]
"A lot of Matlab scripts working with the exports are expecting list separator ";" and decimal separator '.' .
 Especially if the function readtab is used."

With this  I meant scripts, which are written by different users for there projects and are not part of our toolbox. So they have to change the code, if they want to reuse it with newly generated exports. So we should mention it in the release notes. 

Matlab function readtable works with doublequote, not with quote.

**Comment by KatrinCoboeken** [comment]
In the header of the export the units are sometimes coded with []. So my Matlab code interprets every thing which is in []  as unit. 
It would be nice if [] would therefore also forbidden in parameter names.

**Comment by msevestre** [comment]
@KatrinCoboeken 
>which are written by different users for there projects and are not part of our toolbox

Sure. But they are probably still using a method from the toolbox to read the csv right? 

>It would be nice if [] would therefore also forbidden in parameter names.

added to suggestion

**Comment by Yuri05** [comment]
>It would be nice if [] would therefore also forbidden in parameter names.

Will require project conversion (some parameters contain [] in their name)

**Comment by msevestre** [comment]
Then let's create another issue for that as this is totally unrelated to the issue at hand
Suggestion removed

**Comment by msevestre** [comment]
Suggestion

- Export all parameter names in " " (double quotes)
- Use . (point) as decimal
- Use , (comma) as separator

in PK-Sim, MoBi

- Forbid usage of " (doublequotes) in names (in Core)
- Loading of csv should support ; (semi colon) if , (comma) is not found (for compatibility reason)
- " should be removed from parameter during csv read
