### ISSUE TITLE
Import Population from File error 

### ISSUE THREAD

**Issue by watt0005** [Open-Systems-Pharmacology/PK-Sim#549]
I have created several pediatric populations (e.g., neonate, infant, etc) that were exported to csv for modification then re-imported. All of the re-imports worked without issue except the neonate population where I received the error message in the screenshot below. Thanks for your assistance.
![population error 20180129](https://user-images.githubusercontent.com/31321213/35530869-54d36486-0503-11e8-8a62-fd54ea0fa9fc.jpg)

**Comment by watt0005** [comment]
As a follow up - OSP identified the fact that I had duplicate AAG Ontogeny Columns and this was causing the issue.

**Comment by msevestre** [comment]
Thanks @watt0005 

The error message should explain that there is a duplicate column and specify its name.
