### ISSUE TITLE
Multiselect for color settings in chart editor (curve options)

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#553]
useful for data grouping, e.g. parent, metabolites, plasma, urine, etc.

**Comment by msevestre** [comment]
You can drag and drop the color from one to the other already. That should
help a bit with speed

**Comment by msevestre** [comment]
I think this would be awesome to be able to edit other properties as well at the same time (such as line styke etc). Multiselect and edit first entry would edit all other entries etc..
