### ISSUE TITLE
"Side Margins Enabled" will not work if unchecked in Parameter Identification

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#562]
To reproduce:
1. Run a Parameter Identification task (e.g. create one using the example project "Theophylline" using simulation "Kaumeier oral solution", vary "Lipophilicity").
2. In the ribbon, click on "Time Profile". A chart will appear.
3. In the chart editor, click on tab "Chart Options", then uncheck the tickbox "Side margins enabled".

Unexpectedly, there is no change in the plot, the side margins are still enabled.

**Comment by msevestre** [comment]
Note: Due to chart redesign. An explicit call is probably missing

**Comment by msevestre** [comment]
Interesting. The option does not work also for normal chart. A refresh is simply missing. Cool

**Comment by UlrichSi** [comment]
How do they call it? "Code rot"?  ;-)

**Comment by msevestre** [comment]
Fixed
