### ISSUE TITLE
Define Volume Plasma as Sum parameter

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#572]
Similar to what was implemented with Weight, the parameter volume plasma should be defined as a Sum Parameter

**Comment by msevestre** [comment]
@Yuri05 Any reason why this was not done during previous refactoring?

**Comment by Yuri05** [comment]
Time

**Comment by msevestre** [comment]
@Yuri05 This is done right? Closing. Please reopen if not

**Comment by Yuri05** [comment]
nope, still a TODO

**Comment by Yuri05** [comment]
duplicate of #2
