### ISSUE TITLE
ValueOrigin: BB in simulation state not updated

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#573]
If a ValueOrigin is changed in the simulation for a BuildingBlock-Parameter, Building block is not marked as changed in the simulation tree.
Update/Commit actions however are available in the context menu - so just an icon is nicht updated.
![clipboard01](https://user-images.githubusercontent.com/25061876/36430387-f2245d80-164c-11e8-8da0-91c508892f62.jpg)

**Comment by msevestre** [comment]
@Yuri05 Can't reproduce the issue. 
What parameter did you change in the simulation?

**Comment by Yuri05** [comment]
E.g. value origin of Lipophilicity

**Comment by msevestre** [comment]
ok can reproduce :)
