### ISSUE TITLE
Messed up relative expression

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#586]
1) Create a new PK-Sim project. Load the individual "Standard European Male for DDI" from template.
2) Create any compound and administration protocol and create a simulation.
3) Compare the expression of the enzyme AADAC in the individual BB and the simulation. They are identical.
4) In the Individual-BB, change the relative expression of AADAC in vascular endothelium to 2.

![relexp_bb](https://user-images.githubusercontent.com/25903040/36588855-bafaab22-1889-11e8-9454-fa2ced332026.PNG)

5) Update the simulation.
6) Compare thge expression of the enzyme in the BB and simulation again. The expression in the simulation is totally messed up.

![relexp_sim](https://user-images.githubusercontent.com/25903040/36588918-e4ec250a-1889-11e8-9ac0-382ad81413da.PNG)

It seems that some "normalized expression" values from the BB are treated like "relative expression" in the simulation - e.g., the liver expression values. But the simulation seems to normalize the expression once again!

The expression values in intestinal mucosa are absolutely unclear - where do the values of 0.0684 come from??

**Comment by msevestre** [comment]
I can reproduce the issue

**Comment by msevestre** [comment]
yeah kind of funky

**Comment by msevestre** [comment]
This will be fixed in 7.2.2
