### ISSUE TITLE
Simulation time interval in PK-Sim

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/PK-Sim#594]
I am new to PK-Sim. Could you please guide me how to modify the time duration of a simulation and the time of dose administration? 

Thank you,

**Comment by StephanSchaller** [comment]
If you are new, the best idea would be to start with some simple guided exercises:

http://www.open-systems-pharmacology.org/#tutorials

Good luck!
Stephan

**Comment by msevestre** [comment]
@farzanehmaleki 

Also a good start is the documentation that is installed with the software
I would also kindly ask you to post questions in the forum. PK-Sim issues are for bug report and feature request.

Michael
