### ISSUE TITLE
Create Simmodel-XML from PKML in Matlab interface

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#616]
In PKSim.Matlab: add function, which takes a pkml file and saves it to SimModel-XML file.

**Comment by msevestre** [comment]
@Yuri05 Right now we have two entry points in PKSim.Matlab: `MatlabPopulationFactory` and `MatlabIndividualFactory`. 
This new request method clearly does not belong to either of those class. 

How should we name the new entry point? This looks more like a general utility class / helper class by the look of it

**Comment by Yuri05** [comment]
>This looks more like a general utility class / helper class by the look of it

Agree. So something like MatlabHelper / Matlab.Utility / Matlab.Tasks

**Comment by msevestre** [comment]
@Yuri05 You are going to use it: ) Which one do you prefer (not . however, this will be a class name)

**Comment by Yuri05** [comment]
ok, let's say _MatlabHelper_
