### ISSUE TITLE
Cloned simulations corrupted in 7.3

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#631]
Path to the solubility table is not properly cloned.
[Test4Clone.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1954496/Test4Clone.zip)

E.g in the project attached: clone simulation **S1** into **S2** and try to configure S2: the error below comes.

![clipboard02](https://user-images.githubusercontent.com/25061876/39354864-26c142e2-49fb-11e8-9410-c73021459e1a.jpg)

**Comment by msevestre** [comment]
Yeah same problem with TableWithOffset (luckily path were created relative so no issue)
