### ISSUE TITLE
Refresh of value origin does not work

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#643]
Steps to follow (using version 7.3.0.6):
Create Simulation, change value origin of e.g. lipophilicity in simulation, commit to BB while compound window is open
-->value origin of lipophilicity in compound window is not refreshed

**Comment by msevestre** [comment]
>value origin of lipophilicity in compound window is not refreshed
Is this just a refresh problem? e.g. if you close the window or click in the cell, do you have the right value?

**Comment by TWendl** [comment]
Seems to be just a refresh problem. If I click in the cell or reopen the compound tab, the value is updated!

**Comment by msevestre** [comment]
This is too much work to get that fixed. In general a value is also changed at the same time and this will trigger a full refresh. We can revisit if more people are complaining about that but for now this will have to do
