### ISSUE TITLE
Load from snapshot: no History entry

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#647]
After loading from snapshot, the History is left empty, unlike after creating a new project.

**Comment by msevestre** [comment]
It's by design. /cc @yuri05

**Comment by UlrichSi** [comment]
I would recommend to update the design, though. A one-liner: "Project imported from snapshot in version xxx" would do. 
Rationale: To track what version was used.

**Comment by Yuri05** [comment]
I agree with @UlrichSi : one history entry "Project imported from snapshot XYZ" (and maybe indeed also include the snapshot version) would be good.

**Comment by msevestre** [comment]
I was under the impression that the request was to include the history in the snapshot from previous project and bring it back when loading the snapshot, which we clearly did not want to do.

But adding a one liner is good. 
There is no snapshot version. That's the project version it was created with. Is this what you want?

**Comment by Yuri05** [comment]
>There is no snapshot version. That's the project version it was created with. Is this what you want?

Yes

**Comment by UlrichSi** [comment]
I think that adding the PK-Sim version would be good. Like in the entry of a "Create new project"

**Comment by msevestre** [comment]
I won;t be able to load the version from the snapshot as the actual version is not available in Project.
Instead I will have somethign liek "Project loaded from snapshot 'xxx.json' with version 7.3.0', version being the version of theproject once loaded

**Comment by msevestre** [comment]
see 
![image](https://user-images.githubusercontent.com/1041237/39542946-dede83ce-4e17-11e8-89e1-d01677466606.png)

**Comment by UlrichSi** [comment]
looks informative to me, well done!

**Comment by Yuri05** [comment]
>I won;t be able to load the version from the snapshot as the actual version is not available in Project.

I don't understand this. The project version used during generating of the snapshot is stored in the snapshot.

<img width="150" alt="aufnahme36" src="https://user-images.githubusercontent.com/25061876/39564707-d661717e-4ea4-11e8-882e-26d884169f8c.png">

**Comment by msevestre** [comment]
The project version used to create the snapshot is available in the snapshot file indeed, and in the snapshot project. 
However, we do not have access to this object. This is a temp object that is used to create a PKSimProject object, which does not have a version. The reason behind this is that we said that a PKSImProject should always be converted and always have the latest and greatest version.

So this information is not available in Project at the moment.

**Comment by Yuri05** [comment]
>So this information is not available in Project at the moment.

What about reading the info from https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Core/ProjectVersions.cs ?

**Comment by msevestre** [comment]
This is not the problem.
There is NO field in the Project to store this version. So I cannot display what was the version of the project when the snaphsot was created
