### ISSUE TITLE
Load from snapshot reports error and will not load

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#648]
After loading one of the projects where "Save to shnapshot" works, I get the following error message:

Information: Loading Project from snapshot file 'M:\Test\Sorafenib\Sorafenib.json'
Warning: Snapshot file cannot be used to load a project.

Value "Drug, Observer" is not defined in enum. Path 'ParameterIdentifications[3].Analyses[1].DataRepositories[0].Columns[0].RelatedColumns[0].QuantityInfo.Type'.
Value "Drug, Observer" is not defined in enum. Path 'ParameterIdentifications[3].Analyses[1].DataRepositories[0].Columns[0].QuantityInfo.Type'.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

**Comment by msevestre** [comment]
@UlrichSi Can you attach the file please?
