### ISSUE TITLE
wrong default value in "Scale Individual" function

### ISSUE THREAD

**Issue by TWendl** [Open-Systems-Pharmacology/PK-Sim#649]
when Scaling an individual, the "default value" is not conform with the current default value.
E.g. current Default value for liver half-life for CYP3A4 is 37h, when scaling the template individual, it says 72 h, see screenshot.

**Comment by TWendl** [comment]
![defaultvalue](https://user-images.githubusercontent.com/26460649/39523980-fd9f65be-4e06-11e8-8918-e4cdd205a1cc.gif)

**Comment by Yuri05** [comment]
To reproduce: load "Standard european Male for DDI" from the predefined individual templates and try to scale it.

**Comment by msevestre** [comment]
Scale it to what?

**Comment by Yuri05** [comment]
Does not really matter. E.g. don't change anything in **Biometrics**-Tab of the scaling configuration and click Next. On the **Scaling Configuration** TAB you will see the picture from above.
