### ISSUE TITLE
CLI XML export vs XML export from PK-Sim

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#651]
Version 7.3 EAP:

Comparing the xml export from PK-Sim with the xml file created with the "run" command from a json export and the CLI command

```
C:\Program Files (x86)\Open Systems Pharmacology\PK-Sim 7.3>PKSim.CLI run -i m:\
test\Testomyc -o m:\test\Testomyc -x
```

shows the following differences in the XML files:
1. All observers are set to the property persistable="1" in the CLI-generated xml, versus only the plasma and "fraction absorbed" observers from PK-Sim. This will also create fairly many columns in a CSV file with the -c option.
2. The output schema has only 9 time points (vs. 41 in the PK-Sim export); the simulation was left on the defaults of PK-Sim.

```
<OutputSchema>
    <OutputIntervalList>
      <OutputInterval distribution="Uniform">
        <StartTime>0</StartTime>
        <EndTime>120</EndTime>
        <NumberOfTimePoints>9</NumberOfTimePoints>
      </OutputInterval>
      <OutputInterval distribution="Uniform">
        <StartTime>120</StartTime>
        <EndTime>1440</EndTime>
        <NumberOfTimePoints>89</NumberOfTimePoints>
      </OutputInterval>
    </OutputIntervalList>
  </OutputSchema>

```
When using the "Export" command in CLI, the number of time points for the first segment is 41 and only plasma and "fraction absorbed" observers are set to persistable="1" , as in the PK-Sim export.
```
C:\Program Files (x86)\Open Systems Pharmacology\PK-Sim 7.3>PKSim.CLI export -p
m:\test\testomyc\testomycin.pksim5 -o m:\test\testomyc -x

```
Is there a rationale or a secret message behind it? Clearly, using the Matlab or R toolbox, the 2nd value can always be changed, and the first may allow maximum flexibility to select desired outputs.

**Comment by msevestre** [comment]
@UlrichSi 
Can you attach the PKSim project so that I can look at it?

2: should be the same at any rate. 

1: CLI was implemented especially for batch processing and comparison. We indeed want to compare everything. Now for the specific `run` command, we could do something a bit different. That would probably make sense

**Comment by UlrichSi** [comment]
Here is the project
[Testomycin.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1967561/Testomycin.zip)

**Comment by UlrichSi** [comment]
I just noticed that this is also true for the generated PKML files. The first time segment is changed to 4 pts/h instead of 20.

**Comment by msevestre** [comment]
the problem with the output time remains

**Comment by msevestre** [comment]
@UlrichSi Should be fixed. Good find @UlrichSi !!
