### ISSUE TITLE
7.3 beta: Refresh problem with displaying intestinal solubilities in simulation after change of solubility in table and update of simulation from the building block

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#654]
Simulation “Sol_Tab_1” in attached file was build using solubility “Table”. Solubility at pH 5 and pH 8 was 2E-3 mg/L. Accordingly, the solubility is 2E-3 mg/L in each intestinal segment. 

In the solubility table “Table” the value at pH 8 was changed to 4E-3 mg/L in the Molecule Building Block. After “Update from Building Block” the “intestinal solubility” was still displayed to be 2E-3 mg/l in each intestinal segment in the simulation. Since the simulation results change and the intestinal solubility is updated after saving and re-opening the PK-Sim file (so the problem cannot be seen in the attached file), I think it is an update problem showing the intestinal solubilities in the simulation after the update.

[ph_Sol.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1967685/ph_Sol.zip)

**Comment by msevestre** [comment]
@Christoph27 Does it go away if you click on another node in the tree view? E.g is this just a refresh problem?

**Comment by Christoph27** [comment]
Clicking on another node in the tree view does not help but closing and re-opening the file.

**Comment by msevestre** [comment]
This is **NOT** a refresh problem then

**Comment by msevestre** [comment]
@Yuri05 This is because of the `_cachedValueValid` flag in the parameter. The Formula of each solubility parameter is not updated when the table formula changes and as such no cache invalidation performed. This needs to be done in core

**Comment by msevestre** [comment]
Needs https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/400
