### ISSUE TITLE
Exported PKML throws error in MoBi (v 7.3 EAP)

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#655]
1. Export the simulation "Testomycin SD 100 mg" from project attached to issue #651 as PKML file.
2. Load the PKML file into MoBi.
3. Run the simulation. The error message below is thrown. Maybe just not yet implemented?

MoBi

Formula type 'TableFormulaWithXArgument' is unknown

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

**Comment by Yuri05** [comment]
Seems that SimModelSchema or SimModel was not updated in MoBi

**Comment by Yuri05** [comment]
Yes, SimModel must be updated in MoBi
Closing in favor of https://github.com/Open-Systems-Pharmacology/MoBi/issues/257
