### ISSUE TITLE
Excel import: Grouping and precision

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#665]
Importing [Import_Test_01.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1970233/Import_Test_01.xlsx) using import settings from the screenshot below will create only **_7_** observed data sets, while excel sheet contains **_8_** individuals.
The problem here seems to be grouping by **Age**, because **Age** is defined with too much precision in the excel sheet.

If number of decimal places for **Age** is changed e.g. to 3 in the Excel sheet (s. [Import_Test_02.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1970234/Import_Test_02.xlsx)), importing with the same import settings produces **_8_** observed data sets as expected.

![003](https://user-images.githubusercontent.com/25061876/39568687-7ed57848-4eb2-11e8-9ce8-de74505cebe2.png)

**Comment by msevestre** [comment]
This is crazy! Why would someone define the age like that?

**Comment by Yuri05** [comment]
>This is crazy! Why would someone define the age like that?

That's a good question @Incei ;)

**Comment by Incei** [comment]
It was calculated back in years from days weeks and months. It is indeed not necessary to have this amount of decimals. 

I guess the point here is whether 3 decimals is the maximum with which we can live with (not only for age, but could be any parameter that we want to categorize as 'group by', or whether we want it to be up to the user.

**Comment by msevestre** [comment]
I don't think we should invest any more time in this matter. Probably excel is the one returning the wrong values when reading the info etc.. 
In my opinion, working with this precision (independent from where it comes from, someone did it somehow) is nonsensical

**Comment by Yuri05** [comment]
>I guess the point here is whether 3 decimals is the maximum with which we can live with

For sure 3 it's not the maximum. Should be 15 or 16.

**Comment by msevestre** [comment]
Especially in this case, grouping should be done by Id!

**Comment by Incei** [comment]
@ msevestre, agreed
@Yuri05 then why did this issue occur? Is it something specific?

**Comment by Yuri05** [comment]
>then why did this issue occur? Is it something specific?

Obviously because grouping does not work with this level of precision.

**Comment by msevestre** [comment]
According to me, nothing to change here. Grouping with this column does not make sense
