### ISSUE TITLE
Parameter layout option "Advanced" is not observed in Parameter Identification

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#670]
When setting the Parameter layout option to "Advanced" in PK-Sim (v 7.2.2), all newly created individuals and simulation display parameters in "Advanced". However, a newly created PI task will still start with the selection "Simple" in the Parameters tab. 

Since the parameters mode selection is not stored with the specific project, it would be desirable to observe this option in PI as well. If "Hierarchical" is selected in "Options", we may want to still use "Simple" in PI, since the "Hierarchical" view is not available here.

**Comment by msevestre** [comment]
This is using the default option in the UserSettings.

**Comment by UlrichSi** [comment]
I changed the User Settings to "Advanced", but PI is still set to "Simple".
