### ISSUE TITLE
Snapshots for old projects

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#674]
If a project was created with PK-Sim version <7.3, a lot of ballast will be exported to a snapshot (which would be some megabytes instead of few kilobytes and would contain all constant parameters of the project - also those _not changed by user_)

2 alternatives to handle it:
1. If a project was created with version <7.3 and user selects "Export project to snapshot": a warning should be produced, explaining that a snapshot would contain a lot of garbage. After that the user could either continue with export or cancel.

2. Exporting snapshots would for projects created with version <7.3 would be possible only if PK-Sim started in developer mode (per command line with `/dev` switch). Otherwise a message will be shown indicating that export to snapshot is not possible.

**Comment by Yuri05** [comment]
FYI @JanSchlender @TWendl @InceI @ju-rgen @Christoph27 @UlrichSi @DiedrichC

**Comment by UlrichSi** [comment]
I don't see a reason to hide the functionality for older projects. We already have so much complexity in the program that it won't really matter to have more options here. Maybe some clever user will even find good use for the huge snapshot files?
Thus, I would opt for option 1.

**Comment by DiedrichC** [comment]
I agree with Ulrich. We should go for option one. I see no reason why we should hide that functionality.

**Comment by ju-rgen** [comment]
I agree with Ulrich, too.

**Comment by Incei** [comment]
I would also go for option one.

**Comment by msevestre** [comment]
Option one it is then
