### ISSUE TITLE
Value Origin in Create Individual

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#675]
Add Value Origin in CreateIndividual-Window.
The same value origin should apply for all input individual parameters (Age, Weight, Height, GA)

**Comment by msevestre** [comment]
This will be another 1 to n mapping then and won't be editable in the simulation

**Comment by Yuri05** [comment]
>This will be another 1 to n mapping then and won't be editable in the simulation

That's ok; (Age, Weight, Height, GA) are not editable in the simulation either.
