### ISSUE TITLE
Typographical: in vivo / in vitro

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#683]
7.3 beta, "value origin", "method" drop down menu:
Items "in vitro" and "in vivo" should not be hyphenated (remove "-") but instead written in two words like "parameter identification".

**Comment by msevestre** [comment]
Are you saying it should read "Parameter identification" and not "Parameter Identification"? 
Should it be "In vivo" or "In Vivo"?

Hard to guess from the issue since we do not display "parameter identification"...

**Comment by msevestre** [comment]
Sticking with Upper Case to be consistent with other combo box
so Not In vivo but In Vivo
