### ISSUE TITLE
Typographical: in vivo / in vitro still misspelled

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#692]
Since I apparently cannot re-open #683 :
Please remove the "hyphens" ("-") which are still present in the 7.3.0.13 beta and are incorrect to use.

**Comment by msevestre** [comment]
This was corrected in core. Please give it a few days to make it to the app

**Comment by msevestre** [comment]
This will be fixed as soon as PR #696 is merged
