### ISSUE TITLE
Feature: Add user defined observers to PK-Sim

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#697]
I would like to propose the addition of a new feature in PK-Sim that would allow users to add their own observers to PK-Sim.

Right now, every time I need to simply use a custom observer, I need to : 
* export the simulation to MoBi
* define my observer in the ObserverBuildingBlock
* Recreate my simulation
* Send it back to PK-Sim so that it belongs in my project

At that stage, it works fine. However I have **lost** the possibility to swap building block, update or commit parameters etc..

I think it would be  a great addition to add a new step when creating the simulation. Alongside selection of Individual, Compound, Application, etc.. we could also have a new section where the user could define observers to use. The very easiest way would be to allow the user to load an observer from pkml file. The observer would be added to the simulation during the build step and would be available from now on.

Alternatively we could allow the definition of observers directly in PK-Sim but this could be a second step / not even required. 

One could also see that as a new building block type: Instead of observer building block, one could add /load single building blocks and combine them in the simulation at build time. 

At any rate, this would remove the need to go to MoBi **JUST** to get user defined outputs

Thoughts?

**Comment by SRuedesh** [comment]
I would greatly appreciate the implementation of such a feature. Currently I have to export simulations to MoBi only to implement an observer which essentially just adds up concentrations of two enantiomers to display the concentration of the racemic substance and export the simulations back to PK-Sim.

> At that stage, it works fine. However I have lost the possibility to swap building block, update or commit parameters etc..

This is where it gets really problematic. Essentially, the current workaround is to change the initial simulation (i.e. swapping building blocks), import it back to MoBi to implement the observer and back to PK-Sim.
When handling a larger amount of simulations, this is a time-consuming and frustrating procedure.

**Comment by msevestre** [comment]
@SRuedesh This will be part of the next release (Version 8) coming up in the next few weeks

**Comment by msevestre** [comment]
you can give it a spin by downloading the nightly version
http://pksim-portable.open-systems-pharmacology.org
