### ISSUE TITLE
Value Origin: Source may not be UNDEFINED if description is provided

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#704]
![image](https://user-images.githubusercontent.com/1041237/39870864-d48e31f2-5430-11e8-926b-a4b10bfe3960.png)

This should actually never happen (e.g. Undefined source and a caption!)

**Comment by msevestre** [comment]
And BSA is empty, which is also wrong

**Comment by Yuri05** [comment]
There are quite a few value origins, which are not properly defined now.
Regarding BMI: could delete a description. The idea behind "Standard definition" was: commonly used, well known formula.

**Comment by msevestre** [comment]
@Yuri05 That's fine. However the Source should not be undefined. This is NOT possible to create something like that in the UI (For example it should be publication or sthg like that)
