### ISSUE TITLE
Wrong Value origin for new Specific intestinal permeability alternative

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#710]
Add new parameter alternative in compound for **_Specific intestinal permeability_**
New alternative automatically gets value origin of the "Calculated" alternative, which is wrong.

(7.3.0.14 beta)

**Comment by Yuri05** [comment]
New alternative becomes the default ValueOrigin of the "Calculated"-Alternative ("Publication XY")
![unbenannt](https://user-images.githubusercontent.com/25061876/39892628-8d2fce30-54a1-11e8-9568-7f53429d954b.png)

**Comment by msevestre** [comment]
Not sure how we can deal with that. We have the SAME parameter that should have different behavior and ValueOrigin

**Comment by msevestre** [comment]
Hum I cannot even set the ValueOrigin for those...

**Comment by msevestre** [comment]
Ok I just cannot reproduce the issue. Do you have antoher database? Where does this value comes from?

**Comment by msevestre** [comment]
ok I could finally reproduce!
