### ISSUE TITLE
Snapshot/Compound: Value Origin Difference

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#720]
7.3.0.16 ß
There are some problems with reimporting of compound snapshots.
All can be reproduced with the workflow described below.
Other problems will be described in separate issues.

* Open project attached
* Save compound building block **_C1_Everything_** as template
* Export project to Snapshot
* Close project and import saved snapshot
* Reload compound building block **_C1_Everything_**  from template (rename when prompted to e.g. **_ORIG_C1_Everything_**)
* Compare compound building blocks **_C1_Everything_** and **_ORIG_C1_Everything_**
  * In comparison options:
    * Deactivate "`Only compare properties relevant to simulation results`"
    * Activate "`Compare hidden entities`"
    * Activate "`Show value origin for changed values`"

[CompoundSnapshot.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1997513/CompoundSnapshot.zip)

Value origin values for `Metabolizing Enzynes==>E12==>cc==>Content of CYP Proteins in liver microsomes` differ

![01](https://user-images.githubusercontent.com/25061876/39956528-d299af44-55e2-11e8-9073-9089fb0ed2cc.png)

**Comment by msevestre** [comment]
Was the value changed? Default parameter where only value origin was changed won't be saved to snapshot. That makes sense because well they haven't changed;-)

**Comment by Yuri05** [comment]
In this case indeed, the _value_ was **not** changed, only value origin.

**Comment by Yuri05** [comment]
We should mention this in the Release Notes.

**Comment by msevestre** [comment]
I have added the Milestone 7.3.0 so that we don't forget to add to release note. This is an ok behavior in my opinion. Changing ValueOrigin without changing value does not make sense in general
