### ISSUE TITLE
Snapshot/Compound: Difference in calculation parameters for Liver Plasma Clearance

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#721]
Steps to reproduce described in #720
Calculation parameters `Fraction unbound (experiment) `and `Lipophilicity (experiment)` are different in `Total Hepatic Clearance==>Liv1` process.

![01](https://user-images.githubusercontent.com/25061876/39956574-c83d375e-55e3-11e8-84b8-5a64f8b7be88.png)

**Comment by msevestre** [comment]
That's because we override default with conpoubd parameters and don't set those parameters as changed

**Comment by Yuri05** [comment]
Hmm, this would be the case if the user changes fu/Lipo **_after_** creating a plasma clearance process.
As far as I remember it was not the case here (I created all the parameter alternatives for fu/Lipo/... **_before_** creating the processes). Will try to reproduce once again with a simpler compound.

In any case, we should mention this in the Release Notes.

**Comment by msevestre** [comment]
No that's the other way around. It takes value of Lipo etc of compound at
time of creation. After that, those are not linked anymore

**Comment by msevestre** [comment]
I think we can fix this by ensuring that values updated from conpound are marked as changed

**Comment by Yuri05** [comment]
>I think we can fix this by ensuring that values updated from conpound are marked as changed

That's a good idea in any case
