### ISSUE TITLE
Snapshot/Compound: Dimension issues

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#722]
Steps to reproduce described in #720
A lot of parameters are recreated from snapshot with a wrong dimension.
See attachment for the full list
[Dimensions.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1997529/Dimensions.xlsx)

**Comment by msevestre** [comment]
Very weird.

**Comment by Yuri05** [comment]
Almost there. Only 2 differences in dimension now:
<img alt="aufnahme40" src="https://user-images.githubusercontent.com/25061876/40118913-c672dbf2-590a-11e8-9b2b-26a47514b467.png">
(project taken again from #720)

**Comment by msevestre** [comment]
probably a DB Error again. Snapshot load DOES NOT Assign dimensions

**Comment by msevestre** [comment]
I cannot reproduce with a new compound. Please check again with a new project and attach the project if you can reproduce

**Comment by Yuri05** [comment]
OK, cannot reproduce it either with a new compound

**Comment by Yuri05** [comment]
Happens again with the compound attached.
It was created with one of the versions 7.3.0.20, 7.3.0.21, 7.3.0.22
[DimensionBug.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2019760/DimensionBug.zip)
<img width="515" alt="aufnahme3" src="https://user-images.githubusercontent.com/25061876/40272149-b810c2dc-5b98-11e8-8e6d-e7fe49807b6e.png">

**Comment by Yuri05** [comment]
OK the problem with dimension is not the snapshot - something is wrong during creation of new intestinal permeability alternatives.

Here, Compound C1 was created in 7.2.2 and project was opened in 7.3 (latest dev version)
In 7.3, Compound C1_NEW was created with the same settings as C1
<img alt="aufnahme4" src="https://user-images.githubusercontent.com/25061876/40272498-924333b4-5b9d-11e8-8af3-c7ad09c3ee07.png">

Comparing C1 and C1_NEW shows dimension difference
[DimensionBug3.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2019773/DimensionBug3.zip)
<img width="701" alt="aufnahme1" src="https://user-images.githubusercontent.com/25061876/40272486-45d4f3e6-5b9d-11e8-9c33-8193ebbd021a.png">

[DimensionBug3.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2019772/DimensionBug3.zip)

**Comment by Yuri05** [comment]
>This is nothing new

This is new; in 7.2 dimension was correct, as can be seen in example above.

Closed in favor of #779

**Comment by msevestre** [comment]
Going to check it out. If feels to me however more like the problem we had before with dimension not being set properly until we save and reload the project because of faulty DB references
