### ISSUE TITLE
Snapshot/Individual: Difference in ontogeny factors

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#724]
7.3.0.17 ß

There are some problems with reimporting of individual snapshots.
All can be reproduced with the workflow described below.
Other problems will be described in separate issues.

* Open project attached
* Save individual building block **_I1_AllEnzymes_** as template
* Export project to Snapshot
* Close project and import saved snapshot
* Reload individual building block **_I1_AllEnzymes_**  from template (rename when prompted to e.g. **_I1_AllEnzymes_ORIG_**)
* Compare individual building blocks **_I1_AllEnzymes_** and **_I1_AllEnzymes_ORIG_**
  * In comparison options:
    * Deactivate "`Only compare properties relevant to simulation results`"
    * Activate "`Compare hidden entities`"
    * Activate "`Show value origin for changed values`"

[IndividualSnapshot.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1997828/IndividualSnapshot.zip)

`Ontogeny factor` and `Ontogeny Factor GI `differ for some enzymes
![unbenannt](https://user-images.githubusercontent.com/25061876/39960371-1e715da6-5622-11e8-8720-8535cdbafff3.png)

**Comment by msevestre** [comment]
Same problem. Those parameters were not marked as changed (because they are set != from default in code and not via UI interactions) .All those spots (and you've found a lot of them) will always results in differences
