### ISSUE TITLE
Snapshot/Individual: Differences in Membrane location

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#725]
Steps to reproduce described in #724

![unbenannt](https://user-images.githubusercontent.com/25061876/39960384-75a95330-5622-11e8-9a60-2071aeb79340.png)

I changed membrane location in from default in much more places; surprisingly the difference between original building block and reimported from snapshot occurs only in this 2 cases..

**Comment by msevestre** [comment]
Brain and Rectum.... interesting

**Comment by msevestre** [comment]
for example T2 looks like so in Snapshot
```
     {
          "Name": "T2",
          "Type": "Transporter",
          "TransportType": "Influx",
          "Expression": []
        },
```

**Comment by msevestre** [comment]
In my eyes, ok behavior. We can add it to release notes

**Comment by Yuri05** [comment]
Think, that's ok.
