### ISSUE TITLE
Transporters: UI

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#727]
7.3.0.17 ß

Usability issue: properties of transporter proteins in Individual building block are shrinked so that user has to scroll.
![unbenannt](https://user-images.githubusercontent.com/25061876/39960447-910128f0-5623-11e8-88cc-1b69ac920858.png)

In Metabolizing Enzymes/ Protein Binding Partners it looks good:
![unbenannt](https://user-images.githubusercontent.com/25061876/39960450-a3f0803c-5623-11e8-85f5-ebcfe33128a6.png)

**Comment by msevestre** [comment]
Can't reproduce with current version. Are you using some weird resolution?
Please try with latest version as I have changed something related to resize yesterday

**Comment by Yuri05** [comment]
Tried on: 
* resolution: 1280 x 1024
* font size: 100% (standard)

As soon as new nightly build is available, will try again.

**Comment by msevestre** [comment]
Fixed by https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/736
