### ISSUE TITLE
Import from Snapshort: missing warning for invalid parameters

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#732]
E.g. try to import attached snapshot. It contains the piece of invalid information below. However, no warning is shown.

[InvalidParameters.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2000635/InvalidParameters.zip)

```
        "Favourite_animal": {
          "Value": "Spider",
          "Unit": "pieces"
        }
```
![invalidparametersimport](https://user-images.githubusercontent.com/25061876/39997494-a3ce9788-5772-11e8-91f2-a039e045de32.jpg)

**Comment by msevestre** [comment]
Node that are unknown the object model are not parsed. This is similar to adding unknown xml nodes to an xml. They would be ignored unless a loop is made to explicitely check for everything

If you want to test that behavior, you need to add this parameter under a parameters [] array.
Behaves as expected
