### ISSUE TITLE
7.3 Event templates disappeared

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#739]
7.3 beta: template database does not contain any predefined event (all Meal/Gallbladder emptying events disappeared)

**Comment by msevestre** [comment]
Events are not defined as template. Rather the selection can be done directly when creating an event

![image](https://user-images.githubusercontent.com/1041237/40065575-1beae2b8-5830-11e8-9272-6cecd82917b9.png)
