### ISSUE TITLE
Feature request: Update function for Observed Data

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#740]
It often happens that a set of observed data is updated in the process of an ongoing study: more individuals or doses may be included, more data points measured (e.g., progressing time points), or PD data or biomarkers become only available with some delay.

After importing and using preliminary data, it may thus become necessary to replace/extend already data with the updated data set. Currently, one has to manually delete each data set from all simulations and PI tasks where they are in use, and then import the latest data file. This can become quit tedious, e.g., if many individual patient data sets need to be used.

The following suggested solutions may ease that process:
1. A method of global deletion of observed data from the project file is implemented. Data can be deleted from the Observed Data building block regardless if they are in use in simulations, PI or elsewhere. Multiselect should be possible, safety confirmation needed. New data will then be imported; if the same name convention as with the old data is used (e.g., by the grouping functionality), the new data replace the old sets in simulations etc.
2. Data can be imported on top of already existing observed data. Extra data points are added, old points overridden. Simulations are updated correspondingly.

This request also applies to MoBi.

**Comment by Yuri05** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/785
