### ISSUE TITLE
7.3 beta: Changed „Is small molecule“ property is not shown in the “User Defined” group of parameters at a simulation

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#745]
Deselecting „Is small molecule“ property of a molecule  is not shown in the “User Defined” group of parameters at a simulation in PK-Sim. Thus a changed default value is not shown as “User Defined” parameter.

I would even suggest to show the property „Is small molecule“ generally as a “User Defined” parameter (i.e. also if it is not changed) as it is done for other arbitrary defaults (e.g. koff = 1 /min)

**Comment by Christoph27** [comment]
This is still present in 7.3.0.19

**Comment by Yuri05** [comment]
Hmm, Is Small Molecule is also not exported to snapshot (but it has IS_INPUT=1).
@msevestre Could the reason be that the parameter is ReadOnly?

**Comment by msevestre** [comment]
Is Small Molecule readonly??

**Comment by msevestre** [comment]
@Yuri05 Do you see any problem if I set visible = true ? Parameter will appear as readonly in the simulaiton view and that's all I believe

**Comment by msevestre** [comment]
THat's how it will look like
![image](https://user-images.githubusercontent.com/1041237/40125504-181088ae-58f9-11e8-80a3-78d38c9e71cd.png)

**Comment by Yuri05** [comment]
>Do you see any problem if I set visible = true ? Parameter will appear as readonly in the simulaiton view and that's all I believe

Don't see a problem
