### ISSUE TITLE
7.3 beta: Parameters at "User Defined" for projects created with earlier versions

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/PK-Sim#746]
If projects created with earlier versions are opened with 7.3 beta, it is possible that either too few parameters (happened with PK-Sim)  or too many parameters (happened with MoBi) are shown in the group "User Defined" at a simulation. If it is not possible to fix that behaviour without a cumbersome and error-prone project conversion, would it be possible for "old" simulations to attach a warning mark to the group "User Defined" explaining e.g. in a mouse-over information that the information in the group "User Defined" is not valid since it is a pre-7.3 model?

**Comment by msevestre** [comment]
FYI:
We have implemented a project conversion in MoBi. Starting with the version from tomorrow, MoBi will behave like PKSim and all parameters will be marked as unchanged as there is no way to actually know what was changed and what was default

**Comment by Yuri05** [comment]
Closing. Please reopen if there are any further issues on this topic
