### ISSUE TITLE
Reference concentration and HalfLifes are not saved to snapshot for enzymes with non-default values

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#757]
* Open project attached
* save individual **tmp_I1_Snap** as template 
  * In this Individual-BB, CYP3A4 was loaded from Gene Expression DB; after that only Value Origin of Reference Concentration was changed manually.
* export project to Snapshot
* Load project from snapshot
* Load individual **tmp_I1_Snap** from template and rename to **tmp_I1_Snap_ORIG**
* Compare individuals **tmp_I1_Snap** and **tmp_I1_Snap_ORIG**

[06_7.3.0.20_17Mai.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2013990/06_7.3.0.20_17Mai.zip)

The differences below are shown.

<img alt="aufnahme41" src="https://user-images.githubusercontent.com/25061876/40190480-91bc4486-59ee-11e8-8427-a17ddef7038c.png">

**Comment by Yuri05** [comment]
OK, same problem if adding CYP3A4 manually (not from DB).
Guess the problem is that for known enzymes, where we have info about RefConc/HalfLifes, those parameters are still set do default and not exported to snapshot

**Comment by msevestre** [comment]
Another case of parameters being set in code.we need to call the same method when we load probably

**Comment by msevestre** [comment]
As long as I update those parameters BEFORE the parameters are updated from snapshot, we should be good to go
Good find

**Comment by msevestre** [comment]
PS: Loading and saving bb to snapshot proves extremely valuable to debug all those issues quickly eh?

**Comment by Yuri05** [comment]
>Loading and saving bb to snapshot proves extremely valuable to debug all those issues quickly eh?

Yep, absolutely.

**Comment by msevestre** [comment]
Ok the only way I can retrieve those parameters is if the user does not sthg like that
Add Molecule CYP3A4 => prameter will be loaded from DB
Rename Molecule to XXXXX
Save to snapshot
Load from snapshot. At that stage, I have no refeerence to CYP3A4 and parameters will not be molecule dependent.

Alternatively, I set those parameters to IsDefaut = false if they are updated automatically.

I think version 1 is better but let me know

**Comment by Yuri05** [comment]
>Ok the only way I can retrieve those parameters is if the user does not sthg like that
Add Molecule CYP3A4 => prameter will be loaded from DB
Rename Molecule to XXXXX
Save to snapshot
Load from snapshot. At that stage, I have no refeerence to CYP3A4 and parameters will not be molecule dependent.

I think we can live with that. Adding a "standard" enzyme and renaming it to smthg else does not make much sense for me
