### ISSUE TITLE
Old projects: applications not properly saved to snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#771]
7.3.0.22
Open the project attached (created with 7.2.2) and save to snapshot.
Reload project from snapshot.
Dose and infusion time do not match
[7.2.2_AppTest.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2017514/7.2.2_AppTest.zip)
![clipboard01](https://user-images.githubusercontent.com/25061876/40243859-d6ff63d0-5ab0-11e8-8e39-e783557ffaf9.jpg)

Both parameters were not exported to snapshot even though they are both IS_INPUT=true and their values differ from defaults
```

  "Protocols": [
    {
      "Name": "App1",
      "ApplicationType": "Intravenous",
      "DosingInterval": "Single"
    }
  ],
```

**Comment by msevestre** [comment]
This is once again a conversion from old project issue. We can say for this one that ALL application parameters are IS_DEFUALT=true when we convert. But using snapshot export from old project will alaws results in errors

Definitely not HIGH prio in my opinion

**Comment by Yuri05** [comment]
>We can say for this one that ALL application parameters are IS_DEFUALT=true when we convert.

Should do.

>But using snapshot export from old project will alaws results in errors

That's why: #773

**Comment by msevestre** [comment]
Project conversion updated to ensure that Schema and Schema Items parameters are marked as Default=false if changed
