### ISSUE TITLE
Advanced protocol: sorting ignore units

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#774]
In advanced application protocol window doses are sorted by start time.
However units are obviously ignored (e.g. in the screen below dose at `t=30 [sec]` is placed after dose at `t=3[h]`
<img alt="aufnahme2" src="https://user-images.githubusercontent.com/25061876/40248540-c4d5cd70-5abf-11e8-862e-6391ea296464.png">

**Comment by msevestre** [comment]
Default sorting by devexpress.  why would someone works with min, h, s at the same time?

**Comment by UlrichSi** [comment]
Working with different units (like hours and days) might be desired on a complex drug application scheme, like an initial "flooding" by infusion followed by a later bolus dose. If I were doing it, however, I would also prefer to have everything in the same unit.
