### ISSUE TITLE
Tutorial on MoBi

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/PK-Sim#785]
Is there any tutorial for MoBi?

**Comment by StephanSchaller** [comment]
[Here](https://github.com/Open-Systems-Pharmacology/ACoP-2018-Workshop)

;-)

**Comment by StephanSchaller** [comment]
Or [here](https://github.com/Open-Systems-Pharmacology/PAGE-2018-Workshop), if you are in a hurry and can travel to Europe...

**Comment by msevestre** [comment]
Hi there,

There are no online tutorials that I am aware of dedicated specifically to
MoBi. This is something that the community should try to work on as this
would benefit everyone.

You can find all tutorials at
http://tutorials.open-systems-pharmacology.org/

Cheers,

**Comment by msevestre** [comment]
Right live training with hands one exercise is obviously another option if you can attend. 
@StephanSchaller Are you planing on recording the tutorial so that it can be posted online?

**Comment by StephanSchaller** [comment]
@msevestre No, we are not planning to record the training as it will not a demo-like tutorial but a hands-on workshop for the most part and this is too messy for videotaping ;-)
