### ISSUE TITLE
Import from snapshot: differences in populations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#789]
With the example from #788:
* Open project and save population **Adults** as template
* Close project and load project from Snapshot
* Load population **Adults** from template and rename it to OLD_Adults
* Extract from both populations the same Individual (e.g. Individual 1) and compare both extracted Individuals **Adults-1** and **OLD_Adults-1**.

There is only one difference: **Lumen/LowerIleum/Length** (same happens if comparing other extracted individuals for these 2 populations)
<img width="514" alt="aufnahme12" src="https://user-images.githubusercontent.com/25061876/40378293-a48102bc-5de2-11e8-8086-027840760da5.png">

The reason for that is probably: **Lumen/LowerIleum/Length** was additionally distributed in the population **Adults** using **_Uniform_** distribution.

<img width="310" alt="aufnahme11" src="https://user-images.githubusercontent.com/25061876/40378298-a9a8ebba-5de2-11e8-92ac-f6f8468dc823.png">

Some other parameters were additionally distributed using, Normal, LogNormal and Constant distributions - all of them show no differences between original population and imported from snapshot.

**Comment by msevestre** [comment]
We had agreed that it was not possible to recreate the same Advanced parameters between populations. Nothing to change here

**Comment by msevestre** [comment]
See [here]https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/6d50be080e18b310b6e4725c95aeeef8adee7367/src/PKSim.Core/Model/AdvancedParameter.cs#L69

We reset the random generator explicitely so that we do not always get the same values

**Comment by msevestre** [comment]
This should never be statistically different provided that we have enough individual in the population AND same mean and std

**Comment by Yuri05** [comment]
>We reset the random generator explicitely so that we do not always get the same values

Random generator is reseted with the Seed saved in `AdvancedParameter`. If `AdvancedParameter.Seed` is not set to the random seed saved in snapshot, I would expect differences in **all** distributions (except for const).

However in my example it perfectly works for all Advanced parameters distributed via Normal/LogNormal distribution. Only the one with uniform fails.
So I think the Seed is set also for advanced parameters, and for some unclear reason uniform distribution behaves differently

**Comment by msevestre** [comment]
na I remember clearly having this discussion with you. There was something about the order with which parameters were added as advanced parameters to the population. I'll check it out but I am almost certain that this is the reason

**Comment by msevestre** [comment]
>So I think the Seed is set also for advanced parameters

nope. The Seed is not saved in Snapshot

**Comment by msevestre** [comment]
But if we were to save seed, because of this one line [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/6d50be080e18b310b6e4725c95aeeef8adee7367/src/PKSim.Core/Model/AdvancedParameter.cs#L71) where the _randomGenerator is always saved, before generating the value, this may actually work
