### ISSUE TITLE
Renaming Time Profile Analysis tab only possible after closing and re-openening simulation window

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#795]
In the attached file, I renamed the Time Profile Analysis 2 to "Plot 2". 
The new name is only shown after the simulation window is closed and re-opened, otherwise the old name is shown as in the figure below

![image](https://user-images.githubusercontent.com/26541603/40498401-40b3c758-5f7f-11e8-9fd1-361fe24b7af9.png)

[Test.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2036244/Test.zip)

**Comment by msevestre** [comment]
Thanks @AndreDlm  for the bug description .Clear and to the point :)

**Comment by Yuri05** [comment]
Hmm, can reproduce with 7.3.0.29.
3 days ago it definitely worked. Interesting...

**Comment by msevestre** [comment]
Well this is with version 7.2 so the bug has been in for a while.
