### ISSUE TITLE
Cloning a simulation destroys Persistable-property

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#796]
Once a simulation was run in PK-Sim: cloning this simulation will set a lot of quantities as persistable.
E.g. in project attached: clone simulation **S1** to **S1_clone** and compare both simulations
[CloneTest.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2036413/CloneTest.zip)

<img width="556" alt="aufnahme1" src="https://user-images.githubusercontent.com/25061876/40500962-0d4dcee4-5f76-11e8-8462-c8018043e2cb.png">

It happens only after original simulation was run. If cloned **before** the first run: all Persistable flags are cloned properly.

In the UI the differences cannot be seen directly
E.g. if **Define Settings and Run** dialog is opened in the cloned simulation: only the quantities which were selected for output in the _original_ simulation are also selected.

However exporting SimModel-XMLs for both simulations will also show the differences in persistable flag
(**which will result in much higher memory consumption of the cloned simulation during calculation, especially for population simulations and PIs if run in parallel on multiple cores**!)

[XMLs.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2036437/XMLs.zip)

In the example above following quantities were set to persistable after cloning :
* ALL Observers (with 3 or 4 exceptions, hmm)
* 3 molecule amounts: **Gallbladder**, **Lumen|Feces** and **Organism|Kidney|Urine**

 (happens in 7.2 and 7.3)

**Comment by Yuri05** [comment]
just tried it with **6**.1: same problem. Seems it's here for quite a while...

**Comment by msevestre** [comment]
My observations are slightly different, or maybe the same but then let me formulate it my way

- When creating a simulation (or cloning),  a bunch of variables are set to persistable, even though they should not be set to persistable. This happens as well when creating a brand new simulation (which variable is persisted is not defined yet...probably default persisted flag is true in Core
![image](https://user-images.githubusercontent.com/1041237/40564283-1be3b62e-6036-11e8-8d6c-47c9d4e87335.png)

- as soon as I run the simulation, the persistable flag is set properly according to selection (and Xml is also ok)
![image](https://user-images.githubusercontent.com/1041237/40564313-35e8500c-6036-11e8-9595-bd2938704aa2.png)

(here we only see displayunit issue that are solved when  saving loading project)

- So in my opinion, there is no higher memory consumptions UNLESS the simulation is exported without being run once in PKSim. 

![image](https://user-images.githubusercontent.com/1041237/40564363-63240822-6036-11e8-8445-cbaf27fdff1d.png)

You can see in the picture above the SimModel Xml exported after running the simulation once. It's is absolutely correct. Only 4 persistable entities. The flag is actually SET before sending to SimModel xml the first time

So I'd say all in all this is all fine. The display unit should probably be set properly  upon creation, but this is very minor

**Comment by msevestre** [comment]
Do you agree that this is not HIGH prio?

**Comment by msevestre** [comment]
@Yuri05 Do you agree that this bug is absolutely not critical? You set it to high and 7.3 but the only issue is when creating/cloning a simulation without running it once!

**Comment by msevestre** [comment]
I think this is however a pretty easy fix. See PR
