### ISSUE TITLE
Renaming of Parameter Identification via PI tab context menu not possible

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#797]
When I open the context menu of the Parameter Identification via the PI tab and select "Rename..." nothing happens (see figure below).
However, renaming the PI through the context menu from the tree view works.
PK-Sim file attached below. Probably related to [#795](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/795).

![image](https://user-images.githubusercontent.com/26541603/40531367-7bf6ea48-5ffc-11e8-9183-bdda9918b6f2.png)

[Test.zip](https://github.com/Open-Systems-Pharmacology/Forum/files/2038410/Test.zip)

**Comment by msevestre** [comment]
good find
