### ISSUE TITLE
Population simulation window: Name of statistics for display not properly shown after (de)selection

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#798]
In the Time Profile Dialog of Run Population Simulation, Tab Output --> Output: Select distribution statistics for display, the name of the different statistics changes when being ticked or unticked as shown below:

![image](https://user-images.githubusercontent.com/26541603/40533650-b5bcd29a-6003-11e8-879e-8627dfc1862e.png)

![image](https://user-images.githubusercontent.com/26541603/40533678-cbc40a9a-6003-11e8-9f60-72841a141c6c.png)

![image](https://user-images.githubusercontent.com/26541603/40533901-74616102-6004-11e8-9352-4da3595379b8.png)

(Of note, the correct statistics are subsequently calculated, despite the wrong display here)
PK-Sim file:
[Test.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2038544/Test.zip)

**Comment by Yuri05** [comment]
Indeed...

**Comment by msevestre** [comment]
Interesting
