### ISSUE TITLE
Differences between snapshot file and snapshot-to-snapshot-export file

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#799]
After having exported the attached project to a snapshot (TC_4.77_Snapshots.json), I have loaded the snapshot in a new project. Then, I have exported the project again to a snapshot (TC_4.77_Snapshots_Reexport.json) and compared both snapshot files via cmd fc. I have exported the results in a txt file (Diffs.txt). 
Surprisingly, quite some differences are listed in the txt file, although both files should be the same.

[Snapshots.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2039127/Snapshots.zip)

**Comment by msevestre** [comment]
Was the project created with 7.3?

**Comment by AndreDlm** [comment]
Yes (7.3.0.29 b)

**Comment by Yuri05** [comment]
@msevestre Any thoughts on the differences?

**Comment by ju-rgen** [comment]
With build 7.4.0.93 - EAP there are still differences, see diffs93.txt
[diffs93.txt](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2608856/diffs93.txt)

**Comment by Yuri05** [comment]
>With build 7.4.0.93 - EAP there are still differences, see diffs93.txt

OK, in this diff I see only unproblematic differences:
* Colors (e.g. `"Color": "0, 255, 0"` vs. `"Color": "Green"`). Recreating from snapshot produces correct results.
* Formatting. E.g. `0.0` vs `0`

Issues reported previously are obviously fixed in 7.3 or 7.4. Closing the issue.
