### ISSUE TITLE
Differences between snapshot-loaded simulation and identical working journal-loaded simulation 2

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#805]
Similar to #803, I have built a simulation in v 7.3.0 with an adult scaled down to a preterm and a large molecule. I have exported it to a snapshot and to working journal. Then, I have opened a new project and loaded the snapshot-simulation and the working journal simulation (in the attached file called S2_Preterm_Protein and OLD_S2_Preterm_Protein, respectively).
When comparing both simulations, a breadth of differences is shown, some probably redundant or similar compared to #803, but in particular there's also a difference shown for the property Value Point. 

![image](https://user-images.githubusercontent.com/26541603/40550297-09aef6c2-603a-11e8-83c6-57fc4d6625ab.png)

[Snapshots.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2039751/Snapshots.zip)

**Comment by msevestre** [comment]
Points are only found according to X values. Saving values to snapshot truncate the X values to a certain number of digits so hence the difference (one can see that values are there, absent and present .... but this is an issue with float representation)

Nothing to do in my eyes

**Comment by msevestre** [comment]
this should be fixed with #806
