### ISSUE TITLE
Differences between snapshot-loaded simulation and identical working journal-loaded simulation 3: comparison function arguable

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#806]
Similar to #803, I have built a simulation in v 7.3.0 with an adult scaled down to a preterm and a large molecule. I have exported it to a snapshot and to working journal. Then, I have opened a new project and loaded the snapshot-simulation and the working journal simulation (in the attached file called S2_Preterm_Protein and OLD_S2_Preterm_Protein, respectively).
When comparing both simulations, a breadth of differences is shown, some probably redundant or similar compared to #803. In addition to those shown in #803 and #805 the comparison function also yields differences for the property Y, which seems arguable, at least from the number of decimal point shown here...

![image](https://user-images.githubusercontent.com/26541603/40550512-945c13ea-603a-11e8-991c-e5b150a499ee.png)

Files are attached in #805

**Comment by Yuri05** [comment]
OK, this has nothing to do with snapshots, but only with comparison itself.
Values seems to be identical (especially within given comparison tolerance 1e-5)

**Comment by msevestre** [comment]
@AndreDlm Agreed. Probably a bug with the comparison. All of those guys should be identical

**Comment by msevestre** [comment]
indeed. Tolerance not used to find point or to compare values
Great find @AndreDlm
