### ISSUE TITLE
Load observed data from template: Multiselect does not work

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#814]
(7.3) Only the first data set is loaded. 
<img width="300" src="https://user-images.githubusercontent.com/25061876/40585416-0f321106-61a2-11e8-9bd1-c78067115336.jpg"> :arrow_right: :arrow_right: <img width="300" src="https://user-images.githubusercontent.com/25061876/40585411-e174079c-61a1-11e8-8cbd-6eaee0f69e0a.jpg">

**Comment by msevestre** [comment]
Didn't event know one could load observed data from templtae!!
