### ISSUE TITLE
Update Example submodules when all update tasks are done

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#818]
FYI @Yuri05

**Comment by msevestre** [comment]
@Yuri05 Are all project updated?

**Comment by Yuri05** [comment]
>Are all projects updated?

Yes - s. PR

**Comment by msevestre** [comment]
Ok . I need to update the submodule. It does not happen automatically

**Comment by Yuri05** [comment]
>I need to update the submodule. It does not happen automatically

https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/849
