### ISSUE TITLE
Add Dimension "Dimensionless per time"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#827]
When I try to load my MoBi-model in PKSim for Population Simulation; I get the following error:

PK-Sim®

Could not load simulation from file 'C:\Temp\fcgumbkf.pkml'
-----------------------------------------------------
Dimension Dimensionless per time not available in DimensionFactory.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

**Comment by UlrichSi** [comment]
To my knowledge, this unit has been removed, because it is identical to "inversed time". A quick fix would be to edit the PKML file and change the dimension there. Or make it temporarily dimensionless?

**Comment by PavelBal** [comment]
1. I could never transfer my model from MoBi to PK-Sim, even pre-OSPS.
2. The model was build with OSPS 7.2 (or 7.1), so it cannot be an artefact from the past.
3. I think this is the problem of dimensioneless parameters that are state variable. I cannot recall that I ever created a parameter and selected "Dimensionless per time".

**Comment by msevestre** [comment]
> I think this is the problem of dimensioneless parameters that are state variable. I cannot recall that I ever created a parameter and selected "Dimensionless per time".

Yes that's the problem. As long as we do not implement support for dimension generated dynamically in PK-Sim, this will not work. There is an issue to that effect https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/440

**Comment by msevestre** [comment]
Closing in favor of #440 
@PavelBal That being said, MoBi should be clever enough NOT to create dimension such as Dimensionless per time, when we have already a dimension that is equivalent.

Can you look at your pkml file and see if you see this dimensiona nd replace it with Inversed time?
(https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/master/OSPSuite.Dimensions.xml#L410)
