### ISSUE TITLE
Load from Template: multiselect+Delete

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#834]
While loading building block from template, it's possible to multiselect >1 BBs.
However after right mouse click only 1 item remains selected ==> deleting **multiple** building blocks not possible.

**Comment by msevestre** [comment]
Is this really that urgent that we need to do it in 7.4??

**Comment by Yuri05** [comment]
would be nice but not that urgent, can be done later
