### ISSUE TITLE
P-gp and specific binding query

### ISSUE THREAD

**Issue by ms-12345** [Open-Systems-Pharmacology/PK-Sim#850]
Hello,

I'm trying to replicate a prior PBPK model of Digoxin. 
The publication mentions ATP1A2 Koff and Kd values and P-gp Km and Kcat.

In the compounds- distribution- specific binding- protein binding partners tab, I entered the values for ATP1A2 Koff and Kd

In the transport and excretion- transport proteins tab, I selected "specific active transport" and entered values for p-gp Km and Kcat. 
How do we decide whether to use 
-Intrinsic active transport - MM
- Specific active transport - MM
- In-vitro active transport - MM?

Then, in the individual (expression) tab, I added transport protein for p-gp and expressed it 100% in the kidney. The transporter showed up as "Efflux" by default and then I changed it to P-gp type.
Also added ATP1A2 as the protein binding partner with reference conc and expressed it 100% in brain. 

Added the administration protocol and ran a simulation.

In the create simulation tab, there was a warning near specific binding. But its showing up as transporter in individual. Anything that I'm missing here?

![doubt 1](https://user-images.githubusercontent.com/37451822/41248096-8a580b4a-6d75-11e8-923a-033b6c4b5efc.jpg)

Also the reaction diagram doesn't mention P-gp. 

![doubt 2](https://user-images.githubusercontent.com/37451822/41248207-ea29434a-6d75-11e8-8745-f61cc2877e19.jpg)

My simulation resulted in the following plot 

![digoxin simulation 15 ugkg](https://user-images.githubusercontent.com/37451822/41248464-c7798cbe-6d76-11e8-9265-9b54388126a0.png)

The model seems to have over predicted the Cmax values.
Have I made a mistake somewhere while entering the values for P-gp?

Any help will be greatly appreciated!!
Thank you!

**Comment by msevestre** [comment]
@ms-12345 Thanks for posting.
If you want to increase your chance of getting an answer to your question, I'd suggest to post your question in the [FORUM](https://github.com/Open-Systems-Pharmacology/Forum). The issues here are solely for release planing and bug reporting. 

My suggestion would be to
1. Create a new entry in the forum with the exact same content as this one (do not link the issues, simply duplicate the content)
1. Close this issue

Cheers,

**Comment by ms-12345** [comment]
Sure, thank you!
