### ISSUE TITLE
Adding new metabolization process: Value Origin entry is ignored

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#853]
In contrast to what is claimed (OSP Suite 7.3.0 released #193), the issue reported in #529 is still not completely working. While creating a new compound, I added a renal clearance and entered information into the field "Value Origin". These entries are lost after completing the "Add process" procedure.

**Comment by msevestre** [comment]
#529 deals with metabolite name being reset.
How is it linked to value origin?

**Comment by msevestre** [comment]
@UlrichSi I don't understand the issue. 529 deals with metabolite name and you are talking about value origin.

**Comment by UlrichSi** [comment]
@msevestre You are probably right, it might not be related to issue 529.

**Comment by Yuri05** [comment]
Not reproducible (assume was fixed). Please reopen if there is still an issue
