### ISSUE TITLE
Incompleted absorbtion

### ISSUE THREAD

**Issue by farzanehmaleki** [Open-Systems-Pharmacology/PK-Sim#855]
Hi,

I am using PK-Sim built-in template for Rifampin. I get this error message for oral dose. Any thought?

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/35151285/41500989-daaf2b80-7169-11e8-8850-19f363016ce5.png">

Thank you,
Farzan

**Comment by msevestre** [comment]
Increase simulation time?

**Comment by farzanehmaleki** [comment]
The simulation time is 48 hours. I have zoomed in in the picture attached. I increased the time to 72 but still getting the same error. 
Is the PKSim template developed for IV or Oral administration? It seems that the model does not capture the elimination phase.

**Comment by msevestre** [comment]
Well actually I think that the message is not quite correct. The normal use case it to check if the absorption is complete by looking at fraction absorbed. The code says fraction absorbed !=1, show warning.
In your case however, you have a fraction absorbed of 3??? 

Do you have some transport process, EHC etc... going on?

**Comment by msevestre** [comment]
@farzanehmaleki Because you need some help here I would suggest to ask the question in the forum where you will get more attention from modeler. This repository is really to report bugs and feature requests and is only monitored by a few people

**Comment by farzanehmaleki** [comment]
I have ABCB1 (Efflux) OATP1B1 (Influx) as transporters. 
I just posted this issue on the forum.

Thank you

**Comment by Yuri05** [comment]
s. https://github.com/Open-Systems-Pharmacology/Forum/issues/195 
Closing
