### ISSUE TITLE
Feature request: save/transfer entire observed data tree between projects

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#858]
We currently can transfer individual observed data sets into the template database and load it back from there. Also, we can save individual observed data sets to a PKML file for later MoBi import.

There are cases where a larger number of observed data sets pile up, and where they may be cleverly organized in a subfolder structure. It would be a useful feature to be able to transfer an entire subfolder tree between projects in the same way.

**Comment by msevestre** [comment]
I like this idea a lot

**Comment by Yuri05** [comment]
duplicate of #1053
