### ISSUE TITLE
Prevent user from setting Template Database path to Predefined Template Database path

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#859]
The path to the user's template database can be set in Utilities/Options. If this path is set by mistake to the Predefined Template Database path, typically 
`C:\ProgramData\Open Systems Pharmacology\PK-Sim\<version>\PKSimTemplateDBSystem.mdb`
this will duplicate each addition to the templates into both database sections, the "User templates" and the "Predefined templates".

A bit disturbing. - For some reason, during the last update, the path of my installation got set to 
`C:\ProgramData\Open Systems Pharmacology\`
(maybe that's a default path? Or it was set after selecting the gene database which I put there?), so it misled me to chose the wrong database.

**Comment by msevestre** [comment]
I think the system database should not have the same extensions. That way it would not happen (unless you try to use *.* in the selection file to which case you might end up selection xlsm instead of xlsx..seee #864 ).

**Comment by UlrichSi** [comment]
The other thing we might untangle are the "default path" for the gene database and for the template database. Currently, setting the gene database first and the template database second might lead you to searching in the wrong place.

**Comment by Yuri05** [comment]
Suggestion:
```
TemplateDatabase user: xxx.mdb=> xxx.templateDbUser
TemplateDatabase system: xxx.mdb=> xxx.templateDbSystem
Expression : GeneDB_Human.mdb => GeneDB_Human.expressionDb
ModelDatabase: PKSimDb.mdb ==> keep AS IS (all other DBs are not mdb anymore, so no confusion possible)
```

**Comment by msevestre** [comment]
PKSimDB.mdb does not exist anymore after migration to 64 bit. Suggestion would be PKSimDB.sqlite.
Still, because other sqlite db might be lying around from other program, I'd suggest to rename this one as well
