### ISSUE TITLE
Feature wish: Multiple metabolites arising from a single enzyme

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#861]
Currently, one enzyme can only produce one metabolite. Frequently, multiple metabolites are formed from one enzyme, e.g. 1-hydroxylation and 4-hydroxylation of midazolam from CYP3A4.

It would be very helpful to add the possibility to model multiple metabolites arising from a single enzyme (and NOT make use of the work-around with doubling (or even more) the enzyme).

**Comment by msevestre** [comment]
See https://github.com/Open-Systems-Pharmacology/Forum/issues/196

**Comment by msevestre** [comment]
The only place to change would be the UI. The core engine already supports this

**Comment by Yuri05** [comment]
@sfrechen Are **all** metabolites always built with the **same** metabolization rate?

**Comment by msevestre** [comment]
>Are all metabolites always built with the same metabolization rate?

No there is no reason to expect the same rate

**Comment by sfrechen** [comment]
@Yuri05 Michael is right. No reason to assume same rate.

**Comment by msevestre** [comment]
@all: This will be implemented in 7.4

**Comment by msevestre** [comment]
Here is how it's going to look like

In case of multiple compound, the following will appear for metabolism only!

![image](https://user-images.githubusercontent.com/1041237/48643812-c3998680-e9ae-11e8-8e58-d151f1221662.png)

Note the + - to add a new line.  - will only be activated if there is at least two lines for the same molecule

Clicking on plus will copy the enzyme and set the process to <None>
![image](https://user-images.githubusercontent.com/1041237/48644100-a3b69280-e9af-11e8-88b0-252cafd81983.png)

After that, another process can be selected (not the same one however, that cannot be changed)

![image](https://user-images.githubusercontent.com/1041237/48644198-deb8c600-e9af-11e8-9958-c97877c50b9f.png)


which will result in

![image](https://user-images.githubusercontent.com/1041237/48644177-cf397d00-e9af-11e8-8871-892d48c7cac2.png)

**Comment by sfrechen** [comment]
Wonderful! Thanks!

**Comment by sfrechen** [comment]
Does not work in case the different metabolites are not modelled/selected (sink condition).
Mutliple metabolites via one enzyme ist just possible if the explicit metabolites are added to the simulation as compounds.

**Comment by msevestre** [comment]
>Does not work in case the different metabolites are not modelled/selected (sink condition).
What's happening? Do you get an error ?

**Comment by Yuri05** [comment]
No error, but :heavy_plus_sign: are missing if no metabolites are selected 
![grafik](https://user-images.githubusercontent.com/25061876/49302033-400b8980-f4c6-11e8-941e-c957a4c7864b.png)

**Comment by msevestre** [comment]
oh ok. So you simply need to select another compound... fair enough
