### ISSUE TITLE
Feature Request: Allow import of xlsm files for Observed data import  (Excel with macros)

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#864]
Some data files contain macros, e.g., to calculate geoSD. PK-Sim will not accept importing numerical data from such file, but instead throw an error.

Current workaround: Copy the data to an XLSX spreadsheet.

**Comment by msevestre** [comment]
@UlrichSi It is not possible to select xlsm from the selection dialog correct? (e.g. you had to enter *.* to see all files as opposed to xls or xlsx files?). 
So you are trying to import a file that is not supported...and is wondering why it is not supported ?:)

**Comment by UlrichSi** [comment]
@msevestre Good to learn that this missing feature caused some entertainment. ;-)
Thanks for clarifying that it is indeed a feature wish.

Hostorically, the old XLS files could also contain scripts. With the new XLSX standard, Microsoft spun off the XLSM as separate format for security reasons. So we just did not notice the import shortcoming, as long as our data providing colleagues stuck to the old XLS format - which can be another workaround, to convert XLSM to XLS.
