### ISSUE TITLE
Different partition coefficient calculation methods impart different physiologies!!

### ISSUE THREAD

**Issue by aelmokadem** [Open-Systems-Pharmacology/PK-Sim#865]
Hi,
While working with PK-Sim I noticed that depending on the partition coefficient calculation method, some physiological parameters change (like fraction of neutral lipids in the attached screenshots).
Is there a reason for that?? 

Thank you.
 
<img width="2526" alt="screen shot 2018-06-28 at 11 06 05 am" src="https://user-images.githubusercontent.com/31896854/42043018-6a0a90e6-7ac3-11e8-90bb-b32ba33f886d.png">

**Comment by msevestre** [comment]
@aelmokadem Those were the parameters from the original publication. In your case, Schmitt uses different parameters than Poulain & teil for example.

**Comment by aelmokadem** [comment]
Thanks @msevestre.

**Comment by Yuri05** [comment]
@aelmokadem Closing. Please reopen if there are any further questions
