### ISSUE TITLE
Plot of dissolution kinetics should rather be linear scaled

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#871]
If I define a Formulation BB with dissolution kinetics (e.g., Weibull or Table), a plot shows "Fraction of dose" versus time. The y axis is log scaled, which does make little sense in my opinion. In some cases, the kinetics information is even lost. For example, try the following kinetics table:
Time    Fraction
0         0
0.5      1
1         1
Here, the initial linear rise is not displayed.

I propose to either plot it only linear or, if log is needed for some reason, to make it switchable.

**Comment by Yuri05** [comment]
@msevestre v9?

**Comment by StephanSchaller** [comment]
Can you enable the "edit" functionality for axes as for other plots to make it switchable?

**Comment by msevestre** [comment]
done
![image](https://user-images.githubusercontent.com/1041237/74184901-9cfbe700-4c15-11ea-875e-b484ca6a7592.png)
