### ISSUE TITLE
Matlab toolbox: new simulation time not exported by saveSimulationToXML.m

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/PK-Sim#882]
After setting a new simulation time via setSimulationTime.m to an initialized simulation in Matlab, this new time pattern is not exported if a xml is saved from the simulation via saveSimulationToXML.m.

**Comment by msevestre** [comment]
It seems to be a bug with the Matlab toolbox. Could you define that issue in the Matlab repo? Thanks;-)
