### ISSUE TITLE
Working Journal file is updated/changed even though no changes were made

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#889]
I open a project which has a working journal attached, make some changes in the project and save the project. I have never opened the working journal or made any changes to it, but still, the time stamp of the .sbj file is changed as well as some content of the file.

This behavior is different from MoBi, where the .sbj file remains unchanged as long as it is not being touched.

It's a minor nuisance, but will result in the same .sbj file being checked in again when using a versioning system like Subversion/Tortoise.

**Comment by msevestre** [comment]
@UlrichSi 
I cannot reproduce the bug
![image](https://user-images.githubusercontent.com/1041237/57266170-e563f400-7048-11e9-8ca6-838715bfc4f0.png)


In the attached picture, you can see that I have open the project at 9:49pm (lock file is created when the project is opened) but the last modified time for the attached wj was 9:44pm

Please attach steps to reproduce (maybe with a project?)

**Comment by msevestre** [comment]
@UlrichSi Can you try in MoBi and let me know (PKSim will be availble on Friday but the fix is the same). Thanks

**Comment by UlrichSi** [comment]
Looks like the bug is fixed in MoBi EAP 7.5, build 8. Well done!

**Comment by UlrichSi** [comment]
PK-Sim EAP 7.5, build 76 works fine too.
