### ISSUE TITLE
Simulation Chart Editor: Changing the Layout not working

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#899]
Selecting another layout in the chart editor (see below) does not work anymore; when selecting a different layout, nothing happens.

![untitled](https://user-images.githubusercontent.com/26541603/43395159-6269fc52-93fd-11e8-921c-154347dab0ba.png)

**Comment by msevestre** [comment]
@Yuri05 I can confirm the issue.  It happens sometime with new version of DevExpress. Templates need to be recreated by hand. Can you ask Juergen to do it?

**Comment by msevestre** [comment]
@Yuri05 Ping. This needs to be delegated to Juergen. Can you follow up with this?
