### ISSUE TITLE
Content data not deleted in project

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#904]
When deleting building blocks / simulations from a project, corresponding data is not removed from the `CONTENTS `database table. As a result, PK-Sim project files do not shrink when removing simulations / BBs.

**Comment by msevestre** [comment]
I cannot reproduce with a brand new project

How are you deleting the entries? 
How old was the original project? I fear this is something that lies deeply in how the project is setup

**Comment by msevestre** [comment]
I could reproduce. The problem is with ObservedData. They are added again everytime we save. The problem is probably also in MoBi BTW
