### ISSUE TITLE
Exception error and program freeze after attempt to create invalid population

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#910]
This issue might happen by accident if the units of some entries are changed by accident, i.e., if "mm" instead of "cm", or "g" instead of "kg" is selected by scrolling with the mouse wheel.

To reproduce, open a new project in PK-Sim, then:
1. Create an individual (leave everything on default)
2. Create a new population. In the Demographics tab, set either the height limits to 1 to 2 cm, or set the weight limits to 1 to 2 kg. 
3. Click on "Next". 
The following error is thrown. Clicking on "Continue" will work, but after 3 repeats PK-Sim will freeze.

![grafik](https://user-images.githubusercontent.com/27352743/43639255-e124d46a-971b-11e8-9f1a-a948057d4c56.png)

**Comment by msevestre** [comment]
This is fixed
