### ISSUE TITLE
Feature: Clear History

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#911]
Add a button in the history manager that would allow the user to clear the history

**Comment by msevestre** [comment]
@Yuri05 Version 7.4?

**Comment by Yuri05** [comment]
>Version 7.4

Yes

**Comment by Erik-Sjogren** [comment]
Thank you!

**Comment by msevestre** [comment]
@Yuri05 Button in history manager or in the ribbon? What would be better? (or both!)

**Comment by msevestre** [comment]
It could go under utilities => ribbon group History (does not exist yet)  => Clear
