### ISSUE TITLE
EHC incorporation 

### ISSUE THREAD

**Issue by Krache** [Open-Systems-Pharmacology/PK-Sim#917]
Dear all, 

I wanted to know how to plug enterohepatic cycle in the PBPK model (Species: Mouse). I have a second peak after oral administration and the bioavailability of my compound is superior to 100% 
After reading the manual, there is a possibility to do it by adding "Event" and plugin the condition: FED. When I do it, there is a message error: No solution after 10000 iteration.

Observation: two peak of concentration (Bouncing) after oral injection (Gavage). 
Question: What other information shall I put in my model to have a better fit?

Thank you,

Best regard, 
Anis

**Comment by Yuri05** [comment]
To add an enterohepatic circulation:

1. Create event of type "**_Gallbladder emptying_**"
<img width="500" src="https://user-images.githubusercontent.com/25061876/44089515-929756bc-9fb6-11e8-9d57-9c681c2bdf12.jpg"></img>

2. When creating a simulation, add created event and specify its start time
<img width="500" src="https://user-images.githubusercontent.com/25061876/44089513-927ecf02-9fb6-11e8-9521-136fade5ed30.jpg"></img>

**Comment by Krache** [comment]
Dear Yuri, 

Thanks a lot! I'll try it ASAP

Best regard, 

Anis
