### ISSUE TITLE
Different partition coefficient - IV/Oral? 

### ISSUE THREAD

**Issue by Krache** [Open-Systems-Pharmacology/PK-Sim#921]
Dear all, 

A quick question, While working on PK-Sim, I used Schmitt Partition coefficient for I.V bolus and I had the best fit (Less error) but for Per Os, Berezhkovskiy gave me the best fit and visually corresponds more to what I see versus the experiment points. My question is: What should I use in the end? Berezhkovskiy or Schmitt?. Both of the partition coefficient give different elimination values and my compound is administered orally. 

Thanks,  

BR, Anis

**Comment by msevestre** [comment]
@Krache Similar to the other issue, please ask you questions in the forum if you want to have some response. Closing for now. Please copy this issue in the forum if you still need some help
