### ISSUE TITLE
Feature wish: amount (instead of concentrations or fractions) of compound dissolved, absorbed  in gut

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#922]
not sure if this si the wish-list. If not it is not easy enough to find ;-).

User would like to get the amount (instead of concentrations or fractions) of compound dissolved, absorbed with time from PKSim like he  gets in GastroPlus? 
This might be a good feature to compare results in PK-sim or at least in MoBi to other programms

**Comment by Yuri05** [comment]
In MoBi it's easily possible, s. [here](https://github.com/Open-Systems-Pharmacology/Forum/issues/216#issuecomment-414674564)

**Comment by msevestre** [comment]
@Yuri05 Is it something that should be done in 7.4?

**Comment by Yuri05** [comment]
IT can be done now e.g. via the defintion of corresponding observers in MoBi and importing them in PK-Sim.
@tobiasK2001 Would it be enough, so that we can close the issue? Or are those values **directly in PK-Sim** still a requirement?

**Comment by Yuri05** [comment]
> @tobiasK2001 Would it be enough, so that we can close the issue? Or are those values directly in PK-Sim still a requirement?

@tobiasK2001 ping

**Comment by tobiasK2001** [comment]
Hi Juri, that seems to be a good solution. Thanks for following up ;-)
