### ISSUE TITLE
MICE GENOME DATABASE

### ISSUE THREAD

**Issue by REVATHICHAPA** [Open-Systems-Pharmacology/PK-Sim#931]
Hi guys,

Where can I find mice genome database, i recently saw a paper of sorafenib pbpk modeling in mice using pksim. so they might have used mice genome database right

**Comment by msevestre** [comment]
Is it stated that they use a mice database? They may have used the human one for mice?

**Comment by msevestre** [comment]
If you want any answer to your questions, please ask the questions in the forum. Closing
