### ISSUE TITLE
Observed data import from Excel: Cutoff at ~1000 rows

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#932]
When importing a longer list of PK data from a dose escalation study, I noticed that there appears to be a cutoff at line 1001 or 1002, depending on title line. Can this limit be extended?

**Comment by Yuri05** [comment]
[LongExcel.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2352707/LongExcel.xlsx)
Cannot reproduce. When importing attached excel file (over 11.000 rows with random data) all data is imported.

Can you try with the file attached?

**Comment by Yuri05** [comment]
Might be also something special with your import settings. Can you provide the structure (column names) of your file(s) and share a screen of your import settings?

**Comment by UlrichSi** [comment]
Was indeed caused by several peculiarities of the import file and selection of the columns. I will see that I open a separate issue for errors caused by settings that PK-Sim appears to dislike.
