### ISSUE TITLE
Observed data import: exception after assigning value to header field

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#934]
If importing a table that also contains columns with information that might be useful to insert it into one of those metadata fields which have a drop-down menu selection (e.g., Molecule, Compartment, Gender), and if the input provided by the data file does not exactly match the spelling selectable by the drop-down menu, nothing appears to be imported. 

If I then input a valid selection by the drop-down menu and click the button "Apply to all", the exception error shown below is thrown. Clicking on "Continue" is ok, but has possible side effects later on. Clicking "Quit" is not advisable.

Example: One column of my input file has the compartment spelled as "PLASMA" instead of "Plasma", or in another column the drug is spelled with an extra space, or in a third column the gender is given as "1" or "2" instead of "Male" or "Female". 

It would be ok if such entries are just ignored and could be overridden, better if the user could select a replacement. Currently, I have to go back to the "Source" tab, deselect my entry and re-import everything to avoid the exception. 

![grafik](https://user-images.githubusercontent.com/27352743/45102193-6a4ee480-b12d-11e8-9289-d4f1d4776d57.png)

**Comment by Yuri05** [comment]
[ImportTest.xlsx](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2353496/ImportTest.xlsx)
Cannot reproduce. In the example attached, there are 2 columns with invalid values: Gender and Compartment.

For both Apply to all button is deactivated after import. Can you reproduce the error with the file attached?

<img width="350" alt="aufnahme10" src="https://user-images.githubusercontent.com/25061876/45104947-af214e00-b122-11e8-9a2d-70be080c7640.png">
<img width="374" alt="aufnahme11" src="https://user-images.githubusercontent.com/25061876/45104953-b2b4d500-b122-11e8-80d3-5b265b1d8a18.png">

**Comment by UlrichSi** [comment]
You did not see the error because you are not done yet. I used the Theophylline model that comes with PK-Sim to test it
Do the following:
1. Select a value for Compartment from the drop-down menu (e.g., Plasma). The Apply to all button will now become active.
2. Optionally, do the same for Gender.
3. Then click "Apply to all" (not yet renamed "Self destruct")

The error should now appear.

**Comment by Yuri05** [comment]
OK, can reproduce (must click on the "global" `Apply to all `button)

<img width="315" alt="aufnahme12" src="https://user-images.githubusercontent.com/25061876/45144934-ffde8880-b1ae-11e8-994c-b7fe968a363a.png">

**Comment by UlrichSi** [comment]
so, let's all pray for the programmers' eternal life....

**Comment by Yuri05** [comment]
obsolete with the new data import
