### ISSUE TITLE
Simulation time range 0-72 hours

### ISSUE THREAD

**Issue by REVATHICHAPA** [Open-Systems-Pharmacology/PK-Sim#935]
Hi Team,
While I am performing simulation, I am getting 0-24 hour profile only, how do I change setting for 72 hours. I mean how can I run the simulation for 72hours?

**Comment by msevestre** [comment]
Dear @REVATHICHAPA 

Open the simulation, select the Settings tab and update the output schema
![image](https://user-images.githubusercontent.com/1041237/45175878-72199200-b1dc-11e8-9f0c-8c317562bf31.png)

I would strongly advise you to spend some time reading the manual as those steps are outlined explicitly.

Also please ask questions in the forum. The PK-Sim repository is here to track bugs and feature request

Cheers,
Michael

**Comment by REVATHICHAPA** [comment]
Sure, Thank  you!
