### ISSUE TITLE
Test DevExpress Office File API

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#939]
IF works fine, we should switch to this component.

**Comment by msevestre** [comment]
Maybe something for @ktseow ? 
/cc @StephanSchaller

**Comment by ktseow** [comment]
Dear Micahel,

https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/939#issuecomment-487154156
I just tried to compile and run MoBi.BatchTool.exe and PKSim.BatchTool.exe. Both need the DevExpress license.
Plese provide steps to get the license. Thank you

Regards,
Kah Tong

________________________________

**Comment by msevestre** [comment]
DevExpress license can be purchased at DevExpress.com

You do not need a license to compile however. You need the licence to edit and modify the UI in any shape or form

I don't think this Office API is part of their standard package is this would have to be purchased separately. However there is surely a 30days trial?
