### ISSUE TITLE
tablet delay factor is not visible 

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/PK-Sim#945]
The formulation Parameter "tablet delay factor" which slows down a tablet relative to fluids in the small intestine, is not visible in PK-SIM an can be changed only within MoBi.
This Parameter should be adjustable by the user!

**Comment by msevestre** [comment]
@KatrinCoboeken I could not find parameter "tablet delay factor" in PK-Sim.
Are you talking about "tablet time delay factor"?

**Comment by msevestre** [comment]
@Yuri05 This is parameter is a formulation parameters defined in SIMULATION. Why? Shouldn't that be a building block parameter?
