### ISSUE TITLE
Observed Data import: location of error is difficult to spot in long lists

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#947]
When importing a list of PK data from a larger number of patients, every patient's data set needs to be strictly ordered, or the following error will be displayed:

![grafik](https://user-images.githubusercontent.com/27352743/45754029-d267f500-bc1a-11e8-9f80-c6a01c4fbcfd.png)

It would be helpful if the error message would report the location of the issue in the table to make it feasible to manually correct the problem. In longer lists, it is nearly impossible to visually spot it. Currently, one has to return to Excel and add some sort of search algorithm to find it.

**Comment by msevestre** [comment]
Yes I had the same issues in some projects and spent quite some time finding the source of the error.
While showing the exact line in the excel sheet where it happens will be with the current implementation difficult, we could very easily show which values are not monotone (e..g 5 and 4). That way the user could simply search for theses values in the excel file. Much easier :)

**Comment by msevestre** [comment]
@Yuri05 : I'd suggest to implement it in 7.4

**Comment by msevestre** [comment]
Fixed by #974
