### ISSUE TITLE
Scale Individual: Manually entered reference concentration is reset

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#948]
If I had an individual with metabolizing enzymes, and if I override the reference concentrations to values found in the literature or identified by PI, these manually set values will be reset to default when "Scale" is applied. However, the "Value Origin" field is left to the reference.

Since, to my understanding, there is an ontogeny factor which will do the scaling, I suggest to leave manually entered values unchanged in the scaling process.

**Comment by Yuri05** [comment]
Indeed, it's a problem with the reference concentration. If changed in Individual, it's not recognized by the Scaling routine and is resetted to the default value.
<img width="550" alt="aufnahme13" src="https://user-images.githubusercontent.com/25061876/45806259-dd756080-bcc0-11e8-82a0-1db2b66e0899.png">

Other enzyme properties (e.g. half lives) are recognized by the scaling routine.
<img width="550" alt="aufnahme15" src="https://user-images.githubusercontent.com/25061876/45806316-0695f100-bcc1-11e8-8e9c-8abc088f039b.png">

However _default_ scaling method (**_Use default value_**) differs from the suggestion of @UlrichSi (which would be **_Use source value_**)
<img width="550" alt="aufnahme16" src="https://user-images.githubusercontent.com/25061876/45806772-2ed21f80-bcc2-11e8-93e9-b8f9b84095bd.png">

@UlrichSi Please open a separate issue for the latter.

**Comment by Incei** [comment]
I fully agree with Ulrich, I see this as a bug which should be fixed asap. Also, this may become painful when scaling is needed to several individuals.
Q: what will happen when scaling to a pediatric population?

**Comment by Yuri05** [comment]
>Q: what will happen when scaling to a pediatric population?

Currently there is no "scale to population" feature in PK-Sim.
IF you create a population based on individual XY, enzyme parameters like Ref.Conc nad Half Lives are set to the value defined in XY (additional variability can be added by user). Ontogeny factor for the enzyme is of course set differently for every individual in the population

**Comment by UlrichSi** [comment]
Shall we really use the "Use default value" as default for scaling? My opinion is to change the scaling method default generally to "Use source value". Also, if "Use default value" is manually selected, the "Origin" field needs to be set in synch to the value selection.

**Comment by Incei** [comment]
@ Yuri05 :In that case we would need to manually adjust all standard reference concentrations to the manually set ones (source value) and apply a random ontogeny factor to these...this is too much work. I agree again with UlrichSi that we need to change this asap.

**Comment by Yuri05** [comment]
>Shall we really use the "Use default value" as default for scaling...

As suggested above, please open a separate issue for this discussion. Thank you.

**Comment by UlrichSi** [comment]
> As suggested above, please open a separate issue for this discussion. Thank you.

That's what I am wondering about. I am not sure if it makes sense to first change everything to "Use default value", and then, at some time down the road, change this procedure again to "Use default value". Or am I misunderstanding something?

**Comment by Yuri05** [comment]
@UlrichSi Those are 2 different topics:

1. Reference concentration is not taken into account by the scaling workflow.
2. Default scaling method

Even if we change the default scaling method, the problem with the Ref. Conc. will persist.

**Comment by UlrichSi** [comment]
Default scaling method branched off to #951.

**Comment by Incei** [comment]
Many thanks, looking forward to the bugfix!
