### ISSUE TITLE
Error while incorporating human gene database

### ISSUE THREAD

**Issue by Krache** [Open-Systems-Pharmacology/PK-Sim#949]
Dear All, 

After linked PBPK model to human gene data base, I am not able to open it, the problem is 

"Not a valid password."

Thanks for your help, 

BR
Anis

**Comment by msevestre** [comment]
@Krache Please ensure that you are using the latest version of the gene expression database provided with the suite setup for 7.3

https://github.com/Open-Systems-Pharmacology/Suite/releases/download/v7.3.0/GENEDB_human.mdb

**Comment by msevestre** [comment]
Let us know if this fixes your issue

**Comment by Krache** [comment]
Many thanks, 

It works 

BR,
Anis
