### ISSUE TITLE
Simulation creation: handling of selecting the same inhibition/induction process more than once

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/PK-Sim#95]
In a project with inhibition/induction processes, when creating a simulation:

Creation Simulation -> Processes -> Inhibition/Induction,

when adding an interaction and selecting a process already present in the list (see screenshot), a warning dialog appears:
"PK-Sim®

'Inhibitor CYP3A4-01_Comp' cannot be selected more than once.
For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org)."

However, after selecting "OK", the process is selected. When clicking on "Next" and then "Previous", the process next to the initially selected is chosen (secreenshot 2). The behavior is misleading. It should not be possible to proceed until the duplicated process is deselected by user.

![inhibitioninduction](https://cloud.githubusercontent.com/assets/25903040/24852308/489f29ca-1dd7-11e7-996f-12f76b59b86b.jpg)
![inhibitioninduction2](https://cloud.githubusercontent.com/assets/25903040/24852309/48a4678c-1dd7-11e7-8f36-186457e7d79d.jpg)

**Comment by msevestre** [comment]
The behavior at the moment should be to reset the selection to none

**Comment by msevestre** [comment]
This is an issue with the DevExpress component that is not resetting the view as expected
