### ISSUE TITLE
Feature wish: expand manual for explanation how to include additional clearance in Mechanism based inhibition

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#950]
add Sebastians and Stephans explanations to manual: https://github.com/Open-Systems-Pharmacology/Forum/issues/226#issuecomment-422757607

**Comment by msevestre** [comment]
@tobiasK2001 Very soon, the documentation will be pushed online with possibility for users to suggest edit. My suggestion would be that you take care of that once this is ready

**Comment by msevestre** [comment]
Hence assigning to you for now

**Comment by msevestre** [comment]
@tobiasK2001 I have created an issue in the docs repository
https://github.com/Open-Systems-Pharmacology/docs/issues/6

We can follow up there
