### ISSUE TITLE
Scale Individual: Change method default to "Use Source Value"

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#951]
Branch-off from issue #948: In the "Scaling Configuration" tab, the default "Scaling Method" should be changed to "Use Source Value". See discussion in #948.

**Comment by msevestre** [comment]
@UlrichSi @Yuri05  Assuming this should be the case also for parameter such as t1/2 ?

**Comment by msevestre** [comment]
Of course all other paraemters will still have the same logic as before. Using default value for parameter such as volume is non sensical
