### ISSUE TITLE
Scale Individual: Select proper "Value Origin" field dependent on change method

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/PK-Sim#952]
Another branch-off from issue #948: The Value Origin field content (see tab "Expression") should be set dependent on the selection done in "Scaling Configuration". If the Source Value is selected as Scaling Method, its Value Origin should be transferred to the scaled individual. If the Default Value is selected, the corresponding default value origin entry should be used - currently this field is usually empty, but it may change in the future.

**Comment by sfrechen** [comment]
Agree!

**Comment by msevestre** [comment]
so what needs to be done here is simply update value origin when using source value correct?

**Comment by msevestre** [comment]
This was already working for molecule parameters. Now working for all parameter using the above mentioned scaling method
