### ISSUE TITLE
feature wish: Population BB export to PDF add Info: "based on individual"

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#954]
in the generated PDF file after rmc on Population BB "Export to pdf": add under 1.1.1. Population Properties the info seen by  from mouse over the population BB like: "based on individual yx". Also pplease add the race of the populatio e.g. European ICRP.

**Comment by Yuri05** [comment]
Export to PDF is not available anymore
