### ISSUE TITLE
 Bug: Simulation export to PDF observed data are not shown in 1.3.1. Time profile analysis

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#956]
PK-Sim 7.3.0. Build 42: 
[PDF-report bugs.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2414357/PDF-report.bugs.zip)
in the generated PDF file after rmc on Simulation"Export to pdf": the observed data is not shown in th Grapgh under 1.3.1 under 

![grafik](https://user-images.githubusercontent.com/25585248/46002139-8949f200-c0ad-11e8-8f74-4bacbd37b62e.png)

in report it is gone in the graph
![grafik](https://user-images.githubusercontent.com/25585248/46002158-94048700-c0ad-11e8-970b-d6b4ea228752.png)

Although PK-analysis is there:
![grafik](https://user-images.githubusercontent.com/25585248/46002190-aaaade00-c0ad-11e8-8d10-9d3b5d912650.png)

in some cases in other projects observed data are shown. However I could not figure out a pattern why.

**Comment by Yuri05** [comment]
obsolete (no more pdf reports)
