### ISSUE TITLE
Bug: Simulation export to PDF wrong specific intestinal permeability shown under 1.2.2.1. compound configuration

### ISSUE THREAD

**Issue by tobiasK2001** [Open-Systems-Pharmacology/PK-Sim#957]
PK-Sim 7.3.0. Build 42:
in compound BB fitted specific intestinal permability is chosen as default and used in Simulation
![grafik](https://user-images.githubusercontent.com/25585248/46002768-383afd80-c0af-11e8-97a7-b4c3b3a4faf5.png)
![grafik](https://user-images.githubusercontent.com/25585248/46002794-48eb7380-c0af-11e8-8ce7-0c8a08b2ad0f.png)
however in report the specfific intestinal permeability for the fitted lipophilicity is shown, which makes no sense here, as it is not used in the Simulation.
![grafik](https://user-images.githubusercontent.com/25585248/46002866-733d3100-c0af-11e8-882a-bab749ed650a.png)

Please show the compound's specific intestinal permeability used in the simulation. Also show the Intestinal permeability (transcellular) used in the simulation. Especially when this different than calculated from the compound's specific intestinal permeability (formula overwritten) this must be shown.
[PDF-report bugs.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2414436/PDF-report.bugs.zip)

**Comment by Yuri05** [comment]
obsolete
