### ISSUE TITLE
Special characters in PI names/long PI names shouldn't be allowed

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/PK-Sim#958]
In PK-Sim it is possible to create names for Parameter Identifications with invalid characters or too many characters. While such such can be given, the following error messages are thrown when the PI is exported to MATLAB:

![l_fe11 tmp](https://user-images.githubusercontent.com/26541603/46215902-cd075a80-c33e-11e8-8abf-1219d487b356.PNG)

![l_4118 tmp](https://user-images.githubusercontent.com/26541603/46215913-d1cc0e80-c33e-11e8-8542-5593dc42c7e7.PNG)

Instead of the error message, I would suggest that special characters/long PI names are not allowed (similar to simulation names).

**Comment by Yuri05** [comment]
PI Export to Matlab will be dropped in v9
