### ISSUE TITLE
Cannot zoom-out after zoom-in simulated-plot

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/PK-Sim#97]
After zoom-in into a simulated plot, it is not possible to zoom-out anymore. Right-mouse click option only allows to copy the image.

![zoom_issue](https://cloud.githubusercontent.com/assets/25530079/24899445/9997a64e-1ea0-11e7-9bf4-3ff101b88b1a.png)

[zoom-in_issuel.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/912544/zoom-in_issuel.zip)

**Comment by msevestre** [comment]
Fixed in Core
