### ISSUE TITLE
Update from Building Block: Problem mit relative Expressions

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#973]
[P4_EnzymeUpdate_01.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2469380/P4_EnzymeUpdate_01.zip)

In the project attached, there is no difference between Individual-building block and simulation; relative expressions for enzyme E1 are defined as following:
<img width="633" alt="aufnahme28" src="https://user-images.githubusercontent.com/25061876/46812133-5b82cf80-cd74-11e8-9559-5bd5d72618b1.png">

1. In the simulation, set relative Expression in Plasma = 3
<img width="526" alt="aufnahme29" src="https://user-images.githubusercontent.com/25061876/46812272-ad2b5a00-cd74-11e8-8129-28e814002822.png">
2. Update individual in the simulation from the building block. New relative expressions are shown below and are NOT the expressions from the individual.
<img width="633" alt="aufnahme31" src="https://user-images.githubusercontent.com/25061876/46812424-fda2b780-cd74-11e8-8c09-1103479395fa.png">

@twendl FYI

**Comment by msevestre** [comment]
Very interesting indeed.
