### ISSUE TITLE
Validation suite is missing in version 7.3

### ISSUE THREAD

**Issue by rgollen** [Open-Systems-Pharmacology/PK-Sim#979]
Hi All, 
Is anyone is aware of the validation suite in the latest version (I am missing it or don't know where to find it)? I am using version 7.3.
I have used the same in version 7.1 (when it was launched the first time) and found it very helpful as per FDA guidance on the PBPK reports.

Any advice will be helpful.

Best regards
Rakesh

**Comment by msevestre** [comment]
@rgollen THe installation validator is installed with the suite and can found alongside other tools such as MoBi and PK-Sim

How did you install the suite? Did you use the setup provided [here](http://setup.open-systems-pharmacology.org) or did you use the portable install of PKSim and MoBi

You can find the InstallationValidator in the program file folder
Typically something like

C:\Program Files (x86)\Open Systems Pharmacology\InstallationValidator 7.3 for x64 bit PC
and 
C:\Program Files)\Open Systems Pharmacology\InstallationValidator 7.3 for 32 bit PC

If you are using Windows 10, you can simply type the windows command and search for InstallationValidator

Hope that helps,

Cheers,
Michael

**Comment by msevestre** [comment]
@rgollen Going to close the issue here as this is not related to PK-Sim whatsoever. If you need more help, I'd suggest to open an issue in the forum. 

Of course, any bugs you may find in PK-Sim should be posted in this repository. 

Thanks

**Comment by rgollen** [comment]
Thanks Michael,
This is helpful. I appreciate.

Best regards
Rakesh
