### ISSUE TITLE
Default alternative for intestinal/organ permeability corrupted after reimport from snapshot

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/PK-Sim#983]
If an additional alternative was added for `Specific Intestinal Permeability` or for `Specific Organ Permeability` and set to default: after export/reimport from snapshot **_both_** alternatives are set as default.

(Default alterantives for other parameters(_Lipophilicity_, _fu_...) are set correctly)

[P4.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/2535213/P4.zip)

### Original project
![grafik](https://user-images.githubusercontent.com/25061876/47800592-e3814700-dd2c-11e8-9def-533bc24fe903.png)
![grafik](https://user-images.githubusercontent.com/25061876/47800744-27744c00-dd2d-11e8-91e1-81d72a4995ec.png)
### After reimport from snapshot
![grafik](https://user-images.githubusercontent.com/25061876/47800885-5d193500-dd2d-11e8-88c2-a72ed7c6fe34.png)
![grafik](https://user-images.githubusercontent.com/25061876/47800898-63a7ac80-dd2d-11e8-9c48-92406bb9e36f.png)

**Comment by msevestre** [comment]
looking at that now
