### ISSUE TITLE
RFC: Observer support in PK-Sim 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#984]
I would like to submit a proposal for observer support in PK-Sim:

# Problem

I strongly believe that one of the most common reason why users export a PK-Sim simulation to MoBi is because they need some user defined output to be generated. In generals, these outputs can be defined as observers. The workflow is always the same

1. Create a simulation in PKSim
1. Export to MoBi
1. Add an observer to the observer building block (or load an existing one)
1.Create a new simulation in MoBi and use the newly created observer

This is all perfect and works great until you realize that you have forgotten a process in PKSim or want to add an enzyme etc.. You have to do the whole export import dance again

# Solution

The issue could be solved easily by allowing users to add custom observers in PK-Sim. They will be defined as building block (similar to MoB or maybe one observer is one building block). During simulation creation, the user could select one or more observers to be added to the simulation. 

# Implementation

* My suggestion would be for a first version to simply import one or more pkml observers defined in MoBi and exported as file. You would load the observer from PKSim and they would be readily available to use when creating a simulation

* An extended version would allow the user to edit/create an observer in PK-Sim directly. This is purely convenience at that stage as observer do not change often within a project. Requiring definition of observers in MoBi for a first step and re-importing them in PKSim would be sufficient until proven otherwise :)

* I would consider one observer as being a building block, and not a list of observers (to discuss). I am not sure what a typical scenario is, but in my uses cases, I only had 2 or 3 observers that I wanted to use in a simulation, and not in all of them. Having each single one as building block, similar to one event, would make sense. The alternative would be to defined the PKSim building block as being exactly an observer building block, Then the import export would be a bit more cumbersome / would require more implementation to cover all use cases

* Purely extension: No project conversion required

**Comment by Yuri05** [comment]
>I would consider one observer as being a building block, and not a list of observers (to discuss).

I would vote for the **list of observers** as building block. If the user would like to have every observer as separate building block, it would still be possible (just define new building block for every observer with observer list consisting of exactly this one observer).

When importing observers from (MoBi-)pkml (like the idea btw.!), i would:
* offer "Import: Yes/NO" option for every observer
* offer "Import all observers into the same building block" option.

With that, user would be compeltely flexible in distributing imported observers over N building blocks in PK-Sim

**Comment by PavelBal** [comment]
I vote for @Yuri05 proposal.

**Comment by msevestre** [comment]
I think it is important to see it from 1/ the typical PK-Sim usage 2/ The creation simulation flow.

1. if we decide to have an Observers building block (e.g. a LIST), the selection would be made at the "BuildingBlock" level and not at the simulation level. That means that in the simulation creation flow, along to events, application etc..,  one would select only one Building block and that would be the one that would be added to the simulation. Selecting the building block would then pursue to add all observer in the list to the simulation (details of what to do when an observer in this list cannot be added will need to be specified later)

2. If we decide to have one observer as a building block, then the user would select the observers to add at the simulation level, switching them on and off as he may please. e.g. the selection is made at the simulation creation level and not at the building block level


>offer "Import: Yes/NO" option for every observer

I am not sure about that. If you import a list from MoBi, then you certainly don't want to be ask for EACH observer if you really want to import it. In MoBi, you can export the observer at your convenience. We are in general talking about a handfull of observers that would be exported that way. As long as you can multiselect and export in one file, the flow is clear


> offer "Import all observers into the same building block" option.

Agreed. However This should be the one and only behavior. Why would you want to split the list in building blocks of one observer ?  


I think we need to make it simple here. Either a list and and only a single observer bb in simulation or element, and then N observers per simulation.

**Comment by Yuri05** [comment]
>Either a list and and only a single observer bb in simulation or element, and then N observers per simulation.

I don't see why it should be "either..or" decision. We could also add **multiple** observer bulding blocks to a simulation where every building block contains a list of observers.

>I am not sure about that. If you import a list from MoBi, then you certainly don't want to be asked for EACH observer if you really want to import it. In MoBi, you can export the observer at your convenience. We are in general talking about a handful of observers that would be exported that way. As long as you can multi select and export in one file, the flow is clear

Currently you cannot multiselect observes in MoBi (would be also not possible in the future if the user would like to export some container and some molecule observers at the same time, because they reside in different tabs).

So how I imagine the workflow:
1. User exports **the whole observers building block** in MoBi as pkml
    * Alternatively: user exports just 1 observer as pkml
2. User selects exported observers-pkml in PK-Sim for import
    * Here I would also allow multiselect of exported observer-pkmls
3. PK-Sim filters all predefined observers (=standard PK-Sim observers) out and shows the list of remaining observers to the user (which usually would be very short, in the most cases 1-2 observers).
    * All observers in this list are selected for import per default
    * User can **deselect** some observers
4. User decides if selected observers:
    * Should be imported as a **new** observers building block
    * Or added to **existing** observers building block

Thus we would have N observer building blocks in a project, where every building block contains a list of observers.

When creating a simulation:
1. User selects a subset of observer building blocks available in the project.
2. All observers from all selected observer building blocks are added to the simulation.
  * In case of conflicts (e.g. observer with the same name is available in more than 1 selected observer building blocks): simulation cannot be created. In this case user has e.g. to deselect some observer BBs.

**Comment by StephanSchaller** [comment]
Yes, I like the workflow described by @Yuri05 in the previous post

**Comment by msevestre** [comment]
> We could also add multiple observer bulding blocks to a simulation where every building block contains a list of observers.

Sure. 

>User exports the whole observers building block in MoBi as pkml

I disagree with this proposal. User should select the observer he wants to use. This will save us time later when explaining why something does not work and will ensure that the user things about what he needs.

>User selects exported observers-pkml in PK-Sim for import
Here I would also allow multiselect of exported observer-pkmls

sure

>PK-Sim filters all predefined observers (=standard PK-Sim observers) out and shows the list of remaining observers to the user (which usually would be very short, in the most cases 1-2 observers).
All observers in this list are selected for import per default
User can deselect some observers

Disagree with that as well. What the user selects, is what the user is going to import. This is what we do almost everywhere (unless we import a container in MoBi, but here the structure is admittedly hierarchical). In our case, The user will in general export at max a hand full of single observer file from MoBi. He should simply select them and that's it. 

>User decides if selected observers:
Should be imported as a new observers building block
Or added to existing observers building block

I would as well try to keep the usage consistent with what we do everywhere else. Either ADD To an existing building block or start from the observer root folder menu and add new. That way the flow is started and clear from the beginning

I agree with the flow for creating a simulation

**Comment by Yuri05** [comment]
>Disagree with that as well. What the user selects, is what the user is going to import. This is what we do almost everywhere (unless we import a container in MoBi, but here the structure is admittedly hierarchical). In our case, The user will in general export at max a hand full of single observer file from MoBi. She/He should simply select them and that's it.

OK for me in case we will allow **_only_** export of single/selected Observers from MoBi. If also export of the whole observers building block will be allowed, I disagree.

>I would as well try to keep the usage consistent with what we do everywhere else. Either ADD To an existing building block or start from the observer root folder menu and add new. That way the flow is started and clear from the beginning

Fine with that.

**Comment by fweysser** [comment]
Fully agree with the Yuri05 & msevestre solution! Thanks for thinking this through.

**Comment by msevestre** [comment]
@all: Starting with this implementation

**Comment by msevestre** [comment]
FYI: This is implemented in PK-Sim 7.5. It is possible to add observers as building block (save them or load them from template also) and use them in a PKSim Simulation. No need to go for MoBi for that

In a later version, some basic editing of an observer (specifically editing the molecules) could be added
At the moment, readonly
