### ISSUE TITLE
Seed can be negative in PKSim.

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/PK-Sim#995]
https://docs.microsoft.com/en-us/dotnet/api/system.environment.tickcount?view=netframework-4.7.2

Not sure if this is an issue or not. We can definitely use the trick described in this document to ensure it's always positive

**Comment by msevestre** [comment]
@Yuri05 Thoughts?

**Comment by Yuri05** [comment]
According to the [docu of System.Random](https://docs.microsoft.com/en-us/dotnet/api/system.random.-ctor?view=netframework-4.7.2#System_Random__ctor_System_Int32_):
![grafik](https://user-images.githubusercontent.com/25061876/48473875-ab343b00-e7f9-11e8-9bb5-80a0a85663b7.png)

So I don't see any problem in negative seeds. Or why do u think it's problematic?

**Comment by msevestre** [comment]
@Yuri05 The seed might be used outside of .NET and I am not sure if a negative seed is expected.
But this is good.
We have to change however  the test that is failing on my machine because I haven't restarted it in a very long time (no BLue sceen anymore :))
https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/tests/PKSim.Tests/Core/IndividualFactorySpecs.cs#L135
