### ISSUE TITLE
Old website in Help Menu

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/PK-Sim#999]
SHould we change the Listed website to open-systems-pharmacology.org?

![image](https://user-images.githubusercontent.com/25477643/48419685-e29edb00-e758-11e8-95e6-b60895f38db0.png)

**Comment by msevestre** [comment]
duplicates https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/998
